### ISSUE TITLE
L-arogenic acid duplication

### ISSUE THREAD

**Issue by muthuvenkat** [ebi-chebi/ChEBI#11]
From marek@genome.stanford.edu

The term L-arogenic acid is duplicated with two IDs:

[Term]
id: CHEBI:21239
name: L-arogenic acid
is_a: CHEBI:25359

[Term]
id: CHEBI:17530
name: L-arogenic acid
alt_id: CHEBI:13081
alt_id: CHEBI:6190 
alt_id: CHEBI:21238
synonym: "1-[(2S)-2-amino-2-carboxyethyl]-4-
hydroxycyclohexa-2,5-diene-1-carboxylic
acid" EXACT IUPAC_NAME [:IUPAC]
synonym: "alpha-Amino-1-carboxy-4-hydroxy-2,5-
cyclohexadiene-1-propanoic
acid" EXACT [:ChemIDplus]
synonym: "L-arogenate" EXACT [:IntEnz]
synonym: "L-Arogenate" EXACT [:KEGG COMPOUND]
synonym: "L-Arogenic acid" EXACT [:KEGG COMPOUND]
synonym: "Pretyrosine" EXACT [:KEGG COMPOUND]
synonym: "C10H13NO5" EXACT FORMULA [:KEGG COMPOUND] 
xref: ChemIDplus:53078-86-7 "CAS Registry Number"  
xref: KEGG COMPOUND:53078-86-7 "CAS Registry Number"
xref: KEGG COMPOUND:C00826 "KEGG COMPOUND"
is_a: CHEBI:21239

Reported by: *anonymous

**Comment by linuxjackto1** [comment]
thanks www.movied.org
