### ISSUE TITLE
Discrepancy number of SMILES and InChIs

### ISSUE THREAD

**Issue by muthuvenkat** [ebi-chebi/ChEBI#13]
There is a discrepancy between the number of SMILES and
InChI's. This seems to have occurred when the
auto-generation was switched off.

Here is a current list of the items:
CHEBI: 28420
CHEBI: 30409
CHEBI: 33157
CHEBI: 33158
CHEBI: 33160
CHEBI: 33169
CHEBI: 33170
CHEBI: 4782
CHEBI: 3688
CHEBI: 4307
CHEBI: 33177
CHEBI: 3654
CHEBI: 2979
CHEBI: 2980
CHEBI: 5076
CHEBI: 8066
CHEBI: 9427
CHEBI: 33181
CHEBI: 33182
CHEBI: 6758
CHEBI: 31084
CHEBI: 1233
CHEBI: 1235
CHEBI: 1236
CHEBI: 20436
CHEBI: 33206
CHEBI: 33207
CHEBI: 33213
CHEBI: 33214
CHEBI: 33215
CHEBI: 18145
CHEBI: 33225
CHEBI: 33227
CHEBI: 23607
CHEBI: 33254
CHEBI: 9355
CHEBI: 33277
CHEBI: 27017
CHEBI: 27974
CHEBI: 5206
CHEBI: 33421
CHEBI: 33438
CHEBI: 33439
CHEBI: 33440
CHEBI: 33442
CHEBI: 22990
CHEBI: 27500
CHEBI: 1015

Reported by: pauladematos

**Comment by linuxjackto1** [comment]
thanks www.movied.org
