### ISSUE TITLE
Please merge CHEBI:64489 

### ISSUE THREAD

**Issue by muthuvenkat** [ebi-chebi/ChEBI#2789]
Hi, I tried to submit the structure attached to this message, but apparently it already exists as CHEBI:64489, only that I cannot see it and check if it is major species at pH 7.3. Could you please merge the structures? If different protonation, then please add the one I'm sending to you. The description and synonyms are:
Definition:
major species at pH 7.3
is_a_CHEBI:64483_has_functional_parent_CHEBI:30807
Synonyms:
Uniprot name: 1-tetradecanoyl-sn-glycero-3-phosphocholine 
Others: 1-tetradecanoyl-sn-glycero-3-phosphocholine betaine
1-C<smallsub>14:0</smallsub>-lysophosphatidylcholine betaine
1-myristoyl-sn-glycero-3-phosphocholine betaine
Thanks in advance,
Lucila

Reported by: lucilaimo

[myristoyl-LPC.mol.zip](https://github.com/ebi-chebi/ChEBI/files/77113/myristoyl-LPC.mol.zip)

**Comment by G-Owen** [comment]
CHEBI:64489 is the correct record. I will close the ticket.
