### ISSUE TITLE
Add new class 'b vitamins' to ChEBI

### ISSUE THREAD

**Issue by muthuvenkat** [ebi-chebi/ChEBI#2822]
I would like to request that a new Class ‘B vitamins’ be added to the ChEBI database.  This class would include as subclasses:

Cobalamin       CHEBI:30411
Biotin          CHEBI:15956
Pyridoxine      CHEBI:16709
Riboflavin      CHEBI:17015
Pantothenic acid    CHEBI:7916
Folic acid      CHEBI:27470
Nicotinic acid      CHEBI:15940
Thiamine        CHEBI:26948

This is a common mixture of vitamins used to grow microorganisms.  Reference: Wikipedia:B_vitamins.  Proposed Outgoing: ‘B vitamins’ is_a ‘water-soluble vitamin’

-Carrine

Reported by: carrineblank

**Comment by ddooley** [comment]
But what about adding the subclasses listed in the definition?  Any of the group of eight water-soluble vitamins ... vitamin B1, B2, B3, B5, B6, B7, B9, and B12. ...

**Comment by G-Owen** [comment]
Hi Damion,
As far as I can see, these entities are already present in ChEBI. If you go to CHEBI:75769 (B vitamin; synonyms B vitamins; B group vitamin; vitamin B) and scroll down below the Wikipedia section to the ChEBI Ontology section, you will find them listed (and linked to) in the "Incoming" section. Admittedly

**Comment by G-Owen** [comment]
Admittedly the linked entries all have "chemical" names as their display names, but the "vitamin" names (B1, B2, etc.) are present as synonyms.

Hope this helps!
Gareth

**Comment by ddooley** [comment]
I'm looking at:
https://www.ebi.ac.uk/ols/ontologies/chebi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHEBI_75769
In it I see various ROLE axioms - but they are pointing to material entities.  Can't have it both ways.  Either B1, B2, B3, B5, B6, B7, B9, and B12 must be moved to role (and renamed with "role" suffix). Or we consider them primarily molecular entities, and create a "B Vitamin" molecular entity group with those as subclasses.

**Comment by ddooley** [comment]
I prefer the latter, and others can get around to defining roles and for example what it takes to be a B1 vitamin role.

**Comment by G-Owen** [comment]
It is always a problem with vitamins - the names can be used to mean both structure and role. The problem with treating them as entities comes in defining the structural features that they (and only they) can have...

**Comment by ddooley** [comment]
Well, I think the suffix "role" should be added if entity has role semantics.  Can't have the entity be both role and material entity. It will break reasoning into the future.
