### ISSUE TITLE
The OWL build available from the CHEBI FTP site is non-standard

### ISSUE THREAD

**Issue by muthuvenkat** [ebi-chebi/ChEBI#3105]
The chebi.owl available here ftp://ftp.ebi.ac.uk/pub/databases/chebi/ontology/

is potentially confusing to users. It uses an annotation vocabulary that is non-standard and unique to CHEBI.

I recommend you use the standard OWLAPI obo<->owl translation. You can use the latest version of Protege, or a command line tool such as

 * Robot - https://github.com/ontodev/robot/
 * owltools/Oort - https://github.com/owlcollab/owltools

If you do this we can also simplify the OBO central build pipeline (at the moment we are forced to make our own CHEBI build using this jenkins job - http://build.berkeleybop.org/job/build-chebi/ )

Reported by: cmungall

**Comment by muthuvenkat** [comment]
@cmungall, I have tried the owltools as a dependency, but the owl file exported doesn't have any major changes, can you please elaborate bit more on what is "Standard annotation vocabulary", and the things that are confusing the users.  Also if you can provide an example to look, would be helpful.

**Comment by muthuvenkat** [comment]
@adekker2  check this

**Comment by cmungall** [comment]
These are your annotation properties:

```
    <owl:AnnotationProperty rdf:about="http://purl.obolibrary.org/obo#InChIKey"/>
    <owl:AnnotationProperty rdf:about="http://purl.obolibrary.org/obo#InChI"/>
    <owl:AnnotationProperty rdf:about="http://purl.obolibrary.org/obo#xref"/>
    <owl:AnnotationProperty rdf:about="http://purl.obolibrary.org/obo#altId"/>
    <owl:AnnotationProperty rdf:about="http://purl.obolibrary.org/obo#Synonym"/>
    <owl:AnnotationProperty rdf:about="http://purl.obolibrary.org/obo#SMILES"/>
    <owl:AnnotationProperty rdf:about="http://purl.obolibrary.org/obo#Definition"/>`
```

This is the official mapping
http://owlcollab.github.io/oboformat/doc/obo-syntax.html#5.6

There are some other things you should switch as well, for example, you should either use the standard part-of object property (BFO_0000050), removing your own axioms about it; or if the CHEBI one is truly different best to choose a different label so as not to confuse.

Is the code that makes the conversion in github? I could point to specific problems

@dosumis is often at the EBI and can provide local help if need be

**Comment by dosumis** [comment]
Unless you have expressiveness outside of OBO, it should be to sufficient to make the OWL version using the OBO dump of ChEBI and convert using Oort or Robot.

**Comment by muthuvenkat** [comment]
Thanks @dosumis. 
@cmungall, we generated a OWL file using Robot (converted from OBO to OWL). Its available in the public [ftp](ftp://ftp.ebi.ac.uk/pub/databases/chebi/ontology/chebi_robot.owl), can you please take a look and let us know if there are anything missing.

**Comment by muthuvenkat** [comment]
@cmungall do you want us to generate the future OWL file using Robot library. Can you please confirm.

**Comment by cmungall** [comment]
Correct. Tool is here https://github.com/ontodev/robot/

```
robot convert -i chebi.obo -o chebi.owl
```

**Comment by muthuvenkat** [comment]
Thanks @cmungall, thats how i generated this one, shall do it for the future releases too.
