### ISSUE TITLE
CHEBI:38501 'cytochrome-c oxidase inhibitor' == CHEBI:62966 'cytochrome c oxidase inhibitor' 

### ISSUE THREAD

**Issue by muthuvenkat** [ebi-chebi/ChEBI#3122]
What is the difference between these?

I note that CHEBI:38501 is marked preliminary (it has been in this state a while)

CHEBI:62966 recently changed its name from

cytochrome c oxidase inhibitor

to

EC 1.9.3.1 (cytochrome c oxidase) inhibitor

(why prefix the label with the EC number?)

I suggest these two are merged, and the ID is removed from the label

Reported by: cmungall

**Comment by G-Owen** [comment]
Now merged!
