### ISSUE TITLE
Follow OBO/GO ID policy and do not change meaning of existing IDs

### ISSUE THREAD

**Issue by muthuvenkat** [ebi-chebi/ChEBI#3123]
CHEBI from early 2014 had this:

```
[Term]
id: CHEBI:38234
name: DNA polymerase inhibitor
namespace: chebi_ontology
synonym: "DNA polymerase inhibitors" RELATED []
is_a: CHEBI:23924  ! enzyme inhibitor
```

which had no definition, yet the concept is clear and unambiguous from the label, and is easily recognized as corresponding to the inhibition of this activity:

```
id: GO:0034061
name: DNA polymerase activity
```

CHEBI has reused the same ID for a more specific concept:

```
[Term]
id: CHEBI:38234
name: EC 2.7.7.7 (DNA-directed DNA polymerase) inhibitor
def: "An EC 2.7.7.* (nucleotidyltransferase) inhibitor that interferes with the action of a DNA-directed DNA polymerase (EC 2.7.7.7)." []
...
```

If OBO/GO ID policy was followed, then CHEBI:38234 would have been obsoleted, and a new ID would have been introduced for the more specific class.

Incidentally, why is EC being used to define the hierarchy rather than GO? As CHEBI is an OBO Foundry ontology it should be setting a good example and reusing other OBO ontologies.

Reported by: cmungall

**Comment by G-Owen** [comment]
Now fixed as follows:
CHEBI:38234 has now been reverted to the more general term 'DNA polymerase inhibitor', which now has two child terms:
     CHEBI:131699 EC 2.7.7.7   (DNA-directed DNA polymerase) inhibitor; and  
     CHEBI:59897   EC 2.7.7.49 (RNA-directed DNA polymerase) inhibitor
