### ISSUE TITLE
Possible error in brand name for CHEBI:7071

### ISSUE THREAD

**Issue by mjw99** [ebi-chebi/ChEBI#3126]
Dear Devs,
 
Is one of the brand names for entry CHEBI:7071, "Off" correct? I think it should be "Off!":

http://www.atsdr.cdc.gov/phs/phs.asp?id=1447&tid=201

Thanks,

Mark

**Comment by G-Owen** [comment]
Hi Mark,
I think you're right! The synonym came from ChemIDplus, who cite the Hazardous Substances Data Bank and the Register of Toxic Effects of Chemical Substances, both of which omit the exclamation mark (as does the Merck Index).
I have now added the exclamation mark the name as well as some other data to ChEBI:7071.

Kind regards,
Gareth
