### ISSUE TITLE
new term request: pneumocandin B0

### ISSUE THREAD

**Issue by mah11** [ebi-chebi/ChEBI#3129]
name: pneumocandin B0
CAS: 135575-42-7
PubChem: http://pubchem.ncbi.nlm.nih.gov/compound/5742645

I don't know anything else about this molecule, but let me know if there's anything else I should do for this request.

Midori

**Comment by G-Owen** [comment]
Hi Midori,

Now done - see CHEBI:131609. Sorry it took so long.

Best regards,
Gareth
