### ISSUE TITLE
error in class name for CHEBI:90443

### ISSUE THREAD

**Issue by carrineblank** [ebi-chebi/ChEBI#3132]
The gamma in the class name for CHEBI:90443 / N-(γ-L-glutamyl)-2-naphthylamine(1−) should be alpha given the definition and parent classes.

-Carrine

**Comment by carrineblank** [comment]
Similarly,
the alpha in the class name for CHEBI:90439 / N-(α-L-glutamyl)-2-naphthylamine(1−) should be gamma given the definition and parent classes.

-Carrine

**Comment by stevet7** [comment]
Hi Carrine,

I've had a look at these and according to IUPAC conventions, gamma-glutamyl always corresponds to attachment at the side-chain carboxy group while alpha-glutamyl always corresponds attachment at the carboxy group adjacent to the amino function. For some examples aee CHEBI:85894, 30307 and 28296.

Kind regards,
Steve

**Comment by carrineblank** [comment]
I am not a chemist, so pardon my ignorance.

However, the class name does not match the definition or the parent classes, therefore perhaps the definition and parent classes need to be looked at??

-Carrine
