### ISSUE TITLE
request for new terms of microbial-related compounds

### ISSUE THREAD

**Issue by carrineblank** [ebi-chebi/ChEBI#3133]
Hi all,

I have created a Google Doc spreadsheet of an additional 85 chemicals derived from taxonomic descriptions of microbial prokaryotes and from published microbiological culture media.  I've shared the document with you folks already, so you should have access:

https://docs.google.com/spreadsheets/d/1xKQwUl35GgfYZBZfF57e16ULNyJ5-QV-IKqfX7NpDU0/edit#gid=0

Do you want me to fill out "possible parent is_a relationships", like I have before?  I don't know if this is helpful for you guys or not.

Also, there are still a couple remaining compounds from my last Google Doc spreadsheet that I submitted through SourceForge in October, and I wonder if there were some issues with these or if they are still awaiting adding to ChEBI.  If you need any additional information from me, just let me know.  The link is:

https://docs.google.com/spreadsheets/d/1dG43uULDVuGh7TBgRje2zYbsaqnjsv1C9ubvtkKtjZQ/edit#gid=0

Sincerely,
Carrine

**Comment by G-Owen** [comment]
Hi Carrine,

Thanks for the new spreadsheet - we will try to finish off the old one asap and then work our way through the new one. Apologies in advance if this takes a while - we lost a curator recently!

The "possible is_a relationships" are certainly helpful, but not essential.

Kind regards,
Gareth

**Comment by G-Owen** [comment]
Hi Carrine,
These look as if they were all dealt with, so I will close the issue! 

Kind regards,
Gareth
