### ISSUE TITLE
Replace CiteXplore seeAlso (and any other) annotations in OWL

### ISSUE THREAD

**Issue by alanruttenberg** [ebi-chebi/ChEBI#3134]
There are currently 10s of thousands of references to CiteXplore in ChEBI, which leads to confusion as
CiteExplore is dead, having been replaced by the European Pubmed Central. T. (google "CiteXplore was withdrawn from service on 15 February 2013, replaced by Europe PubMed Central")

I believe the identifiers are pubmed ids, but this is not clear. I suggest replacement with seeAlso links with the value being URIs to either the US, or European pubmed abstract page, as seeAlso links are conventionally URIs rather than arbitrary strings. If used in other fields, such as definition source, then use the current convention PMID:xxxxxx pr ARTICLE:PMID:xxxx as in http://www.w3.org/wiki/OBI_Definition_Source

**Comment by muthuvenkat** [comment]
@alanruttenberg  Thanks for reporting its fixed in the OBO / OWL file.
