### ISSUE TITLE
Accessing previous versions of CHEBI

### ISSUE THREAD

**Issue by cmungall** [ebi-chebi/ChEBI#3135]
In the obo format version of CHEBI, the data-version field is a number like '136'

According to the obo2owl spec, this is translated to
http://purl.obolibrary.org/obo/chebi/136/chebi.owl

Which is how it shows up in the latest release in http://purl.obolibrary.org/obo/chebi.owl

However, these do not resolve.

If you can provide an ftp location with historic versions of the obo and the owl (using the official conversion - see  #3105 ) then I can help you set up the purls.

**Comment by muthuvenkat** [comment]
@cmungall we have created an archive from release 100 in the ftp folder. ftp://ftp.ebi.ac.uk/pub/databases/chebi/archive/

**Comment by alanruttenberg** [comment]
Can you use the date saved to create the versionIRI instead of the data version field? Put the data version field in some other property.

**Comment by cmungall** [comment]
@alanruttenberg -- versionIRI is syntactically coupled to data-version at the level of the OBO/OWL translation.

However, it would be possible to move the current integer version into an entirely new field and reserve data-version/versionIRI for ISO-8601 OBO-style version info. The question for OBO is how much we want to enforce one particular versioning scheme, especially for ontologies like CHEBI with pre-existing schemes, and the question for CHEBI is it worth the churn for them to change
