### ISSUE TITLE
biogenic mineral (CHEBI_64391) heirarchy is logical inconsistant

### ISSUE THREAD

**Issue by cooperl09** [ebi-chebi/ChEBI#3136]
A biogenic mineral (CHEBI_64391)  is_a mineral (CHEBI:46662)

mineral  (CHEBI:46662)
Def’n: A mineral is a naturally occurring substance **formed through geological processes** that has a characteristic chemical composition, a highly ordered atomic structure and specific physical properties.

biogenic mineral (CHEBI_64391) Any mineral **formed by life processes**.

Thus biogenic mineral (CHEBI_64391) cannot be a mineral (CHEBI:46662) as defined above.

**Comment by G-Owen** [comment]
Thanks for letting us know. I have now updated the definition of both terms, based on the recommendations of the International Mineralogical Association.
