### ISSUE TITLE
Incomplete ontology for CHEBI:80961 (Uracil 5-carbaldehyde)

### ISSUE THREAD

**Issue by cviner** [ebi-chebi/ChEBI#3140]
[CHEBI:80961 Uracil 5-carbaldehyde](http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:80961) or 5-Formyluracil (5fU) is only annotated as ![is a](https://camo.githubusercontent.com/cff1412b81e8bb6c5e3c1fac35ab9a3e581d2450/687474703a2f2f7777772e6562692e61632e756b2f63686562692f696d616765732f6f6e746f6c6f67792f636865636b65642f69735f612e676966) is a [9,11,15-octadecatrienoic acid (CHEBI:38387)](http://www.ebi.ac.uk/chebi/searchId.do;jsessionid=1B64B4533DAE8338F69A614D2FB7A210?chebiId=CHEBI%3A38387).

However, it should also have the following (outgoing) relationships:

-  ![has functional parent](https://camo.githubusercontent.com/a2db830ba48121b41b8203ac2ecda097789e04ed/687474703a2f2f7777772e6562692e61632e756b2f63686562692f696d616765732f6f6e746f6c6f67792f636865636b65642f6861735f66756e6374696f6e616c5f706172656e742e676966) has functional parent [uracil (CHEBI:17568)](http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:17568)
- ![is a](https://camo.githubusercontent.com/cff1412b81e8bb6c5e3c1fac35ab9a3e581d2450/687474703a2f2f7777772e6562692e61632e756b2f63686562692f696d616765732f6f6e746f6c6f67792f636865636b65642f69735f612e676966) is a [pyrimidone (CHEBI:38337)](http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:38337).
- ![is a](https://camo.githubusercontent.com/cff1412b81e8bb6c5e3c1fac35ab9a3e581d2450/687474703a2f2f7777772e6562692e61632e756b2f63686562692f696d616765732f6f6e746f6c6f67792f636865636b65642f69735f612e676966) is a [nucleobase analogue (CHEBI:67142)](http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:67142)

**Comment by G-Owen** [comment]
The entry had 2-star status - (i.e. it arose from a batch loading that has not yet been checked). The "is_a 9,11,15-octadecatrienoic acid" classification is clearly nonsense (one of about 30 similar mis-assignments during the loading of this particular batch) and has now been deleted! I have now added additional classification terms, links, citations, etc. and upgraded the entry to "3-star" status.

Thanks for drawing it to our attention.

Kind regards,
Gareth

**Comment by cviner** [comment]
Thanks!
