### ISSUE TITLE
CHEBI:90631

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3148]
Dear ChEBI curators;
I would like to know if you can modify ChEBI:90631 to add stereo bonds 5S and 15S instead of the current flat bonds, or if you would prefer that I submit a new compound.
Thanks in advance for contacting me asap for this matter.
Best,
Lucila

**Comment by G-Owen** [comment]
Hi Lucila,
It's probably safest if we don't change CHEBI:90631 - I have created CHEBI:131564 instead.

Kind regards,
Gareth
