### ISSUE TITLE
CHEBI:34896 reaches role entity via is_a relation

### ISSUE THREAD

**Issue by bitbarbie** [ebi-chebi/ChEBI#3149]
The graph view of CHEBI:34896 reveals that it is possible to reach the role root entity when following the is_a relations that belong (only?) to the structure classification. Maybe at least one relation in this path should be has_role? 

![reach_role](https://cloud.githubusercontent.com/assets/3034317/13778570/eeebcf4a-eab6-11e5-8560-ee1dc35a77a1.png)

**Comment by muthuvenkat** [comment]
Thanks @bitbarbie, its fixed now.
