### ISSUE TITLE
wrong inchikey for CHEBI:28749 in obo-file (download) 

### ISSUE THREAD

**Issue by bitbarbie** [ebi-chebi/ChEBI#3150]
In the current obo retrieved from the download link at the chebi webpage CHEBI:28749 (aryl β-D-glucoside) is annotated with the following line:

_synonym: "NEZJDVYDSZTRFS-RMPHRYRLSA-N" RELATED InChIKey [ChEBI:]_

The webpage entry has no InChIKey-entry!

Searching CHEBI with this InChIKey, it reveals CHEBI:8083 (Phenyl beta-D-glucopyranoside), which is on a first sight not even in the tree of CHEBI:28749.

**Comment by muthuvenkat** [comment]
@bitbarbie  Thanks for reporting its fixed in the new OBO file
