### ISSUE TITLE
wrong average mass for CHEBI:17403

### ISSUE THREAD

**Issue by bitbarbie** [ebi-chebi/ChEBI#3151]
For CHEBI:17403 (3-chloro-L-alanine) a mass of 123.009 is annotated whereas for its tautomere CHEBI:66916 (alanine zwitterion) a mass of 123.53800 is annotated. enviPat calculates an average mass of 123.5379 from the molecular formula which seems acceptable similar to the zwitterion mass but not to the first one.

**Comment by G-Owen** [comment]
This looks to me to be a developer issue.

For C3H6ClNO2, ACD chemsketch gives values of:
123.5382 for the average mass and
123.008706 for the monoisotopic mass

The Mol Wt on CHEBI:17403 has been calculated using whatever Ketcher/Indigo structures now use and it is wrong (123.009).
This is the monoisotopic weight, NOT the molecular weight

In contrast, CHEBI:58123, which has the same formula and was produced with ChemAxon, has a displayed molecular weight of 123.53800 (which is correct).

**Comment by muthuvenkat** [comment]
@bitbarbie, Sorry for the delay, but its fixed now.
