### ISSUE TITLE
Formula change for CHEBI:78648 please

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3155]
Dear ChEBI curators;
This CHEBI still has its old formula which lacks an R, can you please modify it so that we can balance the reactions in RHEA?
Thanks for your help,
Lucila

**Comment by aimol** [comment]
Dear ChEBI curators;
I just realized CHEBI:78648 might be the same as CHEBI:67090, can you double check and merge if necessary?
Thanks!
Lucila

**Comment by G-Owen** [comment]
Hi Lucila,

The entries have now been merged and the formula issue has been sorted. The parent ID is CHEBI:78648.

Kind regards,
Gareth
