### ISSUE TITLE
programmatic access to CHEBI instances

### ISSUE THREAD

**Issue by deustp01** [ebi-chebi/ChEBI#3156]
In the tool that Reactome curators use for annotation, we have a wizard that takes the numerical identifier of the CHEBI entry for a chemical and returns all the information needed to create a local copy of the CHEBI record. Within the past week, approximately, it has stopped working. Instead it returns a 301 error. Has something changed on your side in either the format or the location of your records? Could you point us to the relevant documentation so our developers can patch our tool? (I looked a bit but don't really know what to look for and couldn't find anything.)
If you need more information, please let me know.
Thanks.
Peter D'Eustachio
editor, Reactome

**Comment by muthuvenkat** [comment]
Our web services and download files are working fine. We haven't changed anything recently. May be if you let me know how you are accessing our data (Via Web services or FTP files) I can have a look. Can you please check with your developers and send me some more information regarding this issue. 

Thanks,
Venkat

**Comment by deustp01** [comment]
Thanks. I've asked the developers to add that information as a comment to this ticket.
Peter
