### ISSUE TITLE
NTR: methane clathrates

### ISSUE THREAD

**Issue by pbuttigieg** [ebi-chebi/ChEBI#3158]
Over at ENVO, we're adding a class for `methane clathrate`https://github.com/EnvironmentOntology/envo/issues/308. We'd like to link to CHEBI's clathrate classes, but I haven't spotted `methane clathrate`.
Could this be added?

xref: https://en.wikipedia.org/wiki/Methane_clathrate

**Comment by G-Owen** [comment]
Now done - see CHEBI:132140
