### ISSUE TITLE
CHEBI:94191 and CHEBI:132082 should probably be merged

### ISSUE THREAD

**Issue by sabrinatoro** [ebi-chebi/ChEBI#3159]
Hello Chebi curators, 

I submitted a new record: Entinostat (CHEBI:132082). I had some difficulties doing so (this is the first submission I make directly), and after managing to enter a structure, I got a message saying that the structure already existed (CHEBI:94191). 
However, I cannot delete my submission (I only get the "view" or "edit" options). 

So I guess that either my submission (CHEBI:132082) should be merged to CHEBI:94191, or my submission (CHEBI:132082) should be deleted and synonyms should be added to CHEBI:94191.

Thank you! 
Sabrina, ZFIN

**Comment by G-Owen** [comment]
Hi Sabrina,
The records have been merged. (the parent id is CHEBI:132082).

Kind regards,
Gareth
