### ISSUE TITLE
InChi/SMILES are synonyms in OWL export

### ISSUE THREAD

**Issue by dcmcshan** [ebi-chebi/ChEBI#3160]
The OWL export collapses InChi and SMILES fields into hasRelatedSynonym.  This makes the formula less accessible, as we have to look for regular expressions in synonyms to identify these representations.  A better approach might be to use the Chemical Information Ontology - it has classes for "Molecular Formula", "Canonical SMILES", "IUPAC InChi", etc.  For reference, this is what PubChemRDF does.

Thanks!

**Comment by muthuvenkat** [comment]
All the OWL classes have axioms with a type #InChIKey, #InChI, #SMILES. 

`<owl:Axiom>
<owl:annotatedTarget rdf:datatype="http://www.w3.org/2001/XMLSchema#string">COc1cc2CCN(C)[C@H]3Cc4ccc(Oc5cc(C[C@@H]6N(C)CCc7cc(OC)c(O)c(Oc1cc23)c67)ccc5O)cc4</owl:annotatedTarget>
        <oboInOwl:hasDbXref rdf:datatype="http://www.w3.org/2001/XMLSchema#string">ChEBI:</oboInOwl:hasDbXref>
        <owl:annotatedSource rdf:resource="http://purl.obolibrary.org/obo/CHEBI_10"/>
        <oboInOwl:hasSynonymType rdf:resource="http://purl.obolibrary.org/obo/chebi#SMILES"/>
        <owl:annotatedProperty rdf:resource="http://www.geneontology.org/formats/oboInOwl#hasRelatedSynonym"/>
</owl:Axiom> ` 

I would also recommend to use OBO file which is lot simpler and smaller. Below is the information for the whole entry while comparing to the above one which is only for SMILES.

`[Term]
id: CHEBI:10
name: (+)-Atherospermoline 
def: "An isoquinoline that has formula C36H38N2O6." []
synonym: "(+)-Atherospermoline" EXACT [KEGG COMPOUND:]
synonym: "C36H38N2O6" RELATED FORMULA [KEGG COMPOUND:]
synonym: "COc1cc2CCN(C)[C@H]3Cc4ccc(Oc5cc(C[C@@H]6N(C)CCc7cc(OC)c(O)c(Oc1cc23)c67)ccc5O)cc4" RELATED SMILES [ChEBI:]
synonym: "InChI=1S/C36H38N2O6/c1-37-13-11-23-18-31(41-3)32-20-26(23)27(37)15-21-5-8-25(9-6-21)43-30-17-22(7-10-29(30)39)16-28-34-24(12-14-38(28)2)19-33(42-4)35(40)36(34)44-32/h5-10,17-20,27-28,39-40H,11-16H2,1-4H3/t27-,28-/m0/s1" RELATED InChI [ChEBI:]
synonym: "XGEAUXVPBXUBKN-NSOVKSMOSA-N" RELATED InChIKey [ChEBI:]
xref: KEGG COMPOUND:C11141 "KEGG COMPOUND"
xref: KEGG COMPOUND:21008-67-3 "CAS Registry Number"
xref: KNApSAcK:C00001814 "KNApSAcK"
is_a: CHEBI:24922`

We generate the OWL file from the OBO file using toolkits. 

I hope this helps.
