### ISSUE TITLE
new term request: CHIR-090; N-{(1s,2r)-2-Hydroxy-1-[(Hydroxyamino)carbonyl]propyl}-4-{[4-(Morpholin-4-Ylmethyl)phenyl]ethynyl}benzamide

### ISSUE THREAD

**Issue by dsiegele** [ebi-chebi/ChEBI#3164]
To annotate CHIR-090 sensitivity/resistance phenotypes in OMP we'd like to request a CHEBI term for 
N-{(1s,2r)-2-Hydroxy-1-[(Hydroxyamino)carbonyl]propyl}-4-{[4-(Morpholin-4-Ylmethyl)phenyl]ethynyl}benzamide
other synonyms: 
.....PubChem CID:11546620 https://pubchem.ncbi.nlm.nih.gov/compound/11546620#section=Top

Thank you!

Debby

**Comment by stevet7** [comment]
Hi Debby,
I have added this compound to CHEBI with ID #134107.
Apologies for the slow response time, this is due to a manpower shortage.

Kind regards,
Steve
