### ISSUE TITLE
Expanded entry request for CHEBI:20689 (6-O-methylguanine)

### ISSUE THREAD

**Issue by cviner** [ebi-chebi/ChEBI#3166]
It would be great if the preliminary entry for [CHEBI:20689 6-O-methylguanine](http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:20689) could be expanded into a full entry. This could largely be modeled after the version of this compound with the carbohydrate moiety ([CHEBI:27549 O<sup>6</sup>-methyl-2&prime;-deoxyguanosine](http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:27549)). O<sup>6</sup>-methylguanine should be added as a synonym. 

The below citation could also be added:

[Clark, T. A., Spittle, K. E., Turner, S. W., & Korlach, J. (2011). Direct detection and sequencing of damaged DNA bases. Genome Integrity, 2(1), 10.](http://doi.org/10.1186/2041-9414-2-10)

**Comment by M-Ennis** [comment]
Hi Coby

As requested I've now curated a full entry for 6-O-methylguanine (see 
http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:20689).

Thanks again for your interest in ChEBI.

Regards,
Marcus

--------------------------------------------
Marcus Ennis, CChem, MRSC
ChEBI Curation Consultant
--------------------------------------------
European Bioinformatics Institute (EMBL-EBI)
Wellcome Trust Genome Campus
Hinxton, Cambridge
CB10 1SD
United Kingdom
---------------------------------------------
La Jolla Institute for Allergy and Immunology
9420 Athena Circle
La Jolla
CA 92037
USA
----------------------------------
t: +44 (0)1638 50 81 95 (office)
    +44 (0)7866 29 29 26 (mobile)

e: mennis@ebi.ac.uk
    marcus.ennis@mail.com

----------------------------------

Visit ChEBI at www.ebi.ac.uk/chebi

**Comment by cviner** [comment]
Thank you!
