### ISSUE TITLE
CHEBI:72582 has wrong structure

### ISSUE THREAD

**Issue by alanbridge** [ebi-chebi/ChEBI#3176]
Hi ChEBI 

very sorry for this mistake created by myself - the submitted structure for ChEBI:72582 is supposed to have a 18 carbon sphingoid base:

"A mannosylinositol phosphorylceramide(1−) having an acyl group attached to the ceramide nitrogen and hydroxylation at C4 of the C18 sphingoid base; major species at pH 7.3..."

Unfortunately the structure is actually too short - it only has a 16 carbon base. The attached molfile (with a txt extension to make it compatible with GitHub) should fix this. 

Sorry for the trouble, 

All the Best, Alan

**Comment by G-Owen** [comment]
Hopefully now done (couldn't see any sign of the molfile - sometimes attaching files seems fine with GitHub, other times not - don't know why!) Sorry it took so long to get to.

Thanks for your patience,
Gareth
