### ISSUE TITLE
New term requests: 8-oxoadenine and 8-hydroxyadenine

### ISSUE THREAD

**Issue by cviner** [ebi-chebi/ChEBI#3179]
It would be great if 8-oxoadenine and 8-hydroxyadenine (7,8-dihydro-8-oxoadenine) could be added.

Details for 8-oxoadenine are already available from ChemSpider: http://www.chemspider.com/Chemical-Structure.11178462.html

Both would have HAS FUNCTIONAL PARENT relationships to [adenine (CHEBI:16708)](http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:16708).

A couple of relevant references:
- [Talhaoui I, Couvé S, Ishchenko AA, Kunz C, Schär P, Saparbaev M. 7,8-Dihydro-8-oxoadenine, a highly mutagenic adduct, is repaired by Escherichia coli and human mismatch-specific uracil/thymine-DNA glycosylases. _Nucleic Acids Res._ 2013;41(2):912-23.](http://doi.org/10.1093/nar/gks1149)
- [Clark TA, Spittle KE, Turner SW, Korlach J. Direct detection and sequencing of damaged DNA bases. _Genome Integr._ 2011;2:10.](http://doi.org/10.1186/2041-9414-2-10)

**Comment by stevet7** [comment]
Hi, 
I've added 8-oxoadenine (CHEBI:134104) and 8-hydroxyadenine (CHEBI:134105).

Kind regards,
Steve
