### ISSUE TITLE
New term requests: N2,3-ethenoguanine (N2,3-εG) and 1,N2-ethenoguanine (1,N2-εG)

### ISSUE THREAD

**Issue by cviner** [ebi-chebi/ChEBI#3182]
It would be great if N2,3-ethenoguanine (N2,3-εG) and 1,N2-ethenoguanine (1,N2-εG) could be added.

N2,3-εG is on PubChem: https://pubchem.ncbi.nlm.nih.gov/compound/176480

The 1,N2-εG nucleoside is on PubChem: https://pubchem.ncbi.nlm.nih.gov/compound/481078

Both would have HAS FUNCTIONAL PARENT relationships to [guanine (CHEBI:16235)](http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:16235).

A couple of relevant references:
- [Prem D. Sattsangi, Nelson J. Leonard & Charles R. Frihart (1977). 1,N2-Ethenoguanine and N2,3-ethenoguanine. Synthesis and comparison of the electronic spectral properties of these linear and angular triheterocycles related to the Y bases. _The Journal of Organic Chemistry_, 42, 3292-3296.](http://doi.org/10.1021/jo00440a020)
- [Chang SC, Fedeles BI, Wu J, et al. Next-generation sequencing reveals the biological significance of the N(2),3-ethenoguanine lesion in vivo. _Nucleic Acids Res._ 2015;43(11):5489-500.](http://doi.org/10.1093/nar/gkv243)

**Comment by stevet7** [comment]
Hi, 
These two entities have been added to CHEBI

N2,3-ethenoguanine (CHEBI:134095)
1,N2-ethenoguanine (CHEBI:134096)

Kind regards,
Steve
