### ISSUE TITLE
New term request: alpha-Putrescinylthymine

### ISSUE THREAD

**Issue by cviner** [ebi-chebi/ChEBI#3184]
It would be great if α-Putrescinylthymine / 5-(4-Aminobutylaminomethyl)uracil could be added.

Its details are already available from PubChem: https://pubchem.ncbi.nlm.nih.gov/compound/188337

It would have a HAS FUNCTIONAL PARENT relationship to [thymine (CHEBI:17821)](http://www.ebi.ac.uk/chebi/searchId.do;?chebiId=CHEBI%3A17821).

A relevant reference:

- [Kropinski, A. M. B., R. J. Bose, and R. A. J. Warren. "5-(4-Aminobutylaminomethyl)Uracil, An Unusual Pyrimidine From The Dioxyribonucleic Acid Of Bacteriophage .Phi.W-14". _Biochemistry_ 12.1 (1973): 151–157.](http://doi.org/10.1021/bi00725a025)

**Comment by G-Owen** [comment]
Hi Coby,
Now added: α-putrescinylthymine (CHEBI:132931).

Kind regards,
Gareth

**Comment by cviner** [comment]
Thanks, Gareth! I especially appreciated the description mentioning its being a hypermodified base in φW&#x2011;14 and the detailed reference list.
