### ISSUE TITLE
CHEBI:65658 (cordyheptapeptide A) has minor error in definition

### ISSUE THREAD

**Issue by baoilleach** [ebi-chebi/ChEBI#3186]
The SMILES string for cordyheptapeptide A agrees with my understanding but the definition has an error. Instead of "D-phenylalanyl" it should be "N-methyl-D-phenylalanyl". See Citation 2 on the ChEBI page.

**Comment by G-Owen** [comment]
Thanks for letting us know. Now fixed.

Kind regards,
Gareth
