### ISSUE TITLE
questionable has-role relationship between protein polypeptide chain and mouse metabolite

### ISSUE THREAD

**Issue by cmungall** [ebi-chebi/ChEBI#3189]
CHEBI has an axiom:

    'protein polypeptide chain' SubClassOf has_role some 'mouse metabolite'

This property would be inherited by all protein polypeptide chains, not just ones synthesized in mice. This seems dubious.

It looks like CHEBI previously had `peptide SubClassOf has_role some 'mouse metabolite'`, which was even more problematic.

**Comment by muthuvenkat** [comment]
Thanks @cmungall its fixed now.
