### ISSUE TITLE
need synonymtypedef for "RELATED MASS" synonym type

### ISSUE THREAD

**Issue by zebrafishmine** [ebi-chebi/ChEBI#3191]
ftp://ftp.ebi.ac.uk/pub/databases/chebi/ontology/chebi.obo

The file above has a synonym type not defined in the header.

Could "RELATED MASS" be defined with the tag "synonymtypedef" in the obo file header?  This is currently preventing us from loading the ontology.

Thanks so much for your time!
Sierra (ZFIN, zebrafish model organism database)

**Comment by muthuvenkat** [comment]
Thanks @zebrafishmine for reporting. Its fixed now, please try and let us know.
