### ISSUE TITLE
New term request: hydroxy-CBDs

### ISSUE THREAD

**Issue by fehrhart** [ebi-chebi/ChEBI#3193]
Hi all,

 please consider adding some hydroxy-cannabidiols in the database.  According to this reference (http://www.ncbi.nlm.nih.gov/pubmed/?term=21704641) cannabidiol (CBD) is hydroxylated by cytochrome P450 to 6α-OH-, 6β-OH-, 7-OH-, 1″-OH-, 2″-OH-, 3″-OH-, 4″-OH-, and 5″-OH-CBD. 

Best regards,
Freddie

**Comment by G-Owen** [comment]
Hi Freddie,

The class term hydroxy-cannabidiol (CHEBI:133048) is now in ChEBI. It currently has 8 child terms (the CBDs described in PMID 21704641:
1''-hydroxycannabidiol (CHEBI:133056)
2''-hydroxycannabidiol (CHEBI:133058)
3''-hydroxycannabidiol (CHEBI:133059)
4''-hydroxycannabidiol (CHEBI:133055)
5''-hydroxycannabidiol (CHEBI:133062)
6α-hydroxycannabidiol (CHEBI:133049)
6β-hydroxycannabidiol (CHEBI:133052)
7-hydroxycannabidiol (CHEBI:133053)

Kind regards,
Gareth
