### ISSUE TITLE
new term request: Cutin-1

### ISSUE THREAD

**Issue by mah11** [ebi-chebi/ChEBI#3195]
To be used in a PomBase FYPO logical definition.

IUPAC name: N-carbamoyl-2-(triphenyl-λ5-phosphanylidene)acetamide
Human-friendly name: Cutin-1*
Paper: PMID:26869222
CAS Registry Number: 53296-08-5

As to where to place it in the ontology, I will need your input. Some web pages I found may help - http://www.chemicalregister.com/find/Find.asp?SearchTy=Product&SearchSu=53296-08-5&SearchKe=AllKey&SearchLo=ALL&x=0&y=0
http://www.molbase.com/en/cas-53296-08-5.html

*Unfortunately, this appears to be structurally and functionally totally unrelated to the plant cutins represented by CHEBI:23417.

The paper also briefly mentions a Cutin-2 (CAS Registry Number: 957489-42-8), but we don't have an immediate need for a CHEBI term for it.

**Comment by G-Owen** [comment]
Hi Midori,

Cutin-1 (CHEBI:133750) is now in ChEBI. It should be fully searchable tomorrow morning.

Kind regards,
Gareth
