### ISSUE TITLE
Non-ascii characters in CHEBI:71190 MOL file

### ISSUE THREAD

**Issue by smoretti** [ebi-chebi/ChEBI#3196]
Hi

CHEBI:71190 contains non-visible non-ascii characters at the top of its mol file.
`od -c ChEBI_71190.mol | head` to view this.
`perl -i -pe 's/[^[:ascii:]]//g' ChEBI_71190.mol` to fix this.

This may disrupt some software.

Regards

**Comment by adekker2** [comment]
Thanks for bringing our attention to this issue, 

the molfile has been fixed now.

Best Regards,
ChEBI Team.
