### ISSUE TITLE
ChEBI Submission tool - Species entry GUI not working

### ISSUE THREAD

**Issue by photocyte** [ebi-chebi/ChEBI#3197]
Hi there,

I'm trying to enter species information for a new metabolite ( Submission ID 10261), however when entering the species information (e.g. Photinus pyralis) into the requisite "* Species Name" text box under the "Species" tab, the entered text immediately disappears upon clicking on any other GUI element.  This is reproducible under Safari, Firefox, and Chrome.   Adding a source type / source accession first then trying to add the species information doesn't fix it either.

Best,
-Tim

**Comment by adekker2** [comment]
Thanks for reporting this bug, it has now been fixed and is expected to be deployed tomorrow.

If you find any other unexpected behaviour please let us know.

Kind Regards,
Adriano.
