### ISSUE TITLE
Inconsistency between ChEBI and GO: vitamin B6 compounds

### ISSUE THREAD

**Issue by paolaroncaglia** [ebi-chebi/ChEBI#3198]
Hello,

Stemming from https://github.com/geneontology/go-ontology/issues/12665

GO has:
GO:0042823 pyridoxal phosphate biosynthetic process points to CHEBI:597326 pyridoxal 5'-phosphate(2-)
GO:0042819 vitamin B6 biosynthetic process points to CHEBI:27306 vitamin B6

ChEBI has:
pyridoxal 5'-phosphate(2−) (CHEBI:597326) is conjugate base of pyridoxal 5'-phosphate (CHEBI:18405) 
pyridoxal 5'-phosphate (CHEBI:18405) is a vitamin B6 phosphate (CHEBI:36970)
vitamin B6 phosphate (CHEBI:36970) has functional parent vitamin B6 (CHEBI:27306)

So vitamin B6 phosphate is a derivative of vitamin B6 according to ChEBI.
But it also seems that vitamin B6 refers to a group of chemically very similar compounds which can be interconverted in biological systems. If this is the case, would you consider having a grouping term that GO could refer to for "vitamin B6 metabolism", and have all compounds under it as is_a children?

Thanks,

Paola

**Comment by paolaroncaglia** [comment]
Good morning ChEBI curators,
I was wondering if there's any news on this one, please?
Many thanks in advance for your help,
Paola

**Comment by stevet7** [comment]
Hi Poala,

I've changed the 'vitamin B6 phosphate (CHEBI:36970) has functional parent vitamin B6 (CHEBI:27306)'
to vitamin B6 phosphate (CHEBI:36970) is a vitamin B6 (CHEBI:27306), as the phosphates are also biologically active forms of vitamin B6. So now the term 'vitamin B6' captures the parent compounds (pyridoxal, pyridoxamine, pyridoxic acid and pyridoxine) and their phosphates as a subclass (the individual phosphates have functional parent links to the individual parents).

Hope this makes sense and you are OK with the change.
Kind regards,
Steve

**Comment by paolaroncaglia** [comment]
Hi @stevet7 ,
Yes, that's exactly what we were hoping for! Thanks. I'll close this ticket now.
