### ISSUE TITLE
Structure for CHEBI:131871 please

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3199]
Dear curators;
I would really appreciate if you could add a structure just like the one in CHEBI:131727 to CHEBI:131871, I need it for a reaction in RHEA. Thanks in advance for your help.
Lucila

**Comment by aimol** [comment]
Actually, I need a different structure for CHEBI:131871, can you please a

dd this mol.file?

**Comment by G-Owen** [comment]
Hi Lucila,
Hopefully a suitable structure is now in place - I will close the ticket.
Best regards,
Gareth
