### ISSUE TITLE
CHEBI:28913 please update name AND structure to allow new (E)-hex-2-enal

### ISSUE THREAD

**Issue by ANiknejad** [ebi-chebi/ChEBI#3201]
Hello ChEBI team,

I tried to submit a new Chebi compound 

'(E)-hex-2-enal' 

but it was refused, saying 'structure is not unique, see CHEBI:28913' which is weird...

Thank you for your help,
Cheers,

Anne

**Comment by G-Owen** [comment]
Hi Anne,
CHEBI:28913 had the name 'leaf aldehyde', which is actually a synonym for (E)-hex-2-enal. I have now renamed it and marked it up to 3-star status. You should now be able to compete your submission - we will merge it with CHEBI:28913.

Sorry for the inconvenience caused.

Kind regards,
Gareth
