### ISSUE TITLE
OWL for CHEBI is still non-standard

### ISSUE THREAD

**Issue by cmungall** [ebi-chebi/ChEBI#3202]
Continuation of #3105 

The chebi OWL on the ftp site has been fixed to use ROBOT/OWLAPI than a historic native mapping

However, the OWL is still non-standard. For example it uses this for has-part http://purl.obolibrary.org/obo/chebi#BFO_0000051

When converting from obo, the correct thing to do is to put the CURIE ID in the xref for the Typedef stanza

This is the current stanza

```
[Typedef]
id: has_part
name: has part
is_cyclic: false
is_transitive: true
xref: BFO_0000051
```

the xref is incorrect, it should be

```
xref: BFO:0000051
```

**Comment by adekker2** [comment]
I believed this one has been fixed so I'm closing it now.
