### ISSUE TITLE
Need some changes to CHEBI:84973

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3206]
Can you please change the formula of CHEBI:84973 to C21H39O7P and the mol file exactly like that in ChEBI: 78279? Otherwise the Rhea reaction wont be balanced when using CHEBI:84973.
Thanks in advance for your help,
Lucila

**Comment by G-Owen** [comment]
Hi Lucila,
Sorry this took so long! I think it is now sorted - please take a look and let me know if anything is wrong.
Kind regards,
Gareth

**Comment by aimol** [comment]
Thank you Gareth!
