### ISSUE TITLE
Newly submitted ChEBI:133899 needs correction

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3207]
Sorry, I now remember I can change this using the submission tool, please disregard this request.

Hi ChEBI curators,
I just realized I made a mistake when drawing this compound and I made 9Z instead of 9E, can you please replace the mol file to represent 9E?
Thanks for your help and apologies for the inconvenience,
Lucila

**Comment by G-Owen** [comment]
Hi Lucila,
No problem - I'll close the ticket.
