### ISSUE TITLE
isoproturon should be classified as phenylurea herbicide

### ISSUE THREAD

**Issue by cmungall** [ebi-chebi/ChEBI#3210]
The current CHEBI classification as urea herbicide is consistent with but less specific than the classification as phenylurea here (which CHEBI xrefs):

http://www.alanwood.net/pesticides/class_herbicides.html

**Comment by G-Owen** [comment]
Have now created a class of phenylureas (CHEBI:134043) and am shifting appropriate entities from the 'ureas' class to the new class.
