### ISSUE TITLE
NTR: Volatile organic compounds

### ISSUE THREAD

**Issue by cmungall** [ebi-chebi/ChEBI#3212]
* SOURCE: https://en.wikipedia.org/wiki/Volatile_organic_compound
* DEF: Volatile organic compounds (VOCs) are organic chemicals that have a high vapor pressure at ordinary room temperature. Their high vapor pressure results from a low boiling point, which causes large numbers of molecules to evaporate or sublimate from the liquid or solid form of the compound and enter the surrounding air, a trait known as volatility.
* Examples: isoprene, benzene

This could be represented using a role 'volatility'. VOC could then be a composition of organic compound AND has-role SOME volatility

**Comment by G-Owen** [comment]
See CHEBI:134179
