### ISSUE TITLE
NTR: polybrominated diphenyl ether

### ISSUE THREAD

**Issue by cmungall** [ebi-chebi/ChEBI#3213]
https://en.wikipedia.org/wiki/Polybrominated_diphenyl_ethers

syn/abbrev: PBDE

```
is_a: CHEBI:37141 ! organobromine compound
```

For role, consider environmental contaminant

**Comment by stevet7** [comment]
Hi Chris,
This term has been added to CHEBI with ID#134094.

Kind regards,
Steve
