### ISSUE TITLE
NTR: perfluorinated compound

### ISSUE THREAD

**Issue by cmungall** [ebi-chebi/ChEBI#3215]
https://en.wikipedia.org/wiki/Perfluorinated_compound

```
is_a: CHEBI:37143 ! organofluorine compound
```

Def:

an organofluorine compound containing only carbon-fluorine bonds (no C-H bonds) and C-C bonds but also other heteroatoms. PFCs have properties that represent a blend of fluorocarbons (containing only C-F and C-C bonds) and the parent functionalized organic species

Consider adding an environmental contaminant role

**Comment by G-Owen** [comment]
Now added (CHEBI:134091).

Best regards,
Gareth
