### ISSUE TITLE
NTR: chlorofluorocarbon

### ISSUE THREAD

**Issue by cmungall** [ebi-chebi/ChEBI#3217]
https://en.wikipedia.org/wiki/Chlorofluorocarbon

```
is_a: CHEBI:50860 ! organic molecular entity
```

syn/abbrev: CFC

consider roles as environmental contaminant and GHG

**Comment by G-Owen** [comment]
Hi Chris,
Now added - chlorofluorocarbon (CHEBI:134024).

Cheers,
Gareth
