### ISSUE TITLE
NTR: 1,4-dioxin --- and general classification of dioxins

### ISSUE THREAD

**Issue by cmungall** [ebi-chebi/ChEBI#3218]
CHEBI has no class with a label or synonym 'dioxin'. Perhaps not surprising given this is a broad term. 

WP has a broad class: https://en.wikipedia.org/wiki/Dioxins_and_dioxin-like_compounds

But it also has the 'canonical' dioxin:
https://en.wikipedia.org/wiki/1,4-Dioxin

This doesn't appear to be in CHEBI

Then there is 
https://en.wikipedia.org/wiki/Polychlorinated_dibenzodioxins

Which *does* exist in CHEBI
CHEBI:36682 ! polychlorinated dibenzodioxine

However, this has no direct role associated with it. It should be classified as an environmental contaminant.

I'm not exactly sure what the best course of action is, perhaps

 * add 1,4 dioxin
 * add 'dioxin' as a BROAD syn to this term AND/OR as a syn of CHEBI:36682
 * assign role to CHEBI:36682 
 * consider a very broad class grouping dioxin and dioxin-like compounds?

**Comment by G-Owen** [comment]
add 1,4 dioxin _Now done (CHEBI:134044)_
add 'dioxin' as a BROAD syn to this term AND/OR as a syn of CHEBI:36682 _Done (for both)_
assign role to CHEBI:36682  _Done [has_role persistent organic pollutant (CHEBI:77853)]_
consider a very broad class grouping dioxin and dioxin-like compounds? _Done. 

- have created **polychlorinated dibenzodioxines and related compounds** (CHEBI:134045) with child terms polybromobiphenyl (new; CHEBI:134049), polychlorobiphenyl (CHEBI:53156), polychlorinated dibenzodioxine (CHEBI:36682), polychlorinated dibenzofuran (new; CHEBI:134046).

Let me know if there are any terms or relationships missing.

Best regards,
Gareth
