### ISSUE TITLE
wrong tag - RELATED FORMULA [ChEBI]

### ISSUE THREAD

**Issue by bitbarbie** [ebi-chebi/ChEBI#3219]
The last obo release (2016-11-01) contains several entries with two tags RELATED FORMULA, of which one contains a mass instead of a formula. Please find an example below and the list of ids attached.

Example:
[Term]
id: CHEBI:4882
name: ethchlorvynol
alt_id: CHEBI:119469
[...]
synonym: "C7H9ClO" RELATED FORMULA [KEGG COMPOUND]
synonym: "144.59900" RELATED FORMULA [ChEBI]
[...]

All Ids:

[chebi20161101_formula_issue.txt](https://github.com/ebi-chebi/ChEBI/files/615728/chebi20161101_formula_issue.txt)

**Comment by adekker2** [comment]
Thanks for reporting this, we have fixed this issue and the next release on 1st December should not have such cases. Please let us know if this or any other issue is found. Best Regards, Adriano.
