### ISSUE TITLE
InChIKey Tag contains "InChIKey=" prefix

### ISSUE THREAD

**Issue by bitbarbie** [ebi-chebi/ChEBI#3220]
In the recent obo release (2016-11-01) the InChIKey-Tag of CHEBI:85624 contains a misplaced "InChIKey=" in front of the InChIKey instead of only the InChIKey (see below).
Maybe this Term is going to be curated anyway then the issue can be closed without comment.

[Term]
id: CHEBI:85624
name: isoarginine
def: "An organic molecular entity that has formula C6H15N4O2." []
synonym: "C6H15N4O2" RELATED FORMULA [SUBMITTER]
[...]
synonym: "InChIKey=XGSVDFYDYLLWRN-SCSAIBSYSA-O" RELATED InChIKey [ChEBI]
[...]

**Comment by adekker2** [comment]
The December version has it fixed
