### ISSUE TITLE
Downloading set of natural products

### ISSUE THREAD

**Issue by janelomax** [ebi-chebi/ChEBI#3221]
Hi - I'd really like to get the set of all CHEBI products that are derived from a natural source. I don't want to have to install the DB locally. 

I tried searching for 'natural product' which gave me ~3000 results - brilliant - but I am only allowed to view or download the first 1000 (can you not allow download of all results, even if the display is limited?)

So I then had a look in your downloads and found a file compound_origins.tsv which seems to contain 8000 entities originating from organisms, so I've used this in combination with compounds.tsv to get the CHEBI names.

What I really need in addition though is the CHEBI synonyms, is there a way I can get these?

thanks.

**Comment by adekker2** [comment]
Hi,

for your first question, you could try to go to Advanced Search
in Text Queries and search for * in ALL SPECIES.
increase the amount of results to 30k on top left. 
and search.
when you get the results, on the top right you have 3 options of download format: TSV, XML and SDF.

for your second question, you need the names.tsv file.
the link between all 3 files will be the compound_id
so names and origins compound_id point to id in compounds.tsv
and within the compounds.tsv id points to parent_id until is null.

I hope it helps, you can read the manuals here and here:
http://www.ebi.ac.uk/chebi/userManualForward.do
http://www.ebi.ac.uk/chebi/developerManualForward.do

If you need further help, please let us know,
Best Regards,
Adriano.

**Comment by janelomax** [comment]
Thanks Adriano, that’s useful.

As a quick follow-on Q - can you tell me what '(rel)-‘ means after a term name? Is it safe to strip these?

thanks

Jane

**Comment by G-Owen** [comment]
Hi Jane,
Further to Adrano's reply - Searching in the species table as he describes is a good start, but there are still a significant number of natural products that have not yet been included in the species table. Some of these can be found quite easily:
In the Advanced Search page, create and run the search as described by Adriano above (it found 13,049 answers when I tried it a few minutes ago). 
Click on Edit Search. In the Filter by Database section, and add the query:
**OR**       _contains a database cross-reference in_      **KNApSAcK** 
Then run the search again (currently finds 16,087 answers).

The (rel)- at the end (or the beginning) of a name is mostly found on 2-star entries. It means that only relative stereochemistry is shown. It generally means that there are two possibilities - either the stereochemistry is as shown in the structure and name (say, 1R,2R,5S) or it is the complete opposite (1S,2S,5R) - they don't know which. Determining which one is correct can be very difficult and time consuming - often it is not established until many years after a natural product was first reported in the literature.

Cheers,
Gareth
