### ISSUE TITLE
CHEBI:134058 has wrong structure, to delete or to correct and merge

### ISSUE THREAD

**Issue by ANiknejad** [ebi-chebi/ChEBI#3222]
Hi ChEBI team,

I am sorry for this compound I created recently, the structure is wrong, and actually the compound should be identical to CHEBI:92381, but I wanted to create 'N-palmitoyl dopamine' and this name is not reported at least as synonym in CHEBI:92381. Thoughts?

Many thanks in advance

Anne

**Comment by G-Owen** [comment]
Hi Anne,
I have now corrected the structure, merged the two entries and upgraded the merged entry to 3-star status. The parent ID is CHEBI:134058.

Kind regards,
Gareth
