### ISSUE TITLE
ATP wrongly classified as nucleoside?

### ISSUE THREAD

**Issue by dosumis** [ebi-chebi/ChEBI#3224]
ChEBI classifies ATP correctly as a purine nucleotide but also incorrectly as a purine nucleoside.

![image](https://cloud.githubusercontent.com/assets/112839/20808364/31ef58d2-b7fa-11e6-8731-e7b7635db2b7.png)

I may be missing something = I'm not a chemist - but any biologist would say this is incorrect.

Can this be fixed?  It is causing problems with classification in the GO.

Many thanks,
David

CC @valwood @hdrabkin

**Comment by hdrabkin** [comment]
yes nucleotide; tide = + phosphate
side = + sugar
so tide = base + sugar + phosphate
It isn't is_a nucleoside.
it could be has_part nucleoside + has_part phosphate

**Comment by stevet7** [comment]
I think the link that is causing the problems is 'adenosine phosphate is_a adenosines' which takes it up the nucleoside branch, so I have deleted it (it's been there since 2007!)

Cheers,
Steve

**Comment by dosumis** [comment]
Thanks!

> it's been there since 2007!

Odd this wasn't spotted during the process of integrating ChEBI into GO.

**Comment by dosumis** [comment]
Hiya,  There seems to be some lag with this fix showing up.  Do we need to wait for monthly release>

https://www.ebi.ac.uk/ols/ontologies/chebi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHEBI_15422

Many thanks again,
David
