### ISSUE TITLE
14 missing ChEBI relations

### ISSUE THREAD

**Issue by alanbridge** [ebi-chebi/ChEBI#3225]
Hi ChEBI 

reviewing some existing ChEBIs used in Rhea, we found a few missing relations - could you possibly add these?

Thanks and best regards, Alan

CHEBI:28610 is_a CHEBI:58168

CHEBI:74669 is_a CHEBI:58293
CHEBI:75034 is_a CHEBI:58293 

CHEBI:74670 is_a CHEBI:60000 

CHEBI:74671 is_a CHEBI:75063 
CHEBI:74965 is_a CHEBI:75063
CHEBI:74967 is_a CHEBI:75063 
CHEBI:74970 is_a CHEBI:75063

CHEBI:74667 is_a CHEBI:75279 
CHEBI:75017 is_a CHEBI:75279
CHEBI:75026 is_a CHEBI:75279
CHEBI:75062 is_a CHEBI:75279
CHEBI:75294 is_a CHEBI:75279 

CHEBI:72837 is_a CHEBI:75116

**Comment by G-Owen** [comment]
All now done.
Merged CHEBI:75294 with CHEBI:86106 (parent ID is CHEBI:75294).

Best regards,
Gareth
