### ISSUE TITLE
missing ChEBI relations

### ISSUE THREAD

**Issue by alanbridge** [ebi-chebi/ChEBI#3226]
Hi ChEBI 

please find below more suggested relations identified while reviewing Rhea reactions.

Best Regards, Alan 

CHEBI:75217 is_a CHEBI:36707
CHEBI:74892 is_a CHEBI:75066
CHEBI:74897 is_a CHEBI:75065
CHEBI:72834 is_a CHEBI:75243
CHEBI:72829 is_a CHEBI:75280
CHEBI:85090 is_a CHEBI:85110
CHEBI:85091 is_a CHEBI:85111 
CHEBI:61405 is_a CHEBI:85097

**Comment by G-Owen** [comment]
All now done. 
CHEBI:75217 has been merged with CHEBI:52450; the parent ID is 52450.
