### ISSUE TITLE
missing is_a CHEBI:90725 relations

### ISSUE THREAD

**Issue by alanbridge** [ebi-chebi/ChEBI#3227]
Hi ChEBI 

following on from the last couple of requests, here is another set of proposed relations identified during review of Rhea; all with the same parent. 

Best Regards, Alan 

CHEBI:74230 is_a CHEBI:90725
CHEBI:74228 is_a CHEBI:90725
CHEBI:74292 is_a CHEBI:90725
CHEBI:74304 is_a CHEBI:90725
CHEBI:74427 is_a CHEBI:90725
CHEBI:73980 is_a CHEBI:90725
CHEBI:74254 is_a CHEBI:90725
CHEBI:74261 is_a CHEBI:90725
CHEBI:74286 is_a CHEBI:90725
CHEBI:74290 is_a CHEBI:90725
CHEBI:74320 is_a CHEBI:90725
CHEBI:74313 is_a CHEBI:90725
CHEBI:74283 is_a CHEBI:90725
CHEBI:74288 is_a CHEBI:90725
CHEBI:74305 is_a CHEBI:90725
CHEBI:74663 is_a CHEBI:90725
CHEBI:73976 is_a CHEBI:90725
CHEBI:76419 is_a CHEBI:90725
CHEBI:74249 is_a CHEBI:90725
CHEBI:74263 is_a CHEBI:90725
CHEBI:74246 is_a CHEBI:90725
CHEBI:74294 is_a CHEBI:90725
CHEBI:74311 is_a CHEBI:90725
CHEBI:74316 is_a CHEBI:90725
CHEBI:74318 is_a CHEBI:90725

**Comment by G-Owen** [comment]
Now done!

Best regards,
Gareth
