### ISSUE TITLE
missing is_a CHEBI:90736 relations 

### ISSUE THREAD

**Issue by alanbridge** [ebi-chebi/ChEBI#3228]
Hi ChEBI,

please find below another set of missing relations identified during Rhea reaction review. 

Best Regards, Alan 

CHEBI:74229 is_a CHEBI:90736
CHEBI:74141 is_a CHEBI:90736
CHEBI:74291 is_a CHEBI:90736
CHEBI:74298 is_a CHEBI:90736
CHEBI:74424 is_a CHEBI:90736
CHEBI:65052 is_a CHEBI:90736
CHEBI:74247 is_a CHEBI:90736
CHEBI:74260 is_a CHEBI:90736
CHEBI:74285 is_a CHEBI:90736
CHEBI:74289 is_a CHEBI:90736
CHEBI:74319 is_a CHEBI:90736
CHEBI:74312 is_a CHEBI:90736
CHEBI:74282 is_a CHEBI:90736
CHEBI:74287 is_a CHEBI:90736
CHEBI:74086 is_a CHEBI:90736
CHEBI:74083 is_a CHEBI:90736
CHEBI:64868 is_a CHEBI:90736
CHEBI:74087 is_a CHEBI:90736
CHEBI:74259 is_a CHEBI:90736
CHEBI:74262 is_a CHEBI:90736
CHEBI:74233 is_a CHEBI:90736
CHEBI:74293 is_a CHEBI:90736
CHEBI:74306 is_a CHEBI:90736
CHEBI:74315 is_a CHEBI:90736
CHEBI:74317 is_a CHEBI:90736

**Comment by G-Owen** [comment]
Now done.

Best regards,
Gareth
