### ISSUE TITLE
missing roles: NAD/NADP has_role CHEBI:13193 (hydrogen acceptor) and NADH/NADPH has_role CHEBI:17499 (hydrogen donor)

### ISSUE THREAD

**Issue by alanbridge** [ebi-chebi/ChEBI#3229]
Hi ChEBI 

would you please consider adding the following relations? These deal with biochemical roles in the context of reactions.

CHEBI:57540 (NAD+) has_role CHEBI:13193 (hydrogen acceptor)
CHEBI:58349 (NADP+) has_role CHEBI:13193 (hydrogen acceptor)

CHEBI:57945 (NADH) has_role CHEBI:17499 (hydrogen donor)
CHEBI:57783 (NADPH) has_role CHEBI:17499 (hydrogen donor)

Thanks and Best Regards, Alan

**Comment by G-Owen** [comment]
Hi Alan,

Now done - sorry it took so long to get to these!
Thanks for you patience.

Gareth
