### ISSUE TITLE
Add new class or synonym: thionyl chloride

### ISSUE THREAD

**Issue by cmungall** [ebi-chebi/ChEBI#3231]
https://www.wikidata.org/wiki/Q409171 maps 'thionyl chloride' to 

 * [CHEBI:29290](http://purl.obolibrary.org/obo/CHEBI_29290) - thionyl dichloride

If this is correct, add a synonym to CHEBI:29290

parent ticket: https://github.com/cmungall/environmental-conditions/issues/5

**Comment by G-Owen** [comment]
A Google search suggests that the term 'thionyl chloride' is used much more widely than the more precise name, thionyl dichloride, so I have changed the ChEBI name to thionyl chloride; thionyl dichloride remains as a synonym.

Kind regards,
Gareth
