### ISSUE TITLE
NTR or synonym request: diethylethanolamine

### ISSUE THREAD

**Issue by cmungall** [ebi-chebi/ChEBI#3233]
Consider:

 * [CHEBI:52153](http://purl.obolibrary.org/obo/CHEBI_52153) - 2-diethylaminoethanol __ADD SYNONYM:__ diethylethanolamine _from:_ https://www.wikidata.org/wiki/Q21174182

From: https://github.com/cmungall/environmental-conditions/issues/5

**Comment by G-Owen** [comment]
Now done.

Best regards,
Gareth
