### ISSUE TITLE
NTR or synonym request: boron trioxide

### ISSUE THREAD

**Issue by cmungall** [ebi-chebi/ChEBI#3234]
Consider:

 * [CHEBI:30163](http://purl.obolibrary.org/obo/CHEBI_30163) - diboron trioxide __ADD SYNONYM:__ boron trioxide _from:_ https://www.wikidata.org/wiki/Q21172903

Parent ticket: https://github.com/cmungall/environmental-conditions/issues/5

**Comment by G-Owen** [comment]
Now done.

Best regards,
Gareth
