### ISSUE TITLE
missing is_a relations for CHEBI:65111

### ISSUE THREAD

**Issue by alanbridge** [ebi-chebi/ChEBI#3237]
Dear ChEBI, 

could you please add the following missing relations? 

Many thanks and best regards, Alan 

CHEBI:57379 is_a CHEBI:65111
CHEBI:57380 is_a CHEBI:65111
CHEBI:57394 is_a CHEBI:65111
CHEBI:64868 is_a CHEBI:65111
CHEBI:65052 is_a CHEBI:65111

CHEBI:65059 is_a CHEBI:65111
CHEBI:70827 is_a CHEBI:65111
CHEBI:71461 is_a CHEBI:65111
CHEBI:73856 is_a CHEBI:65111
CHEBI:73870 is_a CHEBI:65111

CHEBI:74068 is_a CHEBI:65111 
CHEBI:74069 is_a CHEBI:65111
CHEBI:74083 is_a CHEBI:65111
CHEBI:74087 is_a CHEBI:65111
CHEBI:74128 is_a CHEBI:65111

CHEBI:74141 is_a CHEBI:65111
CHEBI:74229 is_a CHEBI:65111
CHEBI:74233 is_a CHEBI:65111
CHEBI:74247 is_a CHEBI:65111
CHEBI:74259 is_a CHEBI:65111

CHEBI:74260 is_a CHEBI:65111 
CHEBI:74262 is_a CHEBI:65111
CHEBI:74264 is_a CHEBI:65111
CHEBI:74265 is_a CHEBI:65111
CHEBI:74282 is_a CHEBI:65111 

CHEBI:74285 is_a CHEBI:65111
CHEBI:74287 is_a CHEBI:65111 
CHEBI:74289 is_a CHEBI:65111
CHEBI:74291 is_a CHEBI:65111
CHEBI:74293 is_a CHEBI:65111

CHEBI:74328 is_a CHEBI:65111
CHEBI:76386 is_a CHEBI:65111
CHEBI:76410 is_a CHEBI:65111
CHEBI:76442 is_a CHEBI:65111
CHEBI:76484 is_a CHEBI:65111

**Comment by stevet7** [comment]
Added all relationships as requested,
Cheers,
Steve
