### ISSUE TITLE
Missing relations ChEBI:57643 and other

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3241]
Hi ChEBI curators;
Could you please add the following missing relations to your ontology?

73000 is_a 57643
73001 is_a 57643
74963 is_a 57643
75018 is_a 57643
75300 is_a 57643
75302 is_a 57643
75304 is_a 57643

58189 is_a 57930
58280 is_a 57930
58223 is_a 57930
58069 is_a 57930
456216 is_a 57930

37565 is_a 61557
61402 is_a 61557
46398 is_a 61557
37563 is_a 61557
30616 is_a 61557

Thanks in advance for your collaboration,
Lucila

**Comment by stevet7** [comment]
All done,
The ones to 57643 did not need adding as they were already inherited.
Kind regards,
Steve
