### ISSUE TITLE
Missing relations for ChEBI:66954 and others

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3242]
Hi ChEBI curators;
Could you please also add the following missing relations to your ontology?

60837 is_a 66954
60873 is_a 66954
60877 is_a 66954
60879 is_a 66954

60732 is_a 66949
60784 is_a 66949
60875 is_a 66949
60880 is_a 66949

32689 is_a 59871
85306 is_a 59871

64496 is_a 30909

57444 is_a 134019

90680 is_a 131871

Thanks in advance again for your help,
Lucila

**Comment by stevet7** [comment]
Added all relationships as requested with the exception of 32689 is_a 59871. 32689 is a cation and not a zwitterion (a zwitterion must be charge-neutral).
Kind regards,
Steve
