### ISSUE TITLE
Structures for CHEBI:132123 and CHEBI:132124

### ISSUE THREAD

**Issue by alanbridge** [ebi-chebi/ChEBI#3243]
Hi ChEBI

would you please consider adding the attached structures for 

CHEBI:132123 1,2-benzoquinones
CHEBI:132124 1,4-benzoquinones

These are mol files saved with a txt extension to allow attachment here. 

These structures would allow us to create balanced Rhea reactions representing these classes of molecules, as well as "child" reactions representing actual structures
[CHEBI_132124.txt](https://github.com/ebi-chebi/ChEBI/files/663071/CHEBI_132124.txt)
[CHEBI_132123.txt](https://github.com/ebi-chebi/ChEBI/files/663070/CHEBI_132123.txt)

. 

Thanks and Best Regards, Alan

**Comment by G-Owen** [comment]
Now done.

Cheers,
Gareth
