### ISSUE TITLE
CHEBI:134233  wrong formula

### ISSUE THREAD

**Issue by ANiknejad** [ebi-chebi/ChEBI#3247]
Hello ChEBI team,

I recently created this compound from this paper
https://www.ncbi.nlm.nih.gov/pubmed?term=23071109

I am not sure about the structure but the formula should be C20H27O4.

Many thanks in advance.

Anne Niknejad

**Comment by aimol** [comment]
I can see Formula: C20H27O4  has status submitted, can you please set to status Checked so that the formula can be updated in Rhea? Thanks in advance for your help,
Lucila

**Comment by G-Owen** [comment]
Hi Anne and Lucila,

Sorry this took so long to sort out!

Kind regards,
Gareth
