### ISSUE TITLE
S-adenosyl homocysteine  parentage

### ISSUE THREAD

**Issue by ValWood** [ebi-chebi/ChEBI#3249]
Hello,

Should S-adenosyl homocysteine be an amino-acid derivative rather than amino acid?
See
https://github.com/geneontology/go-ontology/issues/12925

For further info.

Many thanks,
Val

**Comment by stevet7** [comment]
Hi,
I have created the class 'homocysteine derivatives' (CHEBI:136505) and made it a parent term for S-adenosyl homocysteine.  This will lead to 'amino-acid derivative'.
Kind regards,
Steve

**Comment by ValWood** [comment]
thanks!
