### ISSUE TITLE
Missing Relations ChEBI:61557, 58043 and 77286

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3251]
Please add the following relationships that are currently missing and we need them for Rhea:

ChEBI: 30616  is a_ ChEBI:61557
ChEBI: 37565  is a_ ChEBI:61557
ChEBI: 46398  is a_ ChEBI:61557
ChEBI: 37563  is a_ ChEBI:61557
ChEBI: 61314  is a_ ChEBI:61557
ChEBI: 61402  is a_ ChEBI:61557

ChEBI: 456215  is a_ ChEBI:58043
ChEBI: 58115    is a_ ChEBI:58043
ChEBI: 57865   is a_ ChEBI:58043
ChEBI: 58053    is a_ ChEBI:58043
ChEBI: 60377    is a_ ChEBI:58043
ChEBI: 57464    is a_ ChEBI:58043

CHEBI:77294 is_a CHEBI:77286

Thanks in advance for your prompt action. Best,
Lucila

**Comment by stevet7** [comment]
I've added all these relationships as requested,
Kind regards,
Steve
