### ISSUE TITLE
Missing relations CHEBI:58342, CHEBI:57643 and CHEBI:64612

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3252]
Please add the following relationships, we need them for RHEA. Thanks in advance for your help,
Lucila

CHEBI:57368 is_a CHEBI:58342
CHEBI:57383 is_a CHEBI:58342
CHEBI:57387 is_a CHEBI:58342
CHEBI:57379 is_a CHEBI:58342
CHEBI:61540 is_a CHEBI:58342
CHEBI:73862 is_a CHEBI:58342
CHEBI:74146 is_a CHEBI:58342

CHEBI:75034 is_a CHEBI:57643
CHEBI:74669 is_a CHEBI:57643
CHEBI:73001 is_a CHEBI:57643
CHEBI:75300 is_a CHEBI:57643

CHEBI:73007 is_a CHEBI:64612
CHEBI:73008 is_a CHEBI:64612
CHEBI:73009 is_a CHEBI:64612
CHEBI:73999 is_a CHEBI:64612

**Comment by stevet7** [comment]
Hi Lucila,
There was no need to add any of these relationships as they are already present further up the ontology tree so are automatically inherited.
For instance 73999 has 71712 as its parent and 71712 has 64612, hence the relationship 73999 is a 64612 is inherited, so there is no need to add it.
Hope this makes sense,
Kind regards,
Steve
