### ISSUE TITLE
Missing relations CHEBI:59871, CHEBI:57319, CHEBI:90726 and CHEBI:57318

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3253]
Please add the following relationships, we need them for RHEA. Thanks in advance for your help,
Lucila

CHEBI:32557 is_a CHEBI:59871

CHEBI:76378 is_a CHEBI:57319
CHEBI:74278 is_a CHEBI:57319
CHEBI:57315 is_a CHEBI:57319

CHEBI:57286 is_a CHEBI:90726
CHEBI:57348 is_a CHEBI:90726
CHEBI:77041 is_a CHEBI:90726
CHEBI:71407 is_a CHEBI:90726
CHEBI:65115 is_a CHEBI:90726
CHEBI:71451 is_a CHEBI:90726

CHEBI:132183 is_a CHEBI:57318
CHEBI:77038  is_a CHEBI:57318

CHEBI:64940 is_a CHEBI:64993

**Comment by stevet7** [comment]
A couple of these were valid so I've added them.
Kind regards,
Steve
