### ISSUE TITLE
Missing relations CHEBI:64991, CHEBI:51973, CHEBI:52639 and CHEBI:30909

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3254]
Please add the missing relationships to the following CHEBI, we need these for RHEA. Thanks in advance for your cooperation,
Lucila

CHEBI:72582 is_a CHEBI:64991
CHEBI:35305 is_a CHEBI:51973
CHEBI:74457 is_a CHEBI:52639
CHEBI:64496 is_a CHEBI:30909
CHEBI:58721 is_a CHEBI:58722
CHEBI:58826 is_a CHEBI:57513

**Comment by stevet7** [comment]
I've added the relationships that needed adding.
Kind regards,
Steve
