### ISSUE TITLE
Missing relations CHEBI:57570, CHEBI:57880, CHEBI:64771, CHEBI:57262

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3255]
Please add the missing relations to the following CHEBIs, we need these for RHEA. Thanks in advance for your cooperation,
Lucila

CHEBI:132523 is_a CHEBI:57570

CHEBI:74244 is_a CHEBI:57880
CHEBI:74245 is_a CHEBI:57880

CHEBI:74243 is_a CHEBI:64771

CHEBI:75029 is_a CHEBI:57262
CHEBI:75032 is_a CHEBI:57262
CHEBI:75031 is_a CHEBI:57262

CHEBI:73001 is_a CHEBI:58293

**Comment by stevet7** [comment]
I've added the relationships that needed adding.
Kind regards,
Steve
