### ISSUE TITLE
Missing CHEBI relations that we need in RHEA

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3256]
If you could please add the following missing relations, it would greatly help the RHEA project, thanks in advance for your help!

CHEBI:52961 is_a CHEBI:86265
CHEBI:61256 is_a CHEBI:58856
CHEBI:74281 is_a CHEBI:58856
CHEBI:75020 is_a CHEBI:64379
CHEBI:73004 is_a CHEBI:64381
CHEBI:72999 is_a CHEBI:75279
CHEBI:73003 is_a CHEBI:75063
CHEBI:73002 is_a CHEBI:60000
CHEBI:74244 is_a CHEBI:75243
CHEBI:75269 is_a CHEBI:75223
CHEBI:76373 is_a CHEBI:71455
CHEBI:76375 is_a CHEBI:71456
CHEBI:74000 is_a CHEBI:75240
CHEBI:71446 is_a CHEBI:65102

Best,
Lucila

**Comment by G-Owen** [comment]
CHEBI:52961 is_a CHEBI:86265 - Done
CHEBI:61256 is_a CHEBI:58856 - This doesn't look right. Not done.
CHEBI:74281 is_a CHEBI:58856 - Done
CHEBI:75020 is_a CHEBI:64379 - Done
CHEBI:73004 is_a CHEBI:64381 - Done
CHEBI:72999 is_a CHEBI:75279 - Done
CHEBI:73003 is_a CHEBI:75063 - Done
CHEBI:73002 is_a CHEBI:60000 - Done
CHEBI:74244 is_a CHEBI:75243 - Done
CHEBI:75269 is_a CHEBI:75223 (both records now merged: 55430 is_a 28894)
CHEBI:76373 is_a CHEBI:71455 Done
CHEBI:76375 is_a CHEBI:71456 Done
CHEBI:74000 is_a CHEBI:75240 Done
CHEBI:71446 is_a CHEBI:65102 Done
