### ISSUE TITLE
CHEBI:134257 erroneous structure and charge

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3258]
We need this compound for Rhea, but the tool flags it is not normalized. Can you please change the structure of CHEBI:134257 to represent the major microspecies at pH 7.3 which would be charge 4- and Formula:C94H174N2O25P2 ?
Thanks in advance for your prompt answer to this request.
Best,
Lucila

**Comment by stevet7** [comment]
Done as requested,
Cheers,
Steve
