### ISSUE TITLE
Missing ChEBI relationships (ChEBI:28868, 64615, 83955, 76619 and 35746)

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3259]
Dear ChEBI Curators, please add these missing relationships in ChEBI (we need them in Rhea):

CHEBI:30823	is_a	CHEBI:28868
CHEBI:30245	is_a	CHEBI:28868
CHEBI:7896	is_a	CHEBI:28868
CHEBI:32387	is_a	CHEBI:28868
CHEBI:32372	is_a	CHEBI:28868
CHEBI:25646	is_a	CHEBI:28868
		
CHEBI:75583	is_a	CHEBI:64615
CHEBI:75841	is_a	CHEBI:64615
CHEBI:75844	is_a	CHEBI:64615
CHEBI:75845	is_a	CHEBI:64615
CHEBI:75846	is_a	CHEBI:64615
CHEBI:76978	is_a	CHEBI:64615
CHEBI:53753	is_a	CHEBI:64615
		
CHEBI:31014	is_a	CHEBI:83955
CHEBI:7896	is_a	CHEBI:83955
CHEBI:23858	is_a	CHEBI:83955
CHEBI:25629	is_a	CHEBI:83955
CHEBI:7896	is_a	CHEBI:83955
CHEBI:32360	is_a	CHEBI:83955
CHEBI:31014	is_a	CHEBI:83955
CHEBI:30807   is_a	CHEBI:83955

CHEBI:23858	is_a	CHEBI:76619
CHEBI:31013	is_a	CHEBI:76619
CHEBI:18262	is_a	CHEBI:76619
CHEBI:30807	is_a	CHEBI:76619
CHEBI:7896	is_a	CHEBI:76619

CHEBI:50626	is_a	CHEBI:35746

**Comment by stevet7** [comment]
I've added the relationships with 76619 and 83955. The others were not valid.
Kind regards,
Steve
