### ISSUE TITLE
Missing relationships in ChEBI needed for RHEA (ChEBI:84422, 64694, 84443, 78396 and 1269)

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3260]
Dear ChEBI Curators;
Please add the following relationships (we need these in RHEA);
CHEBI:84423	is_a	CHEBI:84422
CHEBI:84431	is_a	CHEBI:84422
CHEBI:64182	is_a	CHEBI:84422
CHEBI:64253	is_a	CHEBI:84422
CHEBI:61705	is_a	CHEBI:84422
CHEBI:58373	is_a	CHEBI:64694
CHEBI:62793	is_a	CHEBI:64694
CHEBI:62789	is_a	CHEBI:64694
CHEBI:84450	is_a	CHEBI:64694
CHEBI:84452	is_a	CHEBI:64694
CHEBI:57916	is_a	CHEBI:84443
CHEBI:62796	is_a	CHEBI:84443
CHEBI:62791	is_a	CHEBI:84443
CHEBI:1617	is_a	CHEBI:78396
CHEBI:84496	is_a	CHEBI:78396
CHEBI:84492	is_a	CHEBI:78396
CHEBI:84502	is_a	CHEBI:78396
CHEBI:84503	is_a	CHEBI:78396
CHEBI:40407	is_a	CHEBI:1269
CHEBI:1110	is_a	CHEBI:1269

Thanks in advance for your prompt cooperation,
Lucila

**Comment by stevet7** [comment]
I've added all these relationships as requested,
Kind regards,
Steve
