### ISSUE TITLE
Please add these relationships for CHEBI:73316, 65317 and 61560

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3261]
Please add the following relationships, it will greatly help our work in Rhea:
CHEBI:58595	is_a	CHEBI:73316
CHEBI:60471	is_a	CHEBI:73316
CHEBI:62286	is_a	CHEBI:73316
CHEBI:57667	is_a	CHEBI:73316
CHEBI:58593	is_a	CHEBI:73316
		
CHEBI:57673	is_a	CHEBI:65317
CHEBI:58245	is_a	CHEBI:65317
CHEBI:63528	is_a	CHEBI:65317
CHEBI:246422	is_a	CHEBI:65317
CHEBI:57566	is_a	CHEBI:65317
CHEBI:61194	is_a	CHEBI:65317
		
CHEBI:37568	is_a	CHEBI:61560
CHEBI:61429	is_a	CHEBI:61560
CHEBI:61555	is_a	CHEBI:61560
CHEBI:61382	is_a	CHEBI:61560
CHEBI:61404	is_a	CHEBI:61560
CHEBI:61481	is_a	CHEBI:61560

TIA for your help!
Lucila

**Comment by stevet7** [comment]
Added all relationships as requested.
Kind regards,
Steve
