### ISSUE TITLE
NTR: TOP-53

### ISSUE THREAD

**Issue by mah11** [ebi-chebi/ChEBI#3264]
We could use a CHEBI term for TOP-53, a drug that targets topoisomerase II. It's structurally related to etoposide (CHEBI:4911), and is described in PMID:11170388. The full text provides a structure.

http://pubs.acs.org/doi/full/10.1021/bi0021838

thanks,
m

**Comment by G-Owen** [comment]
Hi Midori,

Now done - see CHEBI:134547

Kind regards,
Gareth
