### ISSUE TITLE
Merge CHEBI:58856 with CHEBI:85097 ?

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3265]
Can you please check if these 2 entities are the same and need to be merged? CHEBI:58856 and CHEBI:85097
Thanks in advance,
Lucila

**Comment by G-Owen** [comment]
Hi Lucila,

The terms:
2,3-trans-enoyl CoA(4−)  (CHEBI:58856) and
4-saturated trans-2-enoyl-CoA(4−) (CHEBI:85097) are similar, but not the same.

CHEBI:85097 specifies that position 4 **must** be saturated,  whereas in CHEBI:58856, the nature of position 4 is not stated - it  _could_  be saturated, but it _could_ be unsaturated [as is the case with one of its child terms, (2E,4Z,7Z,10Z,13Z,16Z,19Z)-docosaheptaenoyl-CoA(4−) (CHEBI:77559)].
