### ISSUE TITLE
Please add relationships for these ChEBIs (CHEBI:132124, 24646, 85489, 83273, 58521 and 85097)

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3266]
Dear ChEBI Curators;
Can you please add the following relationships that we need in Rhea?
CHEBI:16374	is_a	CHEBI:132124
CHEBI:18151	is_a	CHEBI:24646
CHEBI:61968	is_a	CHEBI:85489
CHEBI:52639	is_a	CHEBI:83273
		
CHEBI:85108	is_a	CHEBI:58521
CHEBI:87710	is_a	CHEBI:58521
CHEBI:71586	is_a	CHEBI:58521
		
CHEBI:131990	is_a	CHEBI:85097
CHEBI:61405	is_a	CHEBI:85097
CHEBI:87701	is_a	CHEBI:85097
CHEBI:62242	is_a	CHEBI:85097
CHEBI:61405	is_a	CHEBI:85097

Thanks in advance for your cooperation.
Lucila

**Comment by stevet7** [comment]
I've added the relationships that were needed.
Kind regards,
Steve
