### ISSUE TITLE
Please also add relationships to these other ChEBIs: 76533, 76176, 90823, 76928, 84196 and 90769

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3267]
Dear ChEBI Curators;
Can you please also add the following ChEBI relations? We need these in Rhea, thanks!
CHEBI:58367	is_a	CHEBI:76533
CHEBI:58127	is_a	CHEBI:76533
CHEBI:57498	is_a	CHEBI:76533

CHEBI:85637	is_a	CHEBI:76176
CHEBI:85636	is_a	CHEBI:76176

CHEBI:57466	is_a	CHEBI:90823
CHEBI:133985	is_a	CHEBI:90823

CHEBI:30807	is_a	CHEBI:76928

CHEBI:85635	is_a	CHEBI:84196

CHEBI:90481	is_a	CHEBI:90769

Thanks again for your cooperation.
Lucila

**Comment by stevet7** [comment]
I've added the relationships that were needed, the rest were inherited anyway.
Kind regards,
Steve
