### ISSUE TITLE
Mistake in IUPAC Name for CHEBI:91148

### ISSUE THREAD

**Issue by OlivierClerc** [ebi-chebi/ChEBI#3270]
Hi,
I think there is a mistake in IUPAC Name for CHEBI:91148.
In ChEBI Name, ChEBI ASCII Name and Definition, the last GlcNS(6S) is alpha but in IUPAC Name it's beta ("2-deoxy-6-O-sulfo-2-(sulfoamino)-β-D-glucopyranosyl").

Olivier

**Comment by G-Owen** [comment]
Hi Oliver,
Well spotted! Now fixed.

Kind regards,
Gareth
