### ISSUE TITLE
Mistake in ChEBI Name for CHEBI:60290

### ISSUE THREAD

**Issue by OlivierClerc** [ebi-chebi/ChEBI#3271]
Hi,
I think there is a mistake in ChEBI Name and ChEBI ASCII Name for CHEBI:60290.
The second monosaccharide is not "beta-D-GalpNAc6**6**" but "beta-D-GalpNAc6**S**".

Olivier

**Comment by G-Owen** [comment]
Now corrected - thanks for letting us know!
