### ISSUE TITLE
Mistake in Definition for CHEBI:18376

### ISSUE THREAD

**Issue by OlivierClerc** [ebi-chebi/ChEBI#3272]
Hi,
I think there is a mistake in Definition of CHEBI:18376.
For dermatan sulfate, the link between iduronic acid and galactosamine is **alpha** 1-3 and not **beta** 1-3.

Olivier

**Comment by G-Owen** [comment]
Hi Olivier,

Thanks for letting us know. The error has now been corrected.

Kind regards,
Gareth
