### ISSUE TITLE
new children of fatty acid derivative (CHEBI:61697)

### ISSUE THREAD

**Issue by ukemi** [ebi-chebi/ChEBI#3273]
We recently had a request to classify wax metabolic process, fatty-acyl CoA metabolic process and ketone body metabolic process as types of fatty acid derivative metabolic process. Would it be possible to classify wax (CHEBI:73702), fatty-acyl-CoA (CHEBI:37554) and ketone body (CHEBI:73693) as fatty acid derivatives?

**Comment by stevet7** [comment]
Hi,
I've added these three relationships as requested,
Kind regards,
Steve
