### ISSUE TITLE
CHEBI:26710 Formula to be "NaCl"

### ISSUE THREAD

**Issue by RomanGurinovich** [ebi-chebi/ChEBI#3280]
Dear ChEBI team, 

it is "ClNa" now and expected "NaCl" especially from NLP point of view

Best regards,
Roman

**Comment by G-Owen** [comment]
Dear Roman,

Sorry for any problems caused - we don't deliberately go out of our way to frustrate NLP! 
However....
For chemical formulas, we use (and have always used) Hill notation, (https://en.wikipedia.org/wiki/Chemical_formula#Hill_system), which is by far the most commonly used system for indexing formulae in print (text books, chemical supplier catalogues, etc.,) and in chemical databases. The elements are arranged in the order of increasing numbers of carbon, hydrogen, then the remaining elements sorted alphabetically based on the chemical symbols. 
Where the Hill system conflicts with what might be expected from the "put the metal first then the anion" naming system (as in sodium chloride, for which the Hill formula is ClNa), we normally include the 'non-Hill' version (NaCl) as one of the synonyms.

Kind regards,
Gareth

**Comment by RomanGurinovich** [comment]
Dear Gareth,

makes perfect sense. Thank you for the interesting case, will use it in terms variants generator

Best regards,
Roman
