### ISSUE TITLE
CHEBI:15643, the name is wrong, and KEGG x-ref invalid

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#3288]
Hi,

This compound, CHEBI:15643, (6R)-6-(L-erythro-1,2-dihydroxypropyl)-7,8-dihydro-6H-pterin, is in fact D-erythro. KEGG has deleted its original structure C06487. Instead they use C00268 that is wrongly cited in CHEBI:20680.

The correct structure is found in, CHEBI:43120. Please add the cross reference to KEGG C00268 in this entry.

Cheers,
Kristian

**Comment by amalik01** [comment]
Now fixed.
