### ISSUE TITLE
Relationships ChEBI:57319, ChEBI:57318 and ChEBI:65102

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3290]
Dear ChEBI Curators;
Could you please review the relationships of the following ChEBI entities? As discussed with Steve previously, there are some relationships that are indirect and will be automatically inherited and therefore do not need to be added as a direct relation in the ChEBI ontology, but if they exist already we would need to be move those one level up in the ontology. So, for the following entities it should look like this:
ChEBI:76491  is_a ChEBI:57319 and ChEBI:57319 is_a ChEBI:65102
ChEBI:76494  is_a ChEBI:57319 and ChEBI:57319 is_a ChEBI:65102
ChEBI:76496  is_a ChEBI:57319 and ChEBI:57319 is_a ChEBI:65102
ChEBI:76502  is_a ChEBI:57319 and ChEBI:57319 is_a ChEBI:65102
ChEBI:76505  is_a ChEBI:57319 and ChEBI:57319 is_a ChEBI:65102
ChEBI:76513  is_a ChEBI:57319 and ChEBI:57319 is_a ChEBI:65102
ChEBI:74279  is_a ChEBI:57319 and ChEBI:57319 is_a ChEBI:65102
ChEBI:74279  is_a ChEBI:86040 and ChEBI:86040 is_a ChEBI:65102
ChEBI:74276  is_a ChEBI:57319 and ChEBI:57319 is_a ChEBI:65102
ChEBI:87687  is_a ChEBI:57318 and ChEBI:57318 is_a ChEBI:65102
ChEBI:87705  is_a ChEBI:57318 and ChEBI:57318 is_a ChEBI:65102
ChEBI:62617  is_a ChEBI:57318 and ChEBI:57318 is_a ChEBI:65102
ChEBI:62616  is_a ChEBI:57318 and ChEBI:57318 is_a ChEBI:65102

Thanks for your cooperation, we need to fix these for the RHEA ontology.
Best,
Lucila

**Comment by G-Owen** [comment]
Hi Lucila,
Now sorted. [We are also looking in to automatic removal of redundant is_a relationships as described by Alan Bridge in issue #3277]

Kind regards,
Gareth
