### ISSUE TITLE
Relationship correction for ChEBI:83860, ChEBI:88234 and ChEBI:88235

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3291]
Dear ChEBI Curators;
Please double check the relationship between these 2 entities:
ChEBI:83860 and ChEBI:83861

Can you please add ChEBI:83860 is_a ChEBI:63640 ?

And also modify/add the following relationships please:
ChEBI:88234 is_a ChEBI:78437 and ChEBI:78437 is_a ChEBI:79214
ChEBI:88235 is_a ChEBI:60065 and ChEBI:60065 is_a ChEBI:79210

Thanks again for your cooperation.
Best,
Lucila

**Comment by G-Owen** [comment]
The relationship between ChEBI:83860 and ChEBI:83861 was wrong - sorry!
 All now corrected/modified/added.
