### ISSUE TITLE
steroid glucuronate

### ISSUE THREAD

**Issue by nnouspikel** [ebi-chebi/ChEBI#3292]
Dear ChEBI curators,

Whenever you have time could you please update the following entries:
- CHEBI:28919 by replacing the CH3 group at C3 of glucuronic acid with an OH group
- add CHEBI:57529 and CHEBI:82961 as children of CHEBI:136637

Many thanks for your help.

All the best,
Nevila

**Comment by G-Owen** [comment]
Now done.

**Comment by nnouspikel** [comment]
Many thanks Gareth!
