### ISSUE TITLE
Inappropriate use of synonym field in CHEBI to represent charge etc

### ISSUE THREAD

**Issue by cmungall** [ebi-chebi/ChEBI#3294]
E.g.

http://purl.obolibrary.org/obo/CHEBI_101408
http://www.ontobee.org/ontology/rdf/CHEBI?iri=http://purl.obolibrary.org/obo/CHEBI_101408

"0" is not a synonym for this term. This causes all kinds of problems for lexical search, autocomplete, matching etc etc

It looks like you want to be defining a new OWL annotation property here -- not overloading synonym

**Comment by tgbugs** [comment]
It also seems that molecular weights are being pulled in as well. For example:
```
CHEBI:1391 a owl:Class ;
    oboInOwl:hasRelatedSynonym "1-(1,3-Benzodioxol-5-yl)-N-methyl-2-propanamine"^^xsd:string,
        "193.110"^^xsd:string,
        "193.24234"^^xsd:string,
```

**Comment by cmungall** [comment]
Any progress on this @G-Owen?

**Comment by muthuvenkat** [comment]
@cmungall, sorry for the inconvenience. Please check this annotation property and let me know if its  ok.
`[Term]
id: CHEBI:60850
name: cis-2,3-dihydro-3-hydroxyanthranilic acid
def: "A racemate comprising (2R,3S)- and (2S,3R)-2,3-dihydro-3-hydroxyanthranilic acid." []
subset: 3_STAR
property_value: chemical:data "C7H9NO3" xsd:string
property_value: chemical:data “0” xsd:string
property_value: chemical:data "155.058" xsd:string
property_value: chemical:data "155.152” xsd:string
synonym: "cis-2-amino-2,3-dihydro-3-hydroxybenzoic acid" RELATED [ChEBI]
synonym: "cis-6-amino-5-hydroxycyclohexa-1,3-diene-1-carboxylic acid" RELATED [ChEBI]
synonym: "rac-(5R,6S)-6-amino-5-hydroxycyclohexa-1,3-diene-1-carboxylic acid" EXACT IUPAC_NAME [IUPAC]
is_a: CHEBI:60911 ! racemate
relationship: is_tautomer_of CHEBI:60852 ! cis-2,3-dihydro-3-hydroxyanthranilic acid zwitterion
`

**Comment by cmungall** [comment]
Formatted:

```
[Term]
id: CHEBI:60850
name: cis-2,3-dihydro-3-hydroxyanthranilic acid
def: "A racemate comprising (2R,3S)- and (2S,3R)-2,3-dihydro-3-hydroxyanthranilic acid." []
subset: 3_STAR
property_value: chemical:data "C7H9NO3" xsd:string
property_value: chemical:data “0” xsd:string
property_value: chemical:data "155.058" xsd:string
property_value: chemical:data "155.152” xsd:string
synonym: "cis-2-amino-2,3-dihydro-3-hydroxybenzoic acid" RELATED [ChEBI]
synonym: "cis-6-amino-5-hydroxycyclohexa-1,3-diene-1-carboxylic acid" RELATED [ChEBI]
synonym: "rac-(5R,6S)-6-amino-5-hydroxycyclohexa-1,3-diene-1-carboxylic acid" EXACT IUPAC_NAME [IUPAC]
is_a: CHEBI:60911 ! racemate
relationship: is_tautomer_of CHEBI:60852 ! cis-2,3-dihydro-3-hydroxyanthranilic acid zwitterion
```

This is much better, in that it won't pollute the synonym fields.

It may be suboptimal in that the property may not expand well to an OWL IRI. What is the intended OWL IRI for chemical:data? What is the "chemical" prefix intended to expand to? Do you want to add an annotation property to RO or CHEMINF for this?

I think you at least want two distinct APs here, no? Presumably at least one is the weight, and the `0` is...?

**Comment by muthuvenkat** [comment]
@cmungall will this make things clear ...
```
property_value: formula "C7H9NO3" xsd:string
property_value: charge “0” xsd:string
property_value: average_mass "155.058" xsd:string
property_value: monoisotopic_mass "155.152” xsd:string

<!-- http://purl.obolibrary.org/obo/formula -->
<owl:AnnotationProperty rdf:about="http://purl.obolibrary.org/obo/formula"/>
```

**Comment by cmungall** [comment]
On 23 Aug 2017, at 6:32, Venkatesh Muthukrishnan wrote:

> @cmungall will this make things clear ...
> ```
> property_value: formula "C7H9NO3" xsd:string
> property_value: charge “0” xsd:string
> property_value: average_mass "155.058" xsd:string
> property_value: monoisotopic_mass "155.152” xsd:string
>
> 
> <owl:AnnotationProperty 
> rdf:about="http://purl.obolibrary.org/obo/formula"/>
> ```

the obo2owl translation is a bit obscure here but if you test it you'll 
see it won't give what is intended it will make different URLs.

In any case, you should only declare purls in the spaces you control. 
Either http://purl.obolibrary.org/obo/chebi/... or request in another 
ontology.

Let's say you go with chebi for now

either

```
property_value: http://purl.obolibrary.org/obo/chebi/formula "C7H9NO3" 
xsd:string
```


or

```
property_value: formula "C7H9NO3" xsd:string

...

[Typedef]
id: formula
xref: http://purl.obolibrary.org/obo/chebi/formula
is_metadata_tag: true
```

Note it will be incumbent on you to make the purls for the properties 
resolve somewhere

But I'd strongly recommend putting these in an external ontology, an OBO 
one, even schema.org or wikidata

**Comment by tgbugs** [comment]
@cmungall this appears to be fixed now.

**Comment by cmungall** [comment]
I can't reopen but 2 further recommendations

```
id: CHEBI:60850
name: cis-2,3-dihydro-3-hydroxyanthranilic acid
...
property_value: http://purl.obolibrary.org/obo/chebi/mass "155.152" xsd:string
property_value: http://purl.obolibrary.org/obo/chebi/monoisotopicmass "155.058" xsd:string
property_value: http://purl.obolibrary.org/obo/chebi/formula "C7H9NO3" xsd:string
property_value: http://purl.obolibrary.org/obo/chebi/charge "0" xsd:string
```

 1. Strongly recommend you use the correct xsd:type (e.g. flats, ints) where appropriate
 2. All PURLs should be resolvable
 3. Use pre-existing predicates for chemical properties. I'm not sure what to recommend here, but you can ask the OBO list for help. CHEMINF would be an obvious one but it models charge etc as qualities, you need a property here
