### ISSUE TITLE
ChEBI:1722 relations 

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3296]
Would it be possible to change the relations of the following entities to:
27783 is_a 1722 and 1722 is_a 36836
27771 is_a 1722 and 1722 is_a 36836
771  is_a 1722 and 1722 is_a 36836
27486  is_a 1722 and 1722 is_a 36836
27832  is_a 1722 and 1722 is_a 36836
28750  is_a 1722 and 1722 is_a 36836
28043  is_a 1722 and 1722 is_a 36836
41633  is_a 1722 and 1722 is_a 36836
85903  is_a 1722 and 1722 is_a 36836
85899  is_a 1722 and 1722 is_a 36836
2710  is_a 1722 and 1722 is_a 36836
85810  is_a 1722 and 1722 is_a 36836
16581  is_a 1722 and 1722 is_a 36836
65568  is_a 1722 and 1722 is_a 36836
28689  is_a 1722 and 1722 is_a 36836
90931  is_a 1722 and 1722 is_a 36836
71824  is_a 1722 and 1722 is_a 36836
67594  is_a 1722 and 1722 is_a 36836
69114  is_a 1722 and 1722 is_a 36836

Also, if a structure could be added to 1722? Maybe something like the ones attached below? Open to discussion

[3B-OH-D5-R1-3.txt](https://github.com/ebi-chebi/ChEBI/files/912151/3B-OH-D5-R1-3.txt)
[3B-OH-D5-steroid.txt](https://github.com/ebi-chebi/ChEBI/files/912155/3B-OH-D5-steroid.txt)

**Comment by aimol** [comment]
I submitted a new structure to represent this kind of entity, please check ChEBI:136845.

**Comment by amalik01** [comment]
This work has now been completed.
