### ISSUE TITLE
CHEBI:18122 and 15722 structures

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3301]
Dear ChEBI Curators;
Can you please check these 2 ChEBIs? We need these structures in RHEA, but they both have status OK, and CHEBI:18122 is missing a formula as well.
Thanks in advance for your help.
Lucila

**Comment by G-Owen** [comment]
Hi Lucila,
Sorry for taking so long to get to these - both now done.

Best regards,
Gareth
