### ISSUE TITLE
Need structure for CHEBI:33854

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3304]
Dear ChEBI Curators;
Would it be possible to add the attached structure to CHEBI:33854 (similar to the one in CHEBI:33855), we need it for RHEA.
Thanks in advance for your help,
Lucila
[aromatic alcohol.txt](https://github.com/ebi-chebi/ChEBI/files/940320/aromatic.alcohol.txt)

**Comment by G-Owen** [comment]
Hi Lucila,

There is a problem with the structure that you propose - it suggests that the carbon bearing the hydroxy group must also be attached to a hydrogen (i.e. a primary or secondary alcohol). But the term "aromatic alcohol" (CHEBI:33854) does not specify this - members of the class may be primary, secondary, or tertiary.
Not sure how to get round this problem.

Gareth

**Comment by aimol** [comment]
Hi Gareth;
Thanks for your reply. Would it be possible then to add the structure to CHEBI:33857?
Best,
Lucila

**Comment by stevet7** [comment]
Hi Lucila, I've added a structure to 33857. For it to be properly specific for primary aromatic alcohols, both hydrogens need to be explicit, so I've added the structure as shown in the molfile below:


  ACD/Labs05151714222D

  5  4  0  0  0  0  0  0  0  0  3 V2000
   26.8796   -8.4763    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   28.0314   -7.8113    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   28.0314   -6.4812    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   29.3614   -7.8113    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
   28.6964   -8.9631    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  2  3  1  0  0  0  0
  4  2  1  0  0  0  0
  5  2  1  0  0  0  0
A    1
R
M  END

Is that OK?
Kind regards,
Steve

**Comment by aimol** [comment]
great! thanks a lot Steve
