### ISSUE TITLE
Please correct to CHEBI:74281 is_a CHEBI:58856

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3305]
Dear ChEBI Curators;
Can you please correct the relationship 2,3-trans-enoyl CoA(4−) (CHEBI:58856) is a trans-2-hexacosenoyl-CoA(4−) (CHEBI:74281) and make it the inverse? It should be CHEBI:74281 is_a CHEBI:58856.
Thanks in advance for your help,
Lucila

**Comment by G-Owen** [comment]
Hi Lucila,
Now sorted - sorry for the slip!

Kind regards,
Gareth
