### ISSUE TITLE
Add synonym 'cholesteryl ester' to CHEBI:17002 'cholesterol ester'

### ISSUE THREAD

**Issue by cmungall** [ebi-chebi/ChEBI#3311]
This seems to be the standard spelling, so also consider using this as the primarly label and the exiting class label as a synonymL

From justification, see: https://github.com/obophenotype/human-phenotype-ontology/issues/2014

**Comment by G-Owen** [comment]
Hi Chris,
Yes - cholesteryl ester is a better name - it follows the convention of changing the ...ol of the alcohol portion of the ester to ...yl (as with methyl acetate, ethyl benzoate, etc). So I have renamed CHEBI:17002 to 'cholesteryl ester' and made 'cholesterol ester' a synonym.

Best regards,
Gareth
