### ISSUE TITLE
CHEBI:61259, please correct typo under 'Synonyms'

### ISSUE THREAD

**Issue by PolymerChemistry** [ebi-chebi/ChEBI#3314]
The second line under 'Synonyms' subheader is "PHEMA" when the acronym is correctly spelled 'PEHMA' (**p**oly **e**thyl**h**exyl **m**eth**a**crylate.) Thank you

**Comment by G-Owen** [comment]
Thanks for letting us know. The error has now been corrected.

Kind regards,
Gareth
