### ISSUE TITLE
Merge CHEBI:20156 with CHEBI:1625? and CHEBI:13602 with CHEBI:1624?

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3315]
Dear ChEBI curators;
I find these 2 entities represent the same compound, can you check if CHEBI:20156 and CHEBI:1625 need to be merged? Also CHEBI:13602 and CHEBI:1624 might need merging?
Best,
Lucila

**Comment by G-Owen** [comment]
Hi Lucila,

Thanks for bring these to our attention.
I have now merged CHEBI:20156 and CHEBI:1625 (the parent ID is CHEBI:20156)
and CHEBI:1624 with CHEBI:13602 (the parent ID is CHEBI:1624).

Kind regards,
Gareth
