### ISSUE TITLE
Polymer index Chebi:8298 

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3316]
Dear ChEBI curators;
I wonder if the index for polymer Chebi:8298 Poly[(R)-3-hydroxybutanoate] can be changed from "x" to "n" or if you would prefer that I submit a new structure to represent [(R)-3-hydroxybutanoate]n?
Best,
Lucila

**Comment by G-Owen** [comment]
Hi Lucila,
I have updated the structure for CHEBI:8298 - see what you think.

Cheers,
Gareth

**Comment by aimol** [comment]
Thanks Gareth, much better!
