### ISSUE TITLE
re: CHEBI:64645

### ISSUE THREAD

**Issue by BarbaraCzub** [ebi-chebi/ChEBI#3318]
Hello,

There is currently inconsistency in naming of amyloid-beta/beta-amyloid terms in Gene Ontology. E.g. there is a term "GO:1904645 response to beta-amyloid", or a term  "GO:0106003 amyloid-beta complex". The Complex Portal (CP) uses the "amyloid-beta" phrase as the primary term https://www.ebi.ac.uk/intact/complex/?q=amyloid%0D%0A 

Kimberly @vanaukenk is currently working through the various amyloid-beta/beta-amyloid GO terms to ensure consistency in what the primary term is, and what synonyms are associated with it. https://github.com/geneontology/go-ontology/issues/13418#issuecomment-297354357 

"Amyloid-beta" is going to be the primary term in GO, whereas "beta-amyloid" is going to be listed among synonyms.

Would it be possible to update the primary terms and synonyms in ChEBI as well, so that they are in agreement with GO and CP, i.e. use "amyloid-beta" as the primary name and "beta-amyloid" as its synonym?
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:64645 

I will look forward to hearing from you.

Kind Regards,
Barbara

**Comment by G-Owen** [comment]
Hi Barbara,

Now done (also for CHEBI:64646 and CHEBI:64647).

Best regards,
Gareth

**Comment by BarbaraCzub** [comment]
Great. Thank you!
