### ISSUE TITLE
CHEBI:75431 Ghrelin slight error in structure

### ISSUE THREAD

**Issue by baoilleach** [ebi-chebi/ChEBI#3319]
Hi there,

The structure of Ghrelin is missing the n-octanoyl on the 3rd residue (the 2nd serine).

See for example:
http://physrev.physiology.org/content/85/2/495.long
or 
https://www.anaspec.com/products/product.asp?id=30422

**Comment by G-Owen** [comment]
Hi Noel,
Thanks for letting us know. I have now updated the ChEBI entry.

Kind regards,
Gareth
