### ISSUE TITLE
CHEBI:16380, current structure is wrong

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#3322]
Hi,

I have noticed that there is an error in the current checked parent structure. The wedge bond at position 12 (see http://www.chem.qmul.ac.uk/iubmb/enzyme/reaction/alkaloid/alknos/vindol.html for numbering) is turning the wrong way. I have attached a corrected structure mol file. See also KEGG:C01626 for verification.

Cheers,
Kristian
[CHEBI_16380.txt](https://github.com/ebi-chebi/ChEBI/files/1035707/CHEBI_16380.txt)

**Comment by G-Owen** [comment]
Thanks - now corrected.

Kind regards,
Gareth
