### ISSUE TITLE
Request addition to database: Z-DEVD-fmk

### ISSUE THREAD

**Issue by fehrhart** [ebi-chebi/ChEBI#3331]
Dear all,

 I would like to request the addition of Z-DEVD-fmk, a modified tetrapeptide. It acts as an Caspase-3 inhibitor. 

Description of structure: http://www.selleckchem.com/products/z-devd-fmk.html 

Some literature: 
10.3233/RNN-159001
10.5045/br.2014.49.1.49
10.1016/j.surneu.2005.03.042

Best regards,
Freddie

**Comment by G-Owen** [comment]
Hi Freddie,
Now done. CHEBI:138013 should be findable tomorrow morning.

Kind regards,
Gareth
