### ISSUE TITLE
ChEBI:75938 and ChEBI:75757 change in relations

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3332]
Dear ChEBI Curators;
Can you please make the following changes to the existing relation for 75938 and 75757?
Currently ChEBI has both: ChEBI:75938 is_a ChEBI:75937 and ChEBI:75757 is_a ChEBI:75937.

Can you please move ChEBI:75937 a level away and make:

ChEBI:75938 is_a ChEBI:75342
ChEBI:75757 is_a ChEBI:75342
and
ChEBI:75342 is_a ChEBI:75937

Thanks in advance for your help.
Best,
Lucila

**Comment by G-Owen** [comment]
Hi Lucila,

Now done. Sorry it took so long!

Kind regards,
Gareth
