### ISSUE TITLE
ChEBI:52333 change in relation

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3333]
Dear ChEBI Curators;
Can you please make the following changes to the existing relation for ChEBI:52333?
Currently ChEBI has: ChEBI:52333 is_a ChEBI:75945,

Can you please move ChEBI:75945 a level away and make:

ChEBI:52333 is_a ChEBI:52323
and
ChEBI:52323 is_a ChEBI:75945

Thanks in advance for your help.
Best,
Lucila

**Comment by G-Owen** [comment]
Hi Lucila,

Now done - sorry it took so long.

Kind regards,
Gareth
