### ISSUE TITLE
NTR: gas molecular entity

### ISSUE THREAD

**Issue by nicolevasilevsky** [ebi-chebi/ChEBI#3337]
**New term requested**: gas molecular entity
**Suggested text definition**: A main group molecular entity containing one or more atoms of any gas, elemental molecules made from one type of atom, or compound molecules made from a variety of atoms.
**SOURCE**: https://en.wikipedia.org/wiki/Gas
**Examples**: oxygen, carbon dioxide

**Related to ticket**: https://github.com/cmungall/environmental-conditions/issues/6

**Comment by G-Owen** [comment]
Hi Nicole,
Sorry this took so long to get to.
The term has now been created (see CHEBI:138675), but it is likely to be missing some child terms (i.e. some compounds that are gaseous may not be linked to it in the ontology).

Please take a look and let me know if you spot any obvious omissions!

Kind regards,
Gareth
