### ISSUE TITLE
NTR: metalloid

### ISSUE THREAD

**Issue by nicolevasilevsky** [ebi-chebi/ChEBI#3340]
**New term requested**: metalloid
**Suggested text definition**: Any chemical element which has properties in between those of metals and nonmetals, or that has a mixture of them.
**SOURCE**: https://en.wikipedia.org/wiki/Metalloid
**Examples**: Silicon, Arsenic 

**Related to ticket**: https://github.com/cmungall/environmental-conditions/issues/6

**Comment by G-Owen** [comment]
Now done - see CHEBI:137980
