### ISSUE TITLE
NTR: 1,3-dichloropropane

### ISSUE THREAD

**Issue by nicolevasilevsky** [ebi-chebi/ChEBI#3341]
**New term requested**: 1,3-dichloropropane
**Suggested text definition**: A compound of chlorine, hydrogen, and carbon.
**SOURCE**: https://pubchem.ncbi.nlm.nih.gov/compound/1_3-dichloropropane, https://en.wikipedia.org/wiki/1,3-Dichloropropane

Note - there are 76 synonyms for this term, please see the synonyms in the source link.

**Related to ticket**: https://github.com/cmungall/environmental-conditions/issues/6

**Comment by G-Owen** [comment]
Now added - see CHEBI:137978
