### ISSUE TITLE
NTR: 2,2',4,4',5,5'-hexabromobiphenyl

### ISSUE THREAD

**Issue by nicolevasilevsky** [ebi-chebi/ChEBI#3347]
**New term requested**: 2,2',4,4',5,5'-hexabromobiphenyl
**Parent class**: CHEBI:134094 polybromodiphenyl ether
**SOURCE**: https://pubchem.ncbi.nlm.nih.gov/compound/42948#section=Top

There are 42 synonyms for this term, see source link.

**Related to ticket**: https://github.com/cmungall/environmental-conditions/issues/6

**Comment by G-Owen** [comment]
Hi Nicole,

Now made up to 3-star status: 2,2',4,4',5,5'-hexabromobiphenyl (CHEBI:134050). [It is actually a member  of the class of polybromobiphenyls (CHEBI:134049) rather than a polybromodiphenyl ether (CHEBI:134094).]

Best regards,
Gareth
