### ISSUE TITLE
NTR: inorganic acid

### ISSUE THREAD

**Issue by nicolevasilevsky** [ebi-chebi/ChEBI#3348]
**New term requested**: inorganic acid
**Suggested parent class** CHEBI:24835 inorganic molecular entity
**Suggested text definition**: An acid derived from one or more inorganic compounds. All organic  acids form hydrogen ions and the conjugate base ions when dissolved in water.
**Synonym** Mineral acid
**SOURCE**: https://en.wikipedia.org/wiki/Mineral_acid
**Examples**: Hydrochloric acid (HCl), Nitric acid (HNO3)

**Related to ticket**: https://github.com/cmungall/environmental-conditions/issues/6

**Comment by G-Owen** [comment]
Hi Nicole,

Now in ChEBI: inorganic acid (CHEBI:138103)

Best regards,
Gareth
