### ISSUE TITLE
NTR: perfluorooctane sulfonamide

### ISSUE THREAD

**Issue by nicolevasilevsky** [ebi-chebi/ChEBI#3349]
**New term requested**: perfluorooctane sulfonamide
**Suggested parent class** 
**Suggested text definition**: A synthetic organofluorine compound, which is a fluorocarbon derivative and a perfluorinated compound, having an eight-carbon chain and a terminal sulfonamide functional group.
**Synonym** Perfluorooctanesulfonamide, PFOSA
**SOURCE**: https://en.wikipedia.org/wiki/Perfluorooctanesulfonamide

**Related to ticket**: https://github.com/cmungall/environmental-conditions/issues/6

**Comment by G-Owen** [comment]
Now done - CHEBI:138089

Best regards,
Gareth
