### ISSUE TITLE
Annotation error: CHEBI:34393 is not an antibiotic (only antiseptic / disinfectant)

### ISSUE THREAD

**Issue by bachev** [ebi-chebi/ChEBI#3350]
4-chloro-3,5-dimethylphenol (CHEBI:34393) should not be a CHEBI:36047 (antibacterial drug / antibiotic).

See https://en.wikipedia.org/wiki/Chloroxylenol
for the compound and 
https://en.wikipedia.org/wiki/Antiseptic and https://en.wikipedia.org/wiki/Disinfectant for distinctions.

**Comment by G-Owen** [comment]
Hi Bastien,

Sorry it took so long to get to this!
Thanks for pointing out the error, which has now been corrected.

Best regards,
Gareth
