### ISSUE TITLE
NTR: acylated glycerophospholipids

### ISSUE THREAD

**Issue by mah11** [ebi-chebi/ChEBI#3354]
We would like ChEBI terms for several acylated glycerophospholipids mentioned in PMID:28667014. Unfortunately, I'm having trouble tracking down much information about them, so what I've put here represents inferences and guesses.

- For "1-stearoylglycerophosphocholine (18:0)" I'm wondering if it's the same compound as CHEBI:88779?

It looks like we need new terms for these, so I've tried to model descriptions or text definitions on some existing terms:

- 2-palmitoleoylglycerophosphoinositol: I think is_a CHEBI:62749, defined as a glycerophosphoinositol palmitoleoylated at O2 of the glycerol moiety.
- 2-myristoylglycerophosphocholine: I'm guessing this is like CHEBI:45240, but with only one myristoyl group at position 1.
- 1-eicosenoylglycerophosphocholine (20:1n9): looks like it's similar to CHEBI:89094, but acylated only at position 1, i.e. just PC(20:1(11Z)) and synonyms.

thanks,
midori

**Comment by G-Owen** [comment]
Hi Midori,

1)  For "1-stearoylglycerophosphocholine (18:0)", you need CHEBI:73858. (Not CHEBI:88779, in which the C18-chain is attached as an enol ether, rather than as an ester).
2)  2-palmitoleoyl-sn-glycero-3-phospho-D-myo-inositol is now in as CHEBI:138108.

More to follow!
Best regards,
Gareth

**Comment by G-Owen** [comment]
Hi Midori,

3. For 2-myristoylglycerophosphocholine, you need 2-tetradecanoyl-sn-glycero-3-phosphocholine (CHEBI:131738).
4. For 1-eicosenoylglycerophosphocholine (20:1n9), see lysoPC(20:1(11Z)) (CHEBI:88685).

Kind regards,
Gareth

**Comment by mah11** [comment]
Thank you!

**Comment by G-Owen** [comment]
4. (Continued) To be more consistent with similar compounds in ChEBI, I have changed the display name [= ChEBI name] for this compound to 1-(11Z)-icosenoyl-sn-glycero-3-phosphocholine. 
[lysoPC(20:1(11Z)) is retained as a synonym.]

Best regards,
Gareth
