### ISSUE TITLE
CHEBI:136976 structure and formula

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3355]
Dear ChEBI Curators,
I can see that CHEBI:136976 has been changed. This entity is part of a RHEA reaction and changing it will break the stoichiometry and the enzymatic activity involved. Can you please have a look and get back to me?
Best,
Lucila

**Comment by stevet7** [comment]
Oops, my mistake!
Now corrected,
Apologies,
Steve
