### ISSUE TITLE
CHEBI:17373, wrong relationship

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#3359]
Hi,

I just found this relationship in CHEBI:17373, ferroleghemoglobin:

ferroleghemoglobin (CHEBI:17373) has role mouse metabolite (CHEBI:75771) via globin (CHEBI:5386)

This is wrong since leghemoglobin is a nitrogen or oxygen carrier and hemoprotein found in the nitrogen-fixing root nodules of leguminous plants. (https://en.wikipedia.org/wiki/Leghemoglobin).

Cheers,
Kristian

**Comment by G-Owen** [comment]
Hi Kristian,

There are a a few 'metabolite' errors in ChEBI resulting from an entry inheriting "has_role xyz metabolite" from a parent compound. They arose from a loading of species data imported from other databases. We have deleted most of them, but this one clearly slipped through the net! Now fixed - thanks for letting us know.

Cheers,
Gareth
