### ISSUE TITLE
CHEBI:17423, wrong definition

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#3360]
Hi,

CHEBI:17423, methemoglobin:

A leghemoglobin that is the ferric (Fe3+) form of hemoglobin.

This is wrong, since Leghemoglobin (also leghaemoglobin or legoglobin) is a nitrogen or oxygen carrier and hemoprotein found in the nitrogen-fixing root nodules of leguminous plants. (https://en.wikipedia.org/wiki/Leghemoglobin)

So methemoglobin is NOT a leghemoglobin (see relationships).

Cheers,
Kristian

**Comment by G-Owen** [comment]
Hi Kristian,

Thanks for letting us know! I've re-assigned it as a hemoprotein (CHEBI:35137), changed the definition accordingly, and deleted the "ferrileghemoglobin" synonyms from Kegg and link (to Kegg C02683), which relate to a specific (non-protein) ferriheme moiety.

Cheers,
Gareth
