### ISSUE TITLE
please update CHEBI:136412 and CHEBI:136416 structures

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#3364]
Dear ChEBI curators,

Please would you update erroneous structures of CHEBI:136412 and CHEBI:136416 with the attached mol files (renamed with .txt extension to be attached). Both have an extra phosphate group in 3' position.

CHEBI:136412: 5'-end 2'-deoxyribonucleotide(2-) residue
CHEBI:136416 5'-end 5'-dephospho-2'-deoxyribonucleotide residue

Thanks for your support,

Cheers, Anne

[ChEBI_136416.txt](https://github.com/ebi-chebi/ChEBI/files/1242078/ChEBI_136416.txt)
[ChEBI_136412.txt](https://github.com/ebi-chebi/ChEBI/files/1242079/ChEBI_136412.txt)

**Comment by stevet7** [comment]
Done as requested,
Cheers,
Steve
