### ISSUE TITLE
CHEBI:63682 and CHEBI:63750, (13E)-labda-7,13-dien-15-yl diphosphate, more stereoconfiguration

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#3365]
Hi Gareth and Steve,

There is now more information available about the stereoconfiguration of (13E)-labda-7,13-dien-15-yl diphosphate, but I am not sure whether you would prefer to have a new entry, or just to amend the existing structure. I have attached the 'improved' structures so you can see the difference.

[CHEBI_63682.txt](https://github.com/ebi-chebi/ChEBI/files/1245533/CHEBI_63682.txt)
[CHEBI_63750.txt](https://github.com/ebi-chebi/ChEBI/files/1245540/CHEBI_63750.txt)

The new information is found in pmid:26814669

Cheers,
Kristian

**Comment by G-Owen** [comment]
Hi Kristian,

Seeing as the entries were created for a particular compound and its pH 7.3 form, I think it is fine to update the entries when more details about their structure is published. 
I have updated the display names and IUPAC names of the entries to reflect the newly-reported stereochemistry, but retained the old display names as synonyms. PMID:26814669 has been added to the citations for both entries.

Best regards,
Gareth
