### ISSUE TITLE
CHEBI:131704, the reference is wrong

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#3366]
Hi Gareth and Steve,

I have just discovered that I submitted a completely wrong reference for this entry. pmid:26663356 has nothing to do with 4-[(2-hydroxyethoxy)carbonyl]benzoate. It is about onocerin (just submitted).
Please replace with pmid:26965627

Cheers,
Kristian

**Comment by G-Owen** [comment]
Hi Kristian,

Now sorted.

Cheers,
Gareth
