### ISSUE TITLE
CHEBI:74098, there is a wrong reference linked to this compound

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#3367]
Hi Gareth and Steve,

There are three references linked to this compound, but pmid:27114550 does not belong, as it is linked to CHEBI:137373 and others.

Cheers,
Kristian

**Comment by G-Owen** [comment]
Hi Kristian,
Thanks for letting us know - I've deleted the bad PMID from CHEBI:137373.

Best regards,
Gareth
