### ISSUE TITLE
Need ChEBI term for two entities

### ISSUE THREAD

**Issue by guptapa** [ebi-chebi/ChEBI#3371]
I did not find ChEBI ids for N,N-dimethyl-beta-alanine and N-methyl-beta-alanine. Please add new terms for both the entities. PubChem details are here:
https://pubchem.ncbi.nlm.nih.gov/compound/25202453
https://pubchem.ncbi.nlm.nih.gov/compound/25201408

**Comment by G-Owen** [comment]
Hi,
These compounds have now been added to ChEBI and can be found using the following links:
http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:13668
http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:13669
(They should be findable by a name or structure search within the next day or so, once the appropriate indexes have been updated).

Best regards,
Gareth
