### ISSUE TITLE
carbohydrate tree

### ISSUE THREAD

**Issue by cornett** [ebi-chebi/ChEBI#3374]
I'm having some problems querying the ChEBI hierarchy around CHEBI:16646 (carbohydrate).   The following queries were run against a local instance of ChEBI created from the Sept 1st generic dump.

Find node ID for CHEBI:16646:

```
# SELECT * FROM vertice WHERE vertice_ref = 'CHEBI:16646';
  id   | vertice_ref | compound_id | ontology_id
-------+-------------+-------------+-------------
 47905 | CHEBI:16646 |       16646 |           1
(1 row)
```

Find nodes above and below:

```
hithub=# SELECT * FROM relation WHERE init_id = 47905 OR final_id = 47905;
   id   | type | init_id | final_id | status
--------+------+---------+----------+--------
 779336 | is_a |   47905 |    30922 | C
 837784 | is_a |  707836 |    47905 | C
(2 rows)
```
Look up their names:

```
hithub=# SELECT
        c.chebi_accession,
        c.name
FROM vertice v
JOIN compounds c ON v.compound_id = c.id
WHERE v.id IN (30922, 707836);
 chebi_accession |                    name
-----------------+--------------------------------------------
 CHEBI:27699     | polygalacturonide
 CHEBI:78616     | carbohydrates and carbohydrate derivatives
(2 rows)
```

What I find looks reasonable, but there appears to be missing data:

http://www.ebi.ac.uk/chebi/chebiOntology.do?chebiId=CHEBI:16646&treeView=true#vizualisation

Based on the above, I would expect to find oligosaccharide, polysaccharide, etc.

Is there some problem with the generic dump, or am I making a query error?

Thanks !

**Comment by muthuvenkat** [comment]
Those relationships are linked to secondary ids for ex. oligosaccharide,
```
select * from relation where FINAL_ID in (select id from vertice where compound_id in (35319, 25679, 7758,50699)) ;
select * from VERTICE where id = 4046;
```

**Comment by cornett** [comment]
Hi,

Thanks !  I think I understand now.

Best Regards,

Ben
