### ISSUE TITLE
Please check Status Ok for Chebi: 89484, 89719, 89891, 89828, 88764, 80946 and 58784

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3375]
Hello,
I have just noticed that the ChEBIs still have status OK:
89484
89719
89891
89828
88764
80946
58784
Can you please check them? We need them for RHEA.
TIA,
Lucila

**Comment by stevet7** [comment]
Hi Lucila,
All these entries have now been upgraded to checked status.
Cheers,
Steve
