### ISSUE TITLE
CHEBI:70315 review

### ISSUE THREAD

**Issue by nnouspikel** [ebi-chebi/ChEBI#3376]
Dear ChEBI curators,

We have annotated CHEBI:70315 in RHEA:52652 (PMID:11906033; 12010494; 8586261) and would like it to be reviewed for RHEA mapping. Could you please help us with this?

Thank you very much for your help.

Nevila Hyka-Nouspikel

**Comment by G-Owen** [comment]
Looks like Steve did this on Oct. 3 - I will close the ticket.
