### ISSUE TITLE
CHEBI:138267 formula to be fixed

### ISSUE THREAD

**Issue by nnouspikel** [ebi-chebi/ChEBI#3378]
Dear ChEBI curators,

Could you please help us with correcting the formula of CHEBI:138267? It should be C11H24NO7P. we need it to balance/validate RHEA:54544.

Many thanks for your help.

Nevila Hyka-Nouspikel

**Comment by stevet7** [comment]
Formula updated as requested. I've also fully checked the entry
Kind regards,
Steve
