### ISSUE TITLE
CHEBI:138658 formula to be fixed

### ISSUE THREAD

**Issue by nnouspikel** [ebi-chebi/ChEBI#3380]
Dear ChEBI curators,

I need your help to fix the formula of CHEBI:138658, a diglyceride in which both groups are linoleoyl with their positions of acylation unspecified. Its formula should be C39H68O5. We need it to balance the stoichiometry of RHEA:55265 (PMID:28248318).

Many thanks for you help.

Best regards,

Nevila Hyka-Nouspikel

**Comment by G-Owen** [comment]
Hi Nevila,

Now sorted.

Kind regards,
Gareth
