### ISSUE TITLE
CHEBI:60627 - typo in the name

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#3382]
Dear Chebi curators,

There is a typo in the name of CHEBI:60627
...-GlaNAc-(1<arrow>right</arrow>4)-<stereo>beta</stereo>-<stereo>D</stereo>-GlcNAc}-Asn residue
-->
...-GlcNAc-(1<arrow>right</arrow>4)-<stereo>beta</stereo>-<stereo>D</stereo>-GlcNAc}-Asn residue

Cheers, Anne

**Comment by G-Owen** [comment]
Hi Anne,

Now sorted - thanks for letting us know.

Kind regards,
Gareth
