### ISSUE TITLE
Update suggestion for CHEBI:93296

### ISSUE THREAD

**Issue by sabrinatoro** [ebi-chebi/ChEBI#3385]
Hello, 
I would like to suggest some update for the term (2R)-N-hydroxy-3-methyl-2-[(4-phenylphenyl)sulfonyl-propan-2-yloxyamino]butanamide (CHEBI:93296)

Cross references to add: 
- 11292680 (PubChem) 

Synonyms to add: 
- ARP 101
- MMP-2 inhibitor

Ontology: 
- has role - matrix metalloproteinase inhibitor (CHEBI:50664)

Thank you!

**Comment by G-Owen** [comment]
Now updated to 3-star status.

Best regards,
Gareth
