### ISSUE TITLE
please update CHEBI:35973

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#3386]
Dear Chebi curators,

Please would you update the 2D structure of CHEBI:35973 in order to have only one R group (i.e remove the 2R groups attached to C2)

I need this compound to balance the reaction catalyzed by EC 2.8.3.5 (RHEA:24564)

Thanks for your support

Cheers, Anne

**Comment by G-Owen** [comment]
Hi Anne,

Now done (I have retained the other structure as an alternative, just in case anyone wants it).

Bet regards,
Gareth
