### ISSUE TITLE
Please update structures of CHEBI:136413, CHEBI:136414, CHEBI:136415 and CHEBI:136418 

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#3391]
Hi Gareth and Steve,

The recent necessary update of the structures of CHEBI:136412 and CHEBI:136416 requested in #3364, necessitates further updates of wrong structures to keep our Rhea reactions balanced.
For all four structures the problem is a wrongly included 3' phosphate group. The updated structures are attached.
[CHEBI_136413.txt](https://github.com/ebi-chebi/ChEBI/files/1470509/CHEBI_136413.txt)
[CHEBI_136414.txt](https://github.com/ebi-chebi/ChEBI/files/1470516/CHEBI_136414.txt)
[CHEBI_136415.txt](https://github.com/ebi-chebi/ChEBI/files/1470519/CHEBI_136415.txt)
[CHEBI_136418.txt](https://github.com/ebi-chebi/ChEBI/files/1470526/CHEBI_136418.txt)

Cheers,
Kristian

**Comment by G-Owen** [comment]
Hi Kristian,

The structures have now been updated. 
(I also modified the ChEBI names of the entries to reflect the reduction in the charge of the structures has become one unit less negative).

Best regards,
Gareth
