### ISSUE TITLE
CHEBI:83891 Formula

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3410]
Dear Chebi curators,
I would like to request that you change the formula of CHEBI:83891 to C44H82NO11S as it is defined to be an N-acyl-(3-O-sulfo-D-galactosyl)sphingosine(1−) in which the N-acyl group is composed of 20 carbons and 1 double bond.
Thank you for your help,
Lucila

**Comment by G-Owen** [comment]
Hi Lucila,

Thanks for spotting this. I have now updated the formula, mass and monoisotopic mass.

Kind regards,
Gareth
