### ISSUE TITLE
CHEBI:68497 and formula

### ISSUE THREAD

**Issue by ANiknejad** [ebi-chebi/ChEBI#3417]
Dear ChEBI curators,

Could you please modify the formula of CHEBI:68497 to have C7H12NO9PR, such 'acyl children' ( 1-acyl-sn-glycero-3-phosphoserine(1−)  (CHEBI:64379) and 2-acyl-sn-glycero-3-phosphoserine(1−) (CHEBI:65214) ) have?

(CHEBI:68510 conjugate acid, to review too)

Many thanks in advance.

Cheers,

Anne Niknejad

**Comment by G-Owen** [comment]
Now done.

Best regards,
Gareth
