### ISSUE TITLE
CHEBI:67274 and formula

### ISSUE THREAD

**Issue by ANiknejad** [ebi-chebi/ChEBI#3418]
Dear ChEBI curators,

Could you please modify the formula of CHEBI:67274, to have C6H13NO7PR, such 'acyl children' ( 1-acyl-sn-glycero-3-phosphoethanolamine zwitterion (CHEBI:64381) and 2-acyl-sn-glycero-3-phosphoethanolamine zwitterion (CHEBI:65213) ) have?

(CHEBI:64574 tautomer, to review too)

Many thanks in advance.

Cheers,

Anne Niknejad

**Comment by stevet7** [comment]
Formulae amended as requested.
Cheers,
Steve
