### ISSUE TITLE
CHEBI:60479, to review

### ISSUE THREAD

**Issue by ANiknejad** [ebi-chebi/ChEBI#3419]
Dear ChEBI curators,

I guess, CHEBI:60479 lysophosphatidylcholine needs some review to follow the logic of CHEBI:64574 (lysophosphatidylethanolamine) for example.

I attach here the structure
[60479.txt](https://github.com/ebi-chebi/ChEBI/files/1702388/60479.txt)

Formula should be C9H20NO7PR, such as in CHEBI:17504

Definition should be (derived from CHEBI:68510)
'An acylglycerophosphocholine resulting from partial hydrolysis of a phosphatidylcholine, which removes one of the fatty acid groups. The structure is depicted in the image where R1 = acyl, R2 = H or where R1 = H, R2 = acyl.'

Many thanks for your help.

Cheers,

Anne Niknejad

**Comment by stevet7** [comment]
Hi Anne,
Done as requested. I've put a negative charge on the phosphate (as this is the pH 7.3. version) and adjusted the formula accordingly.
Cheers,
Steve
