### ISSUE TITLE
CHEBI:137366 class has a different ID as it's name

### ISSUE THREAD

**Issue by cmungall** [ebi-chebi/ChEBI#3424]
see:

http://www.ebi.ac.uk/chebi/searchId.do?chebiId=137366

also in the obo

```
[Term]
id: CHEBI:137366
name: CHEBI:4042
subset: 2_STAR
def: "has_role insecticide" []
is_a: CHEBI:50860
```

something has clearly shifted, the has_role should be a relationship not a def, maybe the name field was meant to be an id field

**Comment by G-Owen** [comment]
Hi Chris,
Thanks for drawing this to our attention. I think somebody used the submission tool to suggest that we add the '_has role_ insecticide' relationship to CHEBI:4042. But ChEBI 4042 (cypermethrin) already has  _has role_  pyrethroid ester insecticide (CHEBI:39116) which _is_a_ pyrethroid insecticide which _is_a_ insecticide, so it should inherit the role anyway. I have changed the status of CHEBI:137366 to 'deleted'.
