### ISSUE TITLE
CHEBI:33853, please update entry

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#3436]
Dear ChEBI curators,

Please would you update CHEBI:33853 structural data (2D structure, formula and charge)
 with attached molfile.
[CHEBI_33853.mol.txt](https://github.com/ebi-chebi/ChEBI/files/1774671/CHEBI_33853.mol.txt)

I would also suggest to replace "Aryl-Alcohols" MetaCyc xref by "Phenols"
See:
http://metacyc.ai.sri.com/compound?orgid=META&id=Aryl-Alcohols
http://metacyc.ai.sri.com/compound?orgid=META&id=Phenols

Cheers, Anne

**Comment by G-Owen** [comment]
Now done.

Cheers,
Gareth
