### ISSUE TITLE
ChEBI with multiple formula, mass 

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#3441]
Hi ChEBI,

We  have identified 22 ChEBI that have multiple formulas or masses in the chebi curator tool with status CHECKED or OK (2018-03-08).
Please would you update these entries in order to have only one formula or mass with status CHECKED or OK (the other formula(s) or mass(es) should all have a status DELETED) .
CHEBI:32955 is the only case we found with 2 formulas status CHECKED

Thanks for your support,

Cheers, Anne

- Multiple formula/mass -- used in Rhea (approved):
CHEBI:35348
CHEBI:72825

- Multiple formulas -- used in Rhea (but not approved)
CHEBI:16460
CHEBI:16051
CHEBI:16366
CHEBI:32955 (2 different formulas with status CHECKED)
CHEBI:76225

- Multiple formulas -- not used in Rhea (UniProt name DELETED)
CHEBI:18122
CHEBI:15986 
CHEBI:62885 
CHEBI:29159 
CHEBI:15722 
CHEBI:75185 
CHEBI:28966 
CHEBI:16635
CHEBI:16663 
CHEBI:29160
CHEBI:16361
CHEBI:29157 
CHEBI:29165 
CHEBI:29164 
CHEBI:17995

**Comment by G-Owen** [comment]
Done
