### ISSUE TITLE
classification of drugs in CHEBI

### ISSUE THREAD

**Issue by cmungall** [ebi-chebi/ChEBI#3442]
We use the CHEBI drug role for reasoning in GO, but people are unhappy with the classification of drugs in CHEBI, see https://github.com/geneontology/go-ontology/issues/15379.

I am working to get you a list of structures that we feel should be reclassified. I realize that drug is a very all encompassing role, and many chemical structures may be used therapeutically used that are not classically thought of as drugs.

The solution may end up as being as simple as introducing a distinction between different senses of the word drug. This may help: https://en.wikipedia.org/wiki/Medication#Definition

**Comment by cmungall** [comment]
You can close this as we have decided to just say NO to drugs in GO

**Comment by G-Owen** [comment]
Will close
