### ISSUE TITLE
ketose should have has-part to ketone functional group

### ISSUE THREAD

**Issue by cmungall** [ebi-chebi/ChEBI#3443]
no definition for: http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A24978

From WP: A ketose is a monosaccharide containing one ketone group per molecule.
https://en.wikipedia.org/wiki/Ketose

the CHEBI term only has is-a links. We would like a link to ketone group for GO, thanks

**Comment by G-Owen** [comment]
Hi Chris,
I think the WP definition is incomplete. Just as the term aldose is used to refer not just to the open-chain aldehydo- sugars, but also to their ring-closed hemiacetal forms (e.g. glucopyranose), so the term ketose refers not just to open-chain keto-sugars, but also their ring-closed hemiketal forms. I have added a definition to ChEBI:24978 which which covers both forms (and is analogous to that for aldose).

Best regards,
Gareth
