### ISSUE TITLE
Formula correction for newly submitted entities ChEBI:140432, 140444, 140445 and 140446.

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3445]
I have submitted 4 new entities (ChEBI:140432, 140444, 140445 and 140446) and they all need a Formula different from the one suggested by the submission tool. I have added the correct formula in the Description box in each case. Please check.
Best,
Lucila

**Comment by G-Owen** [comment]
Hi Lucila,

All now done.

Cheers,
Gareth
