### ISSUE TITLE
NTR: kaolin / kaolinite

### ISSUE THREAD

**Issue by pbuttigieg** [ebi-chebi/ChEBI#3446]
Greetings CHEBI team - over at ENVO, we're cooking up some environmental material classes which would benefit from kaolin being included in CHEBI. The [Wikipedia](https://en.wikipedia.org/wiki/Kaolinite) description seems sufficient. Many thanks in advance!

xref: https://github.com/EnvironmentOntology/envo/issues/583

**Comment by G-Owen** [comment]
Hi Pier,

We now have kaolin [http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:140503] which _has part_ kaolinite [http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:140499].
The entries should be fully searchable after Easter.

Best regards,
Gareth

**Comment by pbuttigieg** [comment]
Many thanks!
