### ISSUE TITLE
CHEBI:140474, please change formula

### ISSUE THREAD

**Issue by ANiknejad** [ebi-chebi/ChEBI#3447]
Dear ChEBI curators,

Could you please check and change the formula for CHEBI:140474 diricinolein, that I recently created?

Formula should be C39H7207, please see here further information

https://www.chemicalbook.com/ChemicalProductProperty_EN_CB1408241.htm

https://www.ncbi.nlm.nih.gov/pubmed/?term=18643899

Many thanks in advance,
Cheers,

Anne N.

**Comment by G-Owen** [comment]
Hi Anne,
Given that diricinolein has contains two ricinoleoyl groups, one of them must be attached to a terminal hydroxy group of the glycerol. Would you prefer an alternative structure that shows this?  - to see what I mean, visit the ChEBI public website entry for CHEBI:140474 and click on the **more structures >>** link underneath the structure box. Let me know if you want me to make swap the current default structure with the alternative structure. 

Best regards,
Gareth

**Comment by ANiknejad** [comment]
Hi Gareth,

I am back only now on your question...sorry about that.
Yes the alternative structure would be great, thank you in advance!

Anne

**Comment by amalik01** [comment]
Alternative structure is now the default structure.

**Comment by amalik01** [comment]
Hi Anne,

I am not able to remove your submitter remarks from the entry. Are you able to remove them via the submission tool?
