### ISSUE TITLE
Compounds used in Rhea with compound status CHECKED and structure status OK

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#3450]
Dear ChEBI curators,

You will find hereafter a list of 3 compounds used in Rhea (public release) that have a status CHECKED (C) but a structure with status OK (E).

Please, would you review and check these structures.

Thanks for your time

Best wishes, Anne

CHEBI  status_compound status_structure UniProt_name
2571	C	E	an aliphatic alcohol
18359	C	E	holo-[acyl-carrier protein]
30212	C	E	hnu

**Comment by G-Owen** [comment]
Now done.

Best regards,
Gareth
