### ISSUE TITLE
Compounds used in Rhea with compound status OK and structure status OK

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#3451]
Dear ChEBI curators,

You will find hereafter a list of 15 compounds used in Rhea (public release) that still have a status OK (E).
Please, would you review these 15 compounds.

Thanks for your time

Best wishes, Anne

CHEBI status_compound status_structure UniProt_name
732	        E	E	5beta-dihydrocortisol
4712	E	E	1alpha-hydroxyvitamin D2
31883	E	E	N-(9Z-octadecanoyl)-dopamine
34172	E	E	16alpha,17beta-dihydroxyandrost-4-en-3-one
34787	E	E	heptanal
80651	E	E	1,2-ditetradecanoyl-sn-glycerol
81013	E	E	7alpha,25-dihydroxy-4-cholesten-3-one
81467	E	E	7alpha-hydroxypregnenolone
81471	E	E	3beta,7alpha-dihydroxyandrost-5-en-17-one
81481	E	E	11beta,17beta-dihydroxyandrost-4-ene-3-one
81485	E	E	osthenol
88752	E	E	cholesteryl (5Z,8Z,11Z)-eicosatrienoate
88756	E	E	cholesteryl (6Z,9Z,12Z)-octadecatrienoate
89268	E	E	2-hydroxy-3-methoxy-17beta-estradiol
125678	E	E	N-acetyl-dopamine

**Comment by G-Owen** [comment]
Dear Anne,
Steve and I have worked through the list over the past couple of days - you'll be pleased to hear that we have now finished.

Best regards,
Gareth
