### ISSUE TITLE
Please update structural data for CHEBI:18000

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#3458]
Dear ChEBI curators,

Please would you update structural data for CHEBI:18000
The 2D structure (status DELETED) was correct for me, could you change it to CHECKED and update also the formula status
Xrefs:
MetaCyc: Arylalkylamines

Needed for Rhea to create the reaction of EC 3.5.1.76
N-acetylarylalkylamine + H(2)O = arylalkylamine + acetate.

(this issue is related to #3457)

Thanks for your support
Cheers, Anne

**Comment by G-Owen** [comment]
Now done.
