### ISSUE TITLE
Missing alprazolam and and midazolam subClassOf benzodiazepine assertions?

### ISSUE THREAD

**Issue by turbomam** [ebi-chebi/ChEBI#3463]
I notice that 
`CHEBI:6931` - Midazolam
is not listed as a subclass of 
`CHEBI:22720` - benzodiazepine
even indirectly (subClassOf* if you're into RDFS)

and
`CHEBI:2611` alprazolam
isn't a subClassOf*
`CHEBI:22720` - benzodiazepine
either, although it is a CHEBI:35501 triazolobenzodiazepine

I'm not a pharmacologist, pharmacist, etc., but those assertions are present in [Wikipedia ](https://en.wikipedia.org/wiki/List_of_benzodiazepines) and the [NDF-RT](http://bioportal.bioontology.org/ontologies/NDFRT?p=classes&conceptid=http%3A%2F%2Fpurl.bioontology.org%2Fontology%2FNDFRT%2FN0000147927)

**Comment by amalik01** [comment]
Hi, 

Thanks for letting us know. I have linked these drugs as a subclass of benzodiazepines.

Midazolam (CHEBI:6931) is a imidazobenzodiazepine (CHEBI:142118) which is a benzodiazepine (CHEBI:22720).

alprazolam (CHEBI:2611) is a triazolobenzodiazepine (CHEBI:35501)  which is a  benzodiazepine (CHEBI:22720) 

Best Regards,
Adnan
