### ISSUE TITLE
Bug in SDF files generation

### ISSUE THREAD

**Issue by mSorok** [ebi-chebi/ChEBI#3466]
Dear ChEBI team,

I noticed that the SDF files, generated from molecule page in ChEBI do not follow the standards for this file format as defined here:
http://www.daylight.com/meetings/mug05/Kappler/ctfile.pdf (page 39)

There should not be a space line between the end of the molecule (line defined by "M  END") and the first line of the properties (line starting with a ">").
I am using CDK to parse these files, and it was not able to read the properties because of this blank line. I don't know if this applies to other chemistry tools.
Thank you very much in advance for the changes or for your advice.
Kind regards,

Maria Sorokina

**Comment by mSorok** [comment]
Just an additional comment: this bug seems to concern only the SDF files that can be downloaded from the molecule page. The total SDF files (ChEBI_complete_3star.sdf) do not have this bug (ie the space line after the "M  END" of the molecule).
Kind regards,
Maria

**Comment by muthuvenkat** [comment]
Sorry for the late reply. Its fixed now. Thanks for reporting.
