### ISSUE TITLE
CHEBI:30529, please correct charges in structure

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#3468]
Hi Gareth,

When looking at this compound,  nitritocobalamin, I can see the charges do not follow the common pattern for cob(III)alamins, where the Co ion has a (phony) negativ charge and the liganding nitrogen atoms positive chargs. Please update the compound.

Cheers,
Kristian

**Comment by amalik01** [comment]
The structure has now been corrected.
Adnan
