### ISSUE TITLE
Add synonym to CHEBI:91326

### ISSUE THREAD

**Issue by sabrinatoro** [ebi-chebi/ChEBI#3469]
Based on the compound structure, CHEBI:91326 could get the following synonym: 
AT7519

Also, this compound could probably have the following parent:
EC 2.7.11.22 (cyclin-dependent kinase) inhibitor (CHEBI:82665)

Information can be found here: 
- PMID: 26202950
- http://www.selleckchem.com/products/AT7519.html
- https://www.medkoo.com/products/4581?gclid=Cj0KCQjwl7nYBRCwARIsAL7O7dGVIlgi8MTCvMywjRHch_A3M8Xz1HluVxDZntP44eZF6NIBwJpMDDAaAorfEALw_wcB
- https://www.medchemexpress.com/AT7519.html?src=google-product&gclid=Cj0KCQjwl7nYBRCwARIsAL7O7dFPkbHnPEvacf8Ab8EG8s4nJ3WUObkCYkUBgolById3sTjH_2yOvkUaAn-6EALw_wcB

**Comment by amalik01** [comment]
The CHEBI entry: 91326 has been updated. Thank you.

Best Regards,
Adnan
