### ISSUE TITLE
Add synonyms to  	CHEBI:91736

### ISSUE THREAD

**Issue by cerivs** [ebi-chebi/ChEBI#3470]
New synonyms: (2S)-1-(6-Chloro-5-fluoroindol-1-yl)propan-2-amine
Ro-600175, Ro-60-0175

Add new Xref: CID 3045227

**Comment by G-Owen** [comment]
Hi Ceri,
As ChEBI:91736 (a 2-star entry) did not have any stereochemistry shown in its structure or name, I have left it as a parent entry for individual enantiomers, but upgraded it to 3-star status.  
There is now a new entry (CHEBI:142183) for the (S)-enantiomer, which is classed as is_a CHEBI:91736. 
All ChEBI entries are automatically linked to the matching PubChem CIDs, but the linking process takes a while - CHEBI:91736 should have an automatic x-ref to CID3045227 by the end of next month.

Kind regards,
Gareth
