### ISSUE TITLE
CHEBI:80729 and CHEBI:121196, please CHECK

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#3474]
Hi Gareth,

Please check CHEBI:80729, toxoflavin and CHEBI:121196, reumycin (1-demethyltoxoflavin), since I need the two for a Rhea reaction.
pmid:27070241

Cheers,
Kristian

**Comment by amalik01** [comment]
Hi Kristian,

These 2 entries have now been checked.

Best Regards,
Adnan
