### ISSUE TITLE
CHEBI:17521 - remove wrong synonyms

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#3477]
Dear Gareth,

CHEBI:17521 has two wrong synonyms coming from HMDB

N-(2-Phenylethyl)-acetamide | SYNONYM | HMDB | English | OK |   | P
N-Acetylphenylethylamine | SYNONYM | HMDB | English | OK |   | P

Cheers, Anne

**Comment by amalik01** [comment]
Hi Anne,

I have marked the 2 synonyms as deleted.

Best Regards,
Adnan
