### ISSUE TITLE
Incorrect inferences found in GO made using Chebi found

### ISSUE THREAD

**Issue by hdrabkin** [ebi-chebi/ChEBI#3479]
These two have been found during spot-checking new chebi import on a local branch.
These are inferred relationships currently found in the LIVE GO ontology using current chebi import
I only note the questionable inferences

ADP metabolic process
is_a purine ribonucleoside monophosphate metabolic process
     should if anything be a purine ribonucleoside diphosphate metabolic process

Also found
CDP metabolic process
is_a ribonucleoside metabolic process; No.; is a ribonucleoside diphosphate metabolic process?

UDP metabolic process
is_a pyrimidine ribonucleoside metabolic process ; no pyrimidine ribonucleoside diphosphate metabolic process?

Not all have a problem.
GDP, GTP, GMP metabolic processes do not include an questionable inference

NTP metablic processes
ATP metabolic process
is_a purine ribonucleoside monophosphate metabolic process
CTP metabolic process
is_a pyrimidine ribonucleoside metabolic process
UTP metabolic process
is_a pyrimidine ribonucleoside metabolic process

NMPs metablic processes
CMP metabolic process
is_a pyrimidine ribonucleoside metabolic process
UMP metabolic process
is_a pyrimidine ribonucleoside metabolic process

**Comment by deustp01** [comment]
Looking at the ChEBI entry for ATP (15422), the ontology view shows that ATP is_a adenosine 5'-phosphate is_a purine ribonucleoside 5'-monophosphate, from which I guess one should infer that ATP is_a purine ribonucleoside 5'-monophosphate. Simultaneously, the ontology view shows a separate path from ATP whereby ATP is_a purine ribonucleoside 5'-triphosphate.
Could this be a part of the problem Harold is describing?

**Comment by hdrabkin** [comment]
Checking in to ask if any progress on this?

**Comment by G-Owen** [comment]
Purine ribonucleoside 5'-monophosphate (CHEBI:37021) was  assigned as a parent term for adenosine 5'-phosphate (CHEBI:37096) in 2013. I suspect it was ok when it was assigned, but the assignment of new terms as is_a adenosine 5'-phosphate rendered the relationship incorrect. The relationship has now been removed from adenosine 5'-phosphate, but been added to the individual child terms where appropriate. This should fix the problem, but let me know if not!

Sorry this took so long to get attention and thank-you for your persistence and help in getting it sorted.
Kind regards,
Gareth
