### ISSUE TITLE
Can't upload structure for NTR

### ISSUE THREAD

**Issue by cerivs** [ebi-chebi/ChEBI#3481]
I am trying to submit a new chemical submission ID   13051.  I drew it in the advanced search, exported the file copied it to a text editor.  Made a new submission pasted in the Ketcher file into the edit structure "open file " set to "Input" 
When I try to update structure  I get a connection failed error and then when I try to save and return I get the error  Error loading molfile  Error: Molfile version unknown: 9999 V2.  The  Smiles information populates and I can see the structure it just isn't saving.

  Ketcher 07111816312D 1   1.00000     0.00000     0

 49 52  0     0  0            999 V2000
   -3.6591    3.9088    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -3.9179    2.9429    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -4.8838    2.6841    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -5.5909    3.3912    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -5.3321    4.3571    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -4.3662    4.6159    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -3.2108    2.2358    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -3.4696    1.2698    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -4.4355    1.0110    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -5.1426    1.7182    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.2448    2.4946    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.5377    1.7875    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.7965    0.8216    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.7625    0.5627    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -6.0392    5.0642    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -3.0213   -0.4032    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -1.9860    3.4605    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -6.1086    1.4593    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -2.6591    3.9088    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.4109    3.9783    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.6698    3.0124    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.6357    2.7536    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.3428    3.4607    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.0840    4.4266    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.1181    4.6854    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.9626    2.3053    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.2214    1.3393    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    3.1874    1.0805    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.8945    1.7876    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.9967    2.5641    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.2896    1.8570    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.5484    0.8911    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.5143    0.6322    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.7911    5.1337    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.7732   -0.3337    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.7379    3.5300    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    4.8604    1.5288    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.4109    3.9783    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.1874    0.0805    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.9305    0.3216    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0645   -0.1784    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0645   -1.1785    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.9305   -1.6785    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.7965   -1.1785    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.7965   -0.1784    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.8016    0.3215    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -2.6625    0.3215    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.9305   -2.6785    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -4.9355    0.1450    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0     0  0
  3  4  2  0     0  0
  4  5  1  0     0  0
  5  6  1  0     0  0
  6  1  1  0     0  0
  2  7  1  0     0  0
  8  9  1  0     0  0
  9 10  1  0     0  0
 10  3  1  0     0  0
  7 11  1  0     0  0
 11 12  1  0     0  0
 12 13  1  0     0  0
 13 14  1  0     0  0
 14  8  1  0     0  0
  5 15  2  0     0  0
 14 16  2  0     0  0
 11 17  2  0     0  0
  4  3  1  0     0  0
 10 18  1  6     0  0
  1 19  1  1     0  0
 20 21  1  0     0  0
 23 24  1  0     0  0
 24 25  1  0     0  0
 25 20  1  0     0  0
 21 26  1  0     0  0
 27 28  1  0     0  0
 28 29  1  0     0  0
 29 22  1  0     0  0
 26 30  1  0     0  0
 30 31  1  0     0  0
 31 32  1  0     0  0
 32 33  1  0     0  0
 33 27  1  0     0  0
 24 34  2  0     0  0
 33 35  2  0     0  0
 30 36  2  0     0  0
 23 22  2  0     0  0
 29 37  1  1     0  0
 20 38  1  6     0  0
 28 39  1  6     0  0
 13 40  1  6     0  0
 32 40  1  1     0  0
 40 41  1  0     0  0
 41 42  1  0     0  0
 42 43  1  0     0  0
 43 44  1  0     0  0
 44 45  1  0     0  0
 45 40  1  0     0  0
 41 46  2  0     0  0
 45 47  2  0     0  0
 43 48  1  1     0  0
  9 49  1  1     0  0
M  END
![image](https://user-images.githubusercontent.com/2602957/42648314-665c858c-85bb-11e8-904f-c4e377ab1dfb.png)

**Comment by muthuvenkat** [comment]
Hi @cerivs, 

I have found a bug in the molfile, there are two bonds that have been pasted on top of each other. 
Please delete only the green coloured bond and redraw the structure, that should fix it. 
I have also attached the mol for your reference. 
Please let us know if this fixes the issue.

![screen shot 2018-07-20 at 11 33 26](https://user-images.githubusercontent.com/1352644/42998101-e99d757c-8c10-11e8-8502-6c6eafb2d04c.png)


  Ketcher 07201811322D 1   1.00000     0.00000     0

 49 51  0     0  0            999 V2000
   -3.6184    3.8653    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -3.8743    2.9102    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -4.7295    2.7293    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -5.4287    3.4285    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -5.2728    4.3086    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -4.3176    4.5646    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -3.1751    2.2109    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -3.4310    1.2557    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -4.3862    0.9998    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -5.0854    1.6991    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.2198    2.4669    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.5206    1.7676    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.7765    0.8125    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.7318    0.5564    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -5.9720    5.0079    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -2.9877   -0.3987    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -1.9639    3.4220    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -6.0407    1.4431    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -2.6295    3.8653    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.3841    3.9341    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.6401    2.9789    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.5953    2.7230    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.2945    3.4222    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.0386    4.3774    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.0834    4.6333    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.9408    2.2797    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.1967    1.3244    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    3.1520    1.0685    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.8512    1.7677    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.9856    2.5356    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.2864    1.8363    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.5423    0.8812    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.4975    0.6252    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.7378    5.0766    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.7535   -0.3300    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.7297    3.4907    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    4.8063    1.5118    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.3952    3.9341    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.1520    0.0796    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.9202    0.3180    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0638   -0.1764    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0638   -1.1654    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.9202   -1.6598    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.7765   -1.1654    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.7765   -0.1764    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.7927    0.3179    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -2.6329    0.3179    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.9202   -2.6487    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -4.8806    0.1434    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0     0  0
  4  5  1  0     0  0
  5  6  1  0     0  0
  6  1  1  0     0  0
  2  7  1  0     0  0
  8  9  1  0     0  0
  9 10  1  0     0  0
 10  3  1  0     0  0
  7 11  1  0     0  0
 11 12  1  0     0  0
 12 13  1  0     0  0
 13 14  1  0     0  0
 14  8  1  0     0  0
  5 15  2  0     0  0
 14 16  2  0     0  0
 11 17  2  0     0  0
 10 18  1  6     0  0
  1 19  1  1     0  0
 20 21  1  0     0  0
 23 24  1  0     0  0
 24 25  1  0     0  0
 25 20  1  0     0  0
 21 26  1  0     0  0
 27 28  1  0     0  0
 28 29  1  0     0  0
 29 22  1  0     0  0
 26 30  1  0     0  0
 30 31  1  0     0  0
 31 32  1  0     0  0
 32 33  1  0     0  0
 33 27  1  0     0  0
 24 34  2  0     0  0
 33 35  2  0     0  0
 30 36  2  0     0  0
 23 22  2  0     0  0
 29 37  1  1     0  0
 20 38  1  6     0  0
 28 39  1  6     0  0
 13 40  1  6     0  0
 32 40  1  1     0  0
 40 41  1  0     0  0
 41 42  1  0     0  0
 42 43  1  0     0  0
 43 44  1  0     0  0
 44 45  1  0     0  0
 45 40  1  0     0  0
 41 46  2  0     0  0
 45 47  2  0     0  0
 43 48  1  1     0  0
  9 49  1  1     0  0
  4  3  2  0     0  0
M  END

**Comment by cerivs** [comment]
Worked like a charm thanks!
