### ISSUE TITLE
add items to CHEBI:75244 - aklaviketone

### ISSUE THREAD

**Issue by rwst** [ebi-chebi/ChEBI#3485]
Please add PMID: 3165374, PubChem CID: 443827, and the species Streptomyces galilaeus.

**Comment by G-Owen** [comment]
The species, taxonomy ID  and associated PMID have now been added to the Species Information section. The PubChem CIDs for all of the compounds in ChEBI are now generated automatically based on structure and name matching, so in the public website appear under the Automatic XRefs tab.

Kind regards,
Gareth
