### ISSUE TITLE
Name errors in several compounds

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#3486]
Hi Gareth,

I have found a number of entries with (methylsulfany) instead of (methylsulfanyl) in the names (missing 'l'). There are several errors in each entry.

CHEBI:136434 | ω-[(methylsulfany)alkyl]glucosinolate
CHEBI:136424 | (E)-ω-[(methylsulfany)alkyl]thiohydroximate
CHEBI:137257 | ω-[(methylsulfany)alkyl]glucosinolic acid
CHEBI:136425 | ω-(methylsulfany)alkyl desulfoglucosinolate
CHEBI:134680 | ω-(methylsulfany)-(E)-alkanal oxime

There is also one example of (methylsulfiny)
CHEBI:136435 | ω-[(methylsulfiny)alkyl]glucosinolate

Cheers,
Kristian

**Comment by G-Owen** [comment]
Hi Kristian,

Thanks for letting us know. 
I also found another one - CHEBI:137260. All are now fixed. The changes should work their way into the public site overnight.

Kind regards,
Gareth
