### ISSUE TITLE
food vs food role

### ISSUE THREAD

**Issue by Public-Health-Bioinformatics** [ebi-chebi/ChEBI#3489]
I think http://purl.obolibrary.org/obo/CHEBI_33290 "food" should be renamed "food role".  People coming across it in OLS etc. may be choosing it as a noun (material entity).  

In FoodOn we have "'food material': subClassOf 'environmental material' and 'has role' some food [CHEBI_33290]"

**Comment by amalik01** [comment]
Food does not imply any structural chemical feature hence it is a biological role in the ChEBI ontology. Food is also a term which is more understandable to the general public rather than food role. However, we have added food role as a synonym for food.

I hope this helps.

Best Regards,
Adnan
