### ISSUE TITLE
CHEBI:131709 error in definition

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#3493]
CHEBI:131709 N(6)-(1-hydroxy-2-oxopropyl)-L-lysine residue(1+)

definition:
... obtained by protonation of the guanidine function...

change 'guanidine function' to 'amino group' ;-)

+ add  
is a L-α-amino acid residue (CHEBI:83228) 

Cheers, Anne

**Comment by amalik01** [comment]
Now done. Thanks
Adnan
