### ISSUE TITLE
New term request: F2-Isoprostane

### ISSUE THREAD

**Issue by egonw** [ebi-chebi/ChEBI#3496]
F2-Isoprostane is a compound class name used in literature (MeSH: [D028441](https://meshb.nlm.nih.gov/record/ui?ui=D028441)). I have [collected literature about this compound in Scholia](https://tools.wmflabs.org/scholia/topic/Q33659470).

Four example compounds are given [in the CTD database](http://ctdbase.org/detail.go?type=chem&acc=D028441). CTD also reports it as a subclass of [CHEBI:138408](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:138408).

**Comment by G-Owen** [comment]
Hi Egon,
F2-isoprostane (CHEBI:142058) should be findable in ChEBI tomorrow.

Best regards,
Gareth

**Comment by egonw** [comment]
Added: https://www.wikidata.org/wiki/Q33659470
