### ISSUE TITLE
CHEBI:78437 status and merge

### ISSUE THREAD

**Issue by nnouspikel** [ebi-chebi/ChEBI#3497]
Dear ChEBI curators,

Could you please merge CHEBI:78436 and CHEBI:78437 keeping CHEBI:78437 as primary ID as it is the one used in RHEA?

Many thanks!

Nevila Hyka-Nouspikel

**Comment by amalik01** [comment]
Hi,

I have now merged CHEBI:78436 and CHEBI:78437. Unfortunately we do not have control of what the primary ID will be when entries are merged. In this case the primary ID is 78436 and the secondary ID is 78437.

Best Regards,
Adnan
