### ISSUE TITLE
Please add these relations to ChEBI:78452, 78542, 71502, 87785 and 27938

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3498]
Dear ChEBI Curators,

Can you please double check the following ChEBI relations? If correct, please add them as we need these relations for RHEA:
ChEBI:78452 is_a ChEBI:82940
ChEBI:78542 is_a ChEBI:79220
ChEBI:71502 is_a ChEBI:79218
ChEBI:87785 is_a ChEBI:82939
ChEBI:82939 is_a ChEBI:88057
ChEBI:27938 is_a ChEBI:88069
Thanks in advance for your help adding these.
Lucila

**Comment by G-Owen** [comment]
Hi Lucila,
I think these are now done. Please check and let me know if I have blundered!

Kind regards,
Gareth
