### ISSUE TITLE
New Term Request: Cinnamycin

### ISSUE THREAD

**Issue by Achchuthan** [ebi-chebi/ChEBI#3499]
Can I request cinnamycin to be added to ChEBI please? 
Here is a link for this chemical from Sigma: https://www.sigmaaldrich.com/catalog/product/sigma/c5241?lang=en&region=GB. There are peer-reviewed papers linked in this page.

In addition, here is another paper characterizing cinnamycin biosynthetic gene cluster: http://www.pnas.org/content/100/7/4316

Thanks & best wishes,
Achchuthan

**Comment by amalik01** [comment]
Hi,

An entry for cinnamycin has now been created (CHEBI: 141991).

Best Regards,
Adnan
