### ISSUE TITLE
New Term Request: Tipifarnib

### ISSUE THREAD

**Issue by Achchuthan** [ebi-chebi/ChEBI#3500]
Can I request an entry for tipifarnib in ChEBI please?

Please see following links for more details:
https://pubchem.ncbi.nlm.nih.gov/compound/159324
http://www.chemspider.com/Chemical-Structure.140122.html
https://www.ebi.ac.uk/chembldb/index.php/compound/inspect/CHEMBL289228
https://www.ncbi.nlm.nih.gov/pubmed/19707311

Thanks,
Achchuthan

**Comment by amalik01** [comment]
An entry has now been created for Tipifarnib (CHEBI: 141969).

Best Regards,
Adnan
