### ISSUE TITLE
Where can I find the current version number for ChEBI?

### ISSUE THREAD

**Issue by christabone** [ebi-chebi/ChEBI#3502]
Apologies if this is a silly question, but I cannot seem to find the "version number" for the most recent release of ChEBI (apart from the August 1st tweet).

I checked GitHub, the front page here (https://www.ebi.ac.uk/chebi/), the "About ChEBI" page, the FAQ, User Manual, the Reference Manual...but no luck. Is there a standard place where it is reported?

There is absolutely the possibility that I simply missed it written somewhere. Any and all help is appreciated. Thanks!

**Comment by christabone** [comment]
It looks to be available via OLS: https://www.ebi.ac.uk/ols/ontologies/chebi

Would this be the best place to check for the current version in the future?

**Comment by amalik01** [comment]
Hi,

You can find the version number in the ontology download files or you can visit the ChEBI statistics page:

https://www.ebi.ac.uk/chebi/statisticsForward.do

The current release is 166.

Best Regards,
Adnan
