### ISSUE TITLE
update name CHEBI:78760 - EC 2.7.1.91  (sphinganine kinase) inhibitor

### ISSUE THREAD

**Issue by cerivs** [ebi-chebi/ChEBI#3503]
The preferred name at EC for  EC 2.7.1.91  is Sphingosine kinase so the ChEBI term name should be
EC 2.7.1.91 (sphingosine kinase) inhibitor

Please add synonyms:
dihydrosphingosine kinase inhibitor
sphinganine kinase  inhibitor
sphingoid base kinase inhibitor

**Comment by amalik01** [comment]
This entry has now been renamed and additional synonyms now added.

Best Regards,
Adnan
