### ISSUE TITLE
Is cisplatin really an alkylating agent?

### ISSUE THREAD

**Issue by dsiegele** [ebi-chebi/ChEBI#3505]
cisplatin (CHEBI:27899) has role alkylating agent (CHEBI:22333).
This doesn't seem correct, because cisplatin doesn't contain an alkyl group.

**Comment by amalik01** [comment]
Thanks for pointing this out. The entry has now been updated and the alkylating agent term has been removed. Cisplatin is commonly but incorrectly referred to as an alkylating agent in the scientific literature due to its mechanism of action. 

Best Regards,
Adnan
