### ISSUE TITLE
CHEBI:27041, error in ChEBI name

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#3506]
Hi ChEBI,
I think there is an error in the common name of CHEBI:27041
(2S,3S)-3,4-dihydroxy-L-proline
should be
(3S,4S)-3,4-dihydroxy-L-proline
or (2S,3S,4S)-3,4-dihydroxyproline
Cheers, Anne

**Comment by amalik01** [comment]
The name has been corrected.
Best Regards,
Adnan
