### ISSUE TITLE
CHEBI:75591, please review and check this old submission

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#3507]
Hi ChEBI,

I submitted CHEBI:75591 the 2013-09-11. Please would you review this entry that still has a SUBMITTED status.

definition:
An <stereo>L</stereo>-aspartate residue that is substituted by an hydroxy group at position  major microspecies at pH 7.3.

synonym
(2S)-3-hydroxyaspartate residue

Relationships:
is a CHEBI:83228
is a CHEBI:32471 

Cheers, Anne

**Comment by G-Owen** [comment]
Now done. 
I merged 3-hydroxy-L-aspartate residue  (CHEBI:75591) with and peptide-3-hydroxy-L-aspartate (CHEBI:17427). Unfortunately, we have no control over how the merging tool does the merge, with the result that the parent ID is now CHEBI:17427 - sorry for any inconvenience caused.

Best regards,
Gareth
