### ISSUE TITLE
CHEBI:141805

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#3508]
Hi ChEBI

I had some trouble during my submission and apparently lost this relation
3R,4R)-3,4-dihydroxy-L-proline residue (CHEBI:141805) is a 3,4-dihydroxy-L-proline residue (CHEBI:141832) 
Please would you check that it is correctly stored in the db
Thanks, Anne

**Comment by amalik01** [comment]
I have now added this relation to the entry.
Best Regards,
Adnan
