### ISSUE TITLE
CHEBI:141993, please add missing relationships

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#3509]
Hi ChEBI

I still got an error when I tried to update my submission (id=13498, CHEBI:141993)  with these missing relationships:
3-hydroxy-L-proline residue (CHEBI:141835)  is_a  hydroxy-L-proline residue 
2-hydroxy-L-proline residue (CHEBI:141809)  is_a  hydroxy-L-proline residue

Thanks for your time
Cheers, Anne

**Comment by amalik01** [comment]
Hi Anne,

I have now added these relationships for you in the CHEBI entry: 141993

Best Regards,
Adnan
