### ISSUE TITLE
Improve ontological consistency of recent dT modifications

### ISSUE THREAD

**Issue by cviner** [ebi-chebi/ChEBI#3514]
Two new dT modifications were recently added, per my [prior](https://github.com/ebi-chebi/ChEBI/issues/3475) [requests](https://github.com/ebi-chebi/ChEBI/issues/3476).

Currently, the ontology annotates [5-(2-aminoethyl)uridine](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=142166) with `has functional parent` [2'-deoxyuridine](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A16450), while  [5-(2-aminoethoxy)methyl-2'-deoxyuridine](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=142164) is instead annotated with `has functional parent` [5-hydroxymethyl-2'-deoxyuridine](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A61288) (→ thymine).

This means that, for now, these two dT modifications are split within the ontology, with one being under the 5hmU → T and the other under dU.

Given that these are both [recently discovered dT modifications](https://doi.org/10.1073/pnas.1714812115), I suggest that the ontology be amended to ensure that both have thymine as their ancestor.

**Comment by amalik01** [comment]
Thanks for letting us know. The ontology has now been corrected. The ideal functional parent for both structures is uracil.

5-(2-aminoethyl)-2'-deoxyuridine (CHEBI:142166) has functional parent, 2'-deoxyuridine (CHEBI:16450) which has functional parent, uracil (CHEBI:17568).

and

5-(2-aminoethoxy)methyl-2'-deoxyuridine (CHEBI:142164) has functional parent, 5-hydroxymethyl-2'-deoxyuridine (CHEBI:61288) which has functional parent, 5-hydroxymethyluracil (CHEBI:16964) which has functional parent, uracil (CHEBI:17568).

Both structure have now been linked in the ontology. I hope this helps.

Best Regards,
Adnan
