### ISSUE TITLE
5hmU should only have functional parent T, not U

### ISSUE THREAD

**Issue by cviner** [ebi-chebi/ChEBI#3515]
[5-hydroxymethyluracil](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A16964) presently has two functional parents: thymine and uracil.

It should be revised to only have functional parent thymine, like [its deoxy counterpart](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A61288).

**Comment by G-Owen** [comment]
Interesting - the relationship to uracil as a functional parent was created in 2007, while that to thymine was only added in 2016! Anyway - now sorted.

Kind regards,
Gareth
