### ISSUE TITLE
CHEBI:60028, CHEBI:71477 and CHEBI:142410

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#3521]
Hi ChEBI,

Please remove  "major species at pH 7.3" from CHEBI:60028 and CHEBI:71477 definitions and review CHEBI:142410 that I've just submitted.

The major species at pH 7.3 is CHEBI:142410.  This is the ChEBI ID I will use in Rhea.
Please, feel free to add relationships between CHEBI:60028 and CHEBI:142410... I don't know which one could be correct... is tautomer of ?
Thanks for your support
Cheers, Anne

**Comment by amalik01** [comment]
Now done.

Best Regards,
Adnan

**Comment by amorgat** [comment]
Thank you!
