### ISSUE TITLE
NTR: CMB4563

### ISSUE THREAD

**Issue by robnash** [ebi-chebi/ChEBI#3522]
Hi,

Not sure this is where these are too be posted but I have a new term request but infortunately not much info. 

The chemical is named CMB4563 

Description: An ATP-competitive small molecule, and TOR complex inhibitor
Chemical name: 1-(4-(1H-Pyrrol-1-yl)phenyl)-3-methyl-8-(pyridin-3-yl)-1,3-dihydro-2H-imidazo[4,5-c]quinolin-2-one

Info links: http://glixxlabs.com/chemical-products/bioactive-screen-leads-p6/GLXC-15119
Paper where I saw this: https://www.ncbi.nlm.nih.gov/pubmed/?term=29895620

Cheers,
Rob

**Comment by G-Owen** [comment]
Hi Rob,
Thanks for all the information you provided with the request - I couldn't find much to add!
CMB4563 (CHEBI:142445) should be visible immediately using the URL:
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:142445
The entry will be indexed overnight and should be findable by name or structure searching tomorrow.

Kind regards,
Gareth
