### ISSUE TITLE
Can't log in to submit chemical

### ISSUE THREAD

**Issue by cerivs** [ebi-chebi/ChEBI#3524]
https://www.ebi.ac.uk/chebi/submission/login
Getting the error 
HTTP Status 500 - /WEB-INF/facelets/layout/template-ebi.xhtml @82,64 test="#{loginBean.databaseSid != 'CHEZPRO'}" Error creating bean with name 'loginBean': Invocation of init method failed; nested exception is org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is javax.persistence.PersistenceException: org.hibernate.TransactionException: JDBC begin transaction failed:

**Comment by muthuvenkat** [comment]
@cerivs, Sorry for the inconvenience caused. Can you please try now, its working.

**Comment by cerivs** [comment]
thanks working now
