### ISSUE TITLE
ntr: tschimganine & derivatives

### ISSUE THREAD

**Issue by mah11** [ebi-chebi/ChEBI#3526]
I would like to have ChEBI terms for three compounds used in PMID:29900664 (full text https://onlinelibrary.wiley.com/doi/epdf/10.1111/gtc.12604):

1. tschimganine
2. alpha-hibitakanine
3. beta-hibitakanine

Unfortunately, I don't know very much about any of them. Tschimganine is CHEMBL2165582, and a google search found the CAS number 38970-49-9:

https://www.ebi.ac.uk/chembldb/index.php/compound/inspect/CHEMBL2165582
https://pubchem.ncbi.nlm.nih.gov/substance/254775907
https://pubchem.ncbi.nlm.nih.gov/substance/163320854
https://www.chemicalbook.com/ChemicalProductProperty_EN_CB4989288.htm
http://www.latoxan.net/details-tschimganine-232.html

For alpha-hibitakanine and beta-hibitakanine, there's even less to go on. PMID:29900664 briefly mentions synthesizing them from tschimganine, and has structure drawings and NMR spectra in supplemental data. I haven't found them mentioned anywhere else.

https://onlinelibrary.wiley.com/action/downloadSupplement?doi=10.1111%2Fgtc.12604&file=gtc12604-sup-0001-Supinfo.pdf

**Comment by amalik01** [comment]
Hi,

I have created 3 entries for you in ChEBI (ChEBI:142517, ChEBI:142523, ChEBI:142524). Unfortunately there isn't much information available regarding the hibitakanine structures.

I hope this helps.

Best Regards,
Adnan

**Comment by mah11** [comment]
Thank you - just having ChEBI IDs for all of them helps for our curation.
