### ISSUE TITLE
Errors in structures of isonocardicin A compounds

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#3527]
Hi Gareth and Adnan,

I have realised that the structures for the isonocardicin A compounds (CHEBI:16483, CHEBI:57788 and CHEBI:77633) are wrong concerning the stereoconfiguration of C-9' and C-5. The correct structure can be found in pmid:15252031 . You can also compare with CHEBI:81022,  isonocardicin C.

I have attached the corrected structures.

Please also add a cross reference from CHEBI:57788 to MetaCyc ISONOCARDICIN-A

**Comment by kaxelsen** [comment]
I just tried to attach the new structures, but I don't think it worked.

I will send them to you in a mail.

Cheers,

Kristian

**Comment by amalik01** [comment]
Now done.

Best Regards,
Adnan
