### ISSUE TITLE
Update CHEBI:83960 common name

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#3529]
Dear ChEBI curators,

I submitted CHEBI:83960 quite a long time ago ;-)
I should have mentioned the anomer in the common name.
So please would you change ChEBI common name to
<element>N</element><smallsup><locant>omega</locant></smallsup>-<stereo>alpha</stereo>-(ADP-<stereo>D</stereo>-ribosyl)-<stereo>L</stereo>-arginine(1<minus/>) residue

arginine OR argininium, I let you decide!
You can also add the citation we use in Rhea
PMID:3090031

Cheers, Anne

**Comment by amalik01** [comment]
Now done.

Best Regards,
Adnan
