### ISSUE TITLE
Please add description to CHEBI:142575 and 142576

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3530]
Please add the following Description to
ChEBI:142575 A cholesterol derivative in which one of the hydrogen attached to the C25 has been replaced by another atom or group.
ChEBI:142576 A cholesteryl beta-D-glucoside derivative in which one of the hydrogen attached to the C25 of the cholesterol has been replaced by another atom or group.
Thanks

**Comment by amalik01** [comment]
I have now checked both entries and have added a definition to the entries.

Best Regards,
Adnan
