### ISSUE TITLE
ChEBI:9788 xrefs

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3531]
Dear ChEBI Curators,
ChEBI:9788 has 2 xrefs to KEGG:
compound C06132,  which has a lacto-series root (-Gal-beta-1-3-GlcNAc-beta-1-3-)
glycan G00054, which has a neolacto-series root (-Gal-beta-1-4-GlcNAc-beta-1-3-)
I believe the error comes from Kegg, because they say these 2 compounds are the same, when actually C06132 is the same as G00042 (if I'm not wrong). 
The current 2D-structure in CHEBI:9788 corresponds to compound C06132, which to me looks the same as CHEBI:62650
And the neolacto G00054 already exists as CHEBI:28471
Can you please double check if changes/merges are needed? 
Thanks for your time,
Lucila

**Comment by amalik01** [comment]
Thanks for letting us know about this issue. It has now been fixed and the duplicate entries have been merged.

Adnan
