### ISSUE TITLE
ChEBI:28743 IV2Fuc-Lc4Cer(d18:1(4E))

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3536]
Dear ChEBI Curators,
Seems like the structure for ChEBI:28743 has the wrong linkage between GlcNAc and Gal, instead of 1->4, it should be 1->3, as it is the root for all lacto-series glycosphingolipids. As you can corroborate, ChEBI:28743 derives from ChEBI:17292, so it should keep the same linkage. Thanks in advance for your prompt action.
Best,
Lucila

**Comment by amalik01** [comment]
Hi Lucila,
I have updated CHEBI: 28743 as requested. Do you want to add the following as synonyms to the entry?

IV2-a-Fuc-Lc4Cer(d18:1(4E))
Lc4Cer(d18:1(4E))

**Comment by amalik01** [comment]
synonyms now added
