### ISSUE TITLE
ChEBI:90802 IV2Fuc-Lc4Cer

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3537]
Dear ChEBI Curators,
As in previous issue, also the structure for ChEBI:90802 (parent of ChEBI:28743) has the wrong linkage between GlcNAc and Gal, instead of 1->4, it should be 1->3, as it is the root for all lacto-series glycosphingolipids. As you can corroborate, ChEBI:90802 derives from ChEBI:90800 (Parent of ChEBI:17292), so it should keep the same linkage. Thanks in advance for your prompt action.
Best,
Lucila

**Comment by amalik01** [comment]
Now done.

Adnan
