### ISSUE TITLE
ntr: ribozinoindole-1

### ISSUE THREAD

**Issue by mah11** [ebi-chebi/ChEBI#3539]
I would like a term to use for curating PMID:27667686:

name: ribozinoindole-1
synonym: Rbin-1
PubChem CID: 5731061
CAS: 328023-11-6

The PubChem page has more synonyms, a formula, InChI data, etc.

The paper shows a structure, and the supplemetary data includes a big long list of analogs, plus the general structure they're based around. I don't have an immediate need for terms for any of the analogs, but if you do want to add them, go ahead. A grouping ribozinoindole(s) term might be useful somewhere along the line.

This is pretty much all I know about these compounds, but if you have any questions I'll try to respond.

thanks,
Midori

**Comment by amalik01** [comment]
Hi Midori, 

I have now created an entry in ChEBI for ribozinoindole-1 (ChEBI=142676).

Best Regards,
Adnan

**Comment by mah11** [comment]
Thank you!
