### ISSUE TITLE
diacylglycerols missing relationship?

### ISSUE THREAD

**Issue by janelomax** [ebi-chebi/ChEBI#3540]
Should 'CHEBI:88759 - DG(16:0/14:0/0:0)' and 'CHEBI:88705 - DG(15:0/15:0/0:0)' be is_a 'CHEBI:85683 - diacylglycerol 30:0'?

**Comment by amalik01** [comment]
Thanks for letting us know. The entries have now been corrected. 

Best Regards,
Adnan
