### ISSUE TITLE
Can't submit HMDB xrefs for new entries

### ISSUE THREAD

**Issue by janelomax** [ebi-chebi/ChEBI#3541]
For example HMDB0004978.

I tried without the HMDB prefix too. Error message is 'HMDB0004978 is not a valid HMDB accession format.'

**Comment by amalik01** [comment]
Sorry, this is a bug in our submission tool. I have added the link manually to ChEBI: 142699.
We will try and get this issue fixed for you sometime in the new year.

Best Regards,
Adnan

**Comment by muthuvenkat** [comment]
@janelomax, thanks for reporting and sorry for the inconvenience caused. Its fixed and working now.
