### ISSUE TITLE
CHEBI synonyms are occasionally preceeded by "a", e,g "a gentamycin"

### ISSUE THREAD

**Issue by cmungall** [ebi-chebi/ChEBI#3544]
E.g.
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:90219

Has the synonym "a gentamycin 2''-phosphate"

The synonym should just be "gentamycin 2''-phosphate"

**Comment by cmungall** [comment]
OK, but can we get an additional synonym for `gentamycin 2''-phosphate`, as currently there is no label or synonym with this exact match in chebi

**Comment by amalik01** [comment]
I have created the neutral form of this molecule (CHEBI:142938) and have named this as gentamycin 2''-phosphate. I hope this helps.

Best Regards,
Adnan

**Comment by cmungall** [comment]
I wasn't clear in that this is an example of something systematic. Is there a systematic fix?

**Comment by amalik01** [comment]
We usually get submissions from UniProt/SIB for charged species. If the neutral form of the compound is not present in ChEBI, we tend to create an entry for it and link the charged and neutral forms using the chemical ontology. We usually do this systematically. Unfortunately, in this case, the curator who was initially working on the dizwitterion (CHEBI: 90219) probably forgot to create an entry for the neutral compound.

Best Regards,
Adnan
