### ISSUE TITLE
Please review CHEBI:16520 and CHEBI:17412, already used in Rhea

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#3545]
Dear ChEBI curators,

Can you please review and check CHEBI:16520 and CHEBI:17412?
Please don't merge before checking with us as CHEBI:16520 and CHEBI:17412 are already used in an approved (and public) Rhea reaction:  RHEA:17357 | EC 1.8.3.2

Note that these compounds are unclassified. 
"is a unclassifieds (CHEBI:27189)"

Merci!
Wish you a nice day!
Anne

**Comment by amalik01** [comment]
Hi Anne,

Regarding CHEBI:16520. Do you want this entry to be any thiol or do you prefer it to be named secondary thiol? 

Also what type of functional groups can the R-group be? Is it just any organyl group or can it include other elements such as oxygen, nitrogen etc.

Adnan

**Comment by amorgat** [comment]
Dear Adnan,

I wish you an happy 2019! All the best for you and your family!

According to NC-IUBMB
http://www.enzyme-database.org/query.php?ec=1.8.3.2
"R may be =S or =O, or a variety of other groups. The enzyme is not specific for R′."

Kind regards,
Anne

**Comment by amalik01** [comment]
Both entries have now been checked.

Adnan
