### ISSUE TITLE
Update structure of CHEBI:132128

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#3546]
Hi Gareth and Adnan,

I suggest to update the stereochemistry of this compound at the site of farnesyl attachment to the dimethylorsellinate moiety. In http://dx.doi.org/10.1016/j.tet.2013.07.029 they assign the stereochemistry based on that of preterretonin A characterized in PMID:22782788. I have attached the updated structure.

Cheers,
Kristian
[CHEBI_132128.txt](https://github.com/ebi-chebi/ChEBI/files/2695144/CHEBI_132128.txt)

**Comment by amalik01** [comment]
Hi Kristian,

I have now updated the structure of CHEBI:132128. As a result of this change, the structure of CHEBI: 131857 has also been updated. Are you able to update the UniProt name for CHEBI:131857 so that it takes into account the 3R stereocentre.

Best Regards,
Adnan

**Comment by kaxelsen** [comment]
Hi Adnan,

Thank you for taking care of this (and other tickets). I have now updated the UniProt name.

Cheers,
Kristian
