### ISSUE TITLE
Please review CHEBI:47325, as it is needed in Rhea

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#3551]
Hi Gareth and Adnan,

Please update CHEBI:47325, 
```
<stereo>alpha</stereo>-<element>N</element>-dichloroacetyl-<element>P</element>-aminophenylserinol

 or 

<element>N</element>-[(1<stereo>R</stereo>,2<stereo>R</stereo>)-1-(4-aminophenyl)-1,3-dihydroxypropan-2-yl]-2,2-dichloroacetamide
```
I need the compound for the reaction:
N-[(1R,2R)-1-(4-aminophenyl)-1,3-dihydroxypropan-2-yl]-2,2-dichloroacetamide + reduced acceptor + 2 O2 = chloramphenicol + acceptor + 2 H2O

The reaction is described in pmid:24347692, 25564306 and 28823151 and the compound in pmid:25267678
I have attached the structure.
[CHEBI_47325.txt](https://github.com/ebi-chebi/ChEBI/files/2734367/CHEBI_47325.txt)

The compound in MetaCyc has ID: CPD-21781

Cheers,
Kristian

**Comment by amalik01** [comment]
Now done.

Best Regards,
Adnan
