### ISSUE TITLE
CHEBI:27311 - volatile oil component - improvement

### ISSUE THREAD

**Issue by sebozon** [ebi-chebi/ChEBI#3552]
The "volatile oil component" category annotation should be improved. Wikipedia's definition states that they are produced by plants, but the ChEBI definition does not further specify the natural origin (e.g. could be from any organism). 
All compounds currently listed in ChEBI under CHEBI:27311 (volatile oil component) are plant metabolites in reality but 15 of them lack this annotation (e.g. they are not annotated as plant metabolites and have no other annotation or are annotated as human metabolite for example). I checked these 15 compounds manually to verify this. One example is CHEBI:34118, which is annotated as volatile oil component, human metabolite and fungal metabolite, all of which are all correct. Another one is CHEBI:24911 which has no further annotation than CHEBI:27311.

The full list of compounds in CHEBI:27311 without a plant metabolite annotation is:
 
α-eudesmol (CHEBI:10278)
β-eudesmol (CHEBI:10417)
β-selinene (CHEBI:49276)
γ-eudesmol (CHEBI:62513)
(E)-oct-2-enal (CHEBI:61748)
10-epi-γ-eudesmol (CHEBI:62514)
borneol (CHEBI:28093)
cadinene (CHEBI:22976)
carvacrol (CHEBI:3440)
cineole (CHEBI:23243)
coniferol (CHEBI:17745)
isopiperitenol (CHEBI:24911)
limonin (CHEBI:16226)
oct-1-en-3-ol (CHEBI:34118)
perillyl aldehyde (CHEBI:15421)

I would suggest to: 

1.  Move the category CHEBI:27311 (volatile oil component) from CHEBI:25212 (metabolite) to CHEBI:76924 (plant metabolite)  
2. Change the definition of volatile oil component from: Any metabolite that is found naturally as a component of a volatile oil."
to: "Any **plant** metabolite that is found naturally as a component of a volatile oil."
3. Add the CHEBI:76924 (plant metabolite) annotation to all compounds listed under CHEBI:27311 (volatile oil component). In my opinion this would be the most important thing to do, even if 1&2 are not adapted, because these compounds are plant metabolites and should turn up when searching ChEBI for plant metabolites.

Cheers
Sebastian

**Comment by amalik01** [comment]
Hi Sebastian,

Thank you for letting us know about this issue. Volatile oil component is now classified as a plant metabolite hence all the child terms in this class will be plant metabolites. Therefore it is not necessary to include plant metabolite annotations to all the child terms since they will be automatically included as plant metabolites when searching in ChEBI.

I hope this helps.

Best Regards,
Adnan
