### ISSUE TITLE
CHEBI:142771, typo in the chebi name ?

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#3554]
Dear ChEBI curators,

I think there is a typo in the ChEBI name and definition of CHEBI:142771
vincaDDiformine
-->
vincadiFFormine

Note that its enantiomer (+)-vincadifformine(1+) (CHEBI:142830) is correct

Thank you for your support!
Anne

**Comment by amalik01** [comment]
Thanks for letting us know. Now corrected.

Adnan
