### ISSUE TITLE
CHEBI:16731, update ChEBI common name

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#3556]
Dear ChEBI curators,

Please would you update the common name of CHEBI:16731 to trans-cinnamaldehyde or (E)-cinnamaldehyde?

I've just submitted CHEBI:142921 for cinnamaldehyde with undefined cis-trans isomerism.
I used "3-phenylprop-2-enal" as common name as I was prevented to use "cinnamaldehyde".
Please feel free to update my submission.

I added is-a relationships:
cinnamaldehyde (CHEBI:16731)  is_a  3-phenylprop-2-enal (CHEBI:142921)
(Z)-3-Phenyl-2-propenal (CHEBI:89729)  is_a  3-phenylprop-2-enal (CHEBI:142921)

Note that CHEBI:89729 is a 2* entry.

All the best, Anne

**Comment by amalik01** [comment]
Now done.
Adnan
