### ISSUE TITLE
CHEBI:77619, wrong outgoing relationships , please correct it

### ISSUE THREAD

**Issue by ANiknejad** [ebi-chebi/ChEBI#3557]
Dear Chebi Team,

Currently 
"Outgoing 1,3-dipalmitoylglycerol (CHEBI:77619) is a hexadecanoic acid (CHEBI:15756)"

The relationship to CHEBI:15756 should be a ' has functional parent'
Thank you.

Anne Niknejad

**Comment by amalik01** [comment]
Thanks for letting us know. This has now been changed.

Adnan
