### ISSUE TITLE
Missing mass

### ISSUE THREAD

**Issue by muthuvenkat** [ebi-chebi/ChEBI#356]
Dear ChEBI team,
when I retrieve data through the sdf file, some molecules have the field Mass filed whereas another do not have.
do you any idea why?

for example the molecule: CHEBI:15714 seems no to have a Mass attributes in the export file \(ComplteSdf\)

could you precompute all mass when a chemical formula is available?

Thank a lot

Francois

Reported by: flefevre

**Comment by adekker2** [comment]
done
