### ISSUE TITLE
CHEBI:17103 needs correction

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3560]
Dear ChEBI Curators,
CHEBI:17103 has a structure and formula corresponding to N-acyl-beta-D-glucosaminyl-(1->3)-beta-D-galactosyl-(1->4)-beta-D-glucosylceramide or Lc3Cer(d18:1(4E)), yet the ChEBI name, several of its synonyms, as well as its SMILES correspond to N-acetyl-beta-D-glucosaminyl-(1->3)-beta-D-galactosyl-(1->4)-beta-D-glucosylceramide. I believe this error was propagated from Kegg https://www.genome.jp/dbget-bin/www_bget?cpd:C04845
Please let me know whether I should I submit N-acyl-beta-D-glucosaminyl-(1->3)-beta-D-galactosyl-(1->4)-beta-D-glucosylceramide as a new entity to ChEBI or if you will correct CHEBI:17103 to represent the latter. 
Thanks,
Lucila

**Comment by amalik01** [comment]
Hi Lucila,

CHEBI:17103 is the N-acetyl-beta-D-glucosaminyl derivative. I think its better if you submit the N-acyl derivative as a new entry.

Adnan

**Comment by aimol** [comment]
Hi Adnan,
If CHEBI:17103 is is the N-acetyl-beta-D-glucosaminyl derivative of the N-acyl derivative I will submit, then please:
1-correct the structure
2-correct the formula
3-delete all synonyms that do not specify it the acyl chain is acetyl.
as I need them for the new submission 
Thank you
