### ISSUE TITLE
CHEBI:133245 - status=CHECKED but Unclassified

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#3561]
Dear ChEBI curators,

I found by chance CHEBI:133245 (quercetin 3,7-di-O-α-L-rhamnoside) which is a 3* entry but has no relationships (Unclassified).

Best wishes

Anne

**Comment by amalik01** [comment]
Thanks for letting us know Anne.

The previous curator seemed to have marked the ontology relationships as deleted. I don't know what the reason was for doing so. I have now re-checked the ontology relationships.

Best Regards,
Adnan
