### ISSUE TITLE
synonym CHEBI:93771

### ISSUE THREAD

**Issue by mah11** [ebi-chebi/ChEBI#3562]
I found CHEBI:93771 via the CHEMBL275665 page. A lot of literature seems to use the designation ICRF-193 for this compound, and that's given as the name on the CHEMBL page, so could a synonym be added to the CHEBI record?

thanks,
Midori

**Comment by mah11** [comment]
It also appears to be
 has role EC 5.99.1.2 (DNA topoisomerase) inhibitor (CHEBI:50276)

**Comment by amalik01** [comment]
Hi Midori,

This entry has now been checked and marked to 3 stars.

Best Regards,
Adnan
