### ISSUE TITLE
adhesin

### ISSUE THREAD

**Issue by Nizal-Shammry** [ebi-chebi/ChEBI#3566]
Is adhesin exist in Chebi in different name?

reference from the Gene Ontology, GO:0015475 adhesin autotransporter activity

**Comment by amalik01** [comment]
Hi Nizal,

No, we don't have this term in ChEBI since ChEBI is a database of small molecules, and we don't usually deal with proteins. Adhesins are generally proteins on the surface of living cells that allow the organism to colonize various surfaces. 

Best Regards,
Adnan
