### ISSUE TITLE
lactoferrin and transferrin 

### ISSUE THREAD

**Issue by Nizal-Shammry** [ebi-chebi/ChEBI#3568]
Hello,

Do lactoferrin and transferrin exist in Chebi?

**Comment by amalik01** [comment]
Hi Nizal,

No, we don't have these terms in ChEBI since both lactoferrin and transferrin are proteins. ChEBI only deals with small molecular entities such as small molecules, natural products, peptides, carbohydrates etc.

Best Regards,
Adnan

**Comment by Nizal-Shammry** [comment]
Hi Adnan
But you have CHEBI:2786 Apotransferrin, 

Transferrin is known as "apotransferrin" : When not bound to iron
ref: https://en.wikipedia.org/wiki/Transferrin

**Comment by amalik01** [comment]
Hi Nizal,

This is a very old entry. In the past, proteins may have been loaded into ChEBI but a decision was made not to add them anymore. Protein structures are very large in terms of the number of atoms they contain and it is quite difficult to draw them in 2D and display the entire structure in ChEBI hence we no longer deal with them.

We do however have enzyme inhibitor classes in ChEBI (based on EC numbers) which allows the classification of inhibitors in terms of the enzymes they inhibit (For example, see CHEBI:78763). 

If you are interested in proteins, EBI has several other resources which you could utilize such as the PDBe database.

I hope this helps.

Best Regards,
Adnan
