### ISSUE TITLE
can 5-dehydrosparteine be added?

### ISSUE THREAD

**Issue by janekg89** [ebi-chebi/ChEBI#3572]
Can  5-dehydrosparteine be added? 
Substance exists in PUBCHem:
https://pubchem.ncbi.nlm.nih.gov/compound/160614

**Comment by amalik01** [comment]
This has now been added (ChEBI:143195) and should become searchable on the ChEBI website by tomorrow.

https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:143195
