### ISSUE TITLE
New Term Request: Culmorin

### ISSUE THREAD

**Issue by Achchuthan** [ebi-chebi/ChEBI#3576]
Can I request culmorin to be added to ChEBI please?

It is present in PubChem: https://pubchem.ncbi.nlm.nih.gov/compound/Culmorin

Here are also some publications characterizing culmorin metabolite and/or genes of culmorin biosynthesis pathway - PMID:11122521, PMID:19880637, PMID:26673640 & PMID: 29465119. 

Thanks & best wishes,
Achchuthan

**Comment by amalik01** [comment]
I have now created an entry for culmorin (CHEBI:143197). 

https://www.ebi.ac.uk/chebi/curation/public/searchId.do?chebiId=CHEBI:143197

Best Regards,
Adnan
