### ISSUE TITLE
Deploy local instance

### ISSUE THREAD

**Issue by sacdallago** [ebi-chebi/ChEBI#3582]
Dear ChEBI team,

thank you very much for the service -- it's highly appreciated!! I'm part of a development team that is relying heavily on your API service to identify chemicals from open ended queries. The project that we are developing is open source and aimed to help the research community: https://github.com/PathwayCommons/factoid 

One of the main observations from some initial user testing is that users of the webapp really dislike to "wait" for responses. This has driven us to decide to service queries in-house, instead of using open services, as your API. Before embarking into downloading the data behind ChEBI and implementing our own -probably not as functional- as your web-service, we were wondering if you offered the possibility to deploy your service locally or create a mirror.

Thank you for any feedback! :)

**Comment by muthuvenkat** [comment]
Thanks @sacdallago for using ChEBI. Please try this project [libChEBI](https://github.com/libChEBI), that downloads and updates a copy of ChEBI automatically where you should be able to query. It is also available in multiple languages (Java, Python and Matlab).

Hope this helps!
Venkat
