### ISSUE TITLE
Wrong amino acid codes in synonyms for ChEBI:73270, ChEBI:140231 and ChEBI:137738

### ISSUE THREAD

**Issue by kp14** [ebi-chebi/ChEBI#3584]
Hi,

I found three ChEBI nodes for tripeptides which have wrong one-letter amino acid codes in their synonyms:

73270
Leu-Gln-Pro
['LGP'] -> should be LQP

140231
Cys-Asp-Gly
['C-A-G', 'CAG'] -> should be C-D-G, CDG

137738
Val-Ala-Lys
['VAL'] -> should be VAK

Thanks.
Klemens

**Comment by amalik01** [comment]
Thank you for pointing this out. These have now been corrected.

Adnan
