### ISSUE TITLE
Additional annotation for xanthine (CHEBI:15318)

### ISSUE THREAD

**Issue by cviner** [ebi-chebi/ChEBI#3585]
It would be useful if the below details could be added to the [xanthine (CHEBI:15318)](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:15318) entry.

A has functional parent relationship with [guanine (CHEBI:16235)](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:16235) should be added.

Chemical details, including synonyms (2,6-dioxopurine) and SMILES can be imported from its PubChem entry: [https://pubchem.ncbi.nlm.nih.gov/compound/1188](https://pubchem.ncbi.nlm.nih.gov/compound/1188).

The below reference could be added:
[T Nguyen, D Brunson, C L Crespi, B W Penman, J S Wishnok, S R Tannenbaum. DNA damage and mutation in human cells exposed to nitric oxide in vitro *Proceedings of the National Academy of Sciences* Apr 1992, 89 (7) 3030-3034; DOI: 10.1073/pnas.89.7.3030.](https://doi.org/10.1073/pnas.89.7.3030)

**Comment by amalik01** [comment]
I have added the guanine functional parent relationship, synonym (2,6-dioxopurine) and the reference provided to this entry. Please be aware that the xanthine (CHEBI:15318) entry is a chemical class with no definitive structure hence a SMILES or InChi cannot be provided. Several different tautomers of xanthine can exist such as 7H-xanthine (CHEBI:48517) and 9H-xanthine (CHEBI:17712) which belong to this class.
