### ISSUE TITLE
Duplicated entry, CHEBI:136732, please DELETE

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#3588]
Hi Adnan,

I just found out that CHEBI:136732 is identical to CHEBI:85454, and when I look at the entry I can see Steve has left a comment stating the entry was deleted at the request of Anne. The only problem is that the entry has NOT been deleted.

Please do it since we already use CHEBI:85454, 5-methyl dCMP(1−) residue in Rhea.

Cheers,
Kristian

**Comment by kaxelsen** [comment]
That would be nice. If you could keep CHEBI:85454 as the primary ID it would be very nice and the most convenient for Rhea.

**Comment by amalik01** [comment]
The entries have now been merged. CHEBI:85454 is the primary ID.
