### ISSUE TITLE
EC 1.14.14.1

### ISSUE THREAD

**Issue by nnouspikel** [ebi-chebi/ChEBI#3589]
Dear ChEBI curators,

I need your help to define the RH molecule in the IUBMB equation for EC 1.14.14.1  
RH + [reduced NADPH-hemoprotein reductase] + O2 = ROH + [oxidized NADPH-hemoprotein reductase] + H2O
This EC is required for annotation of CYP P450 monooxygenases in UniProt.

We could create a new ChEBI, but the challenge would be to name it.  Simply it’s an organic molecule/compound that contains at least one hydrogen atom. What is your advice?

Many thanks in advance.

Nevila Hyka-Nouspikel

**Comment by amalik01** [comment]
Do you know what the R group is? Is it an alkane or can it be any group?

**Comment by nnouspikel** [comment]
Microsomal CYP450 catalyze:
-	hydroxylation of saturated carbon hydrogen bonds (https://www.rhea-db.org/reaction?id=38947;  https://www.rhea-db.org/reaction?id=39755)
-	omega-1 hydroxylation  (https://www.rhea-db.org/reaction?id=39759)
-	bisallylic hydroxylation (https://www.rhea-db.org/reaction?id=52292)
-	hydroxylation with double bond migration (https://www.rhea-db.org/reaction?id=52300)	
-	hydroxylation of aromatics/polycyclic organic molecules (https://www.rhea-db.org/reaction?id=47212; https://www.rhea-db.org/reaction?id=51984 

good reviews: PMID:15352783; PMID:28124606; PMID:21782265

Many thanks!

**Comment by amalik01** [comment]
Hi Nevila,

An entry has now been created specifically for these reactions (CHEBI:142491). 

Adnan

**Comment by nnouspikel** [comment]
Thank you so much Adnan. All the best.
