### ISSUE TITLE
error in names.tsv

### ISSUE THREAD

**Issue by egonw** [ebi-chebi/ChEBI#3591]
There sneaks a format error into the `names.tsv` file it seems in the June 1 release:

![image](https://user-images.githubusercontent.com/26721/59143440-87ba2300-89cb-11e9-9078-143a34465883.png)

I just confirmed it in the current download from ftp://ftp.ebi.ac.uk/pub/databases/chebi/Flat_file_tab_delimited/names.tsv.gz

The screenshots shows the line numbers in the grey~ish left sidebar.

**Comment by muthuvenkat** [comment]
Sorry, for the inconvenience caused. Thanks for reporting. We will fix asap.

**Comment by egonw** [comment]
No worries! The convenience of the Open Data provided by ChEBI greatly outweighs the occasional hiccup :)

**Comment by muthuvenkat** [comment]
Its fixed now and the FTP is updated, please try and let me know.
