### ISSUE TITLE
NTR: Galactosaminogalactan

### ISSUE THREAD

**Issue by Achchuthan** [ebi-chebi/ChEBI#3592]
Can I request for an entry to be created in ChEBI for galactosaminogalactan please?
Synonym: GAG
References: PMID:173713, PMID:22102815, PMID:26932183, PMID:30667338

Thanks & best wishes,
Achchuthan

**Comment by amalik01** [comment]
Hi,

An entry has now been created (CHEBI:143889). The entry should be visible on the website by tomorrow.
Unfortunately, a structure cannot be provided since the polysaccharide contains galactose and N-acetylgalactosamine residues which are randomly distributed.

Adnan

**Comment by Achchuthan** [comment]
HI @amalik01,
Thanks a lot for creating this entry.
Best wishes,
Achchuthan
