### ISSUE TITLE
CHEBI:44597, update chebi common name

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#3593]

**Comment by amorgat** [comment]
Hi Adnan,
The common name of CHEBI:44597 is 4-oxoretinol.
Definition: a retinoid that is all-trans-retinol in which the hydrogens at position 4 have been replaced by an oxo group.
Suggestion: change to <stereo>all-trans</stereo>-4-oxoretinol
Cheers, Anne

**Comment by amalik01** [comment]
Now done.

**Comment by amorgat** [comment]
Thanks for your celerity!
