### ISSUE TITLE
New class request: Manganese hydroxide

### ISSUE THREAD

**Issue by pbuttigieg** [ebi-chebi/ChEBI#3603]
Hi CHEBI team,

Over at https://github.com/EnvironmentOntology/envo/issues/770 we'd like a class for manganese hydroxide for our deep-sea ecosystems and mining classes. 

I notice there's a class for [Mg(OH)2](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:6637), but none for Mn.

**Comment by amalik01** [comment]
An entry has now been created (ChEBI:143901).

**Comment by pbuttigieg** [comment]
Many thanks!
