### ISSUE TITLE
CHEBI:2069, please review and change common name

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#3607]
Hi Adnan,
Please would you review CHEBI:2069 and change its name to "5-hydroxy ferulic acid".
In the same time, I think you could remove the "(1−)" from my recent submission CHEBI:144056 "5-hydroxyferulate(1−)". I'd appreciate if you could help me to find a nice definition!
Cheers, Anne

**Comment by amalik01** [comment]
There is already an entry in ChEBI for 5-hydroxyferulic acid (CHEBI:20582) so i am unable to change the name of CHEBI:2069. It seems that they both are the same hence i will merge them.

**Comment by amalik01** [comment]
Are you interested in the unspecified form of 5-hydroxyferulate or the E-isomer?

**Comment by amorgat** [comment]
unspecified form of 5-hydroxyferulate: yes
E-isomer: not (yet) found a use case ;-)

**Comment by amalik01** [comment]
Now marked to checked status. I have changed CHEBI:2069 to the E-isomer.
