### ISSUE TITLE
Release number 999 for ontology nightly builds

### ISSUE THREAD

**Issue by jannahastings** [ebi-chebi/ChEBI#3610]
I notice that the release number for the nightly ontology build files is always 999. This isn't very informative. 

Would it not be better to use something like RELNO.DAYNO? E.g. on the 8th July, you might have the nightly builds being tagged as release 177.8, and then on the 9th July, 177.9 and so on?

**Comment by muthuvenkat** [comment]
Fixed in the files, from this release
