### ISSUE TITLE
create Bicalutamide racemic mixture; R-Bicalutamide and S-Bicalutamide

### ISSUE THREAD

**Issue by IntAct-EBI** [ebi-chebi/ChEBI#3613]
Hi there,

I need Bicalutamide racemic mixture, and the respective R and S isomer as different entity for IntAct curation; kindly do the needed.

**Comment by amalik01** [comment]
Now done.

Racemate / CHEBI:3090
R-isomer / CHEBI:39589
S-isomer / CHEBI:144094

**Comment by IntAct-EBI** [comment]
Thank you!
