### ISSUE TITLE
insect attractant (CHEBI:24850) is NOT (necessarily) a pesticide (CHEBI:25944) 

### ISSUE THREAD

**Issue by alanbridge** [ebi-chebi/ChEBI#3615]
Hi ChEBI 

could you remove this relationship? 

insect attractant (CHEBI:24850) is a pesticide (CHEBI:25944) 

and maybe change the definition of insect attractant (CHEBI:24850)  from 

A chemical that lures insects to a trap, thereby removing them from crops, animals or stored products.

to 

A chemical that attracts insects.

There are many insect attractants that are not pesticides, some are even used for defense. For instance maize, when damaged by herbivorous insects, produces a compound (https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:10357) that attracts parasitic wasps. These then lay eggs in said herbivorous insects. 

See https://www.uniprot.org/uniprot/B2C4D0 for more on this. 

All the best, Alan

**Comment by amalik01** [comment]
I have removed the existing pesticide relationship and have replaced the definition.
