### ISSUE TITLE
CHEBI:77770, please add synonym

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#3616]
Hi Adnan,
Please would you add
"3,7,4'-<element>O</element>-trimethylquercetin"
synonym to CHEBI:77770 (used in Rhea) as it is a name used in literature to label this compound.
Thank you for your support,
Anne

**Comment by amalik01** [comment]
Now done

**Comment by amorgat** [comment]
You're very quick!!
After thinking, don't you think "3,7,4'-tri-O-methylquercetin" should be a better name, do you?

**Comment by amalik01** [comment]
Hi Anne,
Both synonyms are currently being used for the neutral compound (CHEBI:27825). I generally wouldn't recommend using the same synonyms for the neutral compound and protonated forms.
Adnan

**Comment by amalik01** [comment]
A more suitable synonym for the protonated form (CHEBI:77770) would be 3,7,4'-tri-O-methylquercetin-5-olate

**Comment by amorgat** [comment]
understood - let's go with your suggestion
