### ISSUE TITLE
(−)-β-caryophyllene (CHEBI:10357)  has role insect attractant (CHEBI:24850)

### ISSUE THREAD

**Issue by alanbridge** [ebi-chebi/ChEBI#3617]
Hi ChEBI, 

sorry but in a previous issue I forgot to request this relation:

(−)-β-caryophyllene (CHEBI:10357)  has role insect attractant (CHEBI:24850)

see https://www.ncbi.nlm.nih.gov/pubmed/18296628

Thanks again for all your help, Alan

**Comment by amalik01** [comment]
Now done.
