### ISSUE TITLE
CHEBI:26167

### ISSUE THREAD

**Issue by sandraorchard** [ebi-chebi/ChEBI#3620]
This is not searchable just by CHEBI ID
www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A26167

Can this be fixed as I wat to xref it for a polar amino acid transporter complex

**Comment by amalik01** [comment]
The entry was not searchable since it was a 1-star entry. I have now annotated this entry and marked it up to 3-stars. It should be searchable by tomorrow.
