### ISSUE TITLE
CHEBI:22788 needs some corrections

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3621]
Hi,
I noticed CHEBI:22788 is mapped to KEGG compound CO6273 and KEGG glycan GO1184, this does not look right, only CHEBI:62870 should be mapped to those KEGG IDs.
Also for CHEBI:22788 some synonyms need revision, I guess when removing the incorrect KEGG IDs, these will disappear, but also LIPIDMAPS synonym needs correction, please check.
And please add relation CHEBI:17006 is_a CHEBI:22788
Also seems confusing that synonym LA1 is used for both CHEBI:17006 and CHEBI:62870 when these are different entities. 
Thanks for revising and making changes as appropriate.
Lucila

**Comment by amalik01** [comment]
The changes have been made.

The LA1 synonym was taken from KEGG glycan entries (G00050 and G01184). I have added a comment in ChEBI on both entries to show that the synonym is ambiguous.
