### ISSUE TITLE
CHEBI:16297 and CHEBI:142448 are the same?

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3622]
Hi,
It seems to me that both CHEBI:16297 and CHEBI:142448 have the same structure and seem to represent the same entity. If so, they need to be merged. Can you please check?
Thanks
Lucila

**Comment by amalik01** [comment]
Hi Lucila,
The only difference between the two structures is that one has the hydroxy group on the ceramide in the (R)-configuration and the other has it in the (S)-configuration so they are not the same in terms of structure. CHEBI:16297 has been linked to the KEGG compound entry: C04938. In KEGG, the stereochemstry of the hydroxy group is not shown so this could be a mistake.

Do you by any chance know whether the hydroxy group in ceramides can exist in both (R) and (S)-configurations?. Most of the examples i have seen in LipidMaps show the hydroxy group in the (R)-configuration.

**Comment by aimol** [comment]
Thanks Adnan, 
I had not noticed the S-configuration in CHEBI:16297, like you I have also only seen the R-configuration in ceramides, but I must confess I have focused my curation on natural/physiological ceramides found in mammals.  The major sphingoid base of mammals, also known as sphingosine or sphing-4-enine is (2S,3R,4E)-2-aminooctadec-4-ene-1,3-diol (D-erythro-sphingosine), it can vary in alkyl chain length and branching, the number and positions of double bonds, as well as the presence of additional hydroxyl groups. Sphingosine derives from dehydrosphingosine (also called sphinganine), which also has the R-configuration because of the enzyme D-3-dehydrosphinganine reductase (EC 1.1.1.102) involved in its biosynthesis.
I would suggest to move the link to the KEGG compound entry: C04938 from CHEBI:16297 to CHEBI:142448.
Thanks for your help,
Lucila

**Comment by amalik01** [comment]
I have moved the KEGG links to CHEBI:142448.

By searching the literature, it seems that several different ceramides (diastereomers) can be synthesised including D-erythro-ceramides, L-erythro-ceramides, D-threo-ceramides and L-threo-ceramides which have different configurations.

**Comment by aimol** [comment]
Thanks Adnan, please add those references to CHEBI:16297
