### ISSUE TITLE
CHEBI:144056 xref

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#3623]
Hi Adnan,
CHEBI:144056 is linked to MetaCyc 5-HYDROXY-FERULIC-ACID 
Please could you remove this wrong xref (my fault, but I have no more access to my submission).
I've just submitted (E)-5-hydroxyferulate(1−) CHEBI:144381 and added metacyc xref 5-HYDROXY-FERULIC-ACID to it.
Notice that KEGG: C05619 and HMDB0035484 display a trans double bond too.
Cheers, Anne

**Comment by amalik01** [comment]
now done
