### ISSUE TITLE
CHEBI:30709 incorrect synonym

### ISSUE THREAD

**Issue by johnsantamariajr** [ebi-chebi/ChEBI#3624]
synonym is called "drugs" in the names_3star.tsv - this is problematic. Thanks,

**Comment by amalik01** [comment]
Thanks for letting us know - It is very strange since it is not visible on the ChEBI public website. 
We will try and get this fixed as soon as our ChEBI developer is back from annual leave (in 3-4 weeks time).

**Comment by muthuvenkat** [comment]
30709   23888   SYNONYM Chemical Ontology       drugs   F       en
@johnsantamariajr second column is ChEBI id and first column is row id, so it is not CHEBI:30709 its actually CHEBI:23888. Thanks for writing to us.
