### ISSUE TITLE
Typo is definition of Triton X-100

### ISSUE THREAD

**Issue by cmungall** [ebi-chebi/ChEBI#3626]
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:9750

def: "A poly(ethylene glycol) derivative that is poly(ethylene glycol) in which wone of the terminal hydroxy groups has been converted to the corresponding p-(2,4,4-trimethylpentan-3-yl)phenyl ether." []

change "wone" to "one"

**Comment by amalik01** [comment]
Now corrected. Thanks
