### ISSUE TITLE
Also Concerning CHEBI:26167

### ISSUE THREAD

**Issue by jsgaravelli** [ebi-chebi/ChEBI#3628]
The Incoming list of amino acids for CHEBI:26167 does not include tryptophan (CHEBI:27897) which is most definitely a side-chain proton donor for hydrogen bonds as evidenced by the function of the significant WWD motif in N-glycosyl transferase (PMID:21677752).

**Comment by amalik01** [comment]
Tryptophan has now been added. Thanks
