### ISSUE TITLE
Please add relation is_a to CHEBI:91119

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3629]
Please add relation CHEBI:91119 is_a CHEBI:90803
Thanks,
Lucila

**Comment by amalik01** [comment]
I have added the relationship CHEBI:91119 is_a CHEBI:90803.
I have also deleted the relationship CHEBI:91119 is_a CHEBI:23073 since CHEBI:90803 is_a CHEBI:23073.
