### ISSUE TITLE
CHEBI:52021 is NOT a tautomer of CHEBI:52020

### ISSUE THREAD

**Issue by mpagni12** [ebi-chebi/ChEBI#3632]
Dear ChEBI,

As far as I understand, the relationship: "6-decylubiquinol (CHEBI:52021) is tautomer of 6-decylubiquinone (CHEBI:52020)" is not correct. Indeed, 6-decylubiquinol/6-decylubiquinone are a redox pair, for example they appear on both sides of reaction kegg:R07177.

   Marco

**Comment by amalik01** [comment]
Thanks for letting us know. The relationship has now been removed.
