### ISSUE TITLE
New submission CHEBI:144647, please provide proper CHEBI name

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#3635]
Hi,

I have just submitted a compound that is the result of the enzymic hydroxylation of carbon 4a of 4-chlorotetracycline (CHEBI:133598), but the paper (pmid:28481346) does not name it, and I have no idea how to do it. So I would by grateful if you could help me.

Cheers,
Kristian

**Comment by amalik01** [comment]
Compound has now been given a new ChEBI name.
