### ISSUE TITLE
New submission CHEBI:144697 please provide proper ChEBI name

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#3638]
Hi,

I have just submitted a compound that in the papers reporting is called "deaminated ophthalmic acid". As this is not a precise name as an amino group is replaced by an oxo group I would be grateful if you could help me provide the compound with a proper name. Currently, it carries the Marvin generated IUPAC name.
The relevant pmids are: pmid:28373563 and 30692244 

Cheers,
Kristian

**Comment by amalik01** [comment]
Suggested ChEBI name: N-(4-carboxy-4-oxobutanoyl)-L-ethylglycylglycine(2-)

I have now added this name to the entry.
