### ISSUE TITLE
new feature: meso-lanthionine 

### ISSUE THREAD

**Issue by raaschj** [ebi-chebi/ChEBI#3639]
I did not find an ID on ChEBI for meso-lanthionine. 
Please add meso-lanthionine. 
It is a constituent of bacterial cell wall.
It is associate to the peptidoglycantype A51 (Schumann_2011 published in Taxonomy of Prokaryotes, Elsevier) respectively A3delta (Schleifer_and_Kandler_1972).

We would be glad if it included in ChEBI. We hope you can add the peptidoglycantype to the definition.
Please let me know if you encounter any difficulties with my request or have any questions.

**Comment by amalik01** [comment]
An entry has now been created for meso-lanthionine (CHEBI:25205). It should be visible on the ChEBI website by tomorrow.
