### ISSUE TITLE
DATATYPE_ID column in comments.tsv flat file duplicates DATATYPE column

### ISSUE THREAD

**Issue by jmdale** [ebi-chebi/ChEBI#3643]
In the comments.tsv flat file downloaded from ftp://ftp.ebi.ac.uk/pub/databases/chebi/Flat_file_tab_delimited/comments.tsv, the DATATYPE_ID column contains the same entries as the DATATYPE column. Based on the contents of the comments.sql file in the generic database dump, it appears that the DATATYPE_ID column should instead contain the ID of a specific data element to which the comment refers.

For example, the comment with ID 12, associated with compound ID 176, has the value 'CompoundName' in both the DATATYPE and DATATYPE_ID fields. Instead, the DATATYPE_ID column should contain the value '264', giving the ID of the name to which the comment applies (provided correctly in comments.sql).

**Comment by amalik01** [comment]
Thanks for letting us know. The file has now been fixed.
