### ISSUE TITLE
vertice.tsv not available in latest ftp release of ChEBI 02/10/2019

### ISSUE THREAD

**Issue by fabienjourdan** [ebi-chebi/ChEBI#3649]
Dear Chebi developers
It sounds that on the latest release the vertice.tsv file is missing (maybe other ones are missing but we are using libchebipy and this one is important).
If you could add that it would be great.
Many thanks
Fabien Jourdan

**Comment by muthuvenkat** [comment]
@fabienjourdan thanks for reporting, we have updated the data schema please refer the manual for more information https://bit.ly/2om5jzy. Neil Swainston have fixed the issue on libChEBIpy.
