### ISSUE TITLE
Inconsistent masses

### ISSUE THREAD

**Issue by jmdale** [ebi-chebi/ChEBI#3650]
Hello,

While processing the chemical_data.tsv file in the flat file dump (ftp://ftp.ebi.ac.uk/pub/databases/chebi/Flat_file_tab_delimited/chemical_data.tsv, downloaded 2019-10-10), I've noticed several compounds with multiple inconsistent values for the mass attribute. In most of these cases, the values are close, and the discrepancy seems to result from one of the values having been computed with more digits of precision than the other (example: CHEBI:16808). However, there are a few cases which differ more significantly:

* CHEBI:55429 has MASS values 213.212 and 243.28000.
* CHEBI:61753 has MASS values 1510.558 and 1525.59000.
* CHEBI:35681 has MASS values 30.02600 and 58.07910.

In each of these cases, the value of the MONOISOTOPIC MASS attribute is consistent with the smaller of the MASS values.

**Comment by amalik01** [comment]
Thanks for letting us know about these 3 ChEBI entries. These have now been corrected.
