### ISSUE TITLE
Fix typo in name of CHEBI:76750

### ISSUE THREAD

**Issue by cthoyt** [ebi-chebi/ChEBI#3651]
Currently, CHEBI:76750 is named `EC 1.22* (oxidoreductase acting on halogen in donors) inhibitor`. This appears to be inconsistent with all other inhibitors referring to the top 3 levels of the enzyme class nomenclature, which includes a period between the final number and the start. 

Do you think updating this name to`EC 1.22.* (oxidoreductase acting on halogen in donors) inhibitor` would be appropriate?

**Comment by amalik01** [comment]
Thanks. Now corrected.
