### ISSUE TITLE
Fix typo in name of CHEBI:77118

### ISSUE THREAD

**Issue by cthoyt** [ebi-chebi/ChEBI#3652]
`EC 3.5.5.1 (nitrilase) inhhibitor` has a typo and should be renamed as `EC 3.5.5.1 (nitrilase) inhibitor`

**Comment by amalik01** [comment]
Now corrected.

**Comment by cthoyt** [comment]
@amalik01 thanks, I appreciate the quick feedback for this and a few of my other issues! Keep up the awesome work at ChEBI :)
