### ISSUE TITLE
Rename CHEBI:73181 to promote consistency

### ISSUE THREAD

**Issue by cthoyt** [ebi-chebi/ChEBI#3653]
CHEBI:73181 is currently named `EC 1.11.1.11 (L-ascorbate peroxidase) inhibitors` but all other inhibitor items based on EC codes use the singular form of `inhibitor`.

Do you think it would be appropriate to rename this entry to `EC 1.11.1.11 (L-ascorbate peroxidase) inhibitor`?

**Comment by amalik01** [comment]
Now corrected.
