### ISSUE TITLE
Incorrect or inconsistent formulas

### ISSUE THREAD

**Issue by jmdale** [ebi-chebi/ChEBI#3656]
I've come across a few compounds which appear to have incorrect or inconsistent chemical formulas.

CHEBI:144836 has formula "(13C)4H4D2O3". While not incorrect, the C13 isotope is represented differently than other compounds in the database, which use "[13C]".

CHEBI:132140 has formula "4(CH4).23(H2O)". Again, this is not incorrect, but it seems that it would be more consistent with general usage to omit the parentheses, and use "4CH4.23H2O". In all other cases, it seems that parentheses are only used for grouping when followed by a coefficient.

CHEBI:31813 has formula "(C11H8I3N2NaO4).(C18H26I3N3O9)". The parentheses could be omitted to be more consistent with other compounds.

CHEBI:134219 has in its formula slot the value "154.136", which should probably be a mass value; it is very close to the listed monoisotopic mass value of "154.13577".

CHEBI:20831 has the formula "C02H18O7" (it is a zero following the C). The zero and two appear to be transposed; the formula should be "C20H18O7". That would be consistent with the structure and with the linked cross-reference http://eawag-bbd.ethz.ch/servlets/pageservlet?ptype=c&compID=c0531 (up to protonation).

**Comment by amalik01** [comment]
Thanks for letting us know. These have now been corrected. We have changed the tool kits for the formula generation so as a result, there may be some inconsistencies of how the formula is generated.
If you come across any other inconsistencies, please do let us know.
