### ISSUE TITLE
CHEBI:50010 structural formula inconsistency

### ISSUE THREAD

**Issue by rwst** [ebi-chebi/ChEBI#3660]
Both the IUPAC name of CHEBI:50010 and its parent stilbene have unspecified cis/trans isomery, the structural formula however does not reflect this (it's specific).

**Comment by rwst** [comment]
The same holds for the salt ChEBI:50011.

**Comment by amalik01** [comment]
The presence of the wavy bonds in the structures indicate that the double bond stereochemistry is undefined.
