### ISSUE TITLE
Question about tautomer InChI strings

### ISSUE THREAD

**Issue by jmdale** [ebi-chebi/ChEBI#3664]
Hello,

I understand that in standard InChI, tautomers have identical InChI strings, as discussed here: https://www.inchi-trust.org/technical-faq-2/#6.1.

However, in the [ChEBI Annotation Manual, Section 8.2, Molfiles](https://docs.google.com/document/d/1EZHaOEl-iPZPbqD_GRyIetDoA4U8U2SPr9Qk6RKVRc0/edit#heading=h.9xn1ddd958gu), it is stated that "Tautomer generation for the InChI has been switched on making InChIs generated by tautomers distinguishable."

But in the structures.csv file downloaded from the FTP site, all of the InChIs appear to be standard, and thus the InChIs of pairs of tautomeric compounds are identical. Selected examples:
- CHEBI:15570 (D-alanine) / CHEBI:57416 (D-alanine zwitterion)
- CHEBI:27760 (L-selenocystathionine) / CHEBI:62226 (L-selenocystathionine zwitterion)
- CHEBI:2164 (6-acetamido-3-aminohexanoic acid) / CHEBI:58498 (6-acetamido-3-aminohexanoic acid zwitterion)

Is the Annotation Manual in error, or only referring to internally-accessible InChIs?

**Comment by amalik01** [comment]
The non-standard InChi's are not visible on the ChEBI public website or in the downloadable files. We only use them internally to distinguish between different tautomers when a new structure is submitted via the ChEBI submission tool.

**Comment by jmdale** [comment]
Thank you, that clarifies things.
