### ISSUE TITLE
NTR: galactoxylomannan

### ISSUE THREAD

**Issue by Achchuthan** [ebi-chebi/ChEBI#3665]
Can I request galactoxylomannan to be added to ChEBI please?

The definition, synonyms and references are below:
Name: galactoxylomannan
Synonyms: glucuronoxylomannogalactan, GalXM
Definition: An exopolysaccharide composed of α-(1–6)-galactan backbone containing four potential short oligosaccharide branch structures, produced by the human pathogenic fungus Cryptococcus neoformans, that produces immune paralysis in some animals, including humans.
Source: PMID:21843086, PMID:16441437, PMID:18952901, PMID:19684080

Thanks & best wishes,
Achchuthan

**Comment by Achchuthan** [comment]
Hi,
I am wondering whether anyone at ChEBI had chance to look at my request?
Thanks a lot for your help.
Best wishes,
Achchuthan

**Comment by hdrabkin** [comment]
Hi @Achchuthan . I actually always use the CHEBI request tool (https://www.ebi.ac.uk/chebi/submission/login) because I then get a ticket id and interim CHEBI id. Note that  you may be required to supply a structure.

**Comment by Achchuthan** [comment]
Hi @hdrabkin. Thanks for the suggestion. I will submit a request via ChEBI request tool.

**Comment by hdrabkin** [comment]
Just remember that we cannot actually USE the interim ID, but only the ones that end up in the CHEBI public release. So once CHEBI approves the request, one still needs to wait unitl it appears in CHEBI (public). We can then add it to the CHEBI import file.

**Comment by Achchuthan** [comment]
I have obtained this term by creating a request via the request tool. Here is the ID: CHEBI:145656
