### ISSUE TITLE
Question about 1-O-4-hydroxybenzoyl-beta-D-glucose 

### ISSUE THREAD

**Issue by Nizal-Shammry** [ebi-chebi/ChEBI#3667]
Dear ChEBI curators,

Is 1-O-4-hydroxybenzoyl-beta-D-glucose exist in Chebi under different name?
Ref: https://biocyc.org/compound?orgid=META&id=CPD-15283

Regards

**Comment by amalik01** [comment]
An entry has now been created and should be visible by tomorrow on the ChEBI website (CHEBI:145301).
