### ISSUE TITLE
phenylpropanolamines missing IUPAC

### ISSUE THREAD

**Issue by rwst** [ebi-chebi/ChEBI#3668]
From the InChi keys we have:

1. CHEBI:8104   DLNKOYKMWOXYQA-APPZFPTMSA-N   (1R,2R)-2-amino-1-phenylpropan-1-ol
2. CHEBI:36       DLNKOYKMWOXYQA-VXNVDRBHSA-N  (1S,2R)-2-amino-1-phenylpropan-1-ol
3. CHEBI:80680 DLNKOYKMWOXYQA-CBAPKCEASA-N   (1R,2S)-2-amino-1-phenylpropan-1-ol
4. CHEBI:4109   DLNKOYKMWOXYQA-IONNQARKSA-N   (1S,2S)-2-amino-1-phenylpropan-1-ol

1, 2, and 4 are missing, please fix.

**Comment by amalik01** [comment]
now added. thanks
