### ISSUE TITLE
Add metabolites involved in midazolam metabolism

### ISSUE THREAD

**Issue by matthiaskoenig** [ebi-chebi/ChEBI#3677]
Hi all,
I am workon on a model of midazolam [CHEBI:6931](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:6931) metabolism in the liver.

Unfortunately, I cannot find any of the metabolites of midazolam in CHEBI, i.e., entries for the following are missing

* `1-hydroxymidazolam` (or `alpha-hydroxymidazolam`); https://pubchem.ncbi.nlm.nih.gov/compound/107917
* `4-hydroxymidazolam`; https://pubchem.ncbi.nlm.nih.gov/compound/124449
* `1,4-dihydroxymidazolam`; https://pubchem.ncbi.nlm.nih.gov/compound/10316307
* `1-hydroxymidazolam-glucuronide`; https://pubchem.ncbi.nlm.nih.gov/compound/133640 (detected by Link2008, PMID: 18537963)
* `4-hydroxymidazolam-glucuronide`; likely https://pubchem.ncbi.nlm.nih.gov/compound/71777598
* `1,4-hydroxymidazolam-glucuronide`; ?

![midazolam_metabolism](https://user-images.githubusercontent.com/900538/68091061-7b9f9800-fe7b-11e9-9379-116739e16708.png)
{From Dundee1984}

- "Midazolam is eliminated almost exclusively by metabolic processes (fig. 4). The principal metabolite is a-hydroxymidazolam, which may be present in plasma in similar concentrations to the parent drug after oral administration (Arendt et ai., 1984), is rapidly conjugated by glucuronic acid, has a short elimination half-life of about 1 hour (Heizmann et ai., 1983; 10chemsen et ai., 1983; Taylor et ai., 1983; Vree et ai., 1981) and may contribute to the pharmacological activity of the drug, particularly after oral administration (section 2.5). 50 to 70% of a dose of midazolam is eliminated in the urine as this metabolite within 24 hours of administration (Heizmann and Ziegler, 1981; Sarnquist et ai., 1980a). Two other metabolites, 4-hydroxymidazolam and a,4-hydroxymidazolam, are excreted in small amounts (3% and 1%, respectively) in urine (Heizmann et ai., 1983)." {Dundee1984}
- “Midazolam is metabolized to the hydroxymethyl compound alpha-hydroxymidazolam (Ro 21-634 7) by oxidation of the methyl group and subsequent conjugation with glucuronic acid [42, 59]. Besides this major metabolic pathway, oxidation can occur at position 4 yielding 4-hydroxymidazolam (Ro 21-5975) and alpha,4-dihydroxymidazolam (Ro 21-0284) [55].” {Pieri1981}
- Formation of a minor primary metabolite, 4-hydroxymidazolam, and a minor secondary metabolite 1,4-dihydroxymidazolam, are also catalyzed by CYP3A and together, as glucuronide conjugates, comprise another 4% to 6% of an administered dose
- “Midazolam is extensively metabolized to 1-hydroxymethylmidazolam, a pharmacologically active metabolite that is present in the conjugated and nonconjugated form in both plasma and urine. [6]”{Bornemann1986}

Could you add the metabolites of midazolam to CHEBI?
Best Matthias

**Comment by amalik01** [comment]
I have created 5 entries in ChEBI for these metabolites:
1-hydroxymidazolam (CHEBI:145330)
4-hydroxymidazolam (CHEBI:145331)
1',4-dihydroxymidazolam (CHEBI:145332)
1-hydroxymidazolam β-D-glucuronide (CHEBI:145334)
4-hydroxymidazolam β-D-glucuronide (CHEBI:145335)

These entries should become visible on the ChEBI website by tomorrow.

**Comment by matthiaskoenig** [comment]
@amalik01 Thanks so much.
