### ISSUE TITLE
 Incomplete display of ontology for CHEBI:143797

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3691]
I submitted CHEBI:143797 a while ago and added in the ontology several children, yet I cannot see any of these in the CHEBI webpage nor in the Curator tool, only in the submission tool. Can you please let me know where or when I should expect to see these relations displayed?
CHEBI:143785 is_a CHEBI:143797 added upon submission
CHEBI:143786 is_a CHEBI:143797 added upon submission
CHEBI:143787 is_a CHEBI:143797 added upon submission
CHEBI:143798 is_a CHEBI:143797 caused error, can you please add it?
CHEBI:143799 is_a CHEBI:143797 added upon submission, this is the only relation displayed
CHEBI:143800 is_a CHEBI:143797 added upon submission
CHEBI:143801 is_a CHEBI:143797 added upon submission

**Comment by amalik01** [comment]
Very strange, i can only see 3 child entries: CHEBI:143803, CHEBI:143798 and CHEBI:143799. I have added the other entries myself and these should now be visible. I will let Venkat know when he is back at work tomorrow to find out what the issue is.

**Comment by aimol** [comment]
Thanks, looking fwd to Venkat's response.
