### ISSUE TITLE
STATUS column in compounds.tsv -- what do the values mean?

### ISSUE THREAD

**Issue by jmdale** [ebi-chebi/ChEBI#3694]
In the compounds.tsv file of the flat file downloads, the STATUS column contains one of the following values: C, D, E, O, S.

In the developer manual, it is documented that "C" means "checked" by the curators. None of the other values are documented as far as I can tell.

I can hypothesize that "D" means deleted, since those compounds don't seem to show up when I search on the website. Is this correct?

And what do the other values mean?

**Comment by amalik01** [comment]
We will try and update the developer manual. The status of each entry is indicated as OK (E), CHECKED (C), DELETED (D), SUBMITTED (S) and OBSOLETE (O).

Entries marked as checked (C) have been manually annotated and checked by a ChEBI curator.
Entries which have OK (E) status have been annotated by a third-party (in alot of these cases, the data has been loaded into ChEBI from a different source and has not yet been checked by a ChEBI curator.
