### ISSUE TITLE
Terms not found in ChEBI

### ISSUE THREAD

**Issue by Nizal-Shammry** [ebi-chebi/ChEBI#3697]
Dear ChEBI curators,

Is the following terms exist in ChEBI ?

1. rRNA containing N7-methylguanine  
    - Ref: https://www.ebi.ac.uk/QuickGO/term/GO:0070043
2. rRNA containing N3-methyl pseudouridine  
    -Ref: https://www.ebi.ac.uk/QuickGO/term/GO:0070038
3.  rRNA containing 2'-O-methylguanosine
    -Ref: https://www.ebi.ac.uk/QuickGO/term/GO:0070039 
4. rRNA containing 2'-O-methyluridine
    -Ref: https://www.ebi.ac.uk/QuickGO/term/GO:0008650
5. rRNA containing N4-methylcytosine
    -Ref: https://www.ebi.ac.uk/QuickGO/term/GO:0071424
6. rRNA containing N3-methyluridine
    -Ref: https://www.ebi.ac.uk/QuickGO/term/GO:0070042
7. rRNA containing C5-methyluridine
    -Ref: https://www.ebi.ac.uk/QuickGO/term/GO:0070041

**Comment by amalik01** [comment]
Apologies for the delayed response. All of these have now been added to ChEBI. They should be visible on the ChEBI website by tomorrow.

(1) CHEBI:149718 
(2) CHEBI:149719
(3) CHEBI:149721
(4) CHEBI:149722
(5) CHEBI:149723
(6) CHEBI:149724
(7) CHEBI:149725
