### ISSUE TITLE
CHEBI:28630 and CHEBI:29053 are tautomers

### ISSUE THREAD

**Issue by rwst** [ebi-chebi/ChEBI#3705]
Again, just the tautomer declarations are missing here.

**Comment by rwst** [comment]
Also, CHEBI:17715 and CHEBI:48988 I believe.

In summary many thanks for the maintnance work. These issues came up while importing ChEBI data in Wikidata, by inspecting the created constraint conflicts.

**Comment by amalik01** [comment]
Thanks for letting us know. These tautomer relationships have now been added.
