### ISSUE TITLE
Incorrect formulas

### ISSUE THREAD

**Issue by jmdale** [ebi-chebi/ChEBI#3706]
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:2718 has formula C63H91N17O13. This is inconsistent with the corresponding compounds KEGG and MetaCyc compounds: https://www.genome.jp/dbget-bin/www_bget?cpd:C00873 has formula C62H89N17O14, https://metacyc.org/compound?orgid=META&id=CPD-13004 has formula C62H89N17O14.

https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:31808 has formula C16H12O6. This is inconsistent with the formula part of the InChI string (C24H27NO8) and the corresponding KEGG compound https://www.genome.jp/dbget-bin/www_bget?cpd:C12437 which has formula C24H27NO8.

https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:34949 has formula C34H41NO11. This does not match the formula part of the InChI (C35H43NO11) nor the corresponding KEGG compound https://www.genome.jp/dbget-bin/www_bget?cpd:C14722 which has formula C35H43NO11.

https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:3537 has formula C19H18N3O4S2. This seems to be off by one proton from the corresponding KEGG and MetaCyc compounds https://www.genome.jp/dbget-bin/www_bget?cpd:C11754 and https://metacyc.org/compound?orgid=META&id=CPD-9228, though the structures seem to match.

**Comment by amalik01** [comment]
Thanks for letting us know. The formula's have now been corrected. Since these are 2-star entries, they have not yet been checked by a ChEBI curator.
