### ISSUE TITLE
CHEBI:138233, new information about stereoconfiguration

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#3712]
Hi Adnan,

New information in pmid:29315936 (see Fig. S6 and Fig. 3) shows that 9,13-epoxylabda-14-ene is 13(R). So I would like to have CHEBI:138233 updated with the attached structure to include this new information. Note that Fig 3 includes MvELS that is the origin of this CHEBI compound (see pmid:24990389).

Thank you in advance. 

Best,
Kristian
[CHEBI_138233.txt](https://github.com/ebi-chebi/ChEBI/files/3910277/CHEBI_138233.txt)

**Comment by amalik01** [comment]
Now updated.
