### ISSUE TITLE
CHEBI:145495 and other classes missing is-a parents

### ISSUE THREAD

**Issue by cmungall** [ebi-chebi/ChEBI#3713]
OLS currently looks like this for CHEBI:

![image](https://user-images.githubusercontent.com/50745/69982455-8abd4880-1502-11ea-921c-72df798ea95d.png)

CHEBI:145495 and 5 others are missing is-a parents

**Comment by amalik01** [comment]
Thanks for letting us know. These 6 ChEBI entries have now been fixed.
