### ISSUE TITLE
Incorrect SMILES string for (3S)-citryl-CoA and (3S)-citryl-CoA(6-) entries

### ISSUE THREAD

**Issue by balej** [ebi-chebi/ChEBI#3714]
The SMILES strings for the following two entries seem to incorrectly specify the 3R instead of the 3S stereochemistry:

https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:15459
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:57321

Can you please check and fix the SMILES strings for these entries? Thank you!

**Comment by amalik01** [comment]
Thanks for letting us know. The structures have now been updated.
