### ISSUE TITLE
Question about Salicylic acid 2-beta-D-glucoside

### ISSUE THREAD

**Issue by Nizal-Shammry** [ebi-chebi/ChEBI#3716]
Dear ChEBI curators,

Is **Salicylic acid 2-beta-D-glucoside** exist in Chebi?
Ref: https://pubchem.ncbi.nlm.nih.gov/compound/7099939

Regards

**Comment by amalik01** [comment]
2 ChEBI entries have now been created (CHEBI:145663 (free acid form) and CHEBI:145670 (anion form). These should be visible on the ChEBI website by tomorrow.
