### ISSUE TITLE
Add delphinidin 3-O-rutinoside-7-O-glucoside

### ISSUE THREAD

**Issue by Nizal-Shammry** [ebi-chebi/ChEBI#3717]
Dear ChEBI curators,

It seems that delphinidin 3-O-rutinoside-7-O-glucoside not exist in ChEBI. 
Ref: 
- https://pubchem.ncbi.nlm.nih.gov/compound/Delphinidin-3-rutinoside-5-glucoside
- https://biocyc.org/compound?orgid=META&id=CPD-16558

Could you add the terms please which I think to be subclass of CHEBI:80441

Regards

**Comment by amalik01** [comment]
Hi,
An entry has now been created (CHEBI:145693). The structure shown in MetaCyc (CPD-16558) is incorrect. MetaCyc have obtained their structure from (PMID:24179131) and the stereochemistry of the rutinose disaccharide unit is incorrect in this paper.
