### ISSUE TITLE
Question about beta-D-Mannosylphosphodecaprenol ?

### ISSUE THREAD

**Issue by Nizal-Shammry** [ebi-chebi/ChEBI#3718]
Dear ChEBI curators,

Is beta-D-Mannosylphosphodecaprenol exist in Chebi?
ref: https://www.genome.jp/dbget-bin/www_bget?C04150

Regards

**Comment by amalik01** [comment]
I have now created an entry for beta-D-Mannosylphosphodecaprenol (CHEBI:16402). The entry should be visible on the ChEBI website by tomorrow.
