### ISSUE TITLE
Question about 1,3 alpha-D-galactosyl-lipopolysaccharide

### ISSUE THREAD

**Issue by Nizal-Shammry** [ebi-chebi/ChEBI#3719]
Dear ChEBI curators,

Is 1,3 alpha-D-galactosyl-lipopolysaccharide exist in Chebi?
Ref: https://www.genome.jp/dbget-bin/www_bget?cpd:C04473

Regards

**Comment by amalik01** [comment]
Yes. The ChEBI ID is 27734.
