### ISSUE TITLE
Additional annotation for methylhypoxanthines (CHEBI:73958)

### ISSUE THREAD

**Issue by cviner** [ebi-chebi/ChEBI#3721]
It would be nice if [methylhypoxanthines](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A73958) could receive additional curation.

The plural form could be removed, in favour of retaining the present annotation, perhaps with some additional ontology curation, as the category. Some children of it could then be added, including, though ideally not limited to, 9-methylhypoxanthine, for which a few references could also be added, e.g.:

- [Belanger-Gariepy, Francine, and Andre L. Beauchamp. "Crystal structure of bis (9-methylhypoxanthine) silver (I) perchlorate monohydrate, a model complex for the silver-poly (I) system." *Journal of the American Chemical Society* 102, no. 10 (1980): 3461–4.](https://doi.org/10.1021/ja00530a025)
- [van Vliet, Paul M., Jaap G. Haasnoot, and Jan Reedijk. "Binding of 9-Methylhypoxanthine and 9-Ethylguanine to [cis-Ru (2, 2'-bipyridine) 2] 2+. NMR and X-ray Structure of *cis*-Chlorobis (2, 2'-bipyridine)(9-ethylguanine-. kappa. N7) ruthenium (II) Chloride." *Inorganic Chemistry* 33, no. 9 (1994): 1934–9.](https://doi.org/10.1021/ic00087a033)

**Comment by amalik01** [comment]
I have now added the following child classes to CHEBI:73958 including 3-methylhypoxanthine, 7-methylhypoxanthine and 9-methylhypoxanthine. Unfortunately i cannot add the references provided since they do not have a PubMed identifier associated with them.
