### ISSUE TITLE
Additional data for 9-riburonosylhypoxanthine (CHEBI:17643)

### ISSUE THREAD

**Issue by cviner** [ebi-chebi/ChEBI#3722]
It would be useful if the following, [BRENDA-annotated](https://brenda-enzymes.org/ligand.php?brenda_ligand_id=174329), synonyms could be added for [9-riburonosylhypoxanthine](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:17643):

- 5'-oxoinosine
- Inosine-5'-carboxylate

Indexing the mentioned publication would also be nice:

[Koga, Shinji, Jun Ogawa, Yang-Mun Choi, and Sakayu Shimizu. "Coordinate induction of peroxidase and H2O2-forming nucleoside oxidase in Flavobacterium meningosepticum." *FEMS Microbiology Letters* 175, no. 1 (1999): 113–7.](https://doi.org/10.1111/j.1574-6968.1999.tb13609.x)

**Comment by amalik01** [comment]
Hi,

The synonyms used by BRENDA are incorrect for this structure. The structure of 5'-oxoinosine is that shown in CHEBI:27427.

We are unable to add the reference provided to ChEBI since it does not have a PubMed identifier.
