### ISSUE TITLE
CHEBI:1230, please choose different parent structure

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#3723]
Hi Adnan and Gareth,

I need this compound for a Rhea reaction, and since we prefer to avoid using Fischer representation of sugars, I would be grateful if you would change the structure to one of the additional structures linked to this compound. I would prefer the structure with to pyranose rings as this corresponds to all the cross referenced structure in KEGG, MetaCyc, KNApSAcK and Wikipedia. 
If you choose to keep this compound with the aldehydo structure, please create the pyranose version.

Thank you in advance,
Cheers,
Kristian

**Comment by amalik01** [comment]
Structure has now been updated.
