### ISSUE TITLE
CHEBI:6268, please change name and CHECK

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#3725]
Hi Adnan and Gareth,

PLease change the name of this compound to L-lyxonic acid as I have just submitted L-lyxonate(1-) (CHEBI:145753) that I need for a new reaction in Rhea. I have attached the structure for L-lyxonic acid in aldehydo form.
[CHEBI_6268.txt](https://github.com/ebi-chebi/ChEBI/files/4034234/CHEBI_6268.txt)

Thank you in advance.
Cheers,
Kristian

**Comment by amalik01** [comment]
Now checked.
