### ISSUE TITLE
CHEBI:131712 - shinorine

### ISSUE THREAD

**Issue by gabrielmarkov** [ebi-chebi/ChEBI#3727]
Dear curators, 

The molecular formula reported for shinorine is wrong. The one corresponding to the described structure should be C13H20N2O8 (see for example ttps://pubchem.ncbi.nlm.nih.gov/compound/10471931).

Cheers,
Gabriel Markov

**Comment by amalik01** [comment]
This has now been corrected. Thanks for letting us know.
