### ISSUE TITLE
curcumin 4'-O-β-D-gentiotetraside

### ISSUE THREAD

**Issue by Nizal-Shammry** [ebi-chebi/ChEBI#3731]
Dear ChEBI curators,

The compound " curcumin 4'-O-β-D-gentiotetraside " seems not defined in Chebi. Could you please add it.
Ref:
- https://biocyc.org/compound?orgid=META&id=CPD-14836
Best Regards

**Comment by amalik01** [comment]
An entry has now been created (CHEBI:145773).
