### ISSUE TITLE
genistin 7-gentiobioside

### ISSUE THREAD

**Issue by Nizal-Shammry** [ebi-chebi/ChEBI#3732]
Dear ChEBI curators,

The compound "genistin 7-gentiobioside" seems not defined in Chebi. Could you please add it.
Ref:
- https://biocyc.org/compound?orgid=META&id=CPD-14848
- https://pubchem.ncbi.nlm.nih.gov/compound/90657741

Best Regards

**Comment by amalik01** [comment]
An entry has now been created (CHEBI:145776).
