### ISSUE TITLE
(+)-sesaminol 2-O-β-D-gentiobioside

### ISSUE THREAD

**Issue by Nizal-Shammry** [ebi-chebi/ChEBI#3733]
Dear ChEBI curators,

The compound "(+)-sesaminol 2-O-β-D-gentiobioside" seems not defined in Chebi. Could you please add it.
Ref:
- https://biocyc.org/compound?orgid=META&id=CPD-14839

Best Regards

**Comment by amalik01** [comment]
An entry has now been created (CHEBI:145785).
