### ISSUE TITLE
(+)-sesaminol 

### ISSUE THREAD

**Issue by Nizal-Shammry** [ebi-chebi/ChEBI#3734]
Dear ChEBI curators,

Is the compound (+)-sesaminol (ref: https://biocyc.org/compound?orgid=META&id=CPD-14837) the same as CHEBI:136543, if not, could you add it please.

Best Regards

**Comment by Nizal-Shammry** [comment]
Also, (+)-sesaminol 2-O-β-D-glucoside seems not in chebi
Ref: https://biocyc.org/compound?orgid=META&id=CPD-14838

**Comment by amalik01** [comment]
No, they are not the same compound. A separate entry needs to be created.

**Comment by amalik01** [comment]
2 entries have now been created:
(+)-sesaminol (CHEBI:145778) and (+)-sesaminol 2-O-β-D-glucoside (CHEBI:145784).
