### ISSUE TITLE
CHEBI:5931-insulin (human) : ontology issue and species non specific term request

### ISSUE THREAD

**Issue by sabrinatoro** [ebi-chebi/ChEBI#3736]
Hello, 
1) The definition (and the name) for "insulin (human) (CHEBI:5931)" refers to human peptide. However, the ontology shows :  "has role **mouse** metabolism" 

2) could you create a term for "insulin" which is species non specific, please? 

Thank you
Sabrina

**Comment by amalik01** [comment]
I have now deleted the 'has role mouse metabolite' relationship from CHEBI:5931. A new entry for insulin has also been created (CHEBI:145810) which is not species specific. It should be visible on the ChEBI website by tomorrow.
