### ISSUE TITLE
ChEBI:15619 and 26116 have errors in the IUPAC names and structural diagrams

### ISSUE THREAD

**Issue by jsgaravelli** [ebi-chebi/ChEBI#3739]
By the standard numbering for linear tetrapyrroles, in phytochromobilin, ChEBI:26116, and (3Z)-phytochromobilin, ChEBI:15619, the C2 is chiral and according to PMID:1634523 should be (2R).  The structural diagrams for those entries currently lack chiral indicators for the C2.  Also the structural diagram for ChEBI:15619 is not in the same orientation as the other linear tetrapyrroles, which have the C1 and C19 carbonyls at the top and clockwise progression as in ChEBI:15619. (It makes them easier to compare when they have the same orientation.)

**Comment by amalik01** [comment]
Thanks for letting us know. This has now been corrected.
