### ISSUE TITLE
CHEBI:145927, additional cross-references

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#3740]
Hi Adnan,

The compound, CHEBI:145927, 4-(indol-3-yl)butanoyl-beta-D-glucose, was mentioned in pmid:20798329 as the result of glucosylation of indole-3-butanoate (IBA).
The compound is also found in MetaCyc as CPD-12621.

I have also attached a different version of the structure you can use if you like.

Cheers,
Kristian
[CHEBI_145927.txt](https://github.com/ebi-chebi/ChEBI/files/4121812/CHEBI_145927.txt)

**Comment by amalik01** [comment]
Now updated. Thanks.
