### ISSUE TITLE
CHEBI:60242, check is-a relationships

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#3741]
Dear Adnan,
There is a relationship
ammonium (CHEBI:28938) is a monovalent inorganic cation (CHEBI:60242)
I guess it should be
ammonium (CHEBI:28938) is a organic cation (CHEBI:25697)
PS: there is no "monovalent organic cation" in chebi
Cheers, Anne

**Comment by amalik01** [comment]
Hi Anne,

Our definition of organic is that the entity must contain a carbon atom. Since ammonium (CHEBI:28938) does not contain a single carbon atom, it cannot be classed as organic.

**Comment by amorgat** [comment]
Hi Adnan,
I thought, an organic molecule was an entity with C, H, O or N ;-)
Fine with me, if it's your definition.
Cheers, Anne

**Comment by amalik01** [comment]
Organic compounds are molecules composed of carbon and hydrogen, and may contain any number of other elements such as oxygen or nitrogen. See link below:
https://www.quora.com/Is-ammonia-an-organic-molecule
