### ISSUE TITLE
CHEBI:59047 is name correct?

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#3743]
Hi Adnan and Gareth,

CHEBI:59047 is currently called "methyl 8-{[...]oxy}octanoate"
Since the acyl chain consists of 9 C atoms, I believe the name should be "methyl 8-{[...]oxy}nonanoate" (the carbohydrate part of the name is correct).

Cheers,
Kristian

**Comment by amalik01** [comment]
Now corrected. Thanks
