### ISSUE TITLE
Invalid XML Download (CHEBI:456215)

### ISSUE THREAD

**Issue by rfellers** [ebi-chebi/ChEBI#3744]
When downloading the XML for compound CHEBI:456215, I noticed that the last TABLE node was incomplete. For example, the last 2 lines in the file are
`</ENTRY>`
`</TABLE`
where the last node is not closed properly. This obviously will cause problems for any XML parser. I'm not sure if this problem is widespread, only checked a handful of other IDs.

Thanks,
Ryan

**Comment by muthuvenkat** [comment]
@rfellers, thanks for pointing out. It is fixed now. Please let us know if you find any other issues.

Thanks,
Venkat
