### ISSUE TITLE
Question about 3,3',5'-trimethylmyricetin

### ISSUE THREAD

**Issue by Nizal-Shammry** [ebi-chebi/ChEBI#3745]
Dear ChEBI curators,

Is the compound " 3,3',5'-trimethylmyricetin " defined in Chebi ? If not,  could you please add it.
Ref: 
- https://biocyc.org/compound?orgid=META&id=CPD-14938
- https://pubchem.ncbi.nlm.nih.gov/compound/Myricetin-3_3_5_-trimethyl-ether

Best Regards

**Comment by amalik01** [comment]
An entry has now been created (CHEBI:146132).
