### ISSUE TITLE
CDP-diacylglycerol 

### ISSUE THREAD

**Issue by ValWood** [ebi-chebi/ChEBI#3753]
Hello

Through CHEBI the GO term 
CDP-diacylglycerol biosynthetic process (GO:0016024)
https://github.com/geneontology/go-ontology/issues/18899
is_a pyrimidine nucleotide biosynthetic process

but  CDP-diacylglycerol  isn't a pyrimidine nucleotide.

Could you have a look at the classification?

Thanks

Val

**Comment by amalik01** [comment]
Thanks for letting us know. The 'is_a pyrimidine nucleotide' relationship has now been removed.
