### ISSUE TITLE
CHEBI:141966 and CHEBI:146230, discrepancy in structures

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#3754]
Hi Adnan and Gareth,

I have just submitted CHEBI:146230 (−)-voacangine(1+), and I find a discrepancy in the structure compared to CHEBI:141966 that is the conjugated base. It is the chirality of one H bond that differs. I base my structure on two recent papers adn a ChEMBL molecule, and I must admit that I have not verified all the references linked to CHEBI:141966. I have linked the two compounds as they are both labeled (-).

Please help me figure out what is wrong and where,

Cheers,
Kristian

**Comment by amalik01** [comment]
Hi,
I think you are right. I have corrected the structure of CHEBI:141966.
