### ISSUE TITLE
Stereo check in CHEBI:82628

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3756]
Hi,
I just downloaded the molfile of CHEBI:82628 in Marvin and the stereo in the structure does not match the name. The name is 11(R)-HPETE(1-) but in Marvin this bond has S stereo, see screenshot:
![image](https://user-images.githubusercontent.com/17642025/76288187-17855880-62e1-11ea-8a89-141c2a6bb09b.png)
Can you please double check?
Thanks,
Lucila

**Comment by amalik01** [comment]
Thanks for letting us know. The structure has now been updated.
