### ISSUE TITLE
CHEBI:36163, CHEBI:60530, heme a, adding the missing chiral information

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#3758]
Hi Adnan,

I just discovered that the only chiral centre in heme a compounds in ChEBI are flat.
The paper pmid:16204889 elucidates that this is in fact (S). The ligand HEA cited in CHEBI:24479 (heme a) also shows this bond in (S).
So please update all children of CHEBI:24479 with this information.
Curiously, an (S)-ferriheme a (CHEBI:134067) has been created. I suggest to merge this with CHEBI:36183 as all heme a compounds should be in (S) configuration.
The relevant compounds to update are:
CHEBI:36183 ferriheme a
CHEBI:83281 ferriheme a3
CHEBI:83282 ferriheme a3(1-)
CHEBI:60532 ferriheme a(1-)
CHEBI:36163 ferroheme a
CHEBI:61715 ferroheme a(2-)

Cheers,
Kristian

**Comment by kaxelsen** [comment]
I have now submitted updated structures for all compounds except for CHEBI:61715 where I get an error when loading "Edit Structure"

**Comment by amalik01** [comment]
All of the above entries have now been updated with new structures. Thanks.
