### ISSUE TITLE
NTR: ammonium polyphosphate

### ISSUE THREAD

**Issue by marieALaporte** [ebi-chebi/ChEBI#3761]
Could you please add this term. Based on a quick search, it is an inorganic salt of polyphosphoric acid and ammonia containing both chains and possibly branching.
It is also used in agriculture as a fertilizer. 
We would like to import it in the agronomy ontology.

Many thanks!

@celineaubert

**Comment by amalik01** [comment]
An entry for ammonium polyphosphate (CHEBI:147408) has now been created. It should be searchable on the ChEBI website by tomorrow.
