### ISSUE TITLE
Add fertilizer role to some CHEBI terms

### ISSUE THREAD

**Issue by celineaubert** [ebi-chebi/ChEBI#3763]
Could you please add has_role fertilizer to:

- [ ]  CHEBI:23414 copper (II) sulfate

- [ ] CHEBI:63051 diammonium hydrogen phosphate

- [ ] CHEBI:64736 magnesium nitrate

- [ ] CHEBI:32599 magnesium sulfate

- [ ] CHEBI:62982 ammonium dihydrogen phosphate

- [ ] CHEBI:63036 potassium dihydrogen phosphate

- [ ] CHEBI:35176 zinc sulfate

- [ ] CHEBI:31344 calcium oxide

- [ ] CHEBI:3312 calcium chloride

- [ ] CHEBI:48838 gypsum

- [ ] CHEBI:31794 magnesium oxide  

- [ ] CHEBI:32599 magnesium sulfate

- [ ] CHEBI:26836 sulfuric acid

- [ ] CHEBI:131526 potassium carbonate

@marieALaporte

**Comment by amalik01** [comment]
Now done. Thanks

**Comment by amalik01** [comment]
Hi, i have removed the 'has role fertilizer' term from sulfuric acid (CHEBI:26836). I have my doubts, sulfuric acid is used in the production of fertilizers but is not a fertilizer itself. If you can provide any evidence where it says that sulfuric acid is actually a fertilizer, let me know and i will add the term. Thanks.

**Comment by celineaubert** [comment]
Hi, thank you for your rapid action! Indeed, I was not able to find evidence that sulfuric acid is used as fertilizer. It seems that some people used it on their field, but there is no solid evidence of its fertilizer role.
