### ISSUE TITLE
Add some synonyms

### ISSUE THREAD

**Issue by celineaubert** [ebi-chebi/ChEBI#3764]
- [ ] CHEBI:32599 magnesium sulfate has_exact_synonym epsom salt

- [ ] CHEBI:91238 calcium ammonium nitrate has_broad_synonym Ammonium nitrate limestone

@marieALaporte

**Comment by amalik01** [comment]
Now done. The synonym 'epsom salt' has been added to CHEBI:31795 since epsom salt is actually the heptahydrate form of magnesium sulfate.
