### ISSUE TITLE
XML download broken

### ISSUE THREAD

**Issue by rfellers** [ebi-chebi/ChEBI#3766]
At some point in the last week or so, the XML download (and maybe SDF) stopped producing the proper results. For example, when I go to https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:16027 and click on Download XML, I get an empty set of TABLE tags. Any help would be great!

**Comment by muthuvenkat** [comment]
Thanks for pointing it out, its fixed now !
