### ISSUE TITLE
Remove isA biological role (CHEBI:24432) from weigelic acid (CHEBI:66321)

### ISSUE THREAD

**Issue by cthoyt** [ebi-chebi/ChEBI#3767]
[weigelic acid (CHEBI:66321)](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:66321) is currently listed as a [biological role (CHEBI:24432)](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A24432). This relationship should be removed since this is a classification for chemicals based on structure

**Comment by amalik01** [comment]
Now removed. Thanks
