### ISSUE TITLE
CHEBI:6754 'Meperidine' should have role CHEBI:35482 'opioid analgesic'

### ISSUE THREAD

**Issue by turbomam** [ebi-chebi/ChEBI#3768]
Maybe missing due to the use of multiple approved names?

See 
- https://en.wikipedia.org/wiki/Pethidine 
- http://purl.bioontology.org/ontology/NDFRT/N0000147902
    - has 'full opioid agonism' MoA and 'may treat' pain

I hope you're all doing OK with the Corona Virus situation.

**Comment by amalik01** [comment]
Hi,

This role has now been added to CHEBI:6754 along with some additional data.
