### ISSUE TITLE
antipyrine (CHEBI:31225) = non-narcotic analgesic and opioid analgesic ?!

### ISSUE THREAD

**Issue by turbomam** [ebi-chebi/ChEBI#3773]
I **love** ChEBI, but I'm having a hard time believing this one:

- antipyrine (CHEBI:31225) has role non-narcotic analgesic (CHEBI:35481)
- antipyrine (CHEBI:31225) has role opioid analgesic (CHEBI:35482)

**Comment by turbomam** [comment]
Wikipedia and I are going with _non-narcotic_

https://en.wikipedia.org/wiki/Phenazone

**Comment by matthiaskoenig** [comment]
I only see 
antipyrine (CHEBI:31225) has role non-narcotic analgesic (CHEBI:35481)
in the latest version https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:31225
Probably already fixed?

**Comment by amalik01** [comment]
Thanks for letting us know. This has now been corrected.
