### ISSUE TITLE
CHEBI:145593 '-' missing from name

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#3774]
Hi Adnan,

There is '-' missing from the ChEBI name: 
<stereo>beta</stereo>-<stereo>D</stereo>-Gal<ringsugar>p</ringsugar>-(1<arrow>right</arrow>3)-<stereo>alpha</stereo>-<stereo>D</stereo>-Glc<ringsugar>p</ringsugar>NAc

(currently it is </ringsugar>(1<arow>

Cheers,
Kristian

**Comment by amalik01** [comment]
now added.
