### ISSUE TITLE
Adding ions to Chebi

### ISSUE THREAD

**Issue by andredekker** [ebi-chebi/ChEBI#3775]
Background: We are building an OBO foundry ontology for our domain of radiation oncology. Part of that is a description of the particles that we use to treat cancer patients. Many of them are in ChEBI already but we are missing a few.

Request: Please add the following ions to Chebi
(similar to ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:39099) 
3He (1+)
12C (4+)
16O (6+)

**Comment by amalik01** [comment]
Hi,

3 new entries have now been created: 
oxygen-16(6+) - CHEBI:149692
helium-3(1+) - CHEBI:149675
carbon-12(4+) - CHEBI:149691

All 3 entries should be visible on the ChEBI website by tomorrow.
