### ISSUE TITLE
Adding particle superclass to ChEBI

### ISSUE THREAD

**Issue by andredekker** [ebi-chebi/ChEBI#3776]
Background: We are building an OBO foundry ontology for our domain of radiation oncology. Part of that is a description of the particles that we use to treat cancer patients. We want to reuse particles defined by ChEBI. Particles that we use are ions and subatomic particles such as electron, photons, and protons. However we are missing a particle superclass in ChEBI. E.g. the class of subatomic particles is defined as a subclass of "A particle smaller than an atom." but it is actually defined as a subclass of Thing. 

Request: Please create a Particle class and make it a superclass of subatomic particle and a superclass of ions

**Comment by jannahastings** [comment]
I don't think this is a good idea. Let me try to explain. 

The term "particle" can be defined as (according to wikipedia) as:
_A small localized object or entity to which can be ascribed several physical or chemical properties such as volume, density or mass._

There are two problems with introducing a class with this definition as a parent of "ions" and "subatomic particles". 

First, there is no particular reason that only ions, and not other ChEBI entities such as atoms, small molecules, etc., should be included. By this line of reasoning, "particle" should become a parent of both of the "subatomic particle" and "chemical entity" branches of ChEBI's ontology. This would be a trivial change, but I suspect it doesn't really add information that will be useful to you. 

Second, some of the ions in ChEBI would hardly be described as "small" in the sense in which I think you mean. (For example, have a look at [this beauty](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:52911) with a mass of 1,370.) ChEBI's "ion" just means that the entity has a non-zero charge, thus, potentially of broader scope than the ions you want to include in your ontology anyway. As noted in the wikipedia page, the sense of "small" in which something meets the definition of being a "particle" tends to be vague and context- or discipline-dependent. ChEBI serves a few different domains and it would be hard to come up with a rigorous, formal definition of "small" that would satisfy all the needed perspectives. 

Could we perhaps find a different solution? E.g. (outside of the core ChEBI) perhaps we could create for you a fully defined (with an equivalent class expression in OWL) class that is defined as a disjunction (union) of the precise ChEBI parents that you want to have included?

**Comment by andredekker** [comment]
Thanks, I understand and agree with your reasoning. In our radiation oncology context a particle is indeed something small which causes an ionization (and as a results subsequently damages the DNA which kills the cancer cell). So we will define particle in our own context/domain. Thanks - can be closed then.
