### ISSUE TITLE
CHEBI:146216, wrong "has role"

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#3778]
Hi Adnan,

In CHEBI:146216, 2,3,6,8,9-pentahydroxy-3-(2-oxopropyl)-1,2,3,4-tetrahydroanthracen-1-one, the ontology states "has role Saccharomyces cerevisiae metabolite (CHEBI:75772)" .
This is wrong as it enzymes producing the compound are from Aspergillus nidulans, Saccharomyces cerevisiae is just the heterologous expression host.

Cheers,
Kristian

**Comment by amalik01** [comment]
Now corrected. I have changed it to 'has role Aspergillus metabolite'.
