### ISSUE TITLE
α-linolenic acid double bonds

### ISSUE THREAD

**Issue by woleger** [ebi-chebi/ChEBI#3784]
Regarding CHEBI:27432 - α-linolenic acid
the double bonds of α-linolenic acid are at position 3, 6, 9.  The correct name is therefore all-cis-3,6,9-octadecatrienoic acid (and NOT all-cis-9,12,15-octadecatrienoic acid).

**Comment by aimol** [comment]
The positions of the double bonds in CHEBI:27432 are 9,12,15. See https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:27432
