### ISSUE TITLE
Some errors in definitions of compounds including L-idorunate

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#3785]
Hi Adnan,

I have noticed some errors in the definitions of the following two entries (I cannot edit the definitions).
CHEBI:85308 It should be "heparosan L-iduronic acid"
CHEBI:4439 It should be "L-iduronyl-(alpha1->3)-N-"

Cheers,
Kristian

**Comment by amalik01** [comment]
Now corrected.
