### ISSUE TITLE
New class request: Argon-39

### ISSUE THREAD

**Issue by pbuttigieg** [ebi-chebi/ChEBI#3786]
xref https://github.com/EnvironmentOntology/envo/issues/904
Hi CHEBI team - could you please add this isotope of Argon, used in the Essential Ocean Variables.
Annotation properties are textbook, nothing fancy here.

**Comment by amalik01** [comment]
An entry for argon-39 (CHEBI:155827) has now been created. It should be visible on the ChEBI website by tomorrow.
