### ISSUE TITLE
Root of v188 has empty nodes

### ISSUE THREAD

**Issue by safrant** [ebi-chebi/ChEBI#3788]
While trying to load the v188 chebi.obo file I discovered that the hierarchy could not be properly displayed in my local application.  I examined the raw data file and discovered there were two empty concepts at the root level and a handful of other populated concepts at the root level.  I believe this is an error. 

See CHEBI_43262 and CHEBI_45394 for the empty concepts

See the following for possibly misplaced root concepts:
CHEBI_149697
CHEBI_150011
CHEBI_149732
CHEBI_149734

**Comment by muthuvenkat** [comment]
@safrant  Thanks for bring our attention, we will fix ASAP.

**Comment by safrant** [comment]
Everything seems to be fixed except CHEBI_150011.  That is still hanging out as a weird root node with no children. I am going to assume that is on purpose and close this ticket.

**Comment by amalik01** [comment]
I have now fixed CHEBI:150011. Hopefully the issue will be resolved in ChEBI's next months release.
