### ISSUE TITLE
CHEBI:43262 term issue

### ISSUE THREAD

**Issue by cmpich** [ebi-chebi/ChEBI#3789]
When I load the latest Chebi obo file I am getting an error about 
Term with id CHEBI:43262 has no name attribute
When I look into the obo file I see three references to that term but no term stanza for that id.

**Comment by muthuvenkat** [comment]
@cmpich Thanks for reporting it, we will fix it ASAP

**Comment by amalik01** [comment]
Hi,

This has now been corrected.
