### ISSUE TITLE
CHEBI:74856, IUPAC name is wrong

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#3790]
The parent hydride of this compound is stibane and the IUPAC name should be "trichlorostibane", not "trichlorostibine". Alternative IUPAC name (using additive nomenclature) would be  "trichloridoantimony".

According to the IUPAC Red Book (2005) "The names ‘phosphine’, ‘arsine’ and ‘stibine’ are no longer acceptable" <as IUPAC names>

**Comment by amalik01** [comment]
Thanks for letting us know. This has now been corrected.
