### ISSUE TITLE
CHEBI:78067, no IUPAC name, ChEBI name far from ideal

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#3791]
For this compound, "tin dichloride", "tin(2+) chloride", and "tin(II) chloride" are all acceptable compositional IUPAC names. I suggest to use one of these names as the ChEBI name.

In the gas phase, this compound exists as a discrete molecule Cl-Sn-Cl which could be named (additively) "dichloridotin"; this corresponds to the second image/molfile in CHEBI:78067. It probably never exists in solution as Sn(2+) Cl(-) Cl(-) as the first image may imply.

The main ChEBI name "tin dichloride (anh.)" is really not the best. It's better to leave it among  synonyms.

**Comment by amalik01** [comment]
Hi,

I have updated the ChEBI name to tin(II) chloride (anhydrous). The reason being is that there is another entry in ChEBI which is the dihydrate form so to distinguish between this anhydrous form which doesn't contain any water molecules, it is necessary to put the words anhydrous next to the ChEBI name.
