### ISSUE TITLE
Add hydroxytorasemide (M1), Torsemide M3 and Torsemide M5

### ISSUE THREAD

**Issue by matthiaskoenig** [ebi-chebi/ChEBI#3793]
The metabolites of torasemide (https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:9637) are currently missing from CHEBI. These are the following three metabolites.

> “The metabolism and elimination of torasemide involves hepatic biotransformation followed by both renal and nonrenal excretion of metabolites. Three main metabolites have been identified in humans: the M1 metabolite is about one-tenth as potent as torasemide, the M3 metabolite is equivalent in potency, and the M5 metabolite is inactive. [Friedel1991]

Friedel HA, Buckley MM. Torasemide. A review of its pharmacological properties and therapeutic potential. Drugs. 1991;41(1):81‐103. doi:10.2165/00003495-199141010-00008

**Torasemide M1** (hydroxytorasemide)
https://www.drugbank.ca/metabolites/DBMET00297
https://hmdb.ca/metabolites/HMDB0060982
inchikey/WCYVLAMJCQZUCR-UHFFFAOYSA-N

**Torasemide M3**
https://www.drugbank.ca/metabolites/DBMET02233
BJCCDWZGWOVSPR-UHFFFAOYSA-N

**Torasemide M5**
https://www.drugbank.ca/metabolites/DBMET02230
PGPRBNDLCZQUST-UHFFFAOYSA-N

**Comment by amalik01** [comment]
All 3 entries have now been created. They should be searchable on the ChEBI website by tomorrow.
Torasemide M1 - CHEBI:155897
Torasemide M3 - CHEBI:155915
Torasemide M5 - CHEBI:155916

**Comment by matthiaskoenig** [comment]
@amalik01 Thanks a lot. Best Matthias
