### ISSUE TITLE
CHEBI:34055: IUPAC name etc.

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#3795]
Can I ask you to annotate CHEBI:34055 to the "three star" standard?

ChEBI name: 1,2-naphthoquinone
IUPAC name: naphthalene-1,2-dione
add links to NIST and ChemIDplus via CAS 524-42-5
synonyms: _o_-naphthoquinone ; _ortho_-naphthoquinone 
Wikipedia: https://en.wikipedia.org/wiki/1,2-Naphthoquinone

Cf. CHEBI:27418, 1,4-naphthoquinone

Thank you

**Comment by amalik01** [comment]
This entry has now been checked.
