### ISSUE TITLE
NTR- copper phthalocyanine

### ISSUE THREAD

**Issue by laurenechan** [ebi-chebi/ChEBI#3799]
Curators at the Environmental Conditions, Treatments, and Exposures Ontology (ECTO) are interested in this term for use in our exposure patterns.

Term: copper phthalocyanine
Parent: metallophthalocyanines (CHEBI:51584)
Definition: A bright, crystalline, synthetic glue pigment from the group of phthalocyanine dyes. It is a brilliant blue that is often used in paints and dye.
Synonyms: phthalocyanine blue BN, phthalo blue, thalo blue, monastral blue
XRefs: https://en.wikipedia.org/wiki/Phthalocyanine_Blue_BN

**Comment by amalik01** [comment]
An entry has now been created (CHEBI:155903). It should be searchable on the ChEBI website by tomorrow.
