### ISSUE TITLE
NTR - chlorinated naphthalene

### ISSUE THREAD

**Issue by laurenechan** [ebi-chebi/ChEBI#3807]
Curators at the Environmental Conditions, Treatments, and Exposures Ontology (ECTO) are interested in this term for use in our exposure patterns.

Term: chlorinated naphthalene 
Parent: naphthalene (CHEBI:16482)
Definition: A naphthalene that has undergone a non-catalytic chlorination.
Reference: https://en.wikipedia.org/wiki/Naphthalene

**Comment by amalik01** [comment]
Hi,

Are you interested in a particular chlorinated napthalene or do you just want me to create a class in ChEBI since chlorinated napthalenes are a group of compounds. There are 75 possible chlorinated napthalenes and alot of these may not exist in ChEBI.

**Comment by laurenechan** [comment]
Hi @amalik01 ,
At this time, our use case only requires a general term for 'chlorinated naphthalene', but not any specific one.

**Comment by amalik01** [comment]
An entry has now been created (CHEBI:156062). It will be searchable on the ChEBI website by tomorrow.
