### ISSUE TITLE
thiosulfurous acid (CHEBI:35926) and sulfurothionous O,O-acid (CHEBI:50152)

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#3808]
The trivial name "thiosulfurous acid" refers to both tautomers, [SO(OH)(SH)] and [S(OH)<sub>2</sub>S], so maybe it is worth considering making a common parent to CHEBI:50152 and CHEBI:35926 called "thiosulfurous acid".

The IUPAC name of CHEBI:35926 "hydroxidooxidosulfidosulfur" is wrong: there is no "sulfido" in [SO(OH)(SH)].
The correct additive IUPAC name is "hydroxidooxidosulfanidosulfur". Alternatively, the IUPAC functional replacement name for this structure is "sulfurothious _S_-acid".

The IUPAC name of [S(OH)<sub>2</sub>S] CHEBI:50152 is "dihydroxidosulfidosulfur" (additive) or "sulfurothious _O_-acid" (functional replacement). The current IUPAC name "dihydroxido(sulfanediiodo)sulfur" is correct if we want to stress the double bond =S in the structure, i.e. [S(OH)<sub>2</sub>(=S)].

I don't know where the ChEBI name "sulfurothionous O,O-acid" came from, probably from ACD/Name.

For consistency sake, I suggest to call CHEBI:35926 "sulfurothious _S_-acid" and CHEBI:50152 "sulfurothious _O_-acid" as these names clearly stress the difference between the two.

Reference: The Red Book (2005), Table IR-8.2 (p. 139)

**Comment by amalik01** [comment]
Most of your changes have now been made. We use ACD to generate IUPAC names. All of the other synonyms provided by you have been listed as synonyms with source IUPAC. Thanks
