### ISSUE TITLE
CHEBI:144321 wrong formula

### ISSUE THREAD

**Issue by rwst** [ebi-chebi/ChEBI#3809]
CHEBI:144321 is named a residue but none of the residues should have an InChi key, if I understand correctly. The entity associated with the SMILES is rather a compound (it contains no stars).

What is a puzzle to me however is that the formula still contains placeholders. Can you please clarify?

**Comment by kaxelsen** [comment]
I just noted that the definition writes "hepatitUs" not hepatitIs

**Comment by amalik01** [comment]
This has now been corrected. Thanks
