### ISSUE TITLE
wrong lipid maps link to entry 52603

### ISSUE THREAD

**Issue by sonial** [ebi-chebi/ChEBI#3810]
Hi,

I am writing to report what I think is an error for entry 52603. 

This entry represents the scaffold of lysophosphoserines, with a generic acyl side chain. 

However, the lipid maps ID annotated to it refers to a specific lysophosphoserine (LPS 18:0), which instead represents the correctly annotated entry 85403.

Hope this helps!
Sonia

**Comment by amalik01** [comment]
Thanks for letting us know. This has now been corrected.
