### ISSUE TITLE
ChEBI ontology network failures

### ISSUE THREAD

**Issue by balhoff** [ebi-chebi/ChEBI#3811]
For the past week or so I have had a lot of trouble loading ChEBI from the web. I access it from these PURLs:

- `http://purl.obolibrary.org/obo/chebi.obo`
- `http://purl.obolibrary.org/obo/chebi.owl`
- `http://purl.obolibrary.org/obo/chebi.owl.gz`

which are redirected to files in `http://ftp.ebi.ac.uk/pub/databases/chebi/ontology/`

Nearly every time the file arrives truncated and thus corrupted. This happens using both the `curl` command line and loading via OWL API/Protégé.

**Comment by kltm** [comment]
We have similarly run into this on a non-trivial number of runs in the GO pipeline and twice in the last week.

**Comment by matentzn** [comment]
I still think this is an infrastructure rather than a Chebi issue per se.. I am waiting for them to come back and will let you know when they do! I sent them this (Support #430975):

```
Similar as in ticket #416148 (which was mine, but I have just left EBI, while still helping out on a few associated projects), we continue to have huge issues with the CHEBI download on the FTP servers:
http://ftp.ebi.ac.uk/pub/databases/chebi/ontology/

Since beginning of July (2nd), we constantly (very often) get truncated downloads of the files hosted in the above directory, so the download starts, and mid file, its just truncated. The error is mostly noted by our parsers, for example:

org.xml.sax.SAXParseException; systemId: http://purl.obolibrary.org/obo/chebi.owl; lineNumber: 6147609; columnNumber: 10; Premature end of file.        org.semanticweb.owlapi.rdf.rdfxml.parser.RDFXMLParser.parse(RDFXMLParser.java:78)

Some other people also made this ticket:https://github.com/ebi-chebi/ChEBI/issues/3811

Internally, the OLS team has the same problem.

But I think this is no Chebi issue - it must me infrastructure related?
Thank you very much
```

**Comment by muthuvenkat** [comment]
Sorry @balhoff , @kltm I also had the same issue but when I retried it worked. As @matentzn its is an infrastructure issue. I shall  rise a ticket for the concerned group. Sorry for the inconvenience. 

Venkat

**Comment by balhoff** [comment]
I heard some changes were made at EBI; this has improved quite a bit for me. No errors for the last 3 days.
