### ISSUE TITLE
CHEBI:83433 drawing wrong (stereochemistry)

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#3812]
Hello,

I think the drawing of 3,6-anhydro-α-L-galactopyranose (CHEBI:83433) is stereochemically wrong. Have a look at α-L-galactopyranose (CHEBI:42905) from which 3,6-anhydro-α-L-galactopyranose is derived. The hydrogens at positions 3, 4 and 5 in α-L-galactopyranose all look **up**. But in the drawing of 3,6-anhydro-α-L-galactopyranose in CHEBI:83433 the hydrogens at positions 3 and 5 explicitly point **down** which means that the -C-O- bridge should go **up**. Which is not the case. Please have a look at the 3-D structure of 3,6-anhydro-α-L-galactopyranose in PubChem https://pubchem.ncbi.nlm.nih.gov/compound/448931
and PDBeChem entry AAL (which I suppose this entry should be cross-referenced to)

Thanks

**Comment by G-Owen** [comment]
Hi,
A fundamental feature of stereochemistry depiction of tetrahedral carbons is that, where 4 bonds are attached to a stereocentre, adjacent bonds have opposite "type" while non-adjacent ("opposite") bonds have the same "type" (i.e. if one bond is wedged, the two adjacent bonds are both assumed to be dashed. Where only three bonds are drawn to stereocentres, (as in CHEBI:42905) the implied hydrogen is assumed to be above a dashed substituent, or below a wedged substituent. The structures in CHEBI:42905 and CHEBI:83433 both conform to these rules, which are widely used by chemical drawing and naming software.
 
For CHEBI:83433, the bonds to the -CH2-O- bridge are opposite bonds to dashed hydrogens. The bonds to the bridge are therefore also dashed so the -CH2-O- bridge is below the plain of the pyranose ring.

For CHEBI:42905 (alpha-L-galactose) ACD-Name calculates the stereocentres at positions 1, 2, 3, 4, and 5 as  R,S,R,S,S.
For CHEBI:83433 (3,6-anhydro-α-L-galactopyranose) the corresponding calculation for the 5 stereocentres is R,S,R,R,S.
The difference between the two is at position 4, where the adjacent (position 3) substituent has changed from -OH to -OCH2-.

**Comment by K-r-ll** [comment]
My mistake. Thanks for cross-referencing AAL
