### ISSUE TITLE
has part relation reflexivity

### ISSUE THREAD

**Issue by wdduncan** [ebi-chebi/ChEBI#3813]
Is your use of has part relation reflexive? For example, an instance of an oxygen atom has part itself.
We are wanting to a better understanding for this in regards on how to best use reasoning in relation to molecular entities in ENVO.  
The discussion on ENVO is found here: https://github.com/EnvironmentOntology/envo/issues/977

**Comment by amalik01** [comment]
We use has part relation to denote the relationship between the whole and a part, especially between a salt or an addition compound and its components, or between a class of compounds and a substituent group characteristic for that class. 

If A "has part" B then A cannot have the following relationships with B:

- is a
- is conjugate acid of
- is conjugate base of
- is enantiomer of
- is tautomer of
- is substituent group from


Example:
potassium tetracyanonickelate(2−) (CHEBI:30071) has part tetracyanonickelate(2−) (CHEBI:49928).
Definition: "C has_part C' if and only if: given any c that instantiates C at a time t, there is some c' such that c' instantiates C' at time t, and c has c' as a part at t."

More info about ChEBI's ontology relationships can be found in the user manual (https://docs.google.com/document/d/1_w-DwBdCCOh1gMeeP6yqGzcnkpbHYOa3AGSODe5epcg/edit#heading=h.hnsqoqu978s5). See section 3.3 The Relationships.

**Comment by amalik01** [comment]
In the majority of cases, the has part relationship is used for salts and mixtures
