### ISSUE TITLE
norsteroids

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#3815]
Can I ask to annotate B-Norcholest-4-en-3-one (CHEBI:79638) to the ChEBI standard? I suppose the IUPAC name should be 6-norcholest-4-en-3-one as the carbon 6 is lost; compare cholest-4-en-3-one (CHEBI:16175)

Likewise, A-norpregn-3(5)-ene-2,20-dione (CHEBI:79765) can be named 4-norpregn-3(5)-ene-2,20-dione, which is so much shorter than its current systematic name.

**Comment by amalik01** [comment]
These changes have now been made. Thanks

The IUPAC name for CHEBI:79638 is 7-norcholest-4-en-3-one since IUPAC says that the methylene group lost from a steroid is considered to include the highest numbered unsubstituted atom of the ring.
