### ISSUE TITLE
IUPAC name for CHEBI:79500?

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#3816]
Can I ask to annotate 3alpha,21-Dihydroxy-D-homo-5beta-pregn-17a(20)-en-11-one (CHEBI:79500) to the ChEBI standard? 
I suppose the IUPAC name should be 3α,21-dihydroxy-16a-homo-5β-pregn-17(20)-en-11-one

Thanks!

**Comment by K-r-ll** [comment]
And similarly, 3-aza-A-homocholest-4a-en-4-one (CHEBI:79753) can be given a shorter IUPAC name based on cholestane, I guess 3-aza-4a-homocholest-4a-en-4-one

**Comment by amalik01** [comment]
Thanks. The changes have now been made.
