### ISSUE TITLE
seconandro... -> secoandro... 

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#3818]
There is an extra "n" in the ChEBI names:

3,17-dihydroxy-9,10-seconandrost-1,3,5(10)-triene-9-one (CHEBI:85575)
should be "3,17-dihydroxy-9,10-secoandrosta-1,3,5(10)-trien-9-one"

3,4,17-trihydroxy-9,10-seconandrost-1,3,5(10)-triene-9-one (CHEBI:85576)
should be "3,4,17-trihydroxy-9,10-secoandrosta-1,3,5(10)-trien-9-one"

Also, in 3-hydroxy-9,10-secoandrosta-1,3,5(10)-triene-9,17-dione (CHEBI:63245) there is a synonym with source "ChEBI"
"3-hydroxy-9,10-seconandrosta-1,3,5(10)-triene-9,17-dione"

https://www.jbc.org/content/285/29/22264
This publication appears to be the source of these names which were subsequently adopted by UniProt 

Please correct
Thanks

**Comment by amalik01** [comment]
Thanks for letting us know. These have now been corrected.
