### ISSUE TITLE
CHEBI:140439 should be a subclass of indoles (CHEBI:24828), not indole (CHEBI:35581)

### ISSUE THREAD

**Issue by althonos** [ebi-chebi/ChEBI#3819]
`3-geranyl-3-[(Z)-2-isocyanovinyl]-3H-indole` ([CHEBI:140439](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A140439)) is an indole derivative, yet it is listed as a subclass of `indole`.

**Comment by amalik01** [comment]
Thanks for letting us know. This has now been corrected.
