### ISSUE TITLE
Fully annotate CHEBI:40699 (anthramycin)

### ISSUE THREAD

**Issue by althonos** [ebi-chebi/ChEBI#3820]
Hi ! I wanted to submit a fully annotated `anthramycin` compound, however it is already in the ontology as [CHEBI:40699](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:40699), but not properly annotated.

Here are the pieces of information I can provide:

## Cross-reference 
- Wikipedia: Anthramycin
- CAS Registry Number: 4803-27-4
- PubMed citation: 5647054
- PubMed citation: 17584616

## Synonyms
- English, SYNONYM: (+)-anthramycin
- English, IUPAC: (2E)-3-[(11S,11aS)-9,11-dihydroxy-8-methyl-5-oxo-5,10,11,11a-tetrahydro-1H-pyrrolo[2,1-c][1,4]benzodiazepin-2-yl]acrylamide
- French, INN: antramycine
- English, INN: antramycin
- Spanish, INN: antramicina
- Latin, INN: antramycinum

 ## Classification
- is_a pyrrolobenzodiazepine (CHEBI:131437)
- is_a phenols (CHEBI:33853)
- is_a primary amide (CHEBI:33256)
- is_a acrylamides (CHEBI:22216)
- has_role toxin (CHEBI:27026)
- has_role antineoplastic agent (CHEBI:35610)
- has_role alkylating agent (CHEBI:22333)
- has_role bacterial metabolite (CHEBI:76969)

## Species
- Streptomyces refuineus subsp. thermotolerans (NCBI:txid223297) See PubMed Id: 17584616 
 

 Cheers!

**Comment by amalik01** [comment]
Hi,

The entry has now been updated. Thanks
