### ISSUE TITLE
*L-α-amino acid* class should probably not have mouse metabolite role

### ISSUE THREAD

**Issue by althonos** [ebi-chebi/ChEBI#3821]
Hi, it's me again!

The entry for [*L-α-amino acid* (CHEBI:15705)](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A15705) is labeled as having `has_role` [*mouse metabolite* (CHEBI:75771)](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A75771). However, since this class also contains non-proteogenic amino acids such as [*lysidine* (CHEBI:64328)](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A64328) which are probably not mouse metabolites, I'm not sure the entire class should have this annotation.

Maybe an intermediate *proteogenic L-α-amino acid* class should be created, disjoint from [*non-proteinogenic L-α-amino acid* (CHEBI:83822)](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A83822), which would then be able to be annotated with the *mouse metabolite* role. Some other non-proteinogenic amino acids that are actually mouse metabolites, such as [*L-ornithine* (CHEBI:15729)](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A15729), could then receive the *mouse metabolite* role at the class level.

**Comment by amalik01** [comment]
Thanks for letting us know. The role 'mouse metabolite' has now been removed from CHEBI:15705
