### ISSUE TITLE
CHEBI OWL and whole ftp site vanished

### ISSUE THREAD

**Issue by cmungall** [ebi-chebi/ChEBI#3822]
http://purl.obolibrary.org/obo/chebi.owl returns 404

This seems to have been caused by http access to EBI FTP failing:
http://ftp.ebi.ac.uk/pub/

See also https://github.com/OBOFoundry/purl.obolibrary.org/issues/656 @nmatentz

**Comment by muthuvenkat** [comment]
@cmungall, sorry for the inconvenience. There was some network issue in EBI wide scale. Now its back online.

Thanks,
Venkat
