### ISSUE TITLE
Update annotations of thiotropocin (CHEBI:29694)

### ISSUE THREAD

**Issue by althonos** [ebi-chebi/ChEBI#3824]
Hi there!

I just added the thiotropocin tautomer to ChEBI, but thiothropocin itself is lacking some annotations. Here is what I can provide:

## Ontology
- *is_a* `CHEBI:50492` (thiocarbonyl compound)
- *has_parent_hybride* `CHEBI:37519` (cyclohepta-1,3,5-triene)
- *has_role* `CHEBI:33282` (antibacterial agent)
- *has_role* `CHEBI:76969` (bacterial metabolite)

## Cross-references
- PMID:6511658, [*Thiotropocin, a new sulfur-containing 7-membered-ring antibiotic produced by a Pseudomonas sp*](https://pubmed.ncbi.nlm.nih.gov/6511658/)
- PMID:16269767, [*Ecology, inhibitory activity, and morphogenesis of a marine antagonistic bacterium belonging to the Roseobacter clade*](https://pubmed.ncbi.nlm.nih.gov/16269767/)

## Species
- `Pseudomonas sp.` of strain CB-104, NCBI:txid306, PMID:6511658
- `Roseobacter sp.` of strain 27-4, NCBI:txid1907202, PMID:16269767 

Cheers!

**Comment by amalik01** [comment]
The entry has now been annotated. Thanks
