### ISSUE TITLE
Outgoing relationship issue with ortho ester (CHEBI:71989)

### ISSUE THREAD

**Issue by althonos** [ebi-chebi/ChEBI#3825]
Hi there!

`CHEBI:71989` (ortho esther) is marked as being a `CHEBI:69173` (trigoheterin E, (rel)-) subclass, but it's more likely the other way around. Because of this, all ortho esthers are indirect `lipid` subclasses, which is unsound. 

Cheers!

**Comment by amalik01** [comment]
Thanks. Now corrected.
