### ISSUE TITLE
CHEBI:27761 - (S)-prunasin

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#3827]
Please add the trivial name "sambunigrin"
See https://en.wikipedia.org/wiki/Prunasin

Also, synonyms
(_S_)-_O_-β-D-glucopyranosylmandelonitrile
(_S_)-(β-D-glucopyranosyloxy)(phenyl)acetonitrile
source: https://www.qmul.ac.uk/sbcs/iupac/2carb/33.html

Thanks!

**Comment by amalik01** [comment]
Now done. Thanks
