### ISSUE TITLE
CHEBI:61028 - DOTA

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#3831]
CHEBI:61028  has a synonym with source ChemIDplus:
,4,7,10-Tetraazacyclododecane-N,N',N'',N'''-tetraacetic acid

in fact  ChemIDplus has 
1,4,7,10-Tetraazacyclododecane-N,N',N'',N'''-tetraacetic acid

so appears to be copy&paste with the first locant lost. Please correct

**Comment by K-r-ll** [comment]
Also please add:

tetraxetan [INN]
tétraxétan [French INN]
tetraxetanum [Latin INN]
tetraxetán [Spanish INN]

**Comment by amalik01** [comment]
Now done. Thanks
