### ISSUE TITLE
CHEBI:134870 - wrong structure

### ISSUE THREAD

**Issue by rwst** [ebi-chebi/ChEBI#3833]
Using e.g. the introduction of
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5961754/
CHEBI:134870 - toloxatone is 5-(hydroxymethyl)-3-(3-methylphenyl)-1,3-oxazolidin-2-one but your structure is missing the hydroxy group. Please fix.

**Comment by amalik01** [comment]
Thanks. Since it is a racemate, i have removed the structure but have corrected the formula of the structure.
