### ISSUE TITLE
CHEBI:134747 - questionable structure

### ISSUE THREAD

**Issue by rwst** [ebi-chebi/ChEBI#3842]
This is one of a few cases where in ChEBI redundant stereo centers are defined, leading to InChi key mismatch with other databases. Here, the trans-configuration is geometrically impossible. This may be a software problem with your web app.

**Comment by rwst** [comment]
I would close this as the structure is not wrong (#3848 ). We will have to live with multiple InChi keys for some structures. What do you think?

**Comment by amalik01** [comment]
Hi, The correct InChi key for ChEBI:134747 is CTIRHWCPXYGDGF-HDICACEKSA-N so the structure in ChEBI seems correct. The structure has been verified by WHO mednet database. Wikipedia also show the same InChi key.
