### ISSUE TITLE
CHEBI:135633 structure improvement

### ISSUE THREAD

**Issue by rwst** [ebi-chebi/ChEBI#3843]
I think we can agree that if several drug vendors are listed by PubChem with their product SIDs and they all associate to one CID, then this would be the best CID for the drug. For CHEBI:135633 this would be https://pubchem.ncbi.nlm.nih.gov/compound/6917951
and the entry could be improved with it.

**Comment by amalik01** [comment]
Additional data now added to this entry.

**Comment by rwst** [comment]
Thanks.
