### ISSUE TITLE
CHEBI:34001 - (1S,2R)-Naphthalene 1,2-oxide

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#3845]
Can I ask to annotate CHEBI:34001 - (1S,2R)-Naphthalene 1,2-oxide in the same fashion as CHEBI:33998 - (1R,2S)-naphthalene 1,2-oxide and add corresponding ontological relationships:

(1S,2R)-naphthalene 1,2-oxide (CHEBI:34001) is a naphthalene 1,2-oxide (CHEBI:52431)
(1S,2R)-naphthalene 1,2-oxide (CHEBI:34001) is an enantiomer of (1R,2S)-naphthalene 1,2-oxide (CHEBI:33998)

Thank you

**Comment by amalik01** [comment]
Now annotated.
