### ISSUE TITLE
CHEBI:93940 - 1,2,3,4,5,6-hexabromocyclohexane

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#3846]
Can I ask to annotate 1,2,3,4,5,6-hexabromocyclohexane (CHEBI:93940; CAS 1837-91-8) similar to hexachlorocyclohexane (CHEBI:24536)

Some links:

https://chem.nlm.nih.gov/chemidplus/rn/1837-91-8
http://www.chemspider.com/Chemical-Structure.67180.html
https://pubchem.ncbi.nlm.nih.gov/compound/74603

**Comment by amalik01** [comment]
Now annotated.
