### ISSUE TITLE
CHEBI:4912 - wrong structure

### ISSUE THREAD

**Issue by rwst** [ebi-chebi/ChEBI#3847]
Both old and new references have a hydroxy group in the 11-position, missing in CHEBI:4912 - etorphine:
* https://www.ncbi.nlm.nih.gov/pmc/articles/pmc1557229/
* https://onlinelibrary.wiley.com/doi/pdf/10.1002/jccs.201190048

**Comment by amalik01** [comment]
Thanks. This has now been corrected.
