### ISSUE TITLE
CHEBI:50702 inconsistencies

### ISSUE THREAD

**Issue by rwst** [ebi-chebi/ChEBI#3851]
From the name, ontology, and SMILES this is a pair of E,Z isomers, and thus should have the InChi key LLTRNSKZFVUNLQ-UHFFFAOYSA-N. The SMILES clearly does not define E or Z, but if I load it in the tool I get the E version and it identifies with CHEBI:134683. So I think the structure should be redone and explicitly left EZ undefined. Could you have a look? But the fact that the SMILES yields a different entry is worrisome.

**Comment by amalik01** [comment]
Now fixed. I think it was the drawing package which was not able to recognize that the structure drawn did not have a double bond configuration specified, so i have added a wiggly bond in the structure to generate the correct InChiKey.
