### ISSUE TITLE
CHEBI:7445,7446 full stereochemistry missing

### ISSUE THREAD

**Issue by rwst** [ebi-chebi/ChEBI#3855]
The peptide has the IUPAC name L-pyroglutamyl-L-histidyl-L-tryptophyl-L-seryl-L-tyrosyl-3-(2-naphthyl)-D-alanyl-L-leucyl-L-arginyl-L-prolyl-glycinamide; acetic acid; hydrate, see https://pubchem.ncbi.nlm.nih.gov/compound/25079425. Unfortunately, none of the 9 centers is specified.

**Comment by rwst** [comment]
I'm adding CHEBI:7445 as the functional parent with the same issue here. The FDA document https://www.accessdata.fda.gov/drugsatfda_docs/nda/98/019886s013_synarel_medr_P1.pdf lists the parent peptide as 5-oxo L-prolyl L-histidyl-L-tryptophyl-L-seryl-L-tyrosyl-3-(2-naphthyl)-D-alanyl-L-leucyl-L-arginyl-L-prolyl-glycinamide, consistent with the above for the salt.

**Comment by amalik01** [comment]
Both entries have now been fixed. Thanks
