### ISSUE TITLE
N,N-dimethylaniline ontology

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#3857]
This is wrong:

4-(hydroxylamino)-N,N-dimethylaniline (CHEBI:59991) is a N,N-dimethylaniline (CHEBI:16269)
N,N-dimethyl-4-nitrosoaniline (CHEBI:59990) is a N,N-dimethylaniline (CHEBI:16269)
N,N-dimethylaniline N-oxide (CHEBI:17735) is a N,N-dimethylaniline (CHEBI:16269)

please change the relationships to "has functional parent"

Thanks!

**Comment by amalik01** [comment]
Thanks for letting us know. The relationships have now been corrected.
