### ISSUE TITLE
pentaerythritol (CHEBI:134760)

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#3858]
Can I ask to annotate pentaerythritol please

CAS 115-77-5 
Beilstein 1679274
https://chem.nlm.nih.gov/chemidplus/rn/115-77-5
https://webbook.nist.gov/cgi/cbook.cgi?ID=115-77-5
https://en.wikipedia.org/wiki/Pentaerythritol
https://www.kegg.jp/entry/D08331

**Comment by amalik01** [comment]
Now annotated.
