### ISSUE TITLE
CHEBI:42191 - wrong merge

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#3859]
Hello,

it looks the entry for ethylenediaminetetraacetic acid C10H16N2O8 [CHEBI:42191; corresponding CAS 60-00-4; IUPAC name (ethane-1,2-diyldinitrilo)tetraacetic acid; H4edta] has been wrongly merged with that for ethylenediaminetetraacetate C10H12N2O8 [corresponding CAS 150-43-6, IUPAC name (ethane-1,2-diyldinitrilo)tetraacetate; edta or EDTA(4−)]. Please bring 
EDTA(4−) back to life because:

EDTA(4−) is conjugate base of EDTA(3−) (CHEBI:63131)
EDTA(4−) is part of Edetate calcium disodium (CHEBI:4757)
EDTA(4−) is part of ethylenediaminetetraacetatonickelate(2−) (CHEBI:30379) 
EDTA(4−) is part of ethylenediaminetetraacetatoferrate(1−) (CHEBI:30729)
EDTA(4−) is part of ethylenediaminetetraacetatoferrate(2−) (CHEBI:30730) 

Thank you

**Comment by amalik01** [comment]
The entries have now been demerged. Not sure why they were merged in the 1st place.
