### ISSUE TITLE
CHEBI:6722 and 6723 wrong structures

### ISSUE THREAD

**Issue by rwst** [ebi-chebi/ChEBI#3860]
All databases you link to in CHEBI:6722 have a 6-methyl addition on the molecule. Note also that all synonyms of CHEBI:6723 contain the 6-methyl group in the name, in spite of the structure. Most convicing, however, I find the title of PMID: 5320316: _Synthesis of [1,2-3H2]medroxyprogesterone acetate (17-alpha-acetoxy-6-alpha-methyl[1,2-3H2]pregn-4-ene-3,20-dione) and [1,2-3H2]**megestrol** acetate (17-alpha-acetoxy-**6-methyl**[1,2-3H2]pregna-4,6-diene-3,20-dione)_. Please fix.

**Comment by amalik01** [comment]
Now fixed. Thanks
