### ISSUE TITLE
IUPAC name(s) for CHEBI:24786

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#3863]
Hello,

please indicate IUPAC name(s) for iminodiacetic acid (CHEBI:24786). I suppose these are
N-(carboxymethyl)glycine [substitutive]
2,2'-iminodiacetic acid or 2,2'-azanediyldiacetic acid [multiplicative]

Thanks!

**Comment by amalik01** [comment]
Now done. Thanks
