### ISSUE TITLE
CHEBI:7989 name / incomplete stereochem.

### ISSUE THREAD

**Issue by rwst** [ebi-chebi/ChEBI#3866]
Hello,
I think it needs to be decided if the entry should hold pepstatins or pepstatin A (commonly named pepstatin). One of the original sources PMID:4600212 describes them as X-L-valyl-L-valyl-4(s)-amino-3(s)-hydroxy-6-methylheptanoyl-L-alanyl-4(s)-amino-3(s)-hydroxy-6-methylheptanoic acid or short X-Val-Val-Sta-Ala-Sta-OH, with X being isovaleryl for pepstatin A. Compared to this CHEBI:7989 misses the (3S,4S) specification on both statin residues. PDB 4AUC confirms the configuration on both.

**Comment by amalik01** [comment]
The entry is now called pepstatin A and the structure has been updated.

**Comment by rwst** [comment]
Thanks!
