### ISSUE TITLE
CHEBI:32034 name / ontology

### ISSUE THREAD

**Issue by rwst** [ebi-chebi/ChEBI#3869]
The structure is the L-tartrate so I think the name should reflect that. Also there is the statement "is_a L-α-D-Hepp-(1→7)-L-α-D-Hepp-(1→3)-L-α-D-Hepp-(1→5)-α-Kdo (CHEBI:78618)" which is clearly wrong.

**Comment by amalik01** [comment]
Now fixed. Thanks
