### ISSUE TITLE
CHEBI:140503 undefined mixture with formula

### ISSUE THREAD

**Issue by rwst** [ebi-chebi/ChEBI#3870]
CHEBI:140503 defines kaoline as mixture of the mineral kaolinite and containing varying amounts of other minerals such as muscovite, quartz, feldspar, and anatase. However, the entry has a structure which should be probably associated with one of the ingredients, not the mixture. Do you agree?

**Comment by amalik01** [comment]
This is a bit tricky. Although in nature, kaolin is a mixture containing various other minerals, the main component is kaolinite, and quite a few journal articles show the same structure depicted in CHEBI:140503. We have only displayed the structure for visualization purposes. if you want i can remove it so its no longer visible.

**Comment by rwst** [comment]
No need for change if your policy regarding mixtures allows a structure for the main component. I'll just ignore such cases then.

**Comment by amalik01** [comment]
Usually we don't show structures for mixtures but sometimes we do make exceptions.
