### ISSUE TITLE
new CHEBI:45302 synonyms

### ISSUE THREAD

**Issue by slaulederkind** [ebi-chebi/ChEBI#3874]
Please add the following synonyms to CHEBI:45302:

5-(6-Quinoxalinylmethylene)-2,4-thiazolidinedione 
5-Quinoxalin-6-ylmethylene-thiazolidine-2,4-dione
AS605240
AS-605240

Thank you

**Comment by amalik01** [comment]
This entry has now been annotated. Thanks
