### ISSUE TITLE
CHEBI:47495 unspecified double bond

### ISSUE THREAD

**Issue by rwst** [ebi-chebi/ChEBI#3878]
https://www.ebi.ac.uk/pdbe-srv/pdbechem/chemicalCompound/show/IQB shows the double bond in the E-configuration, so I think this should be specified in CHEBI:47495 or an additional entry created as part of the mixture. However, this would also affect CHEBI:131489. Can you please have a look?

**Comment by amalik01** [comment]
A separate entry for the E-isomer (CHEBI:191396) has now been created to avoid confusion. The entry should be visible on the ChEBI website by tomorrow. Thanks
