### ISSUE TITLE
CHEBI:135938 missing stere config

### ISSUE THREAD

**Issue by rwst** [ebi-chebi/ChEBI#3881]
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2206632/ names the compound as {(5R,6S)-6-phenyl-5-[4-(2-pyrrolidin-1-yl-ethoxy)-phenyl]-5,6,7,8-tetrahydro-naphthalen-2-ol} and gives the structure too. Can you please add what's missing?

**Comment by amalik01** [comment]
Now fixed. Thanks
