### ISSUE TITLE
CHEBI:60384, discrepancy between name and structure

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#3885]
Hi Adnan,

N-(2,3-dihydroxyhexacosanoyl)-(4S)-hydroxysphinganine is in fact (4R). I suggest to update the names (also the IUPAC name) as we use it in Rhea. If you choose to update the structure please let me know so I can submit the (4R) isomer.

Cheers,
Kristian

**Comment by amalik01** [comment]
I have updated the CHEBI name to 4R. Can you change the Uniprot name to 4R. Thanks
