### ISSUE TITLE
CHEBI:60256, discrepancy between name and structure

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#3886]
Hi Adnan,

(4S)-N-(2,3-dihydroxytetracosanoyl)-4-hydroxysphinganine is in fact (4R). I suggest to update the names (also the IUPAC name) as we use it in Rhea. If you choose to update the structure please let me know so I can submit the (4R) isomer.

Cheers,
Kristian

**Comment by amalik01** [comment]
I have updated the chebi name. Can you update the uniprot name to 4R. Thanks
