### ISSUE TITLE
Same chemicals?

### ISSUE THREAD

**Issue by smoretti** [ebi-chebi/ChEBI#3890]
Hi

I wonder what is the relation between **chebi:138150** and **chebi:17837** ?
Are they similar, conjugate acid/base, ... ?

Best

**Comment by rwst** [comment]
138150 is the 1-phosphate anion, 17837 is the neutral 6-phosphate.

**Comment by smoretti** [comment]
The UniProt synonym of chebi:138150 is however "_D-tagatose 6-phosphate_".
And I don't really see their relation in the ontology.

**Comment by rwst** [comment]
The error is not in UniProt but in Rhea:
```
<rdf:Description rdf:about="http://rdf.rhea-db.org/Participant_47680_compound_13
865">
        <rh:compound rdf:resource="http://rdf.rhea-db.org/Compound_13865"/>
        <rdfs:subClassOf rdf:resource="http://rdf.rhea-db.org/Compound_13865"/>
</rdf:Description>

<rdf:Description rdf:about="http://rdf.rhea-db.org/Compound_13865">
        <rh:id rdf:datatype="http://www.w3.org/2001/XMLSchema#long">13865</rh:id
>
        <rh:accession>CHEBI:138150</rh:accession>
        <rh:name>D-tagatose 6-phosphate</rh:name>
        <rh:htmlName>&lt;small&gt;D&lt;/small&gt;-tagatose 6-phosphate</rh:htmlName>
        <rh:formula>C6H11O9P</rh:formula>
        <rh:charge rdf:datatype="http://www.w3.org/2001/XMLSchema#int">-2</rh:charge>
        <rdfs:subClassOf rdf:resource="http://rdf.rhea-db.org/SmallMolecule"/>
        <rh:chebi rdf:resource="http://purl.obolibrary.org/obo/CHEBI_138150"/>
        <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/CHEBI_138150"/>
</rdf:Description>
```

**Comment by amalik01** [comment]
They ontology of the cationic/anionic forms is not as well developed in ChEBI as compared to the neutral forms. Hence to see the relationship, you will have to look at the ontology of the neutral compound, the conjugate base of CHEBI:138150 which is CHEBI:138801. This is a ketohexose monophosphate and the structure has a phosphate group at position 1.

ChEBI:17837 is a tagotose 6-phosphate (ChEBI:49094) which also is a ketohexose monophosphate (ChEBI:24971), however the phosphate group of this compound is located at position 6.

With sugars, you get several different forms such as open chain, and cyclic forms (furanose and pyranose).

**Comment by smoretti** [comment]
Thanks for the ontology clarification.
I will contact Rhea about "D-tagatose 6-phosphate"
