### ISSUE TITLE
CHEBI:63626 issues

### ISSUE THREAD

**Issue by rwst** [ebi-chebi/ChEBI#3893]
The structure given does not match the biological sequence (UniProt P01286), and also not the sequence given in the original patent (https://patents.google.com/patent/US8435945B2/). Problem is amino acids 30-44, note also CHEBI:63626 has one synonym with the correct sequence:
```
P01286 (63-76): GESNQERGARARL = Gly-Glu-Ser-Asn-Gln-Glu-Arg-Gly-Ala-Arg-Ala-Arg-Leu
patent:                         Gly-Glu-Ser-Asn-Gln-Glu-Arg-Gly-Ala-Arg-Ala-Arg-Leu
CHEBI:63626:                    Gly-Gln-Ser-Asn-Gln-Arg-Gly-Ala-Arg-Ala-Arg-Leu
synonym from JCBM:              Gly-Glu-Ser-Asn-Gln-Glu-Arg-Gly-Ala-Arg-Ala-Arg-Leu
```
If you can see this message formatted, then the amino acids are aligned, and you can see the difference at the second position (Glu vs Gln), and that pos 6 is deleted. 

The other issue is that the final product appears to be an acetate.

I hope this can help to improve the entry.

**Comment by amalik01** [comment]
Hi, I have now fixed the structure. This entry is for tesamorelin hence it doesn't contain the acetate groups. If you want tesamorelin acetate, then you will have to submit an entirely new ChEBI entry via the submission tool. Thanks.
