### ISSUE TITLE
CHEBI:3403 wrong stereo configuration

### ISSUE THREAD

**Issue by rwst** [ebi-chebi/ChEBI#3895]
In CHEBI:3403 is stated: "Prostaglandin F2α (CHEBI:15553) in which the hydrogen at position 15 is substituted by methyl (S configuration)." The methyl is not the problem but the two hydroxyls on the cyclopentane that are in different configuration than in CHEBI:15553.

**Comment by amalik01** [comment]
Now fixed. Thanks
