### ISSUE TITLE
Seems like ChEBI:82643 and ChEBI:141688 are the same

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3900]
Hi,
I just noticed that ChEBI:82643 and ChEBI:141688 look the same, would you please double check and if so, please merge? In case of merging, would it be possible to keep ChEBI:141688 as the principal ID?
Thanks for your help!

**Comment by amalik01** [comment]
Both entries have been merged. Since CHEBI:82643 had a checked status, the program automatically selected this as the primary ID. The entry now has 2 UniProt names, Can you check and correct these? Thanks
