### ISSUE TITLE
CHEBI:5931 not human insulin

### ISSUE THREAD

**Issue by rwst** [ebi-chebi/ChEBI#3907]
The InChi key of CHEBI:5931 is the same as that of CID 70678557 (https://pubchem.ncbi.nlm.nih.gov/compound/70678557), and CID 70678557 starts with `H-Phe-Val-Gly(CONH2)-Gln-` instead of `H-Phe-Val-Asn-Gln-` in CID 118984375 (https://pubchem.ncbi.nlm.nih.gov/compound/118984375). Also, UniProt P01308 (https://www.uniprot.org/uniprot/P01308) shows that the beta chain (amino acids 25-54 of the prepro) starts FVNQ which is `Phe-Val-Asn-Gln`.

However, https://www.accessdata.fda.gov/drugsatfda_docs/label/2008/021868s016s017lbl.pdf makes it clear that at least the original Exubera is plain human insulin (albeit recombinant), so what CHEBI:5931 and CID 70678557 actually is is unclear to me.

**Comment by amalik01** [comment]
Thanks. There were a few incorrect stereocentres in the structure. I have now corrected this. Thanks
