### ISSUE TITLE
CHEBI:63051 Append fertilizer analysis to definition

### ISSUE THREAD

**Issue by tscottm** [ebi-chebi/ChEBI#3921]
Current Definition:
"An inorganic phosphate, being the diammonium salt of phosphoric acid."

Suggested Revision:
"An inorganic phosphate, being the diammonium salt of phosphoric acid. The commercially available fertilizer has an analysis of 18-46-0 (N-P2O5-K2O) and is marketed under the name diammonium phosphate or DAP."

Rationale:
The suggested addition provides additional information needed by ontologies in other disciplines (like AGRO) that use the ChEBI definition.

**Comment by amalik01** [comment]
Now added. Thanks
