### ISSUE TITLE
CHEBI:16199 Append guaranteed fertilizer analysis to definition

### ISSUE THREAD

**Issue by tscottm** [ebi-chebi/ChEBI#3922]
Current Definition:
"A carbonyl group with two C-bound amine groups."

Suggested Revision:
"A carbonyl group with two C-bound amine groups. The commercially available fertilizer has an analysis of 46-0-0 (N-P2O5-K2O).

Rationale:
The suggested addition provides additional information needed by ontologies in other disciplines (like AGRO) that use the ChEBI definition.

**Comment by amalik01** [comment]
Now added. Thanks
