### ISSUE TITLE
Wrong or deprecated xrefs for CHEBI:17408

### ISSUE THREAD

**Issue by smoretti** [ebi-chebi/ChEBI#3935]
Hi

CHEBI:17408 looks to contain deprecated or wrong xrefs:
- LipidMaps LMGL0101 does not exist.
- KEGG C01885 contains a single R group not 3 like CHEBI:17408. CHEBI:35759 looks to be the right xref for KEGG C01885.

**Comment by amalik01** [comment]
Now corrected. Thanks
