### ISSUE TITLE
CHEBI:81526 missing stereo specification

### ISSUE THREAD

**Issue by rwst** [ebi-chebi/ChEBI#3943]
The abstract of https://www.sciencedirect.com/science/article/abs/pii/0045653573900180 gives the original Bayer/IUPAC name as  1,8,9,10,11,11-hexachloro-4,5-exo-epoxy-2,3,-7,6-endo-2, 1–7,8-endo-tetracyclo[6.2.1.1.3,6.02,7] dodec-9-ene, and I think at least the epoxy in CHEBI:81526 should be made exo, like in https://pubchem.ncbi.nlm.nih.gov/compound/12358480. But I'm not sure about the endo specifications. Can you please check that entry?

**Comment by amalik01** [comment]
Now fixed. Thanks
