### ISSUE TITLE
Please check if CHEBI:90381 and CHEBI:144577 represent the same entity

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3948]
Hi Adnan,
As I continue checking the glycosphingolipids, I find more structures that resemble each other. Can you please double check if CHEBI:90381 and CHEBI:144577 represent the same entity? Sorry once again for the duplications.

**Comment by amalik01** [comment]
The entries have now been merged. We unfortunately don't have validations in place to detect duplicate residues. When you submit these gylcan residues to ChEBI, can you do a quick structure search in ChEBI beforehand to see if the same structure already exists. Thanks.
