### ISSUE TITLE
CHEBI:84050 (trabectedin) is an alkylating agent

### ISSUE THREAD

**Issue by althonos** [ebi-chebi/ChEBI#3952]
[`CHEBI:84050` (trabectedin)](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:84050) has been shown to be an alkylating agent, so it should have role [`CHEBI:22333` (alkylating agent)](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:22333).

Source:  [*Trabectedin and its potential in the treatment of soft tissue sarcoma*, Cassier et al.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2503645/)
> ##### Mechanism of action
> 
> Trabectedin (ET743) binds to the minor groove of DNA and alkylates guanine at the N2 position, whereas most alkylating agents bind guanine at position N7 or O6 in the major groove. Binding of trabectedin has been shown to be DNA-sequence specific, with GC rich triplets more frequently bound (David-Cordonnier et al 2005). Covalent binding of trabectedin induces DNA bending towards the major groove and a widening of the DNA minor groove (Takebayashi, Pourquier et al 2001). Modification of the DNA conformation leads to inhibition of activated transcription while constitutive transcription seems unaffected (Friedman et al 2002).

**Comment by amalik01** [comment]
The role has now been added. Thanks
