### ISSUE TITLE
Can you please add a molfile to CHEBI:24026?

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3961]
Hi,
I would like to use CHEBI:24026 in RHEA, but it would need a 2D-structure, formula and charge. Would you please consider adding the same as the one used in CHEBI:30879 (alcohol)?
Thanks in advance for your help,
Lucila

**Comment by amalik01** [comment]
Now added.

**Comment by aimol** [comment]
Thank you Adnan, would you please consider changing the description to include fatty chains starting from 3C  to more than 27C, similar to the one found in MetaCyc?

**Comment by amalik01** [comment]
Now done.
