### ISSUE TITLE
CHEBI:88332 conjugate acid of CHEBI:18000

### ISSUE THREAD

**Issue by smoretti** [ebi-chebi/ChEBI#3965]
Hi

Is CHEBI:88332 really the conjugate acid of CHEBI:18000?
CHEBI:88332 contains an extra C atom.

The other conjugate acid of CHEBI:18000 *CHEBI:142408* has similar number of N and R atoms/groups.

**Comment by amalik01** [comment]
Thanks. This has now been fixed.
