### ISSUE TITLE
Two entities for alpha-cypermethrin?

### ISSUE THREAD

**Issue by andschar** [ebi-chebi/ChEBI#3970]
[CHEBI:39331](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:39331) seems to be the same as [CHEBI:39335](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:39335). Do you agree?

**Comment by andschar** [comment]
It's the same situation as in #3969, so I guess you could also remove the CAS (67375-30-8) in [CHEBI:39335](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:39335)?

**Comment by amalik01** [comment]
CAS number for CHEBI:39335 has been removed.
