### ISSUE TITLE
NTR: ethylene-vinyl acetate

### ISSUE THREAD

**Issue by laurenechan** [ebi-chebi/ChEBI#3971]
Hello,
I am interested in the term ethylene-vinyl acetate to develop a dependency term in ECTO. 

Term: ethylene-vinyl acetate
Parent: copolymer (CHEBI:60804)
Definition: An elastomeric copolymer of ethylene and vinyl acetate used to produce "rubber-like" materials.
Exact synonyms: PEVA, poly(ethylene-vinyl acetate), EVA
Reference: https://en.wikipedia.org/wiki/Ethylene-vinyl_acetate
Logical relationships: 'has part' some CHEBI:29362 (ethylene), 'has part' some CHEBI:46916 (vinyl acetate)

**Comment by amalik01** [comment]
An entry has now been created which should be searchable on the ChEBI website by tomorrow:
poly(ethylene-co-vinyl acetate) - CHEBI:166881
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=166881
