### ISSUE TITLE
Please check if CHEBI:79216 and CHEBI:141753 represent the same entity

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3972]
Please check if CHEBI:79216 and CHEBI:141753 represent the same entity and if they do, please merge them trying to keep CHEBI:141753 as primary if possible.
Thanks

**Comment by amalik01** [comment]
Now merged. Since CHEBI:79216 had a 3-star status, it was automatically selected as the primary identifier. The entry now contains 2 UniProt names, can you please delete one of them. Thanks
