### ISSUE TITLE
CHEBI:166737

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#3973]
Hi Adnan,

Metabolights have named this compound as a 3-sulfate, but they have depicted a compound where the S atom is attached directly to a C, so I don't think it is a sulfate. It is inconsistent when compared to the structure of the 7-sulfate also from Metabolights (CHEBI:166738).

I have also found this catalogue where a compound with the same name has a "real" sulfate group: https://isosciences.com/shop/bile-acids/taurochenodeoxycholic-acid-3-sulfate-sodium-salt/

I ask because I need the conjugated base of taurochenodeoxycholate 3-sulfate for a reaction in Rhea. I plan to submit the relevant compound based on your advice.

Cheers,
Kristian

**Comment by amalik01** [comment]
The structure was loaded as part of a bulk submission process from MetaboLights. I have now corrected the structure.
