### ISSUE TITLE
Is NO a ROS?

### ISSUE THREAD

**Issue by ValWood** [ebi-chebi/ChEBI#3987]
Dear CHEBI,

It seems that NO (Nitric oxide) is not a ROS. See
https://github.com/geneontology/go-ontology/issues/20718
for the full discussion.

v

**Comment by ValWood** [comment]
@raymond91125
@mah11

**Comment by amalik01** [comment]
The term has now been removed. The term was loaded as part of a bulk upload process and had OK status (which means that it hasn't been checked by a curator). Nitric oxide falls under the category of reactive nitrogen species.
