### ISSUE TITLE
respiratory chain inhibitors

### ISSUE THREAD

**Issue by ValWood** [ebi-chebi/ChEBI#3988]
Diuron CHEBI:116509
And NaN3 (I could not find CHEBI entry for this)  
have role respiratory chain inhibitor CHEBI:25355

 PMID:33400299

**Comment by amalik01** [comment]
Do you think mitochondrial complex III inhibitor (CHEBI:38499) would be a more specific role for these compounds rather than CHEBI:25355?

**Comment by ValWood** [comment]
Possibly but I am not 100 % sure because in the publication they are all described as complex III/IV inhibitors...

**Comment by amalik01** [comment]
Okay, i have added 'has role CHEBI:25355' as initially suggested to both entries. NaN3 is sodium azide (CHEBI:278547).
