### ISSUE TITLE
CHEBI_167049 is empty concept at root with children in chebi.obo v195

### ISSUE THREAD

**Issue by safrant** [ebi-chebi/ChEBI#3989]
There is a concept CHEBI_167049 that is listed as the parent of CHEBI_155933 and CHEBI_75023.  However CHEBI_167049 is not defined within the ontology.  This creates an issue when trying to display the hierarchy

[Term]
id: CHEBI:75023
name: Ins-1-P-6-Man-1-2-Ins-1-P-Cer C(2-)
...
is_a: CHEBI:74997
is_a: CHEBI:167049

[Term]
id: CHEBI:155933
name: alpha-D-mannosyl-6-(1D-myo-inositol phospho)-(1<->6)-1D-myo-inositol-1-phospho-N-(2-hydroxy-very-long-chain fatty acyl)-(R)-4-hydroxysphingoid base
...
is_a: CHEBI:139068
is_a: CHEBI:167049

**Comment by amalik01** [comment]
The ontology relationship has now been fixed. Thanks for letting us know
