### ISSUE TITLE
CHEBI:58313 and CHEBI:17892 are acid/base but with different stereo

### ISSUE THREAD

**Issue by smoretti** [ebi-chebi/ChEBI#3991]
Hi

CHEBI:58313 and CHEBI:17892 are acid/base according to the ChEBI ontology but they have incompatible stereochemistry.

What is the right stereo for **L-rhamnulose 1-phosphate**?

**Comment by amalik01** [comment]
This has now been corrected. The correct stereochemistry for L-rhamnulose is that shown in CHEBI:17897. Thanks
