### ISSUE TITLE
Graphene

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#3994]
Not exactly a database issue but I can't help noticing that the entity of the month (January 2021) is graphene which **already** was the entity of the month in November 2010. I mean, there are 58,000+ entries in the database, you can go without repeats for quite a while...

**Comment by amalik01** [comment]
You're right, but entity of the month is not based on how novel or different a compound is compared to previous entity of the months. If a particular compound is in the recent headlines, we write about it, so for this reason it was repeated.
