### ISSUE TITLE
enynes

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#3996]
Is it possible to provide IUPAC names and/or annotate the following entries to ChEBI standard: 

Aethusin (CHEBI:2501)
I suppose it is (2E,8E,10E)-trideca-2,8,10-triene-4,6-diyne
https://de.wikipedia.org/wiki/Aethusin (in German)

//

3-Penten-1-yne (CHEBI:167062)
IUPAC name: (3E)-3-penten-1-yne 

//

Tridec-1-ene-3,5,7,9,11-pentayne (CHEBI:9699)
IUPAC name: tridec-1-ene-3,5,7,9,11-pentayne
https://chem.nlm.nih.gov/chemidplus/rn/startswith/2060-59-5

**Comment by amalik01** [comment]
All 3 entries have now been annotated.
