### ISSUE TITLE
1,4-diphenylbutadiyne (CHEBI:51588) wrong ontology

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#4000]
1,4-diphenylbutadiyne (CHEBI:51588) is a alkadiyne (CHEBI:33651)

The relationship above is wrong because alkadiynes are acyclic. Correct one would be:

1,4-diphenylbutadiyne (CHEBI:51588) is a arylacetylene (CHEBI:51929)

**Comment by amalik01** [comment]
Now corrected. Thanks
