### ISSUE TITLE
some branched alkanes

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#4002]
Can I ask to annotate to "ChEBI standard" the following entries:

Pentane, 2,3-dimethyl- (CHEBI:151115)

Links:
https://en.wikipedia.org/wiki/2,3-Dimethylpentane
https://webbook.nist.gov/cgi/cbook.cgi?ID=565-59-3
https://chem.nlm.nih.gov/chemidplus/rn/startswith/565-59-3
https://pubchem.ncbi.nlm.nih.gov/compound/11260

This is a molecule of **unspecified** stereochemistry. There are two isomers so two more entries have to be created:

(3*S*)-2,3-dimethylpentane 
Synonym: (*S*)-2,3-dimethylpentane
https://webbook.nist.gov/cgi/cbook.cgi?ID=7485-45-2
https://pubchem.ncbi.nlm.nih.gov/compound/22810194

(3*R*)-2,3-dimethylpentane 
Synonym: (*R*)-2,3-dimethylpentane
https://webbook.nist.gov/cgi/cbook.cgi?ID=54665-46-2
https://pubchem.ncbi.nlm.nih.gov/compound/638047

The diagram of (CHEBI:151115) corresponds to the (*S*) isomer, so should be corrected.

//

3-Ethylpentane (CHEBI:165737)

Synonyms:
triethylmethane; ethylpentane

Spanish: 3-etilpentano
French: 3-éthylpentane 
German: 3-Ethylpentan

Links:
https://en.wikipedia.org/wiki/3-Ethylpentane
https://webbook.nist.gov/cgi/cbook.cgi?ID=617-78-7

Literature references:
https://doi.org/10.1098/rspa.1971.0180
https://doi.org/10.1038/189224a0
https://doi.org/10.1371/journal.pntd.0007719
https://doi.org/10.1080/19476337.2018.1561519
https://doi.org/10.1006/jcht.1998.0414
https://doi.org/10.1002/chem.202001259
https://doi.org/10.1093/chemse/bjr094
https://doi.org/10.1021/ja01587a027

//

2,3,6,7-Tetramethyloctane (CHEBI:151050)

Literature references:
https://doi.org/10.3390/foods9060785
https://doi.org/10.1093/chromsci/bms012
http://doi.org/10.3390/en11030490
http://doi.org/10.1128/mBio.00235-15

//

2,3,4-Trimethyl-pentane (CHEBI:165735)

https://en.wikipedia.org/wiki/2,3,4-Trimethylpentane

Literature references:
https://doi.org/10.1007/bf02624137
https://doi.org/10.1016/0378-4274(87)90132-9
https://doi.org/10.1021/es049597z
https://doi.org/10.1023/a:1026594717754

//

Decane, 2,4,6-trimethyl- (CHEBI:151078)

Links:
https://webbook.nist.gov/cgi/cbook.cgi?ID=62108-27-4

Literature references:
https://doi.org/10.3390/molecules25071603
https://doi.org/10.1186/s40694-016-0025-7
https://doi.org/10.1096/fj.06-6927com
//

2,6,8-Trimethyldecane (CHEBI:88814)

Links:
https://webbook.nist.gov/cgi/cbook.cgi?ID=62108-26-3
http://www.pherobase.com/database/compound/compounds-detail-2me6me8me-10Hy.php

Literature references:
https://doi.org/10.1039/c4ra01422g
https://doi.org/10.1088/1752-7163/aaba84
https://doi.org/10.5073/JABFQ.2018.091.023
http://doi.org/10.1016/j.biocontrol.2010.08.009

PMID: 14631828 => http://www.besjournal.com/fileSWYXYHJKX/journal/article/swyxyhjkx/2003/3/PDF/bes200303005.pdf

//

3-Methylpentane (CHEBI:88373)
IUPAC name: 3-methylpentane

Links:
https://webbook.nist.gov/cgi/cbook.cgi?ID=96-14-0
https://chem.nlm.nih.gov/chemidplus/rn/startswith/96-14-0

//

2,9-Dimethyldecane (CHEBI:151058)

Links:
https://webbook.nist.gov/cgi/cbook.cgi?ID=1002-17-1

Literature references:
https://doi.org/10.1093/chromsci/bms012
https://doi.org/10.1039/c8gc03745k
https://doi.org/10.3390/medicina55060301

//

**Comment by amalik01** [comment]
All of these entries have now been checked.
