### ISSUE TITLE
Should guanosines, adenosines have the purine ribonucleoside parent?

### ISSUE THREAD

**Issue by ukemi** [ebi-chebi/ChEBI#4003]
guanosines (CHEBI:2448), adenosines (CHEBI:22260), inosines (CHEBI:24844) and xanthosines (CHEBI:48136) appear to be grouping classes for families of molecules, but are currently undefined and are subclasses of purine ribonucleoside (CHEBI:26399). Are they meant to cover molecules that contain a nucleoside moiety similar to the phenols (CHEBI:33853) class since they have subclasses like guanosine phosphate (CHEBI:24455)? Guanosine phosphate is a parent of nucleotides like GTP and GDP. THis doesn't allow for a clean separation of nucleosides from nucleotides. Would it be better to move guanosines (CHEBI:2448), adenosines (CHEBI:22260), inosines (CHEBI:24844) and xanthosines (CHEBI:48136) to be a subclass of nucleobase-containing molecular entity (CHEBI:61120)? This would allow for a cleaner distinction between nucleobases, nucleosides and nucleotides and nucleoside phosphates.

**Comment by amalik01** [comment]
Hi, Thanks for letting us know about this issue. These are classes which are meant to cover derivatives which lack phosphate groups. E.g. adenosines is a class which covers adenosine derivatives and therefore should not contain any phosphate groups. To solve this problem, i have now removed the 'guanosines' term from guanosine phosphate (CHEBI:24455) so now you should not see any structures with phosphate groups under this class.

**Comment by ukemi** [comment]
Thank you!
