### ISSUE TITLE
dodecene

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#4007]
Currently,

trans-2-dodecene (CHEBI:88609) is a acyclic olefin (CHEBI:33645)
(E)-3-Dodecene (CHEBI:88589) is a acyclic olefin (CHEBI:33645)
(Z)-3-Dodecene (CHEBI:88590) is a acyclic olefin (CHEBI:33645)

Better: create four new entries:
dodec-2-ene (corresponds to CAS 1652-96-6), (2*Z*)-dodec-2-ene (CAS 7206-26-0), dodec-3-ene (CAS 2030-83-3) and dodecene, so that

dodecene is a alkene (CHEBI:32878)

1-Dodecene (CHEBI:89713) is a dodecene 
dodec-2-ene is a dodecene 
trans-2-dodecene (CHEBI:88609) is a dodec-2-ene
(2*Z*)-dodec-2-ene is a dodec-2-ene

dodec-3-ene is a dodecene 
(E)-3-Dodecene (CHEBI:88589) is a dodec-3-ene
(Z)-3-Dodecene (CHEBI:88590) is a dodec-3-ene

1-Dodecene (CHEBI:89713) corresponds to CAS 112-41-4
trans-2-dodecene (CHEBI:88609) corresponds to CAS 7206-13-5
(E)-3-Dodecene (CHEBI:88589) corresponds to CAS 7206-14-6
(Z)-3-Dodecene (CHEBI:88590) corresponds to CAS 7239-23-8

**Comment by amalik01** [comment]
Now fixed. Thanks
