### ISSUE TITLE
1,2,3-butanetriol (CHEBI:131388) wrong ontology

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#4011]
Currently

1,2,3-butanetriol (CHEBI:131388) has functional parent butane (CHEBI:37808)

should be:

1,2,3-butanetriol (CHEBI:131388) has parent hydride butane (CHEBI:37808)

Please correct.

**Comment by amalik01** [comment]
Now corrected. Thanks
