### ISSUE TITLE
butanediol ontology - redundancy

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#4012]
(R)-butane-1,2-diol (CHEBI:52685) has parent hydride butane (CHEBI:37808)
(R)-butane-1,3-diol (CHEBI:52687) has parent hydride butane (CHEBI:37808)
(S)-butane-1,2-diol (CHEBI:52686) has parent hydride butane (CHEBI:37808)
(S)-butane-1,3-diol (CHEBI:52688) has parent hydride butane (CHEBI:37808)
butane-1,2-diol (CHEBI:52682) has parent hydride butane (CHEBI:37808)
butane-1,3-diol (CHEBI:52683) has parent hydride butane (CHEBI:37808)

All these relationships appear to be redundant since their ultimate is_a parent, butanediol (CHEBI:52684), already has butane as a parent hydride:

butanediol (CHEBI:52684) has parent hydride butane (CHEBI:37808)

**Comment by amalik01** [comment]
These relationships have been removed. Thanks
