### ISSUE TITLE
Methylcyclohexane (CHEBI:165745)

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#4013]
Please annotate Methylcyclohexane (CHEBI:165745) and maybe add the 3-D structure from PDBeChem:QTE

http://en.wikipedia.org/wiki/Methylcyclohexane
https://webbook.nist.gov/cgi/cbook.cgi?ID=108-87-2
https://www.ebi.ac.uk/pdbe-srv/pdbechem/chemicalCompound/show/QTE

Synonyms: cyclohexylmethane, hexahydrotoluene, toluene hexahydride

**Comment by amalik01** [comment]
Now checked.
