### ISSUE TITLE
Methylcyclopentane (CHEBI:88429)

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#4014]
Please annotate Methylcyclopentane (CHEBI:88429)

https://en.wikipedia.org/wiki/Methylcyclopentane
https://webbook.nist.gov/cgi/cbook.cgi?ID=96-37-7
https://chem.nlm.nih.gov/chemidplus/rn/96-37-7

Literature references:
PMID: 18105955
PMID: 24239891
PMID: 7251182

**Comment by amalik01** [comment]
Now checked.
