### ISSUE TITLE
Trihydroxycoprostanoic acid (CHEBI:89753) 

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#4015]
This relationship is wrong (since terpenes are hydrocarbons):

Trihydroxycoprostanoic acid (CHEBI:89753) is a triterpene (CHEBI:35191)

please correct to 

Trihydroxycoprostanoic acid (CHEBI:89753) is a cholestanoid (CHEBI:50401)

**Comment by amalik01** [comment]
Now corrected. Thanks
