### ISSUE TITLE
cholesterol-2,2,3,4,4,6-d6 (CHEBI:140435) ontology

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#4016]
cholesterol-2,2,3,4,4,6-d6 (CHEBI:140435) is just a deuterium-labelled cholesterol. Thus

cholesterol-2,2,3,4,4,6-d6 (CHEBI:140435) is a cholesterol (CHEBI:16113) 

Then this relationship is redundant (since cholesterol is a cholestanoid):

cholesterol-2,2,3,4,4,6-d6 (CHEBI:140435) is a cholestanoid (CHEBI:50401)

This relationship is wrong (since it is **not** 4,4-dimethylsteroid), please remove:

cholesterol-2,2,3,4,4,6-d6 (CHEBI:140435) is a 3β-hydroxy-4,4-dimethylsteroid (CHEBI:143563)

**Comment by amalik01** [comment]
Now fixed. Thanks
