### ISSUE TITLE
cycloalkane ontology

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#4017]
All these relationships are wrong since they don't satisfy the definition of cycloalkanea, that is, saturated monocyclic hydrocarbons. Please remove

(+)-4-Carene (CHEBI:89934) is a cycloalkane (CHEBI:23453)
1,1'-Ethylidenebis-cyclopentane (CHEBI:88607) is a cycloalkane (CHEBI:23453)
4-Hydroxycyclohexylcarboxylic acid (CHEBI:89341) is a cycloalkane (CHEBI:23453)
cis-4-Hydroxycyclohexylacetic acid (CHEBI:89344) is a cycloalkane (CHEBI:23453)
cycloalkane antibiotic (CHEBI:23452) is a cycloalkane (CHEBI:23453)
Ethyl cyclohexanecarboxylate (CHEBI:88965) is a cycloalkane (CHEBI:23453)
trans-4-Hydroxycyclohexylacetic acid (CHEBI:88508) is a cycloalkane (CHEBI:23453)
Isolongifolene, 4,5,9,10-dehydro- (CHEBI:89675) is a cycloalkane (CHEBI:23453)
Methyl cyclohexanecarboxylate (CHEBI:88845) is a cycloalkane (CHEBI:23453)

**Comment by amalik01** [comment]
I have now corrected the relationships for these.
