### ISSUE TITLE
NTR: 1,8-dihydroxynaphthalene-melanin

### ISSUE THREAD

**Issue by ValWood** [ebi-chebi/ChEBI#4021]
Dear Chebi,

Please could we have a term for
1,8-dihydroxynaphthalene-melanin to 
logically define this new GO term.

Many thanks,
val

+[Term]
+id: GO:0140614
+name: 1,8-dihydroxynaphthalene-melanin biosynthetic process
+namespace: biological_process
+def: "The chemical reactions and pathways resulting in the formation of dihydroxy naphthalene (DHN)-melanin." [PMID:12788746, PMID:23998343]
+synonym: "DHN-melanin biosynthesis" EXACT []
+is_a: GO:0019290 ! siderophore biosynthetic process
+property_value: term_tracker_item #20974 xsd:string
+created_by: pg
+creation_date: 2021-03-04T11:54:05Z

**Comment by amalik01** [comment]
A ChEBI entry has now been created (CHEBI:167605). The entry should be visible on the ChEBI website by tomorrow.
Since the structure of the fungal melanin is unknown, i therefore haven't added a chemical structure to this entry.

**Comment by ValWood** [comment]
Thanks, that was quick!
