### ISSUE TITLE
CHEBI:136580 misleading synonyms

### ISSUE THREAD

**Issue by ehatton** [ebi-chebi/ChEBI#4023]
Looking at the title and description for **CHEBI:136580 (LRH-1 antagonist)**, I think the word "agonist" should be changed to "antagonist" in the following synonyms:

- liver receptor homologue-1 agonist
- liver receptor homologue-1 agonists
- NR5A2 agonist
- NR5A2 agonists

thanks!

**Comment by amalik01** [comment]
Thanks for letting us know. This has now been corrected.
