### ISSUE TITLE
apholate ontology

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#4024]
apholate (CHEBI:33111) is a inorganic heterocyclic compound (CHEBI:33596)

The relationship above is wrong since apholate is an organic compound. However it is derived from an inorganic heterocyclic parent hydride, cyclotriphosphazene (1,3,5,2λ5,4λ5,6λ5-triazatriphosphinine). Could be nice to have it in ChEBI.

https://chem.nlm.nih.gov/chemidplus/rn/291-37-2
https://webbook.nist.gov/cgi/cbook.cgi?ID=291-37-2
http://www.chemspider.com/Chemical-Structure.107306.html
PubChem CID 120195

Also, apholate (CHEBI:33111) is a ring assembly (CHEBI:36820)

**Comment by amalik01** [comment]
Now corrected.

A new entry for cyclotriphosphazene has now been created (CHEBI:167642). Thanks
