### ISSUE TITLE
phthalic acid (CHEBI:29069) ontology

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#4026]
phthalic acid (CHEBI:29069) is conjugate acid of phthalate(1−) (CHEBI:30800)
this is correct.

phthalic acid (CHEBI:29069) is conjugate acid of phthalate (CHEBI:26092)
this is wrong. In general it is not clear what exactly phthalate (CHEBI:26092) is. 

If phthalate (CHEBI:26092) is a dicarboxylic acid dianion (CHEBI:28965)

then it really should have only one is a child:
phthalate(2−) (CHEBI:17563) is a phthalate (CHEBI:26092)

If we want it to include both phthalate(2−) (CHEBI:17563) and phthalate(1−) (CHEBI:30800), then it should be made an is a child of
carboxylic acid anion (CHEBI:29067)

These two relationships are wrong:
terephthalate(2−) (CHEBI:30043) is a phthalate (CHEBI:26092)
sodium-binding benzofuran isophthalate (CHEBI:52262) is a phthalate (CHEBI:26092)

I suppose there should be generic benzenedicarboxylate(1−) and benzenedicarboxylate(2−) entries. Cf. benzenedicarboxylic acid (CHEBI:26094)

**Comment by amalik01** [comment]
Now fixed. Thanks
