### ISSUE TITLE
benzenedicarboxylic acid (CHEBI:26094) ontology

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#4027]
These relationships are wrong:

2-hydroxyisophthalic acid (CHEBI:19643) is a benzenedicarboxylic acid (CHEBI:26094)
3,4-dihydroxyphthalic acid (CHEBI:17416) is a benzenedicarboxylic acid (CHEBI:26094)
4,5-dihydroxyisophthalic acid (CHEBI:141383) is a benzenedicarboxylic acid (CHEBI:26094)
4,5-dihydroxyphthalic acid (CHEBI:17199) is a benzenedicarboxylic acid (CHEBI:26094)
4-hydroxyphthalic acid (CHEBI:27600) is a benzenedicarboxylic acid (CHEBI:26094)

benzenedicarboxylic acid (CHEBI:26094) has formula C8H6O4 and has three isomers:

phthalic acid (CHEBI:29069) is a benzenedicarboxylic acid (CHEBI:26094)
isophthalic acid (CHEBI:30802) is a benzenedicarboxylic acid (CHEBI:26094)
terephthalic acid (CHEBI:15702) is a benzenedicarboxylic acid (CHEBI:26094)

The rest are their hydroxy derivatives.

**Comment by amalik01** [comment]
Now fixed. Thanks
