### ISSUE TITLE
1H-imidazole (CHEBI:16069) ontology

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#4030]
1*H*-imidazole (CHEBI:16069) **is a** mancude organic heteromonocyclic parent (CHEBI:35555) 

Please remove the relationship above; it is redundant because

1*H*-imidazole (CHEBI:16069) **is a** imidazole (CHEBI:14434)
imidazole (CHEBI:14434) **is a** mancude organic heteromonocyclic parent (CHEBI:35555)

**Comment by amalik01** [comment]
Now fixed. Thanks
