### ISSUE TITLE
thietane ontology

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#4033]
Please make
thietane (CHEBI:87565) **is a** saturated organic heteromonocyclic parent (CHEBI:36389)

Also you may want to add some literature references:

PMID: 3769053
PMID: 12298018
PMID: 12377049
PMID: 27659093
PMID: 28086263
PMID: 28350164
PMID: 29712165
PMID: 32647542

**Comment by amalik01** [comment]
Now added. Thanks
