### ISSUE TITLE
morpholine (CHEBI:34856) 

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#4034]
Please add cross-reference to PDBeChem 
https://www.ebi.ac.uk/pdbe-srv/pdbechem/chemicalCompound/show/6LR
and maybe a 3-D structure of 6LR

Also
https://en.wikipedia.org/wiki/Morpholine

Synonyms:
1-oxa-4-azacyclohexane
diethylenimide oxide
1,4-oxazinane
diethylene imidoxide
diethylene oximide
tetrahydro-p-oxazine

Some references:
PMID: 15017096
PMID: 2699898
PMID: 31978684
PMID: 31512284
PMID: 32017384

**Comment by amalik01** [comment]
now added. thanks
