### ISSUE TITLE
Definition of CHEBI:22860 (amino-acid betaine) conflicts with structure of subclasses

### ISSUE THREAD

**Issue by althonos** [ebi-chebi/ChEBI#4036]
Hi !

CHEBI:22860 is defined as:
> Any amino acid-derived zwitterion - such as glycine betaine (N,N,N-trimethylammonioacetate) - in which the ammonium nitrogen carries three methyl substituents.

However, several of its subclasses break this definition by not having 3 methyl substituents on the ammonium:

* CHEBI:35280 (L-proline betaine):
  ![chebi35280](https://www.ebi.ac.uk/chebi/displayImage.do?defaultImage=true&imageIndex=0&chebiId=35280)
* CHEBI:85534 (cis-4-hydroxy-D-proline betaine):
  ![chebi85534.png](https://www.ebi.ac.uk/chebi/displayImage.do?defaultImage=true&imageIndex=0&chebiId=85534)
* CHEBI:1556 (3-Hydroxystachydrine):
  ![chebi1556.png](https://www.ebi.ac.uk/chebi/displayImage.do?defaultImage=true&imageIndex=0&chebiId=1556)

I assume the definition should be something like:
> Any amino acid-derived zwitterion - such as glycine betaine (N,N,N-trimethylammonioacetate) - in which the hydrogen atoms of the ammonium group are replaced with methyl substituents.

**Comment by amalik01** [comment]
Thanks for letting us know. Definition now updated:
Any amino acid-derived zwitterion - such as glycine betaine (N,N,N-trimethylammonioacetate) - in which the ammonium nitrogen carries methyl substituents and bears no hydrogen atoms.
