### ISSUE TITLE
Confusion around CHEBI:537519 (L-aspartic acid 4-semialdehyde betaine) 

### ISSUE THREAD

**Issue by althonos** [ebi-chebi/ChEBI#4037]
Hi !

CHEBI:537519 (L-aspartic acid 4-semialdehyde betaine) is listed as an amino-acid betaine (CHEBI:22860) and has the following formula:
![formula.png](https://www.ebi.ac.uk/chebi/displayImage.do?defaultImage=true&imageIndex=0&chebiId=537519)

However, there are several problems here, because:
* the molecule corresponding to this formula is not a betaine, since the ammonium nitrogen is linked to hydrogen atoms
* this formula corresponds to the `L-aspartic acid 4-semialdehyde zwitterion`
* `L-aspartic acid 4-semialdehyde betaine` is not a tautomer of `L-aspartic acid 4-semialdehyde` (it has 3 extra methyl groups)

The right formula should be:
![formula](https://user-images.githubusercontent.com/8660647/112778945-f4415e80-9045-11eb-8094-6306e5bbda99.png)

# Proposed fix

* Fix existing term CHEBI:537519 (L-aspartic acid 4-semialdehyde betaine) with:
  - SMILES: `[H]C(=O)C[C@]([N+](C)(C)C)C([O-])=O`
  - remove: is tautomer of: L-aspartic 4-semialdehyde (CHEBI:18051) 

* Create a new term (L-aspartic acid 4-semialdehyde zwitterion) that:
  - has SMILES: `[H]C(=O)C[C@H]([NH3+])C([O-])=O`
  - is tautomer of: L-aspartic 4-semialdehyde (CHEBI:18051)

**Comment by amalik01** [comment]
Thanks for letting us know. The entry has now been fixed and the word 'betaine' has now been removed
