### ISSUE TITLE
piperidine (CHEBI:18049) 

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#4039]
Some literature refs:

PMID: 15412 
PMID: 799462
PMID: 5300194
PMID: 5308835
PMID: 15017096
PMID: 25897321 
http://doi.org/10.1007/BF01299681

**Comment by amalik01** [comment]
all of the above PMID's have now been added except the DOI since at the moment we are unable to add DOI links. thanks
