### ISSUE TITLE
dimethyl sulfoxide (CHEBI:28262) link + literature

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#4042]
Please correct (broken) link to Wikipedia
https://en.wikipedia.org/wiki/Dimethyl_sulfoxide

Also some more literature references
PMID: 4963226 
PMID: 29938311
PMID: 31489176
PMID: 28220525
PMID: 23050031 
PMID: 19443933 
PMID: 16522014 
PMID: 12663039
PMID: 11474739
PMID: 3510103
PMID: 3898376
PMID: 3916302
PMID: 6379027
PMID: 10298633
PMID: 6309056
PMID: 4556944
PMID: 4223708

**Comment by amalik01** [comment]
now added. Thanks
