### ISSUE TITLE
New terms for pH 7.3 charge states of 2-hydroxy-ATP and 2-hydroxy-AMP

### ISSUE THREAD

**Issue by deustp01** [ebi-chebi/ChEBI#4071]
Could we have new terms for  2-hydroxy-ATP(4−) and CHEBI:63212 - 2-hydroxy-AMP(2−) as conjugate bases of the existing terms CHEBI:65119 - 2-hydroxy-ATP (0 charge) and CHEBI:65129 - 2-hydroxy-AMP (0 charge), to correct the annotation of their interconversion at pH 7.3 for Reactome. (We're asking for these terms now because, to try to align better with Rhea, we are correcting our original reactions annotated with uncharged forms of these molecules to reflect their correct pH 7.3 charge states.)
Thanks.

**Comment by deustp01** [comment]
Now I see that these terms already exist, CHEBI:77897 - 2-hydroxy-dATP(4−) and CHEBI:63212 - 2-hydroxy-dAMP(2−), so if anything is missing it is only conjugate acid / base annotations to link them to CHEBI:65119 and CHEBI:65129, a much lower priority!
Apologies for the false alarm

**Comment by amalik01** [comment]
Hi,

I have created 2 new terms and these should be visible on the ChEBI website by tomorrow:
2-hydroxy-ATP(4-) - CHEBI:169970
2-Hydroxy-AMP(2-) - CHEBI:169971

**Comment by deustp01** [comment]
Thanks!
