### ISSUE TITLE
fulvalene (CHEBI:51994) 

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#4076]
Please correct the typo:
1,1'-bi[cylopentadienylidene] --> 1,1'-bi[cyclopentadienylidene]

In Wikipedia, [1,1′-bi(cyclopentylidene)]-2,2′,4,4′-tetraene is given as a PIN. I am not sure about that but it is worth adding as a synonym, together with bicyclopentyliden-2,4,2′,4′-tetraene and pentafulvalene:

https://en.wikipedia.org/wiki/Fulvalene

Plus some references:

PMID: 12055000
PMID: 11671506
PMID: 17711267
PMID: 25284044
PMID: 30113830
PMID: 21117649
PMID: 20812743

**Comment by amalik01** [comment]
now added. thanks
