### ISSUE TITLE
carboplatin (CHEBI:31355)

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#4078]
Please add PDBechem link + 3D structure: QPT
https://www.ebi.ac.uk/pdbe-srv/pdbechem/chemicalCompound/show/QPT

Synonyms:

carboplatine (French) 
carboplatino (Spanish)
carboplatinum (Latin)
carboplatina (Portuguese)

Patent:
DE-2329485-A1

References

PMID: 29632935
PMID: 26000441
PMID: 33324858
PMID: 28511060
PMID: 26239545
PMID: 25195879
PMID: 23396873
PMID: 32579504
PMID: 32487607
PMID: 32072678
PMID: 26893290
PMID: 26327386
PMID: 25195881
PMID: 24121332
PMID: 23275170
PMID: 23143236 
PMID: 22525758
PMID: 21629880
PMID: 17180231
PMID: 15896850
PMID: 31930743 
PMID: 17655933
PMID: 17497898
PMID: 16411667
PMID: 19774597
PMID: 9654475
PMID: 11666286
PMID: 14568240

**Comment by amalik01** [comment]
now added. thanks
