### ISSUE TITLE
lead diacetate (CHEBI:31767)

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#4079]
Please add link to NIST Webbook 
https://webbook.nist.gov/cgi/cbook.cgi?ID=301-04-2
and Wikipedia 
https://en.wikipedia.org/wiki/Lead(II)_acetate

Synonyms:

acetic acid, lead(2+) salt (NIST Webbook)
Goulard powder (NIST Webbook)
sugar of Saturn (NIST Webbook)

References:
PMID: 33498064
PMID: 1894216
PMID: 25052592 
PMID: 25303036
PMID: 27548299
PMID: 33140846 
PMID: 32218311 
PMID: 27411820
PMID: 21582051
PMID: 21582050 
PMID: 21588188
PMID: 33088349

**Comment by amalik01** [comment]
now added.
