### ISSUE TITLE
monoterpene ontology

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#4081]
These relationships are wrong (since terpenes are hydrocarbons and can't contain oxygen): 

Theaspirane (CHEBI:89598) is a monoterpene (CHEBI:35187)
p-Menthan-1-ol (CHEBI:89236) is a monoterpene (CHEBI:35187)
(1R,4R,5R,8S)-8-hydroxy-4,8-dimethyl-2-oxabicyclo[3.3.1]nonan-3-one (CHEBI:141296) is a monoterpene (CHEBI:35187)

Please classify them under monoterpenoid (CHEBI:25409).

**Comment by amalik01** [comment]
now fixed. thanks
