### ISSUE TITLE
Triethylenediamine (CHEBI:151129)

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#4082]
Please annotate Triethylenediamine (CHEBI:151129)

{The relationship 
Triethylenediamine (CHEBI:151129) **is a** N-alkylpiperazine (CHEBI:46845) 
is a bit dodgy; then N-alkylpiperazine (CHEBI:46845) as it stands now is a very poorly defined group. There are very few true N-alkylpiperazines, e.g. 1-Methylpiperazine (CHEBI:166561) 

Probably for a moment 
Triethylenediamine (CHEBI:151129) **is a** organic heterobicyclic compound (CHEBI:27171)
is a safer bet.}

Synonyms: 

DABCO
TEDA
N,N'-endo-ethylenepiperazine 
1,4-diazabicyclooctane

Links:
https://en.wikipedia.org/wiki/DABCO
https://webbook.nist.gov/cgi/cbook.cgi?ID=280-57-9
https://chem.nlm.nih.gov/chemidplus/rn/280-57-9

References
PMID: 22012624
PMID: 19384445
PMID: 11233211
PMID: 11670871
PMID: 11670695
PMID: 11300840
PMID: 12324702
PMID: 33750130 
PMID: 33351592
PMID: 33107528
PMID: 32987864 
PMID: 32243632
PMID: 32657310
PMID: 32441932
PMID: 32150305 
PMID: 31547646
PMID: 31328921
PMID: 31185070
PMID: 31150221
PMID: 30869877
PMID: 30288800
PMID: 30011358
PMID: 29683657 
PMID: 29517094
PMID: 29363694
PMID: 29048081
PMID: 29046863 
PMID: 27991779
PMID: 28252126
PMID: 28112329
PMID: 27982604
PMID: 27726277
PMID: 27375886 
PMID: 26594516 
PMID: 26422219
PMID: 26352613
PMID: 26093554
PMID: 25793444
PMID: 25545310
PMID: 23651877 
PMID: 23044537
PMID: 22903408
PMID: 20013775
PMID: 19360760
PMID: 18465896
PMID: 17441164
PMID: 16999409
PMID: 17147387
PMID: 16172686
PMID: 15861375
PMID: 15726168
PMID: 15074989

**Comment by amalik01** [comment]
now added. thanks
