### ISSUE TITLE
sodium-binding benzofuran isophthalate (CHEBI:52262) 

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#4085]
Please add the relationship:

sodium-binding benzofuran isophthalate (CHEBI:52262) **is a** crown compound (CHEBI:37409)

and a synonym:

4,4'-[1,4,10-trioxa-7,13-diazacyclopentadecane-7,13-diylbis(5-methoxy-1-benzofuran-6,2-diyl)]diisophthalic acid (source: ChemSpider:110415)

**Comment by amalik01** [comment]
now added.
