### ISSUE TITLE
please edit 1-star CHEBI:82960 - raltegravir

### ISSUE THREAD

**Issue by rwst** [ebi-chebi/ChEBI#4092]
Hello, the entry blocks submission of the same compound, so please advance to 3-star. Here is some information:

-synonym: MK-0518
- InChI: InChI=1S/C20H21FN6O5/c1-10-25-26-17(32-10)16(30)24-20(2,3)19-23-13(14(28)18(31)27(19)4)15(29)22-9-11-5-7-12(21)8-6-11/h5-8,28H,9H2,1-4H3,(H,22,29)(H,24,30)
- SMILES: CC1=NN=C(O1)C(=O)NC(C)(C)C2=NC(=C(C(=O)N2C)O)C(=O)NCC3=CC=C(C=C3)F
- Wikipedia: https://en.wikipedia.org/wiki/Raltegravir
- CAS: 518048-05-0
- DrugBank: https://go.drugbank.com/drugs/DB06817
- PDB Ligand: https://pdbe.org/chem/RLT
- PMID 24145879, 17133211

**Comment by amalik01** [comment]
Now checked.
