### ISSUE TITLE
substituted furans

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#4093]
Please annotate to the ChEBI standard the following furan derivatives.

(Could be nice to have the uniform orientation of the structural formulae, e.g. oxygen atom on the top, furan numbering clockwise as in 
<img src="https://www.ebi.ac.uk/chebi/displayImage.do?defaultImage=false&imageIndex=1&chebiId=35559&imageId=14943"> 
long alkyl substituents more or less horizontally to the right)

2-Methylfuran (CHEBI:88912) 
https://webbook.nist.gov/cgi/cbook.cgi?ID=534-22-5
https://chem.nlm.nih.gov/chemidplus/rn/534-22-5
//

2,4-Dimethylfuran (CHEBI:89526)
https://webbook.nist.gov/cgi/cbook.cgi?ID=3710-43-8
https://chem.nlm.nih.gov/chemidplus/rn/3710-43-8
//

2,5-Dimethylfuran (CHEBI:89052) 
https://webbook.nist.gov/cgi/cbook.cgi?ID=625-86-5
https://chem.nlm.nih.gov/chemidplus/rn/625-86-5
//

2-Ethyl-5-methylfuran (CHEBI:88617)
https://webbook.nist.gov/cgi/cbook.cgi?ID=1703-52-2
https://chem.nlm.nih.gov/chemidplus/rn/1703-52-2
//

2-Butylfuran (CHEBI:89750)
Synonym: 2-_n_-butylfuran
https://webbook.nist.gov/cgi/cbook.cgi?ID=4466-24-4
https://chem.nlm.nih.gov/chemidplus/rn/4466-24-4
//

2-Pentylfuran (CHEBI:89197)
Synonym: 2-_n_-pentylfuran
https://webbook.nist.gov/cgi/cbook.cgi?ID=3777-69-3
https://chem.nlm.nih.gov/chemidplus/rn/3777-69-3
//

2-Hexylfuran (CHEBI:171966) 
Synonym: 2-_n_-hexylfuran
https://webbook.nist.gov/cgi/cbook.cgi?ID=3777-70-6
//

2-Heptylfuran (CHEBI:167091)
Synonym: 2-_n_-heptylfuran
https://webbook.nist.gov/cgi/cbook.cgi?ID=3777-71-7
//

2-Decylfuran (CHEBI:168892)
Synonym: 2-_n_-decylfuran
https://webbook.nist.gov/cgi/cbook.cgi?ID=83469-85-6
//

2-Methyl-5-(methylthio)furan (CHEBI:89286)
https://webbook.nist.gov/cgi/cbook.cgi?ID=13678-59-6
https://chem.nlm.nih.gov/chemidplus/rn/13678-59-6
//

2-[(Ethylthio)methyl]furan (CHEBI:168930)
**Note:** "IUPAC name" is wrong! Should be: 2-[(ethylsulfanyl)methyl]furan
Synonym: (furfurylthio)ethane
https://webbook.nist.gov/cgi/cbook.cgi?ID=2024-70-6
//

2-methyl-5-propionylfuran (CHEBI:167764) 
**Note:** "IUPAC name" is wrong! Should be: 1-(5-methylfuran-2-yl)propan-1-one
Synonyms (from NIST Webbook):
5-methyl-2-propionylfuran
1-(5-methyl-2-furyl)propan-1-one
1-(5-methyl-2-furyl)-1-propanone
1-(5-methyl-2-furanyl)-1-propanone
https://webbook.nist.gov/cgi/cbook.cgi?ID=10599-69-6
//

3-Acetyl-2,5-dimethylfuran (CHEBI:167367)
**Note:** "IUPAC name" is wrong! Should be: 1-(2,5-dimethylfuran-3-yl)ethanone
Synonyms (from NIST Webbook):
1-(2,5-dimethyl-3-furyl)ethanone
1-(2,5-dimethyl-3-furyl)ethan-1-one
https://webbook.nist.gov/cgi/cbook.cgi?ID=10599-70-9
//

5-Methyl-2-furaldehyde (CHEBI:2091)
By some reason, the formula C6H6O2 is **repeated twice**
https://webbook.nist.gov/cgi/cbook.cgi?ID=620-02-0
https://chem.nlm.nih.gov/chemidplus/rn/620-02-0
//

5-Methylfuran-2-carboxylic acid (CHEBI:89918)
Synonym: 5-Methylpyromucic acid (ChemIDplus)
https://chem.nlm.nih.gov/chemidplus/rn/1917-15-3
https://www.ebi.ac.uk/pdbe-srv/pdbechem/chemicalCompound/show/2K1
//

3,3'-Dithiobis[2-methylfuran] (CHEBI:172109)
**Note:** "IUPAC name" is wrong! Should be: 
2-methyl-3-[(2-methylfuran-3-yl)disulfanyl]furan {simple substitutive nomenclature} or, better, 
3,3'-disulfanediylbis(2-methylfuran)  {multiplicative}
https://webbook.nist.gov/cgi/cbook.cgi?ID=28588-75-2
//

3,3'-Dithiobis[4,5-dihydro-2-methylfuran] (CHEBI:172469) 
**Note:** "IUPAC name" is wrong! Should be: 
5-methyl-4-[(5-methyl-2,3-dihydrofuran-4-yl)disulfanyl]-2,3-dihydrofuran {simple substitutive nomenclature} or, better, 
4,4'-disulfanediylbis(5-methyl-2,3-dihydrofuran)  {multiplicative}
//

**Comment by amalik01** [comment]
All of the above entries have now been annotated.
