### ISSUE TITLE
pyrene (CHEBI:39106) 

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#4101]
Please add PDBechem ref + 3D structure

https://www.ebi.ac.uk/pdbe-srv/pdbechem/PDBEntry/list/8P0

Literature references

PMID: 30705306
PMID: 33555637
PMID: 32361518
PMID: 32202393
PMID: 31894420
PMID: 31365239
PMID: 31267635
PMID: 31002512 
PMID: 30515937
PMID: 22423596
PMID: 22143550 
PMID: 20201423

**Comment by amalik01** [comment]
now added.
