### ISSUE TITLE
COMe Links are dead

### ISSUE THREAD

**Issue by cthoyt** [ebi-chebi/ChEBI#4102]
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:46442 has a manual xref to a database with prefix `COMe` and identifier `MOL000160`. This links to http://www.flymine.org/come/entry?gn=MOL000160, but this link is dead. It appears the website has been upgraded. However, I could neither find a page mentioning `MOL000160` nor `vanadate` in either the old nor new website.

**Comment by K-r-ll** [comment]
As far as I can see, now it is back: https://www.flymine.org/come/entry?gn=MOL000160

**Comment by cthoyt** [comment]
Huh. Glad to see that. Thanks for looking into it. More generally, it would improve ChEBI to have a more detailed list of what the resources are that it uses in its xrefs (COMe is quite cryptic, for exaple)

**Comment by amalik01** [comment]
Here is the link to the reference manual: 
https://docs.google.com/document/d/13_FqP_8qkDdw5RFv5qMYo7xRyfY4xUiuVtLn845A6Io/edit

It lists all the resources which ChEBI provides links to and also gives a brief intro to each resource.

**Comment by cthoyt** [comment]
That's great, thanks @amalik01
