### ISSUE TITLE
18F-fluciclovine vs fluciclovine 

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#4103]
Please annotate fluciclovine (18F) (CHEBI:134703). I suggest giving it ChEBI name "<sup>18</sup>F-fluciclovine" or "fluciclovine (<sup>18</sup>F)" 

Also, please make <sup>18</sup>F-fluciclovine **is a** <sup>18</sup>F radiopharmaceutical (CHEBI:49127)

CAS 222727-39-1
ChemSpider: 23313216
https://chem.nlm.nih.gov/chemidplus/rn/222727-39-1
https://en.wikipedia.org/wiki/Fluciclovine_(18F)
https://www.kegg.jp/entry/D10860

Patents:
US10967077B2
WO2014023775A1
EP2793954B1
GB2561122B
WO2011044410A2

Synonyms:
(1*r*,3*r*)-1-amino-3[<sup>18</sup>F]fluorocyclobutane-1-carboxylic acid
fluciclovine (<sup>18</sup>F) (English INN)
fluciclovine (<sup>18</sup>F) (French INN)
fluciclovina (<sup>18</sup>F) (Spanish INN)
fluciclovinum (<sup>18</sup>F) (Latin INN)
anti-1-amino-3-<sup>18</sup>F-flurocyclobutane-1-carboxylic acid 
anti-3[<sup>18</sup>F]FACBC
Axumin (brand name)

Literature references:
PMID: 28468238
PMID: 28656060
PMID: 31418054
PMID: 29523631
PMID: 28267449 
PMID: 27749412
PMID: 29359581
PMID: 30031468 
PMID: 29762238
PMID: 30456185 
PMID: 31059396 
PMID: 31358294
PMID: 31773466
PMID: 32396045
PMID: 32551903
PMID: 32771333 
PMID: 32701717 
PMID: 33206564 
PMID: 33668673
PMID: 33648662
PMID: 34012062 
PMID: 27199361 
PMID: 27511856
PMID: 27056619
PMID: 26940766
PMID: 23208700 
PMID: 24943499
//

<sup>18</sup>F-fluciclovine (CAS 222727-39-1) is a labelled variety of "simply" fluciclovine (CAS 222727-43-7). I suggest the new entity to be created for fluciclovine (CAS 222727-43-7) so that

<sup>18</sup>F-fluciclovine (CHEBI:134703) **is a** fluciclovine

Links:
https://chem.nlm.nih.gov/chemidplus/rn/222727-43-7
ChemSpider: 28487364

Literature reference that specifically mention unlabelled fluciclovine (as opposed to <sup>18</sup>F-fluciclovine):
PMID: 27754421

(other varieties of fluciclovine also exist, e.g. <sup>14</sup>C-fluciclovine; PMID: 26278491)

**Comment by amalik01** [comment]
All 3 entries have now been curated:
fluciclovine - CHEBI:176400
fluciclovine (14C) - CHEBI:176516
fluciclovine (18F) - CHEBI:134703


I did not add the following relationship suggested by you: 18F-fluciclovine (CHEBI:134703) is a fluciclovine. In the future we  plan to incorporate additional ontology relationships in ChEBI such as 'isotopologue of' which will capture the relationship between the different isotopes.
