### ISSUE TITLE
benzophenone (CHEBI:41308) 

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#4113]
Please add 3-D structure (from BZQ)

+ Literature references:

PMID: 10864504
PMID: 15373829
PMID: 32736220
PMID: 30720459
PMID: 26254646
PMID: 25788150
PMID: 23963450 
PMID: 26282042
PMID: 19655709
PMID: 19388040
PMID: 17955805
PMID: 16999485
PMID: 16853025
PMID: 16820853
PMID: 16212356
PMID: 15672204
PMID: 14673848
PMID: 10877357
PMID: 10728861
PMID: 24226914

**Comment by amalik01** [comment]
now added.
