### ISSUE TITLE
predominant charge states of dNTPs at pH 7.3

### ISSUE THREAD

**Issue by deustp01** [ebi-chebi/ChEBI#4116]
For all of aATP, dCTP, dGTP, dTTP, dUTP CHEBI annotates the 3- charge state as the predominant one at pH 7.3 - example, CHEBI:495505 - dATP(3−). But the (4-) form of all of these chemicals is actually the predominant one. The relevant entities and conjugate acid-base relationships already exist; as far as I can tell the only fix needed is the more the one sentence of description to the correct entry.
This also applies to the generic NTP terms nucleoside triphosphate(3−) (CHEBI:58104) is conjugate acid of nucleoside triphosphate(4−) (CHEBI:61557)
Thanks.

**Comment by amalik01** [comment]
The definition of these entries have now been fixed. Thanks
