### ISSUE TITLE
new term request - 2'-deoxyuridine 3'-monophosphate(2-)

### ISSUE THREAD

**Issue by deustp01** [ebi-chebi/ChEBI#4117]
2'-deoxyuridine 3'-monophosphate(2-) conjugate base of CHEBI:46322 - 2'-deoxyuridine 3'-monophosphate, following the pattern for CHEBI:17622 - dUMP and CHEBI:246422 - dUMP(2−)

**Comment by amalik01** [comment]
A ChEBI entry has now been created for 2'-deoxyuridine 3'-monophosphate(2−) = CHEBI:176905.
The entry will be visible on the ChEBI website by tomorrow.
