### ISSUE TITLE
quadriphenyl (CHEBI:52240)

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#4118]
The IUPAC name of this compound is most definitely *not* "Benzerythrene" but 1,1':4',1'':4'',1'''-quaterphenyl. Although according to the New Blue Book, the preferred IUPAC name (PIN) should be 1<sup>1</sup>,2<sup>1</sup>:2<sup>4</sup>,3<sup>1</sup>:3<sup>4</sup>,4<sup>1</sup>-quaterphenyl.

**Comment by amalik01** [comment]
IUPAC name has been updated. Thanks
