### ISSUE TITLE
aurasperone A (CHEBI:133760) 

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#4120]
Please provide the IUPAC name for aurasperone A (CHEBI:133760). 
I suppose it is 5,5′-dihydroxy-6,6′,8,8′-tetramethoxy-2,2′-dimethyl-4*H*,4'*H*-7,10′-bibenzo[*g*]chromene-4,4′-dione

**Comment by amalik01** [comment]
now added. thanks
