### ISSUE TITLE
tetrathiafulvalene (CHEBI:52444) 

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#4123]
Please add https://en.wikipedia.org/wiki/Tetrathiafulvalene

Wikipedia cites 2,2′-bi(1,3-dithiolylidene) as PIN but I think it should be 2,2′-bi(1,3-dithiol-2-ylidene)
In any case, 2,2′-bi(1,3-dithiolylidene) is worth adding as a synonym

Literature references:
PMID: 30202469
PMID: 30033473 
PMID: 27753290 
PMID: 26664595
PMID: 21409235
PMID: 34124487
PMID: 34096512
PMID: 34086402
PMID: 32412238
PMID: 32202393
PMID: 30900448
PMID: 32830772
PMID: 33071675
PMID: 29732107
PMID: 28661012
PMID: 27966932
PMID: 27918292
PMID: 24889657
PMID: 23146046
PMID: 23003988
PMID: 21766921
PMID: 26606492
PMID: 21586832
PMID: 21253644
PMID: 21231536
PMID: 20632757
PMID: 20564710
PMID: 19938006
PMID: 19205039
PMID: 19021186
PMID: 18479905
PMID: 17851437
PMID: 12714737
PMID: 11706258
PMID: 11317287
PMID: 17817430
PMID: 9946522
PMID: 9943328 
PMID: 9941139
PMID: 9940622

**Comment by amalik01** [comment]
now added. thanks
