### ISSUE TITLE
diacylglycerols incorrecty assigned as icosanoids

### ISSUE THREAD

**Issue by alanbridge** [ebi-chebi/ChEBI#4126]
Hi, 

the compounds listed below are children of icosanoid (https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:23899) 

DG(14:0/20:2(11Z,14Z)/0:0) (CHEBI:88796) is a icosanoid (CHEBI:23899)
DG(14:0/20:3(5Z,8Z,11Z)/0:0) (CHEBI:88794) is a icosanoid (CHEBI:23899)
DG(14:0/20:3(8Z,11Z,14Z)/0:0) (CHEBI:88805) is a icosanoid (CHEBI:23899)
DG(14:0/20:4(5Z,8Z,11Z,14Z)/0:0) (CHEBI:88804) is a icosanoid (CHEBI:23899)
DG(14:0/20:4(8Z,11Z,14Z,17Z)/0:0) (CHEBI:88803) is a icosanoid (CHEBI:23899)
DG(14:1(9Z)/20:2(11Z,14Z)/0:0) (CHEBI:88723) is a icosanoid (CHEBI:23899)
DG(14:1(9Z)/20:3(5Z,8Z,11Z)/0:0) (CHEBI:88724) is a icosanoid (CHEBI:23899)
DG(14:1(9Z)/20:3(8Z,11Z,14Z)/0:0) (CHEBI:88722) is a icosanoid (CHEBI:23899)
DG(15:0/0:0/20:4n6) (CHEBI:172117) is a icosanoid (CHEBI:23899)
DG(18:0/0:0/20:4n3) (CHEBI:171229) is a icosanoid (CHEBI:23899)
DG(18:0/0:0/20:4n6) (CHEBI:171234) is a icosanoid (CHEBI:23899)
DG(18:1n7/0:0/20:2n6) (CHEBI:171998) is a icosanoid (CHEBI:23899)
DG(18:1n7/0:0/20:3n6) (CHEBI:171226) is a icosanoid (CHEBI:23899)
DG(18:1n7/0:0/20:3n9) (CHEBI:171227) is a icosanoid (CHEBI:23899)
DG(18:1n9/0:0/20:2n6) (CHEBI:171999) is a icosanoid (CHEBI:23899)
DG(18:1n9/0:0/20:3n6) (CHEBI:171224) is a icosanoid (CHEBI:23899)
DG(18:1n9/0:0/20:3n9) (CHEBI:171225) is a icosanoid (CHEBI:23899)

However they don't match the definition of icosanoid 

_Any member of the group of signalling molecules arising from oxidation of the three C20 essential fatty acids (EFAs) icosapentaenoic acid (EPA), arachidonic acid (AA) and dihomo-gamma-linolenic acid (DGLA)._

and their relationship to it should be removed. They are actually diacylglycerols that contain a 20 carbon fatty acid, but that C20 fatty acid is not an icosanoid either.

Thanks and all the best, Alan

**Comment by amalik01** [comment]
Thanks for letting us know. These child classes have now been reassigned.
