### ISSUE TITLE
CHEBI:140757 - timnodonyl CoA (4-)

### ISSUE THREAD

**Issue by ANiknejad** [ebi-chebi/ChEBI#4129]
Hello @amalik01 

this compound is actually the same as CHEBI:73862, except for a non-canonical CoA.

CHEBI:28364 all-cis-5,8,11,14,17-icosapentaenoic acid
has synonym Timnodonic acid 

so I am wondering if you can remove (or correct and merge to CHEBI:73862) CHEBI:140757 - timnodonyl CoA (4-) ?
(also same question for CHEBI:140756 timnodonyl CoA, the third-party submission, versus the canonical CHEBI:63539 (5Z,8Z,11Z,14Z,17Z)-icosapentaenoyl-CoA )

Note that a rapid overview in the literature does not allow to understand if 'timnodonic' means only C20:5n-3 or if it involves a more detailed structure, but anyway chebi already reports "CHEBI:28364 all-cis-5,8,11,14,17-icosapentaenoic acid
has synonym Timnodonic acid "
and Lipidmaps does the same:
https://www.lipidmaps.org/databases/lmsd/LMFA01030759?LMID=LMFA01030759

(May I also do a comment? https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:73862 was recently updated (Last Modified -- 27 July 2021) and it is a pity that the issue with CHEBI:140757 was not detected at that time)

Thanks in advance, Adnan,

best regards,

Anne

**Comment by amalik01** [comment]
Hi Anne,

Thanks for letting us know. The two entries have now been merged. It was someone at SIB who recently updated ChEBI:73862 by adding a new ontology term. Its difficult to spot such errors when you have two different InChi Keys for the structures, you can only spot them if you compare the first part of the InChi key. The ChEBI curator tool only spots identical structures if there is an exact InChi Key match.
