### ISSUE TITLE
UCL 1684 (CHEBI:35040) 

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#4133]
Please annotate UCL 1684 (CHEBI:35040).
Synonym: UCL-1684

ChemSpider https://www.chemspider.com/Chemical-Structure.571070.html gives a very long and unwieldy ACD/IUPAC Name: 
17,24-diaza-1,9-diazoniaheptacyclo[23.6.2.2<sup>9,16</sup>.2<sup>19,22</sup>.1<sup>3,7</sup>.0<sup>10,15</sup>.0<sup>26,31</sup>]octatriaconta-1(32),3(38),4,6,9,11,13,15,19,21,25(33),26,28,30,34,36-hexadecaene.

The KEGG name has a comma wrongly placed. Should be:
6,10-diaza-3(1,3),8(1,4)-dibenzena-1,5(1,4)-diquinolinacyclodecaphane [this was the name given to it in the original publication, PMID: 9438015].

A better IUPAC name constructed according to the phane nomenclature recommendations (https://www.qmul.ac.uk/sbcs/iupac/phane/ and https://www.qmul.ac.uk/sbcs/iupac/phane2/) should be something like

1<sup>1</sup>λ<sup>5</sup>,5<sup>1</sup>λ<sup>5</sup>-6,10-diaza-3(1,3),8(1,4)-dibenzena-1,5(1,4)-diquinolinacyclodecaphane-1<sup>1</sup>,5<sup>1</sup>-bis(ylium)

Literature References

PMID: 9438015 
PMID: 12678783 
PMID: 15180477
PMID: 10096777
PMID: 33041794
PMID: 30694690
PMID: 29631373 
PMID: 26825543
PMID: 29330041
PMID: 28981145
PMID: 25652142 
PMID: 25421636
PMID: 25344384
PMID: 24703998
PMID: 24390175
PMID: 23488619 
PMID: 23685886
PMID: 23376397 
PMID: 23086994
PMID: 22331352
PMID: 22242975 
PMID: 21665944
PMID: 21297022
PMID: 20040579
PMID: 19820882 
PMID: 19766962 
PMID: 19645713 
PMID: 18783364
PMID: 18574459 
PMID: 17209000
PMID: 16186562 
PMID: 15655533 
PMID: 10742306
PMID: 10742299
PMID: 10696100
PMID: 10669569

**Comment by amalik01** [comment]
now annotated.
