### ISSUE TITLE
ChEBI REST API

### ISSUE THREAD

**Issue by anandijain** [ebi-chebi/ChEBI#4134]
Hello, thank you all for your efforts on ChEBI.

I see that there are client libraries in Python, Java, and Matlab, as well as the web services examples in Perl, however I don't see any REST API to query for XML/JSON via `curl` commands.

I am interested in this functionality so that I can build a client library for the Julia language. 
I have done this with other EBI services like [BioModels](https://www.ebi.ac.uk/biomodels/docs/).

Is this functionality planned or possible? If it is, I'd greatly appreciate making the schema OpenAPI compliant (like BioModels is). 

If it isn't possible, I am wondering how I should best query the data without downloading anything in bulk. 

Thanks again!

**Comment by amalik01** [comment]
Hi,

We are in the process of building a new REST API (this work is part of a recent grant we just received and will be completed within the next 3 years). Unfortunately for the time being, there is no other option available apart from downloading the files (https://www.ebi.ac.uk/chebi/downloadsForward.do) or using the SOAP web services (https://www.ebi.ac.uk/chebi/webServices.do).
