### ISSUE TITLE
for a consistent synonym list in CHEBI:53604 and CHEBI:87075

### ISSUE THREAD

**Issue by ANiknejad** [ebi-chebi/ChEBI#4135]
Hello Chebi Team,

the UniProt names of both are consistent:

CHEBI:53604  N-acetyl-α-D-galactosaminyl-L-serine residue

CHEBI:87075  N-acetyl-α-D-galactosaminyl-L-threonine residue

but in CHEBI:53604,  there is this information about the synonym 'Tn antigen'

> Tn antigen
> Note: (2016-04-13) L-Threonine may replace L-serine in the structure of Tn antigen.

I guess, it would be useful to have consistent information into CHEBI:87075

Thank you,
Best regards,

Anne

**Comment by amalik01** [comment]
now done.
