### ISSUE TITLE
update CHEBI:45490

### ISSUE THREAD

**Issue by rwst** [ebi-chebi/ChEBI#4137]
Please update CHEBI:45490 with 

- "ribavirin monophosphate" | name
- "metabolite of antiviral drug ribavirin" | definition
- HMDB0257208 | HMDB accession 
- 280136 | PubMed citation 
- 1939181 | PubMed citation
- 2159925 | PubMed citation
- 15917509 | PubMed citation

Thanks,

**Comment by amalik01** [comment]
Now annotated.
