### ISSUE TITLE
update CHEBI:45578

### ISSUE THREAD

**Issue by rwst** [ebi-chebi/ChEBI#4138]
Please update CHEBI:45578 with

- "ribavirin triphosphate" | name
- "active metabolite of antiviral drug ribavirin" | definition
- HMDB0257207 | HMDB accession
- 280136 | PubMed citation 
- 1939181 | PubMed citation
- 2159925 | PubMed citation
- 12606760 | PubMed citation
- 15917509 | PubMed citation

Thanks,

**Comment by amalik01** [comment]
Now annotated.
