### ISSUE TITLE
Please merge CHEBI:61679 and CHEBI:176809

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#4139]
Hi Adnan,

The two above compounds, (-)-endo-alpha-bergamotene and cis-alpha-bergamotene are identical, also at InChIKey level so please merge them.

Cheers,
Kristian

**Comment by amalik01** [comment]
I have not merged these entries since they are the absolute and relative configurations of bergamotene. I have instead fixed the ontology relationship and removed the structure of CHEBI:176809 to prevent confusion.
