### ISSUE TITLE
CHEBI:73255 error in structure

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#4141]
Hi Adnan,

There is an error in the structure of gibberellin A9(1-). The methyl group opposite of the bridge should be flat as it is in the conjugate acid CHEBI:29605. Note that this change changes the stereoconformation of the C to which the methyl group is attached from (S) to (R), so please also check the names.

I have attached the correct structure.
[CHEBI_73255.txt](https://github.com/ebi-chebi/ChEBI/files/7278011/CHEBI_73255.txt)

Cheers,
Kristian

**Comment by amalik01** [comment]
now checked.
