### ISSUE TITLE
NTR: terpenoid phytoalexins

### ISSUE THREAD

**Issue by cmungall** [ebi-chebi/ChEBI#4142]
A terpenoid that has the the role of a phytoalexins

OWL definition: terpenoid (http://purl.obolibrary.org/obo/CHEBI_26873) and has-role some phytoalexin (http://purl.obolibrary.org/obo/CHEBI_26115)

Examples:

 - capsidiol 3-acetate (not in CHEBI), a sesquiterpenoid phytoalexin https://www.nature.com/articles/srep09682

**Comment by amalik01** [comment]
A ChEBI term has now been created for terpenoid phytoalexin (CHEBI:180906).
