### ISSUE TITLE
CAS number for (E)-Dacarbazine (CHEBI:177836) incorrect 

### ISSUE THREAD

**Issue by gedeck** [ebi-chebi/ChEBI#4149]
Entry:  https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:177836

The CAS Registry number is reported as: 3/4/4342
The actual number is: 4342-03-4
The source for this information (ChemIDplus) reports the correct number: https://chem.nlm.nih.gov/chemidplus/name/dacarbazine

It looks as if the number 4342-03-4 was interpreted as a date (YYYY-MM-DD) and converted to (M/D/YYYY)

**Comment by amalik01** [comment]
Thanks for letting us know. This has now been fixed and the CAS number has now been removed from CHEBI:177836. This entry is for the E-configuration of dacarbazine and i am not able to find the CAS number for this configuration.

Just wanted to let you know that the CAS number 4342-03-4 belongs to CHEBI:4305 (this is the unspecified entry for dacarbazine where the stereochemistry of the double bond is not specified) 

see https://commonchemistry.cas.org/detail?cas_rn=4342-03-4&search=4342-03-4
