### ISSUE TITLE
wrong name for CHEBI:179632?

### ISSUE THREAD

**Issue by deustp01** [ebi-chebi/ChEBI#4163]
CHEBI:179632 is named 2,8-Dihydroxyadenine but it appears to have have oxo groups, not hydroxy ones – see CHEBI:134104 - 8-oxoadenine. If this is right, can the name be changed, please, to match the structure? Or do I not understand naming conventions here? I see that PubChem "2,8-dihydroxyadenine" [https://pubchem.ncbi.nlm.nih.gov/compound/92268] likewise has what look to me like oxo groups.

**Comment by deustp01** [comment]
@amalik01 @kaxelsen I am remembering a previous discussion of predominant forms of nucleotides:

From A Morgat e-mail 5/12/21:
After discussion with Adnan (the ChEBI curator), it seems that the predominant form of oxidised nucleotides is the keto form and not the enol one. Consequently I have updated RHEA:67392 (structures update) and RHEA:31583 (names update).

But I am also tripping over my own very limiteds knowledge of the relevant chemistry and nomenclature so this is basically a request for advice and a sanity check.
Thanks

**Comment by amalik01** [comment]
yes, you're right that the name does not match the structure shown. The entry was submitted to ChEBI via a bulk submissions process from MetaboLights. Therefore its a 2-star entry which still needs to be annotated and checked. Our curator tool is not functioning today so i will try to fix the entry as soon as the curator tool is up and running.

**Comment by deustp01** [comment]
Thanks. As to timing, we will actually need this patch when a new reaction I'm now creating gets released in three months. Until then, as long as I know I'm using the right ChEBI entry, no problem.

**Comment by amalik01** [comment]
Entry has now been fixed.
