### ISSUE TITLE
CHEBI:156223, ambiguity of structure

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#4173]
Hi Adnan,

I have just created a reaction with this compound based on the name only, and I have discovered that in some databases the structure is different, including cross-references already in the ChEBI entry.
MetaCyc CPD-13861 and FoodDB FDB005720 present a different structure 

I also found pmid:27038475 that supports the current structure.

I hope you can find out which structure is correct and remove the cross references to the resources showing the wrong strucure.

Cheers,
Kristian

**Comment by amalik01** [comment]
Just wanted to let you know that the structure in ChEBI seems correct. The structure has been revised several times in the past according to this article (http://actachemscand.org/doi/10.3891/acta.chem.scand.24-1618).

MetaCyc and FoodDB are using an older structure which was subsequently revised. You will need to contact them directly to get this changed.

**Comment by kaxelsen** [comment]
Thank you for info. I will contact MetaCyc and maybe FoodDB to get the structure updated.

**Comment by amalik01** [comment]
now checked.
