### ISSUE TITLE
Add synonym to CHEBI:582124 (myriocin)

### ISSUE THREAD

**Issue by robnash** [ebi-chebi/ChEBI#4175]
Please add the synonym ISP-1 to the term myriocin (CHEBI:582124). Currently there is a synonym ISP-I but it is also known as ISP-1:

https://en.wikipedia.org/wiki/Myriocin
https://www.yeastgenome.org/reference/S000076247
https://www.yeastgenome.org/reference/S000081062

Thanks,
Rob

**Comment by amalik01** [comment]
Now added. Thanks
