### ISSUE TITLE
Hierarchy of pesticides

### ISSUE THREAD

**Issue by laurenechan** [ebi-chebi/ChEBI#4177]
Hello,
ECTO was wondering if there are any grouping classes available for pesticides and other agricultural chemicals. We were looking in for terms like 'urea-based herbicide' and 'organophorphorus herbicide' and saw general classes like phenylureas (CHEBI:134043), but not coordinated with the role of herbicide. 
Are these types of terms feasible in ChEBI's existing hierarchy if we were to do term requests or are there perhaps grouping classes that we have just missed? 
Thank you!

**Comment by amalik01** [comment]
Hi Lauren,

The above 2 classes are not in ChEBI. You can create these classes via ChEBI's submission tool and i can then populate them with the relevant chemicals. We have a limited number of these classes already in ChEBI E.g. phenoxy herbicide (CHEBI:60575). At the moment we are very limited in terms of curation resources and most of the terms submitted to ChEBI these days are submitted by our user community. Ideally we would like the arrange the pesticide hierarchy in ChEBI in a similar way to the Alan Woods Pesticides database (https://pesticidecompendium.bcpc.org/class_herbicides.html). Please feel free to submit new classes to ChEBI if you require them.

**Comment by laurenechan** [comment]
Thank you so much, I've just requested our necessary terms for this issue on the submission tool.
