### ISSUE TITLE
Wrong ontological links

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#4179]
Hi Adnan,

I have noticed that 
aglaiabbreviatin F (CHEBI:70267)
crispolide (CHEBI:73231) 
wybutoxosine  (CHEBI:64330)
all have the relationship: is a hydroperoxide (CHEBI:35923) 
It should in stead be: is a peroxol (CHEBI:35924)

Cheers,
Kristian

**Comment by amalik01** [comment]
now fixed. thanks
