### ISSUE TITLE
CHEBI:3252 missing synonym name

### ISSUE THREAD

**Issue by althonos** [ebi-chebi/ChEBI#4180]
Hi!

[CHEBI:3252](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:3252) (C-1027) has a synonym human-friendly name (**lidamycin**) and even a Wikipedia page: https://en.wikipedia.org/wiki/C-1027

It is also missing several roles:
- antineoplastic agent (CHEBI:35610)
- mutagen (CHEBI:25435)
- bacterial metabolite (CHEBI:76969)

and several subclasses:
- enediyne (CHEBI:53272)
- benzoxazine (CHEBI:46969)
- monochlorobenzenes (CHEBI:83403)

**Comment by amalik01** [comment]
This entry has now been checked. Thanks
