### ISSUE TITLE
Some ontology relations can be improved

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#4181]
Hi,
I was checking some ontology relations for hydroperoxy polyunsaturated fatty acid anion (CHEBI:134019) and noticed several entities have relations:
is_a CHEBI:134019 and 
is_a CHEBI:64012
As CHEBI:134019 is_a CHEBI:64012, I think having both relations is redundant. Can you check and delete the relation is_a CHEBI:64012 when redundant?
Some examples:
CHEBI:131564
CHEBI:133558
CHEBI:59720
Other examples where relations are redundant:
CHEBI:133991
CHEBI:133900
CHEBI:133796
CHEBI:133798
CHEBI:133799
CHEBI:140279
CHEBI:140291

**Comment by amalik01** [comment]
Now done. If you encounter anymore, then please do let me know.
