### ISSUE TITLE
CHEBI:35895 - tetraphosphorus

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#4187]
Please add synonyms:

yellow phosphorus (ChemIDplus)
tricyclo[1.1.0.0<sup>2,4</sup>]tetraphosphane {von Baeyer name; see http://www.chemspider.com/Chemical-Structure.109894.html }
tetraphosphy-[04.0<sup>1,3</sup>0<sup>2,4</sup>]tricycle {as in http://doi.org/10.1351/pac199769081659 Fluck, E.O. and Laitinen, R.S. (1997) Nomenclature of inorganic chains and ring compounds (IUPAC Recommendations 1997). _Pure and Applied Chemistry_ **69**, 1659—1692.}
Tetraphosphor (German)
weißer Phosphor (German)
gelber Phosphor (German)
fósforo blanco (Spanish)
fósforo amarillo (Spanish)
tetrafósforo (Spanish)
phosphore blanc (French)
phosphore jaune (French)
tétraphosphore (French)

Literature references:
PMID: 30883971
PMID: 28861275
PMID: 16284670 
PMID: 16673028 
PMID: 32607432
PMID: 33135828
PMID: 33155395
PMID: 28520181
PMID: 22175455
PMID: 22847949
PMID: 25250790
PMID: 29712122
PMID: 19937871
PMID: 12836650
PMID: 18568890
PMID: 19166369
PMID: 15507746
PMID: 11855718
PMID: 20704355
PMID: 21894967
PMID: 27900815
PMID: 28638766
PMID: 26750104

Links:
https://en.wikipedia.org/wiki/Allotropes_of_phosphorus#White_phosphorus
http://www.chemspider.com/Chemical-Structure.109894.html 
https://gestis.dguv.de/data?name=003940

**Comment by amalik01** [comment]
now added. Thanks
