### ISSUE TITLE
CHEBI:37756 - disulfur dinitride

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#4190]
Please add the IUPAC name: 
1λ<sup>4</sup>,3,2,4-dithiadiazete

Please correct a typo in the definition:
N<sub>2</sub>S<sup>2</sup> &rightarrow;  N<sub>2</sub>S<sub>2</sub>

Literature references:
PMID: 31606098
PMID: 25042435
PMID: 25224358
PMID: 11669730
PMID: 30270473
PMID: 21736381
PMID: 16699212

Link: http://www.chemspider.com/Chemical-Structure.124561.html

**Comment by amalik01** [comment]
now added.
