### ISSUE TITLE
dinitrogen tetraoxide (CHEBI:29803) 

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#4193]
Synonyms:

NTO
tetraóxido de dinitrógeno {Spanish}
peroxyde d'azote  {French}
tétraoxyde de diazote {French}

Please add links:

https://en.wikipedia.org/wiki/Dinitrogen_tetroxide
https://www.chemspider.com/Chemical-Structure.23681.html

Literature references:

PMID: 5856526
PMID: 11817931
PMID: 25873662
PMID: 20950004
PMID: 16863145
PMID: 24513304
PMID: 22780428
PMID: 17388577
PMID: 18085811
PMID: 21412525
PMID: 18613660
PMID: 1985394
PMID: 19023069
PMID: 18825290
PMID: 18688517
PMID: 26288049
PMID: 31758160
PMID: 33201710
PMID: 22506560
PMID: 12112710 
PMID: 31111128
PMID: 18533630
PMID: 19388651
PMID: 17569526
PMID: 19767687
PMID: 31887495
PMID: 16483209
PMID: 15053616
PMID: 29891889
PMID: 19708385
PMID: 17854162
PMID: 21585211
PMID: 15268035
PMID: 23085517
PMID: 15267919
PMID: 10001114 
PMID: 12617667
PMID: 17979338
PMID: 32548487 
PMID: 22553554
PMID: 25207524
PMID: 18962905
PMID: 18964108
PMID: 31370230
PMID: 32939522
PMID: 32242551
PMID: 33903859
PMID: 28304020
PMID: 34278120 
PMID: 27668965
PMID: 29719688
PMID: 23237534
PMID: 32320956
PMID: 21341847
PMID: 33708398 
PMID: 14587736
PMID: 9563423
PMID: 26214064
PMID: 16523718 
PMID: 24090349
PMID: 8951244
PMID: 18052437
PMID: 33264012
PMID: 1132385
PMID: 24671439
PMID: 28451375
PMID: 32196290 
PMID: 9466958
PMID: 25909266
PMID: 2494000
PMID: 9801772
PMID: 24671412
PMID: 22940484
PMID: 18064540
PMID: 16509726
PMID: 14620812
PMID: 21280788
PMID: 17571880
PMID: 19759441
PMID: 3046492
PMID: 11461922
PMID: 25139130
PMID: 28390374
PMID: 20843046
PMID: 15674979
PMID: 10641724
PMID: 21993907
PMID: 7690141 
PMID: 19610649
PMID: 18438768
PMID: 18578482
PMID: 16834250
PMID: 10775331
PMID: 28274
PMID: 11695611
PMID: 12586166
PMID: 25647299
PMID: 15986682
PMID: 29999045
PMID: 17441137
PMID: 16852590
PMID: 7228269
PMID: 23215483
PMID: 21322688
PMID: 19691326
PMID: 26140681
PMID: 19181567 
PMID: 16853027
PMID: 1040
PMID: 11975550
PMID: 17579740
PMID: 15853326
PMID: 20024994
PMID: 6620424
PMID: 14535647
PMID: 17176154
PMID: 19045198
PMID: 15165328
PMID: 7141521
PMID: 14264838
PMID: 1865766
PMID: 18964496

**Comment by amalik01** [comment]
now added. thanks
