### ISSUE TITLE
CHEBI:28202, Please update structure

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#4195]
Hi Adnan,

The structure of CHEBI:28202, [hydroxy(phenyl)methyl]succinyl-CoA should be (R,S) as the KEGG compound C09819 and the conjugated base CHEBI:189059 (that I just submitted) are.

The information is from pmid:34601806.

Cheers,
Kristian

**Comment by amalik01** [comment]
Hi,
I have created a separate entry for the conjugate acid (CHEBI:1890777) and moved the KEGG X-ref to this entry.
The original entry (CHEBI:28202) is kept as unspecified since the name 'hydroxy(phenyl)methyl]succinyl' does not specify the configuration of the hydroxy and carboxy groups.
