### ISSUE TITLE
Silanol, trimethyl-, phosphate (3:1) (CHEBI:144345)

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#4197]
Please annotate CHEBI:144345

Ontology-wise: CHEBI:144345 **is a** organosilicon compound (CHEBI:25713)

I suggest ChEBI name "tris(trimethylsilyl) phosphate", making the current name a synonym {NIST Webbook}

Synonyms:
TTSP
phosphoric acid, tris(trimethylsilyl) ester {NIST Webbook}
silanol, 1,1,1-trimethyl-, 1,1',1''-phosphate {chemidplus}
tris(trimethylsilyl) ester of phosphoric acid 

CAS 10497-05-9
Beilstein Registry Number 1794624

Links:
https://chem.nlm.nih.gov/chemidplus/rn/10497-05-9
https://webbook.nist.gov/cgi/cbook.cgi?ID=10497-05-9
https://www.chemspider.com/Chemical-Structure.23649.html

Literature references:
PMID: 5804735
PMID: 31575985
PMID: 31382348
PMID: 29812899
PMID: 33945248
PMID: 7435965
PMID: 12470090
PMID: 4833132 

Also, can it be redrawn in a slightly more legible fashion, e.g.
![CHEBI144345](https://user-images.githubusercontent.com/66882875/149641998-f6ee45ba-a756-4d2d-8447-70792c562fcf.png)

  MJ211400                      

 17 16  0  0  0  0  0  0  0  0999 V2000
    0.5855    0.0966    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.2394    0.0966    0.0000 P   0  0  0  0  0  0  0  0  0  0  0  0
    0.9980   -0.6177    0.0000 Si  0  0  0  0  0  0  0  0  0  0  0  0
   -1.0644    0.0966    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.4750    1.3341    0.0000 Si  0  0  0  0  0  0  0  0  0  0  0  0
    0.5855   -1.3322    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.8230   -0.6177    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.9919   -1.2852    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.3019   -0.6177    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.2394   -0.7283    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.2394    0.9216    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.4750    2.1591    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.4769   -0.6177    0.0000 Si  0  0  0  0  0  0  0  0  0  0  0  0
   -1.8124   -1.3714    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.4105   -1.3322    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.1894    0.9216    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.1894    1.7466    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  1  3  1  0  0  0  0
  2  4  1  0  0  0  0
  3  6  1  0  0  0  0
  3  7  1  0  0  0  0
  2 10  2  0  0  0  0
  2 11  1  0  0  0  0
 11  5  1  0  0  0  0
  5 12  1  0  0  0  0
  4 13  1  0  0  0  0
 13  8  1  0  0  0  0
 13  9  1  0  0  0  0
 13 14  1  0  0  0  0
  3 15  1  0  0  0  0
  5 16  1  0  0  0  0
  5 17  1  0  0  0  0
M  END

**Comment by amalik01** [comment]
now done. thanks
