### ISSUE TITLE
Thiocarbamic acid (CHEBI:88830) 

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#4198]
Please annotate Thiocarbamic acid (CHEBI:88830) 

IUPAC name: carbamodithioic acid (which I think should be also the ChEBI name)

Synonym
dithiocarbamic acid {ChemSpider} 

CAS 594-07-0

Links
https://chem.nlm.nih.gov/chemidplus/rn/594-07-0
http://www.chemspider.com/Chemical-Structure.2273122.html

Refs
PMID: 16561648
PMID: 18123418
PMID: 26706422
PMID: 34223728
PMID: 31247364
PMID: 3011529

**Comment by amalik01** [comment]
now done.
