### ISSUE TITLE
NTR: Sodium orthovanadate

### ISSUE THREAD

**Issue by ValWood** [ebi-chebi/ChEBI#4200]
HI,
I would like a new term "Sodium orthovanadate"
https://en.wikipedia.org/wiki/Sodium_orthovanadate
to build phenotype sensitivity term

Thanks
Val

**Comment by amalik01** [comment]
Hi,

We already have a ChEBI entry for this chemical (CHEBI:35607, https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:35607).

**Comment by ValWood** [comment]
thanks!
