### ISSUE TITLE
New term request: DHS-1P dihydrosphingosine-1 phosphate  

### ISSUE THREAD

**Issue by ValWood** [ebi-chebi/ChEBI#4202]
DHS-1P 
dihydrosphingosine-1 phosphate  

as per https://www.pombase.org/reference/PMID:35008733
The Ceramide Synthase Subunit Lac1 Regulates Cell Growth
and Size in Fission Yeast
Ignacio Flor-Parra et al

**Comment by amalik01** [comment]
Hi,

A ChEBI entry already exists for this chemical (CHEBI:16893).

**Comment by ValWood** [comment]
OK thanks. It's odd that I am not locating these in searches. Are exact synonyms not searchable?

**Comment by amalik01** [comment]
Hi,

The synonym DHS-1P was not present in ChEBI before so i have added this today. Sometimes there are hundreds of similar synonyms in the database so when you search for a name, the result may appear further down the list. If you are unable to find an exact match, try to remove spaces and hyphens in the name. Try searching for dihydrosphingosine1phosphate in ChEBI, it will lead you to a single entry and then try searching for dihydrosphingosine-1 phosphate, this will find several entries.

**Comment by ValWood** [comment]
Thanks for the search tips. Very useful!
