### ISSUE TITLE
CHEBI:60167, Error in name or structure

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#4205]
Hi Adnan,

The name of this compound is 
alpha-D-Gal-(1->6)-alpha-D-Gal-(1->6)-beta-D-Glc-(1<->2)-Fru
but the structure shows
beta-D-Gal-(1->6)-beta-D-Gal-(1->6)-beta-D-Glc-(1<->2)-Fru

Cheers,
Kristian

**Comment by amalik01** [comment]
I have kept the name and fixed the structure.
