### ISSUE TITLE
CHEBI:57937/CHEBI:16886 2-aminomuconic acid and synonyms

### ISSUE THREAD

**Issue by ANiknejad** [ebi-chebi/ChEBI#4206]
Hello,

I had a discussion with Matthew Conroy from LipidMaps about the potential identity between LMFA01170082
https://www.lipidmaps.org/databases/lmsd/LMFA01170082

and CHEBI:57937/CHEBI:16886

because the LipidMaps structure is a (**2E,4Z**)-2-ammoniohexa-2,4-dienedioate
while the corresponding compound CHEBI:57937 is described as (**2Z,4E**)-2-ammoniohexa-2,4-dienedioate by the IUPAC
and CHEBI:16886 has a more 'neutral' name, IUPAC name 2-aminohexa-2,4-dienedioic acid.

Matthew did investigate the literature and here his comments:

What do you think ? any reason to remove the precise IUPAC ' (**2Z,4E**)-2-ammoniohexa-2,4-dienedioate' from CHEBI:57937 ? and/or to the 2E,4Z forms? thank you for your help and sorry in advance if I misunderstood something here:

>  Hi Anne,
>      Assuming this is a tryptophan catabolic product, I think 2E,4Z is correct given the diagrams in these papers which would agree with the geometry of the broken ring.
> https://www.sciencedirect.com/science/article/pii/S0021925817452380?via%3Dihub
> 
> https://link.springer.com/article/10.1007%2Fs002030050624
> 
> Then again
> This paper(https://www.jbc.org/article/S0021-9258(20)39945-2/fulltext) shows 2Z,4E, but as an oxidation product of the semialdehyde which is 2E,4E- even though the reaction does not involve the 2 position.
> 
> This other paper: https://journals.asm.org/doi/10.1128/JB.187.22.7866-7869.2005 gives both semialdehyde and acid as Z,E.
> 
> All four papers are describing the same reaction!
...
> 
> The link from ChEBI to SureCHEMBL shows a compound with neither geometry defined.
> https://www.surechembl.org/chemical/SCHEMBL28815

**Comment by amalik01** [comment]
Hi Anne,

If you look at the structure of muconic acid in ChEBI (CHEBI:38407), the double bond stereochemistry is unspecified. What i can do is change the current structure of 2-aminomuconic acid to an unspecified structure and then create separate entries for the 2E,4Z and 2Z, 4E isomers. What do you think?

**Comment by ANiknejad** [comment]
hello Adnan,

yes good idea, thank you!

**Comment by amalik01** [comment]
These entries have now been fixed.
2-aminomuconic acid - CHEBI:16886
(2E,4Z)-2-aminomuconic acid - CHEBI:189689
(2Z,4E)-2-aminomuconic acid - CHEBI:189697
