### ISSUE TITLE
two records with the same InChIKey: CHEBI:15641 and CHEBI:15641

### ISSUE THREAD

**Issue by egonw** [ebi-chebi/ChEBI#4208]
Both have the InChIKey `ZNOVTXRBGFNYRX-STQMWFEESA-N`:

* https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:15641
* https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:136009

cc @DeniseSl22

**Comment by amalik01** [comment]
The structures have now been fixed. CHEBI:15641 has unspecified stereochemistry at the 6-position whereas CHEBI:136009 is the 6S-stereoisomer.
