### ISSUE TITLE
bromic acid (CHEBI:49382)

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#4211]
Please add xrefs:

https://www.ebi.ac.uk/pdbe-srv/pdbechem/chemicalCompound/show/202
https://en.wikipedia.org/wiki/Bromic_acid

Synonyms: 
acide bromique (French)
ácido brómico (Spanish)
acidum bromicum (Latin)

**Comment by amalik01** [comment]
Now added. Thanks
