### ISSUE TITLE
cyanic acid (CHEBI:28024)

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#4213]
Please add xref and a corresponding 3-D structure:
https://www.ebi.ac.uk/pdbe-srv/pdbechem/chemicalCompound/show/0NM

Synonyms:
acide cyanique (French)
ácido ciánico (Spanish)
acidum cyanicum (Latin)

Literature:
PMID: 16743625
PMID: 20340793
PMID: 19624192
PMID: 16744204
PMID: 12590561
PMID: 237898
PMID: 12573832
PMID: 6493050

**Comment by amalik01** [comment]
Now added. Thanks
