### ISSUE TITLE
superoxide (CHEBI:18421)

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#4214]
Please add to CHEBI:18421 xrefs:

https://en.wikipedia.org/wiki/Superoxide
https://www.ebi.ac.uk/pdbe-srv/pdbechem/chemicalCompound/show/2FK

Note that in case of superoxide, the way it is drawn generates different InChIs. In 2FK and ChemIDplus 11062-77-4, it is InChI=1S/O2/c1-2/q-1
In ChEBI and NIST Webbook 11062-77-4, it is InChI=1S/HO2/c1-2/h1H/p-1 (that is, contains one extra hydrogen in the main layer).

The O–O bond order in superoxide is 1.5 and neither drawing is correct. I suggest adding the alternative drawing such as in 2FK and thus having two InChIs for this entity.

Synonyms:

Dioxid(1−) (German)
superóxido (Spanish)
hiperóxido (Spanish)

Literature references
PMID: 26875845
PMID: 34635271
PMID: 15807660
PMID: 21473702
PMID: 14726604
PMID: 30307099 
PMID: 27085844 
PMID: 26511471
PMID: 33248264
PMID: 23660153 
PMID: 17531522
PMID: 31254369 
PMID: 20868230
PMID: 10523323
PMID: 32220789
PMID: 19857607
PMID: 2552230
PMID: 27590268 
PMID: 24862271
PMID: 30500433
PMID: 28599858
PMID: 29259135
PMID: 22759590 
PMID: 29669742
PMID: 33716500
PMID: 28842347
PMID: 32144830
PMID: 29896077
PMID: 30886134
PMID: 32760286
PMID: 28825637
PMID: 19628033
PMID: 26047895
PMID: 29385710
PMID: 32478084
PMID: 19273321
PMID: 27066179
PMID: 19482633
PMID: 28341974
PMID: 32927603
PMID: 22198225
PMID: 26475962
PMID: 30573187
PMID: 33805942
PMID: 12097818
PMID: 15952898
PMID: 19914407
PMID: 15586010
PMID: 8720916
PMID: 28842493
PMID: 12598407 
PMID: 10440226
PMID: 16814528
PMID: 27965593
PMID: 22729857
PMID: 27066025
PMID: 217531
PMID: 12137408
PMID: 23668959
PMID: 16771675
PMID: 21434856
PMID: 23542447
PMID: 21297912
PMID: 17303648
PMID: 18519744
PMID: 9337481
PMID: 11485972
PMID: 1671684
PMID: 14529453 
PMID: 8577306
PMID: 24567847
PMID: 11008114
PMID: 8959373 
PMID: 11333112
PMID: 17052238
PMID: 18827931
PMID: 22521482
PMID: 14703794
PMID: 7998676
PMID: 2160451
PMID: 22247596 
PMID: 10588368
PMID: 31484901
PMID: 27357008
PMID: 32667121

**Comment by amalik01** [comment]
Now added. Unfortunately our system does not allow several inchi/inchi keys to be displayed. Only the inchi key of the default structure can be displayed. However, i have added the other alternative structure.
