### ISSUE TITLE
Lipid (CHEBI:18059) relations- 1

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#4215]
Hi,
We noticed the entity Lipid (CHEBI:18059) has many children that could be classified under more specific parents. I was wondering if you would agree to switch the current relations for the diacylglycerols listed below from is_a Lipid (CHEBI:18059) to: DG(13:0/18:2(9Z,12Z)/0:0)[iso2] (CHEBI:187991) is a CHEBI:17815
DG(13:0/18:3(9Z,12Z,15Z)/0:0)[iso2] (CHEBI:187954) is a CHEBI:17815
DG(14:0/18:4(6Z,9Z,12Z,15Z)/0:0) (CHEBI:172743) is a CHEBI:17815
DG(14:1(9Z)/18:3(9Z,12Z,15Z)/0:0) (CHEBI:183627) is a CHEBI:17815
DG(15:0/0:0/18:3n3) (CHEBI:171961) is a CHEBI:77272
DG(15:0/0:0/18:4n3) (CHEBI:171921) is a CHEBI:77272
DG(15:0/18:2(9Z,12Z)/0:0) (CHEBI:172754) is a CHEBI:17815
DG(15:0/18:3(6Z,9Z,12Z)/0:0) (CHEBI:172752) is a CHEBI:17815
DG(15:0/18:3(9Z,12Z,15Z)/0:0) (CHEBI:171959) is a CHEBI:17815
DG(15:0/18:4(6Z,9Z,12Z,15Z)/0:0) (CHEBI:171690) is a CHEBI:17815
DG(15:1(9Z)/18:3(9Z,12Z,15Z)/0:0)[iso2] (CHEBI:168488) is a CHEBI:17815
DG(16:0/0:0/18:3n3) (CHEBI:171993) is a CHEBI:17815
DG(17:2(9Z,12Z)/18:3(9Z,12Z,15Z)/0:0)[iso2] (CHEBI:186348) is a CHEBI:17815
DG(18:1n9/0:0/18:4n3) (CHEBI:180732) is a CHEBI:77272
DG(18:2(9Z,12Z)/18:4(6Z,9Z,12Z,15Z)/0:0) (CHEBI:178277) is a CHEBI:17815
DG(18:3(6Z,9Z,12Z)/15:0/0:0) (CHEBI:188212) is a CHEBI:17815
DG(18:3(6Z,9Z,12Z)/18:3(6Z,9Z,12Z)/0:0) (CHEBI:178276) is a CHEBI:17815
DG(18:3(6Z,9Z,12Z)/18:3(9Z,12Z,15Z)/0:0)[iso2] (CHEBI:178275) is a CHEBI:17815
DG(18:3(9Z,12Z,15Z)/15:0/0:0) (CHEBI:171957) is a CHEBI:17815
DG(18:3(9Z,12Z,15Z)/18:3(6Z,9Z,12Z)/0:0) (CHEBI:178274) is a CHEBI:17815
DG(18:3(9Z,12Z,15Z)/18:3(9Z,12Z,15Z)/0:0) (CHEBI:178273) is a CHEBI:17815
DG(18:3n6/0:0/18:3n3) (CHEBI:178278) is a CHEBI:77272
DG(18:3n6/0:0/18:3n6) (CHEBI:178272) is a CHEBI:77272
DG(18:4(6Z,9Z,12Z,15Z)/15:0/0:0) (CHEBI:171923) is a CHEBI:17815
DG(18:4(6Z,9Z,12Z,15Z)/18:2(9Z,12Z)/0:0)[iso2] (CHEBI:178279) is a CHEBI:17815

Thanks!

**Comment by amalik01** [comment]
now done. Thanks
