### ISSUE TITLE
Lipid (CHEBI:18059) last one

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#4224]
Sorry, I just noticed we have a couple more anions, maybe their relation to CHEBI:18059 can be removed and instead use:
ω-carboxy-(fatty acyl)-CoA(5−) (CHEBI:177898) is a CHEBI:61697
and
anionic phospholipid (CHEBI:62643) is a CHEBI:16247
Thanks a lot for your diligent action cleaning up this ontology!

**Comment by amalik01** [comment]
done.
