### ISSUE TITLE
CHEBI:64306, Wrong structure

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#4225]
Hi Adnan,

The current structure of CHEBI:64306, O-5''-β-D-mannosylqueuosine, has recently been proved wrong in pmid:34880214.
I have attached the new structure that shows that CHEBI:64306 is a O-4''-α-D-mannosylqueuosine.

You will have to update the ontology to CHEBI:64306 is an α-D-mannoside (CHEBI:27535)

Cheers,

Kristian
[CHEBI_64306.txt](https://github.com/ebi-chebi/ChEBI/files/8141500/CHEBI_64306.txt)

**Comment by amalik01** [comment]
Now updated, great find.
Thanks
