### ISSUE TITLE
Has CHEBI:29702 / Undecylprodigiosin the right stereochemistry

### ISSUE THREAD

**Issue by smoretti** [ebi-chebi/ChEBI#4226]
Hi

I wonder if CHEBI:29702 / Undecylprodigiosin has the right stereochemistry.

According to CAS common and Wikipedia it should be `HIYSWASSDOXZLC-MOHJPFBDSA-N` not `HIYSWASSDOXZLC-HKOYGPOVSA-N`

**Comment by amalik01** [comment]
Now fixed. Thanks
