### ISSUE TITLE
Has CHEBI:2448 / actinorhodin the right structure

### ISSUE THREAD

**Issue by smoretti** [ebi-chebi/ChEBI#4227]
Hi

I wonder if CHEBI:2448 / actinorhodin has the right structure.

Wikipedia and CAS common show it should be `VTIKDEXOEJDMJP-WYUUTHIRSA-N` like in CHEBI:2448 cross-references C06691 and CPD1A0-6123

**Comment by amalik01** [comment]
Thanks. The structure in ChEBI has now been updated.
