### ISSUE TITLE
'eicosatrienoate' CHEBI:165475 and CHEBI:93688, needs a review

### ISSUE THREAD

**Issue by ANiknejad** [ebi-chebi/ChEBI#4231]
Hello ChEBI team,

CHEBI:165475 (5,8,11-Eicosatrienoic acid) is (5E,8E,11E)-icosa-5,8,11-trienoic acid,
and CHEBI:93688 (eicosa-5,8,11-trienoic acid) may represent the non defined stereoisomer.

While both are not naturally occurring in plants and mammals, as far as I can see in the literature, I am wondering if you consider conserving both structures or if you will merge them or even delete them?

So far none of them is connected to the well known CHEBI:78043 (5Z,8Z,11Z)-icosatrienoate.

Here an interesting review about Eicosanoids in carcinogenesis
https://doi.org/10.1051/fopen/2018008

Thank you in advance

Anne

**Comment by amalik01** [comment]
I have decided to merge both entries since the ChEBI names were similar and referred to the unspecifed form. If you are interested in the E,E,E-form, then you can submit this via the submission tool. Thanks.
