### ISSUE TITLE
also CHEBI:134163 wrong formula (N-acylethanolamine C22 with double bounds, have systematically wrong formula?)

### ISSUE THREAD

**Issue by ANiknejad** [ebi-chebi/ChEBI#4233]
Hello ChEBI team,

CHEBI:134163 N-acylethanolamine 22:4
here also the formula is wrong: as regarding the definition, the formula should be C24H**41**NO2 

The correct formula is available in the relative CHEBI:34478 7,10,13,16-Docosatetraenoylethanolamine (a 2-star compound that still needs a review)

Also 
CHEBI:134163 N-acylethanolamine 22:4
Outgoing	N-acylethanolamine 22:4 (CHEBI:134163) is a N-acylethanolamine (CHEBI:52640)
should maybe be changed to
Outgoing	N-acylethanolamine 22:4 (CHEBI:134163) is a N-(long-chain-acyl)ethanolamine (CHEBI:15897)

Thank you,
Best,

Anne

**Comment by ANiknejad** [comment]
and I am afraid, the error is systematic on C22:(other than 0), please see 
CHEBI:134164 N-acylethanolamine 22:5
formula should be C24H39NO2

**Comment by ANiknejad** [comment]
CHEBI:134165 N-acylethanolamine 22:6 (C24H37NO2)

the correct formula is the one available in CHEBI:85252 N-(4Z,7Z,10Z,13Z,16Z,19Z)-docosahexaenoylethanolamine

C24H37NO2

**Comment by amalik01** [comment]
Now fixed. If you spot any other entries with the wrong formula, then please do let me know. The majority of these entries were deposited into ChEBI by MetaboLights.
