### ISSUE TITLE
New term: 3beta-(2-Diethylaminoethoxy)androst-5-en-17-one hydrochloride

### ISSUE THREAD

**Issue by weichiatseng** [ebi-chebi/ChEBI#4235]
Hi,

Could you add 3beta-(2-Diethylaminoethoxy)androst-5-en-17-one hydrochloride to ChEBI?

Name: 3beta-(2-Diethylaminoethoxy)androst-5-en-17-one hydrochloride
Synonym: U18666A
PubChem CID: 9954082

Thank you!

**Comment by amalik01** [comment]
Hi,

A new entry has now been created (CHEBI:190404). It should be searchable on the ChEBI website by tomorrow.
