### ISSUE TITLE
Fix casing on Wikipedia:Calcium_Chloride mapping

### ISSUE THREAD

**Issue by cmungall** [ebi-chebi/ChEBI#4236]
chebi has mappings to both 

Wikipedia:Calcium_chloride
Wikipedia:Calcium_Chloride

![cc](https://user-images.githubusercontent.com/50745/159100851-511b6914-8300-4cd5-a61e-d977c97b5098.png)

I would retain the one on CHEBI:3312 but normalize it to Calcium_chloride (Wikipedia will only capitalize the first word, unless it is a proper name)

**Comment by amalik01** [comment]
wikipedia link now removed from CHEBI:86158
