### ISSUE TITLE
please update the common name of CHEBI:143209.

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#4241]
Hi Adnan,

I submitted CHEBI:143209 quite a long time ago. Yesterady I failed to update its uniprot name (the submission tool had an issue when I tried to update this synonym, language missing...). This morning I discovered that CHEBI:143209 disappeared from my list of submission. I update the uniprot name in the chebi curator tool, but I'm no more allowed to change the common name.

Please could you update the common name of CHEBI:143209 to 
<element>N</element><smallsup><greek>delta</greek></smallsup>-hydroxy-<element>N</element><smallsup><locant>omega</locant></smallsup>-methyl-<element>N</element><smallsup><locant>omega</locant></smallsup>-nitroso-<stereo>L</stereo>-citrulline zwitterion

i.e remove the prime character.

Thank you
Anne

**Comment by amalik01** [comment]
prime character now removed.
