### ISSUE TITLE
update CHEBI:76596

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#4242]
Hi Adnan,
I updated the UniProt name of CHEBI:76596 to ADP-β-D-ribose 1'',2''-cyclic phosphate to be consistent with its 2D structure.
Please could you update accordingly the ChEBI common namsa of CHEBI:76596 and CHEBI:48582 (its conjugate) and remove the xref to MetaCyc CPD-9007 (I got an error in the CCT when I tried to set the status of CPD-9007 to DELETED).
Thank you
Anne

PS: I considered PMID:7929175 (Figure 5) as an evidence for the 2D structure

**Comment by amalik01** [comment]
Hi @amorgat 

The ribose sugar attached to ADP in CHEBI:76596 is not β-D-ribose but an α-D-ribose hence the UniProt name is incorrect. Can you please change this. Thanks
