### ISSUE TITLE
unsure whether "nickel-iron-sulfur cluster", CHEBI:60400, is a "iron-sulfur cluster", CHEBI:30408?

### ISSUE THREAD

**Issue by alanbridge** [ebi-chebi/ChEBI#4251]
Hi Adnan,

should we add to ChEBI

"nickel-iron-sulfur cluster", CHEBI:60400

is a 

"iron-sulfur cluster", CHEBI:30408?

or is that not true? The definition of CHEBI:30408 doesn't say.

All the best, Alan

**Comment by amalik01** [comment]
Since the definition is not strict, i guess you could call it a iron-sulfur cluster.
The relationship has now been added. Thanks
