### ISSUE TITLE
6 ChEBI IDs containing invalid KEGG ID #nwobridgedb

### ISSUE THREAD

**Issue by DeniseSl22** [ebi-chebi/ChEBI#4259]
- [ ] [CHEBI:166656](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:166656) includes KEGG: [C-5504](http://www.genome.ad.jp/dbget-bin/www_bget?cpd:C-5504), which is an invalid KEGG ID (removing the '-' also doesn't work). Based on chemical formula, one of the following could be a correct [linkout](https://www.kegg.jp/kegg-bin/search_result?db=compound&pid=165726572947019&show=entry,name,formula,structure&q=C11H14O4)
- [ ] [CHEBI:166505](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:166505) includes KEGG: C-4623
- [ ] [CHEBI:166530](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:166530) includes KEGG: C-8113
- [ ] [CHEBI:166495](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:166495) includes KEGG: C-5313
- [ ] [CHEBI:166657](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:166657) includes KEGG: C-4785
- [ ] [CHEBI:165218](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:165218) includes KEGG: C-4542

All of these entries have been submitted by a third party (Metabolights). We've found these IDs based on the regex pattern for KEGG IDs: '^C\d+$' . 

@egonw

**Comment by amalik01** [comment]
Thanks for letting us know. The incorrect KEGG links have now been removed from these 6 ChEBI ID's.
