### ISSUE TITLE
CHEBI:57545, Error in ChEBI name

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#4264]
Hi Adnan,

This entry has a double name including both the IUPAC name and a trivial name.
2-(3,4-dihydroxyphenyl)-5-hydroxy-4-oxo-4H-chromen-7-olate luteolin-7-olate(1-)

Cheers,
Kristian

**Comment by amalik01** [comment]
Now fixed. Thanks
