### ISSUE TITLE
CHEBI:132537, Error in ChEBI name

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#4267]
Hi Adnan,

I have just discovered there is an error in the name for 
N(4)-(alpha-D-Glc-(1->2)-alpha-D-Glc-(1->3)-alpha-D-Glc-(1->3)-alpha-D-Man-(1->2)-alpha-D-Man-(1->2)-alpha-D-Man-(1->3)-[alpha-D-Man-(1->2)-alpha-D-Man-(1->3)-[alpha-D-Man-(1->2)-alpha-D-Man-(1->6)]-alpha-D-Man-(1->6)]-beta-D-Man-(1->4)-beta-D-GlcNAc-(1->4)-alpha-D-GlcNAc)-L-asparaginyl residue

The last alpha should be a beta to make the name correspond to the structure that is correct.
So the last of the name should be:
alpha-D-Man-(1->6)]-beta-D-Man-(1->4)-beta-D-GlcNAc-(1->4)-beta-D-GlcNAc)-L-asparaginyl residue
<stereo>D</stereo>-Man-(1<arrow>right</arrow>4)-<stereo>beta</stereo>-<stereo>D</stereo>-GlcNAc-(1<arrow>right</arrow>4)-<stereo>beta</stereo>-<stereo>D</stereo>-GlcNAc)-<stereo>L</stereo>-asparaginyl residue

**Comment by amalik01** [comment]
Name now fixed. Thanks
