### ISSUE TITLE
CHEBI:187876, please delete

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#4269]
Hi Adnan,

Please delete this submission that I created some months ago. It has several errors, and if corrected would turn it into an already existing compound (CHEBI:137207).

The name of the compound is:
N(4)-{beta-D-GlcNAc-(1->2)-alpha-D-Man-(1->3)-[alpha-D-Man-(1->6)]-beta-D-Man-(1->4)-beta-D-GlcNAc-(1->4)-[alpha-D-Fuc-(1->6)]-beta-D-GlcNAc}-Asn residue (that is also wrong)

Best,
Kristian

**Comment by amalik01** [comment]
Okay, now deleted.
