### ISSUE TITLE
Chebi PURL is very, very flaky: big problem for downstream users

### ISSUE THREAD

**Issue by matentzn** [ebi-chebi/ChEBI#4270]
The persistent URL of ChEBI: http://purl.obolibrary.org/obo/chebi.owl redirects to http://ftp.ebi.ac.uk/pub/databases/chebi/ontology/chebi.owl

but we have trouble, year after year with that file. Many dozens ontologies rely on ChEBI as a source for chemical identifiers - I alone look after more than 30 ontologies which pull terms from ChEBI. I can't count the number of cases where people, from within and outside of EBI, came to me asking for help regarding pipeline failures involving the download of ChEBI, but it was in the multiple hundreds. I have also talked many times to the very helpful EBI FTP team to sort out issues, and sometimes the problems disappear for months until they reappear again. These past 3-4 weeks they are again frequently occurring.

Is there anything you can do to stabilise at least the latest release URL for ChEBI a bit? It would make a very big difference for a community that cherishes and relies on ChEBI.. Thanks for considering :)

**Comment by amalik01** [comment]
Hi, Sorry to hear the issues you are currently facing. We have have recently migrated the database to a different server which has resulted in a lot of downtime. As you may know the ChEBI infrastructure is 18 years old and the tech stack it uses is outdated. We are currently working on a 3 year project the redevelop ChEBI's ageing infrastructure using modern stack so hopefully this will make ChEBI more stable in the future. At the moment, we are maintaining the current database to the best we can until the new infrastructure is up and running.

**Comment by matentzn** [comment]
@amalik01 Thank you! :) Highly appreciated!

**Comment by cmungall** [comment]
@amalik01 did you mean to close this?

I appreciate the problems with the database infrastructure, but we don't need access to the database here - this is just access to a static file via apache or whatever server you are running.

The OBO group is willing to work with you to come up with a solution - for example we could host the file in S3 with CloudFront on top

**Comment by eloyfelix** [comment]
Hi @cmungall and @matentzn. Is the EBI FTP still being troublesome? 
There were some maintenance works not so long ago at EBI's datacenters that could have affected its stability but it should be now working normally. This FTP it's being used by several teams at EBI so it is something that should be working fine. I'll talk to the team in charge of it.

In case it is still causing you issues it would be fine for us if you want to host the file somewhere that makes things better for you.

**Comment by matentzn** [comment]
To be honest, I didn't hear any complaints for (at least) the past 10 days. Maybe let's give it another shot - as soon as the issues resurface, I will reopen this ticket. Thank you for following up!
