### ISSUE TITLE
Term requested: LDL(-)

### ISSUE THREAD

**Issue by DeniseSl22** [ebi-chebi/ChEBI#4272]
Electronegative LDL (LDL(-)), a minor modified LDL present in the circulation. Used in several studies, however there is currently no identifier for it, it seems...

**Comment by amalik01** [comment]
A new entry has now been created for electronegative low-density lipoprotein (CHEBI:192800).

https://www.ebi.ac.uk/chebi/searchId.do?chebiId=192800

The term is currently not searchable on the ChEBI website since our lucene index isn't working properly. Hopefully we will try and get this resolved.

**Comment by amalik01** [comment]
Indexing has now been fixed.
