### ISSUE TITLE
CHEBI:139210 might have an incorect ontology link

### ISSUE THREAD

**Issue by JamesRH** [ebi-chebi/ChEBI#4274]
I think that 

CHEBI:139210 - 1-O-(α-D-galactopyranosyl)-N-[8-(4-trifluoromethyl)phenyloctanoyl]phytosphingosine
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:139210

may have an incorrect ontology link. It currently is list as
1-O-(α-D-galactopyranosyl)-N-[8-(4-trifluoromethyl)phenyloctanoyl]phytosphingosine ([CHEBI:139210](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A139210)) is a α-D-galactose ([CHEBI:28061](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A28061))

I think this should be "has functional parent", as it is only a small subset of the structure. 

Or perhaps it "is a" galactose ([CHEBI:28260](https://www.ebi.ac.uk/chebi/chebiOntology.do?chebiId=CHEBI:28260))

How the entry now stands, this rate compound is pulled in as a child of a much smaller compound that is common in enzyme reactions. 

Thank you,
  James H.

**Comment by amalik01** [comment]
The ontology relationship has now been fixed. CHEBI:139210 has functional parent CHEBI:28061
Many Thanks
