### ISSUE TITLE
CHEBI:65055 and CHEBI:83940 describe the same compound

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#4279]
Hi Adnan,
CHEBI:65055 and CHEBI:83940 describe the same compound
CHEBI:65055 1-octadecanoyl-2-acyl-sn-glycero-3-phospho-1D-myo-inositol(1-)
 
CHEBI:83940 1-stearoyl-2-acyl-sn-glycero-3-phospho-(1D-myo-inositol)(1-)
Both ChEBI are used in Rhea, hence we have duplicated reactions too (RHEA: 33355 and RHEA: 83940).
 
Please, could you merge CHEBI:65055 and CHEBI:83940 and tell me which ChEBI id was retained as the primary id in order that I fix the Rhea reactions.
 
With regards,
Anne

**Comment by amalik01** [comment]
Hi @amorgat

Both entries have now been merged (CHEBI:65055 is the primary ID). Can you please remove one of the UniProt names.

**Comment by amorgat** [comment]
Thank you @amalik01
