### ISSUE TITLE
Please, review/update CHEBI:68193 (Echinulin) structure

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#4280]
Hi Adnan,

I'm curating PMID:29072465 for Rhea.
There is already a 2* ChEBI entry for echinulin (CHEBI:68193) but it has the wrong stereochemistry (R,R) instead of (S,S).
See NMR structure in supplementary Table S6 (PMID:29072465)
Synonym: cyclo-L-2-tert-DMA-5,7-di-DMA-Trp-L-Ala
+ https://www.chemspider.com/Chemical-Structure.103122.html

Please could you review this entry or tell me if I need to submit a new one
Thank you for your time
Anne

**Comment by amalik01** [comment]
Now checked.
