### ISSUE TITLE
CHEBI:18314 should not be a (CHEBI:83922)

### ISSUE THREAD

**Issue by MGlauer** [ebi-chebi/ChEBI#4281]
CHEBI:18314 (L-2-aminopentanoic acid) should not be a (R)-fenbuconazole (CHEBI:83922). The structures for both chemicals do not match.

L-2-aminopentanoic acid:
![image](https://user-images.githubusercontent.com/7835111/186695949-8ac3ece3-7a95-4f12-b9dd-784d68e29a70.png)

(R)-fenbuconazole:
![image](https://user-images.githubusercontent.com/7835111/186695993-51fed2e3-a2aa-47d3-8aef-cd002b96c116.png)

**Comment by amalik01** [comment]
Thanks for letting us know. This incorrect relationship has now been removed.
