### ISSUE TITLE
CHEBI:140206 should not be a CHEBI:15904

### ISSUE THREAD

**Issue by MGlauer** [ebi-chebi/ChEBI#4282]
CHEBI:140206 (6-(2-hydroxyethyl)-2-sulfanylidene-1H-pyrimidin-4-one) is a CHEBI:15904 (long-chain fatty acid).

6-(2-hydroxyethyl)-2-sulfanylidene-1H-pyrimidin-4-one
![image](https://user-images.githubusercontent.com/7835111/186713133-90e3bb0b-1cfc-42e0-8e1a-d9913b247b59.png)

**Comment by MGlauer** [comment]
This can be derived from CHEBI:140206 being classified as a 9,11,15-octadecatrienoic acid ([CHEBI:38387](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A38387))

**Comment by amalik01** [comment]
This has now been fixed. Thanks
