### ISSUE TITLE
Please, update the mol file of CHEBI:15379 (O2)

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#4283]
Dear Adnan,

Please could you update the molfile of CHEBI:15379 (O2) which contains Sgroup annotations and is wrongly identified by our procedure as a polymer, preventing us to use it in Rhea.

Thank you for your support,
Anne

##### CHEBI:15379 current molfile

  Marvin  02030822342D          

  2  1  0  0  0  0            999 V2000
   -0.4125    0.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.4125    0.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  2  0  0  0  0
M  STY  1   1 SUP
M  SAL   1  2   1   2
M  SMT   1 O2
M  END
#####

**Comment by amalik01** [comment]
molfile now updated. Thanks
