### ISSUE TITLE
Check molfiles - wrongly identified as polymer 

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#4284]
Hi Adnan,

This is not an urgent issue, but following #4283, I checked the whole list of ChEBIs newly identified as polymers according to their molfiles, whereas they are not.

Molfiles to check
29441
29443
29444
36826
36827
52445
73975
145171
145172

Cheers, Anne

**Comment by amalik01** [comment]
molfiles for the above compounds have been regenerated.
