### ISSUE TITLE
 olefinic phospholipid (CHEBI:76170) has wrong children

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#4290]
Hi Adnan,
 Olefinic phospholipid (CHEBI:76170) has wrong children. Please could you remove
* 4-O-β-D-glucosyl-4-coumaric acid ([CHEBI:17335](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A17335)) is a olefinic phospholipid ([CHEBI:76170](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A76170))
* N-[9-(dichloromethylene)-1,2,3,4-tetrahydro-1,4-methanonaphthalen-5-yl]-3-(difluoromethyl)-1-methylpyrazole-4-carboxamide ([CHEBI:83097](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A83097)) is a olefinic phospholipid ([CHEBI:76170](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A76170))

**Comment by amalik01** [comment]
Now removed. Thanks
