### ISSUE TITLE
Please check CHEBI:145814 EC 1.2.1.12 (aspartate-semialdehyde dehydrogenase) inhibitor

### ISSUE THREAD

**Issue by paola-scibite** [ebi-chebi/ChEBI#4291]
Dear ChEBI curators,

Could you please check CHEBI:145814 'EC 1.2.1.12 (aspartate-semialdehyde dehydrogenase) inhibitor'.
It seems that the label should read 'EC 1.2.1.11 (aspartate-semialdehyde dehydrogenase) inhibitor' instead, see https://enzyme.expasy.org/EC/1.2.1.11, and compare with (correct) CHEBI:70817 'EC 1.2.1.12 [glyceraldehyde-3-phosphate dehydrogenase (phosphorylating)] inhibitor' (https://enzyme.expasy.org/EC/1.2.1.12). 

Thank you, and kind regards,

Paola Roncaglia

**Comment by amalik01** [comment]
Now fixed. Thanks

**Comment by paola-scibite** [comment]
Thank you @amalik01.
