### ISSUE TITLE
review "carboxyspermidine (CHEBI:66868) is a prednisone (CHEBI:8382)"

### ISSUE THREAD

**Issue by andrewsu** [ebi-chebi/ChEBI#4293]
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:66868 reports that "carboxyspermidine ([CHEBI:66868](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A66868)) is a prednisone ([CHEBI:8382](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A8382))".  I believe this relationship should be removed.

**Comment by amalik01** [comment]
Now removed. Thanks
