### ISSUE TITLE
CHEBI:80308 substance P structure 

### ISSUE THREAD

**Issue by nnouspikel** [ebi-chebi/ChEBI#4295]
Dear Adnan,

I hope everything is going well for you.

We submitted substance P(3+) (CHEBI:190692) and need to add a structure to its conjugate base substance P (CHEBI:80308). Could you please help us with this?

Many thanks,
Nevila Hyka-Nouspikel

**Comment by amalik01** [comment]
Both entries have now been annotated and checked. Thanks
