### ISSUE TITLE
Is there a tutorial to parse ChEBI owl/obo files?

### ISSUE THREAD

**Issue by wanglu2014** [ebi-chebi/ChEBI#4300]
To parse full file in this link, and extract relationship.
https://ftp.ebi.ac.uk/pub/databases/chebi/ontology/nightly/
I do know ChEBI provides csv files in another link, however, the direct parsing of owl files might be important task for our study.
Thank you for your attention.

**Comment by amalik01** [comment]
Hi,

ChEBI provides the ChEBI ontology in the W3C standard web ontology language (OWL) format. Tools such as Protégé, TopBraid, the NeOn toolkit and the OWL-API can be used with this ontology.

**Comment by wanglu2014** [comment]
> Hi,
> 
> ChEBI provides the ChEBI ontology in the W3C standard web ontology language (OWL) format. Tools such as Protégé, TopBraid, the NeOn toolkit and the OWL-API can be used with this ontology.

Thank you for your reply. I do know those tools. However, by my knwoledge, there is no direct function to read owl as a tree or formated data frame, so we can extract information form chebi files . There is a great effort to processing readed files. Could you kindly suggest an example on how to process chebi data?

**Comment by amalik01** [comment]
There is LibChEBI which is available to access ChEBI data (further info: https://jcheminf.biomedcentral.com/articles/10.1186/s13321-016-0123-9).

**Comment by sorenwacker** [comment]
You can also read obo files with `obonet` (Python) and turn them into a NetworkX graph.
