### ISSUE TITLE
CHEBI:61336 C4-dicarboxylate structure

### ISSUE THREAD

**Issue by nnouspikel** [ebi-chebi/ChEBI#4301]
Dear Adnan,

I would like to create a parent reaction in RHEA using CHEBI:61336 C4-dicarboxylate but it has no structure. Could you please help us with adding one? I suggest we use the same structure as CHEBI:28965. 

Many thanks for your help,
Nevila

**Comment by amalik01** [comment]
Structure now added. Thanks
