### ISSUE TITLE
Polyphosphate children

### ISSUE THREAD

**Issue by hdrabkin** [ebi-chebi/ChEBI#4303]
I was asked if the following should have some relationship to 'polyphosphate' [CHEBI:16838]  should have parentage to the following terms:
CHEBI:63740 P1,P6-bis(5'-adenosyl)hexaphosphate(6−)
CHEBI:58529  P1,P3-bis(5'-adenosyl) triphosphate

That is
should these terms have GO:0000298 endopolyphosphatase activity as a parent (

GO:0034431	bis(5'-adenosyl)-hexaphosphatase activity
GO:0034432	bis(5'-adenosyl)-pentaphosphatase activity
GO:0008486	diphosphoinositol-polyphosphate diphosphatase activity
GO:0050072	m7G(5')pppN diphosphatase activity
GO:0047710	bis(5'-adenosyl)-triphosphatase activity
if something has  diphosphate or triphosphate between two moieties, are those polyphosphates?

The CHEBI terms used in the associated RHEAs do not has polyphosphate as a parent.
see ticket https://github.com/geneontology/go-ontology/issues/24268

**Comment by amalik01** [comment]
CHEBI:63740 and CHEBI:58529 should not be under the parent class 'polyphosphate' since this class only deals with polymers composed of repeated phosphate groups.
