### ISSUE TITLE
NTR 3-BrB-PP1 3-[(3-bromophenyl)methyl]-1-tert-butylpyrazolo[3,4-d]pyrimidin-4-amine

### ISSUE THREAD

**Issue by ValWood** [ebi-chebi/ChEBI#4311]
hi

I am looking for chebi
https://www.chemsrc.com/en/cas/956025-99-3_794891.html

I could not locate with searches
3-BrB-PP1
3-[(3-bromophenyl)methyl]-1-tert-butylpyrazolo[3,4-d]pyrimidin-4-amine

**Comment by amalik01** [comment]
A new ChEBI entry has now been created for 3-BrB-PP1 (CHEBI:194136).
It should be searchable on the ChEBI website by tomorrow.

https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:194136

**Comment by ValWood** [comment]
Thanks!
