### ISSUE TITLE
Potentially missing parent for some agonist/blocker terms

### ISSUE THREAD

**Issue by paola-scibite** [ebi-chebi/ChEBI#4316]
Dear CHEBI editors,

On the grounds that 
1) membrane transport modulator CHEBI:38632 = "...affects the transport of molecular entities..."
2) antagonist CHEBI:48706 = "...blocks cell receptors..."
3) ligand-gated ion channels (first 2 below) are types of cell receptors
=> should the following terms have the additional superclass "antagonist":

GABA-gated chloride channel antagonist CHEBI:38999
calcium channel blocker CHEBI:38215
dopaminergic antagonist CHEBI:48561

There might be more, but these were the most evident.
Thanks!

Paola

**Comment by amalik01** [comment]
Thanks - These have now been classified as antagonists. If you come across any others, please do let us know.

**Comment by paola-scibite** [comment]
@amalik01 Thank you for addressing this and other ChEBI edits I requested recently.
