### ISSUE TITLE
NTR: protease-activated receptor-1 agonist

### ISSUE THREAD

**Issue by paola-scibite** [ebi-chebi/ChEBI#4317]
CHEBI already has protease-activated receptor-1 _antagonist_ (CHEBI:83313). Please consider adding 

CHEBI:NEW protease-activated receptor-1 agonist
"An agonist of protease-activated receptor-1."
Subclass of agonist CHEBI:48705
PMID: 11487506
If useful, my ORCID is https://orcid.org/0000-0002-2825-0621

Thanks,
Paola

**Comment by amalik01** [comment]
An entry has now been created for protease-activated receptor-1 agonist (CHEBI:194153). It should be searchable on the ChEBI website by tomorrow.
