### ISSUE TITLE
Parentage of CHEBI:172949 'antimicrobial cosmetic preservative' 

### ISSUE THREAD

**Issue by paola-scibite** [ebi-chebi/ChEBI#4319]
Hi, 

CHEBI:172949 'antimicrobial cosmetic preservative' 
("An antimicrobial agent that is added to cosmetic formulations to maintain the microbiological safety of the products by inhibiting the growth of fungi or bacteria.")
is currently a subclass of both 'antimicrobial agent' and 'cosmetic'.
But the latter is defined as "The role played by a substance in enhancing the appearance or odour of the human body; a name given to the substance itself or to a _component_ of it."
The "component" bit is a little ambiguous, but the antimicrobial substance itself does not have a cosmetic role. Should the link be removed?

Thank you, and kind regards,

Paola

**Comment by amalik01** [comment]
Yes, i think you're right - The link to cosmetic has now been removed. Thanks
