### ISSUE TITLE
CHEBI:131186 'IP3 receptor antagonist' has an incorrect synonym

### ISSUE THREAD

**Issue by paola-scibite** [ebi-chebi/ChEBI#4320]
CHEBI:131186 'IP3 receptor antagonist' has related synonym "IP3 receptor".
All other related synonyms of the same class are of the type "xyz _antagonist_", so "IP3 receptor" may have been added in error, and is confusing.

Thank you,

Paola

**Comment by amalik01** [comment]
It was meant to be 'IP3 receptor antagonists' - Now fixed. Thanks
