### ISSUE TITLE
Are these duplicates? CHEBI:72571 and CHEBI:50927 

### ISSUE THREAD

**Issue by paola-scibite** [ebi-chebi/ChEBI#4321]
CHEBI:72571 'pro-angiogenic agent' = "Any compound that promotes the growth of new blood vessels from pre-existing vessels."

CHEBI:50927 'angiogenesis inducing agent' = "An agent that induces or stimulates the physiologic angiogenesis process."

Both are subclasses of CHEBI:50926 'angiogenesis modulating agent', and have no other superclass.

Thanks,

Paola

**Comment by amalik01** [comment]
Now merged. Thanks
