### ISSUE TITLE
Acyl-CoA (CHEBI:17984) has CAS regno 9029-97-4 for the transferase

### ISSUE THREAD

**Issue by egonw** [ebi-chebi/ChEBI#4323]
Acyl-CoA (CHEBI:17984) has CAS regno 9029-97-4 (source KEGG), but according to CAS Common Chemistry, this CAS registration number is for the Acetyl-coenzyme A C-acyltransferase. See https://commonchemistry.cas.org/detail?ref=9029-97-4

**Comment by amalik01** [comment]
CAS number now removed. Thanks
