### ISSUE TITLE
Add synonym 'Cy3' to 'Cy3 dye' CHEBI_37987

### ISSUE THREAD

**Issue by kristenpeach** [ebi-chebi/ChEBI#4325]
Hello! Would you be willing to update 'Cy3 dye' http://purl.obolibrary.org/obo/CHEBI_37987 to include a synonym or alternative label of 'Cy3'? Thank you!

**Comment by amalik01** [comment]
Additional synonyms have now been added (https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:37987)

**Comment by kristenpeach** [comment]
Wow thank you!!!
