### ISSUE TITLE
CHEBI:30997 == C22350 ?

### ISSUE THREAD

**Issue by micwij** [ebi-chebi/ChEBI#4330]
Hi ChEBI-Team,

It looks to me like CHEBI:30997 is the same as KEGG compound C22350 (https://www.genome.jp/entry/C22350). When checking "Other DBs" from the KEGG entry we can also find the same InChI key (https://www.ebi.ac.uk/pdbe-srv/pdbechem/chemicalCompound/show/4PW). I am not sure if I am overlooking something, because neither Pubchem nor HMDB, connect their compound to KEGG. Maybe someone could check this and potentially add a manual xref. Thanks!

Best,
Micha

**Comment by amalik01** [comment]
I have now added the KEGG link in CHEBI. Thanks
