### ISSUE TITLE
Please merge two submissions with identical structures, CHEBI:192778 and CHEBI:192816

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#4331]
Hi Adnan,

Some time ago, I submitted two compounds that turns out to have the same structure, namely CHEBI:192816 (2S)-naringenin 4',7-dimethyl ether and CHEBI:1928778 (2S)-5-hydroxy-4',7-dimethoxyflavanone.

The problem was not caught by the submission tool as the duplicate structure check did not work at the time, and actually still does not work. Only last week did I have a case where a duplicate structure was not detected, luckily the name was also duplicated, and that was.

But I would be happy if you could merge the two above compounds to avoid any confusion.

Best,
Kristian

**Comment by amalik01** [comment]
Now merged. Thanks
