### ISSUE TITLE
Please fix CHEBI:183059 smiles

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#4332]
Hi Adnan,
CHEBI:183059 smiles = "CC\C=[S+]/[O-]" is erroneous. The Rgroup is missing in it.
(consequently, it has the same smiles as CHEBI:183657)
Please could you fix CHEBI:183059 smiles as this ChEBI is used in Rhea.
Thank you
Anne

**Comment by amalik01** [comment]
Now fixed. Thanks
