### ISSUE TITLE
Version file in https://ftp.ebi.ac.uk/pub/databases/chebi/Flat_file_tab_delimited/

### ISSUE THREAD

**Issue by sorenwacker** [ebi-chebi/ChEBI#4334]
Hi, it would be great to have a version file [here ](Version file in https://ftp.ebi.ac.uk/pub/databases/chebi/Flat_file_tab_delimited/).

e.g. VERSION that only contains the current unique version string for the data.

with the current version of the files. To make it easy to check for updates. 

Or is this info provided somewhere else?

**Comment by amalik01** [comment]
Hi @sorenwacker 

All previous ChEBI releases are stored in the archives folder (https://ftp.ebi.ac.uk/pub/databases/chebi/archive/)

**Comment by sorenwacker** [comment]
So, to find out what the current version is, I have to look into the archive to see what versions are there? Or is the current release always also present in the archive? So that I can simply use the archive?

**Comment by amalik01** [comment]
The current release is 218 and its also present in the archives folder. At the beginning of each month we also put a tweet out on ChEBI's twitter account to notify users that a new release is available. The ontology files (chebi.obo) also contains the version number. The data that is available to download from ChEBI's website (https://www.ebi.ac.uk/chebi/downloadsForward.do) belongs to the current release.

**Comment by sorenwacker** [comment]
Ok, so I know now how to get the version number. I still think, it would be good practice to add the version into the folder, and it would be more convenient for me :-), but that is up to you, or course. Thank you!
