### ISSUE TITLE
Where to find "Submitter" / third-party info in flat files / downloads?

### ISSUE THREAD

**Issue by rgiessmann** [ebi-chebi/ChEBI#4342]
Dear team,

I was looking at https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:166858 and saw "submitter" being "Elad Noor". I searched in the downloadable files referenced from https://www.ebi.ac.uk/chebi/downloadsForward.do to find such a field and/or the content, but couldn't locate it. 

Is the submitter data not part of the "official" data? Did I miss to find it?

Any hints appreciated. :)

Best,
   Robert

**Comment by amalik01** [comment]
Hi,

We currently do not export 'submitter' data as this may require additional consent under GDPR guidelines. You can only see this data on the ChEBI website for a given ChEBI entry and at present you cannot search for entries by 'submitter name' either.

**Comment by rgiessmann** [comment]
Thanks for letting me know! Do you already collect consent (or non-consent)
for new submissions so this would be different in the long-term? I believe
this might be valuable information! Thanks and best!

**Comment by amalik01** [comment]
All of the users have to accept EMBL-EBI terms of use (https://www.ebi.ac.uk/about/terms-of-use) when they register for a submissions account. We are currently redeveloping ChEBI and could possibly make 'submitter data' widely available in the near future but this will require further discussions within the team on how best to proceed and what the implications would be.
