### ISSUE TITLE
NTR: unfolded protein

### ISSUE THREAD

**Issue by vanaukenk** [ebi-chebi/ChEBI#4343]
We would like to model the endoplasmic reticulum unfolded protein response in the GO-CAM framework and it would be helpful to represent the concept of an 'unfolded protein' by using a ChEBI term.

We suggest a new ChEBI term, 'unfolded protein'.

* **Suggested term label:**
* unfolded protein

* **Definition (free text)**
* A protein that lacks correct, or native, secondary or tertiary structure.

* **Reference, in format PMID:#######**
* PMID:35452616
* PMID:32457508
* PMID:30396883

* **Parent term(s)**
* protein (CHEBI:36080)

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**
Related synonym: misfolded protein

Please let me know if you need any additional information or have any questions about the term request.  

Thanks,
--Kimberly Van Auken

**Comment by amalik01** [comment]
A new ChEBI entry has now been created for unfolded protein (CHEBI:194424). The term will be searchable on the ChEBI website by tomorrow.

**Comment by vanaukenk** [comment]
Thank you so much for your rapid response!
