### ISSUE TITLE
pentaphenylphosphorane

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#4345]
Please create an entry for pentaphenylphosphorane, (C<sub>6</sub>H<sub>5</sub>)<sub>5</sub>P

pentaphenylphosphorane **has parent hydride** phosphorane ([CHEBI:30285](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A30285))

IUPAC name: pentaphenyl-λ<sup>5</sup>-phosphane

CAS 2588-88-7

https://pubchem.ncbi.nlm.nih.gov/compound/2785233
https://www.chemspider.com/Chemical-Structure.2065130.html
https://en.wikipedia.org/wiki/Pentaphenylphosphorus and literature references therein (refs. 2, 4, 5)

Thanks

**Comment by amalik01** [comment]
A new ChEBI entry has now been created (CHEBI:194485).
