### ISSUE TITLE
Are CHEBI:165297 '20-HeDE' and CHEBI:72848 'HEDE' related?

### ISSUE THREAD

**Issue by paola-scibite** [ebi-chebi/ChEBI#4347]
Hi,
Are CHEBI:165297 '20-HeDE' and CHEBI:72848 'HEDE' related in some way, please?
Thank you,
Paola Roncaglia

**Comment by amalik01** [comment]
The entry has not been curated yet and therefore its ontology is incomplete. I have now added it to the class 'HEDE'

**Comment by paola-scibite** [comment]
@amalik01 thank you for the prompt reply! So CHEBI:165297 '20-HeDE' should be a subclass of CHEBI:72848 'HEDE', right? Or are the two classes the same thing? Thank you.

**Comment by amalik01** [comment]
yes, that's right 20-HEDE is a subclass of HEDE. 
HEDE contains a hydroxy group but its position is unspecified and 20-HEDE contains a hydroxy group specifically at position 20.
