### ISSUE TITLE
CHEBI:17791 Structure is missing stereoconfiguration at C5

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#4351]
Hi Adnan,

The current "main" structure is missing a wedge bond at C5. The alternative structure (structure 4) has this wedge, that is an H going away (into the paper). Please switch the two structures.

Best,
Kristian

**Comment by amalik01** [comment]
Structure updated and is consistent with CAS (https://commonchemistry.cas.org/detail?cas_rn=16910-32-0&search=16910-32-0)
