### ISSUE TITLE
thiophene oxide (CHEBI:36603)

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#4353]
Please add the names and refs for thiophene oxide ([CHEBI:36603](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A36603))

The Blue Book ([P-64.4.2](https://iupac.qmul.ac.uk/BlueBook/P6.html#640402)) gives the following IUPAC names: 

1*H*-1λ<sup>4</sup>-thiophen-1-one (PIN)
1-oxo-1*H*-1λ<sup>4</sup>-thiophene

Synonyms:

thiophenone 
thiophene *S*-oxide
thiophene-*S*-oxide

CAS 2657-73-0

Literature references:

PMID: 29360357
PMID: 12929638
PMID: 11666909
PMID: 34158534
PMID: 24413192
PMID: 1510686
PMID: 35055091
PMID: 12375952
PMID: 36524997

**Comment by amalik01** [comment]
now added. thanks
