### ISSUE TITLE
CHEBI:89455 and CHEBI:89213, 18-hydroxy- and 18-oxo-cortisol, wrong stereoconfiguration at C-17

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#4356]
Hi Adnan,

These two compounds are (S) at C17 while all other cortisol and cortisone are (R). Please correct these structures or create new compounds for (17R)-hydroxycortisol and (17R)-oxocortisol as we need them for reactions in Rhea.

Best,
Kristian

**Comment by amalik01** [comment]
These 2 entries have now been fixed and both have 17R-stereochemistry.
