### ISSUE TITLE
Is the label of CHEBI:31128 (4-hydroxyphenyl acetate) correct?

### ISSUE THREAD

**Issue by paola-scibite** [ebi-chebi/ChEBI#4357]
Hi, 
I'm comparing the apparent label duplication between

CHEBI:48999 - 4-hydroxyphenylacetate (4-hydroxyphenylacetate ([CHEBI:48999](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A48999)) is conjugate base of 4-hydroxyphenylacetic acid ([CHEBI:18101](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A18101)))

and

CHEBI:31128 - 4-hydroxyphenyl acetate

Could you please confirm that both labels are correct? 
Thank you,

Paola

**Comment by amalik01** [comment]
Hi Paola,

These ChEBI entries are correct and are not duplicated entries.

Although the names are similar, one of the names has a space in it whereas the other doesn't. 4-hydroxyphenylacetate is the deprotonated form of 4-hydroxyphenylacetic acid whereas CHEBI:31128 has a space in the name and is referring  to the acetate ester. All of the acetate esters have a space in the name.

E.g. Ethyl acetate (https://en.wikipedia.org/wiki/Ethyl_acetate)
benzyl acetate (https://en.wikipedia.org/wiki/Benzyl_acetate)

**Comment by paola-scibite** [comment]
@amalik01 thanks for confirming!
