### ISSUE TITLE
Errors in label or IUPAC name?

### ISSUE THREAD

**Issue by paola-scibite** [ebi-chebi/ChEBI#4359]
Hi, 
I noticed 5 pairs of these please, where the IUPAC name of the former is exactly the same as the label of the latter. Should one of the two be revised please?
Thanks.

1st pair:

CHEBI:183430 - 5-acetyl-2,6-dimethyl-1,2,3,4-tetrahydropyridin-4-one
IUPAC Name: 5-acetyl-2,6-dimethyl-2,3-dihydro-1H-pyridin-4-one

CHEBI:181997 - 5-acetyl-2,6-dimethyl-2,3-dihydro-1H-pyridin-4-one
IUPAC Name: 1-(4-hydroxy-2,6-dimethyl-2,3-dihydropyridin-5-yl)ethanone

2nd pair:

CHEBI:179636 - 5-ethyl-5-methyl-2,4-oxazolidinedione
IUPAC Name: 5-ethyl-5-methyl-1,3-oxazolidine-2,4-dione

CHEBI:143436 - 5-ethyl-5-methyl-1,3-oxazolidine-2,4-dione
(no IUPAC name)

3rd pair:

CHEBI:171837 - xi-Dihydro-5-octyl-2(3H)-furanone
IUPAC Name: 5-octyloxolan-2-one

CHEBI:143727 - 5-octyloxolan-2-one
(no IUPAC name)

4th pair:

CHEBI:151031 - 1-Piperazinecarboxaldehyde
IUPAC Name: piperazine-1-carbaldehyde

CHEBI:46907 - piperazine-1-carbaldehyde
(no IUPAC name)

5th pair:

CHEBI:180249 - Hexanethioic acid S-propyl ester
IUPAC Name: S-propyl hexanethioate

CHEBI:177491 - S-Propyl hexanethioate
IUPAC Name: O-propan-2-yl hexanethioate

**Comment by paola-scibite** [comment]
@amalik01 
Hi, it was a pleasure to meet you at the Biocuration conference!
With regards to our conversation of where ChEBI curation might have the most impact, compatibly with resources, I've reviewed my open tickets. At present, if possible, I'd prioritise the 5 apparent duplications above, please. They might not be duplications after all, but that's where I'd need your feedback please.
Thank you in advance!
Paola

**Comment by amalik01** [comment]
Hi @paola-scibite. It was nice meeting you too. I have fixed the above 5 entries. The 1st pair were tautomers and now clearly differentiated. The 2nd and 3rd pairs were duplicates and have now been merged. The 4th pair (one of the compounds was specific compound whereas the other was a class of compounds). The 5th pair were supposed to be two different compounds. 

Thanks
