### ISSUE TITLE
Question on identical IUPAC names

### ISSUE THREAD

**Issue by paola-scibite** [ebi-chebi/ChEBI#4360]
Hi, 

The following 3-star curated entries share the same IUPAC name, 3-(2-amino-2-carboxyethyl)-1H-indol-1-yl:
CHEBI:32731 - 1-tryptophano group 
CHEBI:32730 - tryptophanyl radical
My non-expert understanding is that these are _general_ IUPAC names, rather than Preferred IUPAC Names which should be unique for organic compounds. Could you please confirm if "3-(2-amino-2-carboxyethyl)-1H-indol-1-yl" is a valid name for both CHEBI classes? 

Many thanks,
Paola

**Comment by amalik01** [comment]
We generate IUPAC names using ACD chemsketch and its unable to differentiate between the IUPAC name of a group and a monovalent radical. For example, methyl group (CHEBI:32875) has an IUPAC name called ‘methyl’ and methyl radical (CHEBI:29309) also has an IUPAC name called ‘methyl’.

According to IUPAC, an alkyl group is a group of atoms that results when one hydrogen atom is removed from an alkane. The group is named by replacing the -ane suffix of the parent hydrocarbon with -yl. For example, the CH3 group derived from methane (CH4) results from subtracting one hydrogen atom and is called a methyl group. Alkyl groups are not independent molecules; they are parts of molecules that we consider as a unit to name compounds systematically.
Monovalent radicals are also treated in the same way (see RC-81.1.1 https://iupac.qmul.ac.uk/ions/RC811.html)

**Comment by paola-scibite** [comment]
@amalik01 thank you for explaining that. Best wishes,
Paola
