### ISSUE TITLE
Are CHEBI:2719 and CHEBI:131170 the same?

### ISSUE THREAD

**Issue by shawntanzk** [ebi-chebi/ChEBI#4364]
Hi we have noticed that the inchi for CHEBI:2719 & CHEBI:131170 are the same - do they refer to the same entity or is there suppose to be a difference between them? If they are suppose to be separate entities, should there be a relationship between them? Thank you
tagging @tommycarstensen too

**Comment by amalik01** [comment]
Both entries have now been merged since they were duplicates. Thanks

**Comment by shawntanzk** [comment]
@amalik01 Thanks so much responding to this so quickly. Could you let us know which was the "winning" term ID please so we can use that? Thanks

**Comment by amalik01** [comment]
The primary ID is CHEBI:2719
