### ISSUE TITLE
NTR: activator

### ISSUE THREAD

**Issue by cthoyt** [ebi-chebi/ChEBI#4368]
As an opposite to `inhibitor` ([CHEBI:35222](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:35222)), I think it would be good to have a term for `activator`.

The definition for inhibitor is 

> A substance that diminishes the rate of a chemical reaction.

Therefore, a similar definition for *activator* could be

> A substance that increases the rate of a chemical reaction.

The parent term for `activator` should be `effector` ([CHEBI:35224](https://bioregistry.io/CHEBI:35224)).

Some example terms that are activators:

| CURIE | Label | Notes |
|-----|------|--------|
| [CHEBI:77324](https://bioregistry.io/CHEBI:77324) | UDP-glucuronosyltransferase activator |
| [CHEBI:91189](https://bioregistry.io/CHEBI:91189) | VEGF activator | 
| [CHEBI:71033](https://bioregistry.io/CHEBI:71033) | carbamylphosphate synthetase I |
| [CHEBI:90374](https://bioregistry.io/CHEBI:90374) | histone acetyltransferase activator |
| [CHEBI:73966](https://bioregistry.io/CHEBI:73966) | nitric oxide synthase activator |
| [CHEBI:77731](https://bioregistry.io/CHEBI:77731) | p53 activator |
| [CHEBI:76022](https://bioregistry.io/CHEBI:76022) | soluble guanylate cyclase activator |
| [CHEBI:85053](https://bioregistry.io/CHEBI:85053) | EC 2.7.11.31 \{[hydroxymethylglutaryl-CoA reductase (NADPH)] kinase\} activator |
| [CHEBI:50912](https://bioregistry.io/CHEBI:50912) | cardiotoxic agent | Activates cardiotoxicity process, also arguable |
| [CHEBI:50927](https://bioregistry.io/CHEBI:50927) | angiogenesis inducing agent | There could be a case made that an inducer isn't the same as an activator |
| [CHEBI:68495](https://bioregistry.io/CHEBI:68495) |apoptosis inducer |  see previous row comment |
| [CHEBI:72571](https://bioregistry.io/CHEBI:72571) | pro-angiogenic agent | Activates angiogenesis |

**Comment by amalik01** [comment]
A new term for activator (CHEBI:195251) has now been created.

**Comment by cthoyt** [comment]
Woohoo! Thanks @amalik01. Should we close this issue then?

**Comment by amalik01** [comment]
I have given activators the parent term 'biological role' instead of 'effector'.

Effectors are compounds which usually bind to the allosteric binding site of a protein so this may not hold true for all activators as some may even bind to the substrate binding site and still activate the enzyme.

**Comment by cthoyt** [comment]
I saw, maybe you can imagine a new term that can be a parent to both activator/inhibitor that gives some insight into them being generic "regulators"? 

for example, a compound might be known to have an effect but not in what direction
