### ISSUE TITLE
bacteriochlorophylls: please update CHEBI:60197 CHEBI:22686 structures

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#4369]
Hi Adnan,
Please could you update the structures of CHEBI:60197 and CHEBI:22686 accordingly to the other forms of bacteriochlorophyll (CHEBI:30033, CHEBI:189438) in order to have consistent data (in particular avoiding the use of bond type==any in CHEBI:60197).
Thank you for your support
Best regards, Anne

**Comment by amalik01** [comment]
The structures have now been updated. There are several ways how these metal complexes can drawn.
