### ISSUE TITLE
please consider adding "alkenyl benzene(s)"

### ISSUE THREAD

**Issue by egonw** [ebi-chebi/ChEBI#4372]
We have a data set with "alkenyl benzene" (benzene ring with an attached alkenyl group, e.g. CHEBI:51324 or CHEBI:4917) as term and like to use a ChEBI identifier. We note similar items, like vinyl arene and alkylbenzene.

**Comment by amalik01** [comment]
An entry for alkenylbenzene (CHEBI:195237) has now been created
