### ISSUE TITLE
Please update structures of CHEBI:190667, CHEBI:190668 and CHEBI:190669

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#4375]
Hi Adnan,

Nice meeting you at last. I hope you had a safe trip back from Padova.

I would like to have these three compounds updated as their molfiles behave strangely. I have tried to do it myself in the curator tool, but it seems that you have to intervene to accept my updates. If my updates have been ignored beause I didn't ave the rights to change structures, I hope you will use the attached structures to update the entries. 

Thank you in advance,
Best,

Kristian
[190698_NEW.txt](https://github.com/ebi-chebi/ChEBI/files/11423536/190698_NEW.txt)
[190697_NEW.txt](https://github.com/ebi-chebi/ChEBI/files/11423537/190697_NEW.txt)
[190699_NEW.txt](https://github.com/ebi-chebi/ChEBI/files/11423538/190699_NEW.txt)

**Comment by amalik01** [comment]
It was nice meeting you too.
The mol files of the 3 ChEBI ID's have now been updated. I think the issue occurs if we don't leave a blank/emty space at the beginning of the mol file.
