### ISSUE TITLE
Missing entry for Acetylthreonine

### ISSUE THREAD

**Issue by sorenwacker** [ebi-chebi/ChEBI#4377]
https://pubchem.ncbi.nlm.nih.gov/compound/N-Acetylthreonine

**Comment by amalik01** [comment]
Hi, we already have a CHEBI entry for N-acetyl-L-threonine (CHEBI:45826). Its InChI key is an exact match for the PubChem entry.

**Comment by sorenwacker** [comment]
For some reason, the search tool does not find it:
![image](https://github.com/ebi-chebi/ChEBI/assets/3391614/d31113e1-ea2e-4603-8123-a091a23f689c)
![image](https://github.com/ebi-chebi/ChEBI/assets/3391614/4c4c554b-b90f-4e84-ad2d-667459d12692)

**Comment by amalik01** [comment]
I have now added the synonym 'N-acetylthreonine' to this entry so the name should now be searchable on the ChEBI website.
