### ISSUE TITLE
Please update CHEBI:60492 structure (Mg-protoporphyrin)

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#4385]
Hi Adnan,
Please could you update the Mg-bonds of CHEBI:60197 (magnesium protoporphyrin(2−)) accordingly to  CHEBI:60491. There is an issue with CHEBI:60197 Molfile. We cannot process it correctly and it cannot be loaded in the Advanced search of the public website.
**Error message:**
_Error loading molfile.
Error: Assertion failed: s-group forest invalid_

Thank you for your support
Best regards, Anne

**Comment by amalik01** [comment]
Structure now updated.
