### ISSUE TITLE
Please, update structures

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#4386]
Dear Adnan,
We have some trouble in the processing of the compounds (see below) that are used in Rhea.
Would you mind replacing their structures with the attached Molfiles that I redrew from scratch? 
PS: Kristian and I updated the structure of some of our submissions and it fixed the processing issue.
Thank you for your support,
Anne

17791	obtusifoliol
30834	aldosterone hemiacetal
30997	levoglucosan
42870	N-acetyl-D-glucosamino-1,5-lactone
50068	stemod-13(17)-ene
58690	1,6-anhydro-N-acetyl-beta-muramate
131146	dihydroouabain
131711	(S)-demethyl-4-deoxygadusol(1-)
132139	(R)-demethyl-4-deoxygadusol(1-)
144894	3-dehydrolevoglucosan
173121	(1S,6S,7R)-sesquipiperitol
183368	7beta-hydroxydehydroepiandrosterone

[chebi_58690_updated.mol.txt](https://github.com/ebi-chebi/ChEBI/files/11489480/chebi_58690_updated.mol.txt)
[chebi_50068_updated.mol.txt](https://github.com/ebi-chebi/ChEBI/files/11489482/chebi_50068_updated.mol.txt)
[chebi_42870_updated.mol.txt](https://github.com/ebi-chebi/ChEBI/files/11489483/chebi_42870_updated.mol.txt)
[chebi_30997_updated.mol.txt](https://github.com/ebi-chebi/ChEBI/files/11489484/chebi_30997_updated.mol.txt)
[chebi_30834_updated.mol.txt](https://github.com/ebi-chebi/ChEBI/files/11489486/chebi_30834_updated.mol.txt)
[chebi_183368_updated.mol.txt](https://github.com/ebi-chebi/ChEBI/files/11489487/chebi_183368_updated.mol.txt)
[chebi_17791_updated.mol.txt](https://github.com/ebi-chebi/ChEBI/files/11489488/chebi_17791_updated.mol.txt)
[chebi_173121_updated.mol.txt](https://github.com/ebi-chebi/ChEBI/files/11489489/chebi_173121_updated.mol.txt)
[chebi_144894_updated.mol.txt](https://github.com/ebi-chebi/ChEBI/files/11489490/chebi_144894_updated.mol.txt)
[chebi_132139_updated.mol.txt](https://github.com/ebi-chebi/ChEBI/files/11489491/chebi_132139_updated.mol.txt)
[chebi_131711_updated.mol.txt](https://github.com/ebi-chebi/ChEBI/files/11489492/chebi_131711_updated.mol.txt)
[chebi_131146_updated.mol.txt](https://github.com/ebi-chebi/ChEBI/files/11489493/chebi_131146_updated.mol.txt)

**Comment by amalik01** [comment]
@amorgat Do you know what exactly is wrong with the current mol files?

**Comment by amalik01** [comment]
@amorgat Can you please check whether the mol files are fine now or still causing issues? I haven't yet updated the mol files but left a space at the top of the file to figure out whether this is the issue.

**Comment by amorgat** [comment]
CHEBI:17791
If I load the old Molfile in MarvinSketch and export it as SMILES, the stereoX is missing
[H]C1(CCC2(C)C3=C(CCC12C)C1(C)CCC(O)C(C)C1([H])CC3)C(C)CCC(=C)C(C)C

With your recently updated version, the stereoX is as expected
[H][C@@]1(CC[C@@]2(C)C3=C(CC[C@]12C)[C@@]1(C)CC[C@H](O)[C@@H](C)[C@]1([H])CC3)[C@H](C)CCC(=C)C(C)C

I can see in the chebi curator tool (structure history) that the bond block is different: 7 columns in the old Molfile, 6 in the new one.
Can you confirm that you made other changes than just adding a left space at the top for CHEBI:17791?

SIB local copy: I have to wait the synchro to get the result of the computation with the new structure of  CHEBI:17791

**Comment by amalik01** [comment]
The mol files for all of the above structures have now been updated.
