### ISSUE TITLE
CHEBI:76302 and CHEBI:84746 are identical, please merge

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#4388]
Hi Adnan,
Please merge CHEBI:76302 (used in Rhea) and CHEBI:84746 as they describe the same structure.
Thank you!
Anne

**Comment by amalik01** [comment]
Now merged. Thanks

**Comment by amalik01** [comment]
@amorgat Can you please remove one of the UniProt names.

**Comment by kaxelsen** [comment]
Thank you for taking care of the problem. I have removed one of the UniProt names.
