### ISSUE TITLE
NTR: corn oil

### ISSUE THREAD

**Issue by paola-scibite** [ebi-chebi/ChEBI#4390]
Hi @amalik01 ,

May I please request a new CHEBI term for 'corn oil', similar to the existing CHEBI:140618 'castor oil':

CHEBI:NEW 'corn oil'
subclass of CHEBI:60004 'mixture' 
See https://en.wikipedia.org/wiki/Corn_oil for definition and reference

Thanks,
Paola

**Comment by amalik01** [comment]
A new term for corn oil (CHEBI:195250) has now been created. It should be searchable on the ChEBI website by tomorrow.

**Comment by paola-scibite** [comment]
Thank you @amalik01 !
