### ISSUE TITLE
Please review CHEBI:81465 and CHEBI:81466 

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#4392]
Hi Adnan,
Please could you review 
CHEBI:81465 5-deoxystrigol 
CHEBI:81466 5-deoxystrigol ABC-rings
that are now used in a Rhea reaction (see PMID:34764442).
RHEA:76511 5-deoxystrigol + H2O = 3-hydroxy-4-methyl-furan-2(5H)-one + 5-deoxystrigol ABC-rings 
If you have a better suggestion for naming CHEBI:81466, please don't hesitate to share and Elisabeth will update her submissions (CHEBI:195259 and CHEBI:195257).
Best regards, Anne

**Comment by amalik01** [comment]
CHEBI:81465 and CHEBI:81466 now checked.
