### ISSUE TITLE
2 'donor' chemical entities not in 'donor' role branch

### ISSUE THREAD

**Issue by paola-scibite** [ebi-chebi/ChEBI#4394]
Should 
[CHEBI:139520 - phenolic donor](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:139520)
and
[CHEBI:139521 - phenolic radical donor](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:139521)
be added the relationship has_role CHEBI:17891 - donor, please?

Thanks,
Paola

**Comment by amalik01** [comment]
Now added. Thanks
