### ISSUE TITLE
CHEBI:148316 wrong name, add synonyms

### ISSUE THREAD

**Issue by rwst** [ebi-chebi/ChEBI#4408]
CHEBI:148316 is NOT a sodium salt, and is known as
- Sialyllacto-N-tetraose a
- LSTa

Ref.: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9235823/ (Table IV, Group II)

**Comment by amalik01** [comment]
The entry has now been fixed and the above synonyms added. Thank you.
