### ISSUE TITLE
More bile acid conjugation subtypes requested

### ISSUE THREAD

**Issue by DeniseSl22** [ebi-chebi/ChEBI#4414]
Dear reader,

For a pathway model I am currently working on, I would need some more specific identifiers to describe the different conjugation forms of bile acids. There are two entries in ChEBI which are linked to these proposed new entries, [bile acid glycine conjugate](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:36255) and [bile acid taurine conjugate](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:23219). These current entries are linked to the parent term [bile acid conjugate](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:36249) and could be extended with three more:

- [x] bile acid sulfate conjugate
- [x] bile acid glucuronide conjugate
- [x] bile acid hydroxylation conjugate

These different conjugation forms are mentioned in the following article:
_"The small amount of bile acids that have been modified by the addition of sulfate or glucuronide (S/U) are secreted by the multidrug resistance-associated protein-2 (MRP2; gene symbol ABCC2), whereas those modified by additional hydroxylation (H) are secreted by P-glycoprotein (MDR1; gene symbol ABCB1A)."_ [PMID 21103970](https://doi.org/10.1007%2F978-3-642-14541-4_4) .

The pathway model is located at WikiPathways ([WP5396](https://classic.wikipathways.org/index.php/Pathway:WP5396)).

Thank you in advance for your efforts! If any specific structures would need to be linked to the three suggested entries above, please do not hesitate to reach out to me.

**Comment by amalik01** [comment]
3 new entries have now been created:
bile acid sulfate conjugate (CHEBI:195349)
bile acid hydroxylation conjugate (CHEBI:195351)
bile acid glucuronide conjugate (CHEBI:195350)

**Comment by DeniseSl22** [comment]
Thank you very much @amalik01 ! I will integrate these in the pathway model asap
