### ISSUE TITLE
ChEBI: 27923 and ChEBI: 145393 - missing acid/base relationship?

### ISSUE THREAD

**Issue by deustp01** [ebi-chebi/ChEBI#4420]
CHEBI:27923 - 2-acyl-sn-glycero-3-phosphoglycerol is marked "preliminary" and is shown as an uncharged molecule, while CHEBI:145393 - 2-acyl-sn-glycero-3-phosphoglycerol(1−) is marked as a "third-party annotation". 145393 looks like it should be major microspecies of this entity at pH 7.3. Can the acid - conjugate base relationship between 27923 and 145393 be added to these annotations?

**Comment by amalik01** [comment]
The conjugate acid/base relationships between the two entries have now been added.
