### ISSUE TITLE
Where are the KEGG references?

### ISSUE THREAD

**Issue by sorenwacker** [ebi-chebi/ChEBI#4422]
I wonder where I can find the KEGG IDs in the downloadable files. I looked in the reference.csv file, but 

```
0 ACToR
1 ArrayExpressAtlas
2 BKMS-react
3 BRENDA
4 BRENDALigand
5 BindingDB
6 BioModels
7 CarotenoidsDatabase
8 ChEMBL
9 CompTox
10 EnzymePortal
11 GeneOntology
12 Golm
13 IEDB
14 IntAct
15 IntEnz
16 MassBank
17 MetaboLights
18 NMRShiftDB
19 NURSA
20 PDB
21 Patent
22 PubChem
23 Reactome
24 Rhea
25 SABIO-RK
26 SureChEMBL
27 SwissLipids
28 UniProt
29 VirtualMetabolicHuman
```

It does not seem to contain KEGG for some reason? Since, the KEGG IDs are displayed in the online portal, I thought they will be part of the files as well.

**Comment by amalik01** [comment]
These are the automatic cross-references. KEGG accessions are added manually to ChEBI and found in the database_accession.tsv file (https://ftp.ebi.ac.uk/pub/databases/chebi/Flat_file_tab_delimited/)

**Comment by sorenwacker** [comment]
Thanks!
