### ISSUE TITLE
Link to isotopically labelled compound missing.

### ISSUE THREAD

**Issue by sorenwacker** [ebi-chebi/ChEBI#4423]
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:176631

https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:176632

https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:176633

Should be linked to isotopically modfied compound

**Comment by amalik01** [comment]
Hi Soren,

All of these ChEBI ID's are classified as isotopically modified compounds within the ontology. We do not need to add the relationship directly to these ChEBI ID's as they inherit the class from their parent terms.

For example CHEBI:176631 is a aspartic acid-1,4-13C2 (CHEBI:176633) which is a 13C-modified compound (CHEBI:139357) which is a  isotopically modified compound (CHEBI:139358).
