### ISSUE TITLE
azoxybenzene

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#4430]
Please add and correct the IUPAC names in two isomers of azoxybenzene.

_cis_-azoxybenzene ([CHEBI:51868](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A51868))
[(_E_)-_NNO_-azoxy]benzene --> [(_E_)-phenyl-_NNO_-azoxy]benzene
Add: (_E_)-diphenyldiazene oxide

_trans_-azoxybenzene ([CHEBI:51866](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A51866))
[(_Z_)-_NNO_-azoxy]benzene --> [(_Z_)-phenyl-_NNO_-azoxy]benzene
Add: (_Z_)-diphenyldiazene oxide

Cf. IUPAC names for azoxybenzene ([CHEBI:51865](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A51865)):
(phenyl-_NNO_-azoxy)benzene
diphenyldiazene oxide (PIN)

Blue Book gives more names for azoxybenzene, e.g. for pentacoordinate nitrogen as in C<sub>6</sub>H<sub>5</sub>&ndash;N=N(=O)&ndash;C<sub>6</sub>H<sub>5</sub>: 
1-oxo-1,2-diphenyl-1λ<sup>5</sup>-diazene 
1,2-diphenyl-1λ<sup>5</sup>-diazen-1-one
and another for "zwitterion" C<sub>6</sub>H<sub>5</sub>&ndash;N=N<sup>+</sup>(&ndash;O<sup>−</sup>)&ndash;C<sub>6</sub>H<sub>5</sub>:
(diphenyldiazeniumyl)oxidanide

**Comment by amalik01** [comment]
Now fixed.
