### ISSUE TITLE
Incorrect synonym type for 2 WURCS notations?

### ISSUE THREAD

**Issue by paola-scibite** [ebi-chebi/ChEBI#4431]
Hi,

I noticed that all >10k WURCS notations in ChEBI are entered as related synonyms, except for these 2, which are exact synonyms and have IUPAC as dbxref (and IUPAC_name as synonym type). Are these mistakes, please?

'beta-D-Xylp-(1->3)-beta-D-GlcpA' <http://purl.obolibrary.org/obo/CHEBI_149024>

'beta-D-Xylp-(1->4)-beta-D-Glcp' <http://purl.obolibrary.org/obo/CHEBI_146845>

Thanks,

Paola

**Comment by amalik01** [comment]
This has now been fixed.  Thanks
