### ISSUE TITLE
CHEBI:44859, please update CHEBI name and structure and CHECK compound

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#4432]
Hi Adnan

Please update and CHECK CHEBI:44859 1-MYRISTOYL-2-HYDROXY-SN-GLYCERO-3-[PHOSPHO-RAC-(1-GLYCEROL)] as we need this compound for a reaction in Rhea.
The name is wrong, it should be "3-palmitoyl-<ital>sn</ital>-glycero-1-phospho-(1'-<ital>sn</ital>-glycerol)(1<minus/>)"
A definition could be: A 3-acyl-<ital>sn</ital>-glycero-1-phospho-(1'-<ital>sn</ital>-glycerol)(1<minus/>) in which the acyl group is specified as hexadecanoyl (palmitoyl); major species at pH 7.3.
The compound is mentioned in pmid:37708259
CHEBI:44859 is-a CHEBI:78211 1-acylglycero-3-phospho-1'-glycerol(1<minus/>)
I have attached the molfile of the structure.
[CHEBI_44859.txt](https://github.com/ebi-chebi/ChEBI/files/12817984/CHEBI_44859.txt)

Thank you in advance.
Best,
Kristian

**Comment by amalik01** [comment]
Now checked.
