### ISSUE TITLE
CHEBI:30780 'maleate(2-)' has a highly ambiguous synonym

### ISSUE THREAD

**Issue by paola-scibite** [ebi-chebi/ChEBI#4433]
Morning,

CHEBI:30780 'maleate(2-)' has a related synonym "male", with IUPAC as dbxref.
May I suggest to remove it please, as it is highly ambiguous. Is it even correct?

Thanks,

Paola

**Comment by amalik01** [comment]
The synonym seems fine even though it is highly ambiguous.
Maleic acid (CHEBI:18300) has the synonym H2male (H2 indicates that both carboxy groups have hydrogens attached)
Maleate(1-) (CHEBI:37156) has the synonym Hmale (H indicates that one of the carboxy groups has a hydrogen attached)
Maleate(2-) (CHEBI:30780) has the synonym male (here there are no hydrogens hence structure is completely deprotonated).
