### ISSUE TITLE
CHEBI:189678 'modulator': merge with CHEBI:90710 'receptor modulator'?

### ISSUE THREAD

**Issue by paola-scibite** [ebi-chebi/ChEBI#4434]
Hi again,

CHEBI:189678 'modulator', annotated by a third party, is defined as "a group of substances that bind to a receptor to change that receptor's response to stimulus" and placed in the 'chemical entity' branch rather than the 'role' branch. It has no children. Should it be merged with (or obsoleted in favour of) CHEBI:90710 'receptor modulator'?

Thanks,

Paola

**Comment by amalik01** [comment]
Both entries have now been merged.
