### ISSUE TITLE
Addition of "NMR solvent" (CHEBI:197449) as new role for NMR solvent via "has role" property

### ISSUE THREAD

**Issue by hujo91** [ebi-chebi/ChEBI#4435]
Dear ChEBI team,

we as NFDI4Chem suggest adding the term ["NMR solvent" (CHEBI:197449)](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:197449) as a role via the "has role" property to the ChEBI terms listed below to allow the selection of NMR solvents.

Terms for which ["NMR solvent" (CHEBI:197449)](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:197449) should be added via the "has role" property:

- [x] ["acetone d6" (CHEBI:78217)](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:78217)
- [x] ["acetonitrile-d3" (CHEBI:193038)](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:193038)
- [x] ["benzene-d6" (CHEBI:193039)](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:193039)
- [x] ["deuterated chloroform" (CHEBI:85365)](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:85365)
- [x] ["dideuterium oxide" (CHEBI:41981)](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:41981)
- [x] ["N,N-dimethylformamide-d7" (CHEBI:193040)](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:193040)
- [x] ["dimethyl sulfoxide-d6" (CHEBI:193041)](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:193041)
- [x] ["methanol-d4" (CHEBI:156265)](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:156265)
- [x] ["dichloromethane-d2" (CHEBI:193042)](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:193042)
- [x] ["ethanol-d6" (CHEBI:193043)](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:193043)
- [x] ["nitrobenzene-d5" (CHEBI:193044)](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:193044)
- [x] ["nitromethane-d3" (CHEBI:193045)](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:193045)
- [x] ["pyridine-d5" (CHEBI:193046)](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:193046)
- [x] ["oxolane-d8" (CHEBI:193047)](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:193047)
- [x] ["toluene-d8" (CHEBI:193048)](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:193048)
- [x] ["acetic acid-d4" (CHEBI:193049)](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:193049)
- [x] ["trifluoroacetic acid-d1" (CHEBI:193050)](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:193050)
- [x] ["trichlorofluoromethane" (CHEBI:48236)](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:48236)
- [x] ["1,1,2-Trichlorotrifluoroethane" (CHEBI:193131)](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:193131)
- [x] ["formic acid-d2" (CHEBI:193132)](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:193132)
- [x] ["methanol-d1" (CHEBI:193133)](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:193133)
- [x] ["1,1,2,2-tetrachlorethane-d2" (CHEBI:193134)](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:193134)
- [x] ["dimethyl ether-d6" (CHEBI:193135)](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:193135)
- [x] ["fluorosulfonic acid" (CHEBI:193136)](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:193136)
- [x] ["antimony pentafluoride" (CHEBI:193146)](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:193146)
- [x] ["bromine pentafluoride" (CHEBI:193148)](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:193148)

Thanks a lot!

**Comment by amalik01** [comment]
Now added. Thanks

**Comment by hujo91** [comment]
Thank you so much that went so super fast :-)
