### ISSUE TITLE
CHEBI:219363, CHEBI:219367, and CHEBI:219386 are all Identical

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#4442]
Hi Adnan,

There is an error in a recent Metabolights submission, as they have submitted the same compound three times with different names, i.e. Reedsmycin A, Reedsmycin B, and Reedsmycin E.

InChI keys and IUOAC anmes are identical.

Cheers,
Kristian

**Comment by amalik01** [comment]
Now fixed.
