### ISSUE TITLE
Missing is_a relationship between CHEBI:83813 (proteinogenic amino acid) and CHEBI:33709 (amino acid)

### ISSUE THREAD

**Issue by edwong57** [ebi-chebi/ChEBI#4446]
CHEBI:83813 (proteinogenic amino acid) is missing the amino acid (CHEBI:33709) parent term. It is currently not a child of CHEBI:33709 (amino acid), however CHEBI:83820 (non-proteinogenic amino acid) is. Could you please add this relationship to CHEBI:83813?

**Comment by amalik01** [comment]
Now added. Thanks
