### ISSUE TITLE
CHEBI:87717 wrong definition

### ISSUE THREAD

**Issue by ANiknejad** [ebi-chebi/ChEBI#4449]
Hi ChEBI Team,

https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:87717

(2E,7Z)-**hexadeca**dienoyl-CoA(4-)
--
 
Definition | A polyunsaturated fatty acyl-CoA(4−) obtained by deprotonation of phosphate and diphosphate OH groups of (2E,7Z)-**tetradeca**dienoyl-CoA; major species at pH 7.3.

Please consider correcting the definition.
BTW I am looking for '(2E,7Z)-tetradecadienoyl-CoA', not (yet) in ChEBI, I am currently checking the literature about this compound, but any help from your side will be welcome!
It exists CHEBI:88067 (2E,5Z)-tetradecadienoyl-CoA

Thank you and Happy new year!

Anne

**Comment by amalik01** [comment]
The definition has been updated.

Regarding the (2E,7Z)-isomer. I can find entries for this compound in Lipid Maps (https://www.lipidmaps.org/databases/lmsd/LMFA07050477?LMID=LMFA07050477) and Metabolomics workbench (https://www.metabolomicsworkbench.org/data/StructureData.php?RegNo=199979). However, I'm unable to find any publications which mention this compound.
