### ISSUE TITLE
 Addition of "NMR chemical shift reference compound" (CHEBI:228364) as new role to compounds

### ISSUE THREAD

**Issue by NRayya** [ebi-chebi/ChEBI#4450]
Dear ChEBI team,

we as NFDI4Chem suggest adding the term ["NMR chemical shift reference compound" (CHEBI:228364)](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A228364&conversationContext=8) as a role via the "has role" property to the ChEBI terms listed below:

- [ ] [CHEBI:47032 - 1,4-dioxane](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:47032)
- [ ] [CHEBI:85365 - deuterated chloroform](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:85365)
- [ ] [CHEBI:85363 - sodium 3-(trimethylsilyl)propionate](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:85363)
- [ ] [CHEBI:55317 - tetramethylammonium bromide](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:55317)
- [ ] [CHEBI:85361 - tetramethylsilane](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:85361)
- [ ] [CHEBI:34856 - morpholine](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:34856)
- [ ] [CHEBI:16134 - ammonia](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:16134)
- [ ] [CHEBI:85364 - ammonium bromide](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:85364)
- [ ] [CHEBI:77701 - nitromethane](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:77701)
- [ ] [CHEBI:16227 - pyridine](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:16227)
- [ ] [CHEBI:63005 - sodium nitrate](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:63005)
- [ ] [CHEBI:55317 - tetramethylammonium bromide](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:55317)
- [ ] [CHEBI:228806 - 2,2-Dimethyl-2-silapentane-5-sulfonate](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A228806&conversationContext=7)
- [ ] [CHEBI:38472 - acetonitrile](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:38472)
- [ ] [CHEBI:32954 - sodium acetate](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:32954)
- [ ] [CHEBI:85486 - 3-(trimethylsilyl)propionate](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:85486)
- [ ] [CHEBI:26078 - phosphoric acid](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:26078)
- [ ] [CHEBI:46324 - trimethyl phosphate](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:46324)
- [ ] [CHEBI:183318 - triphenylphosphine](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:183318)
- [ ] [CHEBI:36601 - triphenylphosphane oxide](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:36601)

[The list comes from nmrCV ](https://terminology.nfdi4chem.de/ts/ontologies/nmrcv/terms?iri=http%3A%2F%2FnmrML.org%2FnmrCV%23NMR%3A1400033)

Thanks a lot.

**Comment by amalik01** [comment]
All of the above compounds have now been added. I have also added additional 19F NMR reference standards to the list.
