### ISSUE TITLE
Cyclooctene

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#4451]
The structure of Cyclooctene ([CHEBI:225365](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A225365)) is that of _cis_-cyclooctene; PIN: (_Z_)-cyclooctene; so please rename it to _cis_-cyclooctene, as opposed to _trans_-cyclooctene ([CHEBI:73156](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A73156)), PIN: (_E_)-cyclooctene
(See _Blue Book_, [P-44.4.1.12.1](https://iupac.qmul.ac.uk/BlueBook/P4.html#4404011201))

In  _trans_-cyclooctene ([CHEBI:73156](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A73156)), correct the typo: "eight-memberecd" --> "eight-membered"
 
Ontology-wise: please create a parent term "cyclooctene" so that

cyclooctene **is a** cycloalkene ([CHEBI:33643](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A33643))
_cis_-cyclooctene ([CHEBI:225365](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A225365)) **is a** cyclooctene
_trans_-cyclooctene ([CHEBI:73156](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A73156)) **is a** cyclooctene

and remove Cyclooctene ([CHEBI:225365](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A225365)) **is a** cyclic olefin ([CHEBI:33642](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A33642)) (it will be redundant)

Corresponding Wikipedia links: 
https://en.wikipedia.org/wiki/Cyclooctene
https://en.wikipedia.org/wiki/Cis-Cyclooctene
https://en.wikipedia.org/wiki/Trans-Cyclooctene

**Comment by amalik01** [comment]
Thanks. The entries have now been fixed.

cyclooctene (CHEBI:225365)
cis-cyclooctene (CHEBI:229204)
trans-cyclooctene (CHEBI:73156)
