### ISSUE TITLE
CHEBI:40021 is actually CHEMBL41632, tiratricol (TRIAC)

### ISSUE THREAD

**Issue by ANiknejad** [ebi-chebi/ChEBI#4452]
Hello ChEBI Team,

see https://en.wikipedia.org/wiki/Tiratricol

I was trying to submit CHEMBL41632 to chebi via the submission tool (https://www.ebi.ac.uk/chebi/submission/home),  using the mol file of CHEMBL41632 such as available at

https://www.ebi.ac.uk/chembl/g/#search_results/all/query=CHEMBL41632

However the submission tool says 'Structure is not unique, see [CHEBI:40021](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:40021)' , but the chebi Advanced search (https://www.ebi.ac.uk/chebi/advancedSearchFT.do) does not retrieve chebi:40021 when using this same mol file.

Could you update chebi:40021 in order to have a chebi id for tiratricol?

Many thanks in advance

Anne

**Comment by amalik01** [comment]
The entry was present in the database as a 1-star entry.  1-star entries in ChEBI are not searchable on the ChEBI website unless they have been annotated, however the submission tool detects them to prevent duplicate structures from being submitted.

I have now updated ChEBI:40021 - The entry will be searchable on the ChEBI website by tomorrow.
