### ISSUE TITLE
CHEBI:72342 and CHEBI:46060are identical, please merge

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#4456]
Hi Adnan,

The two above compounds are both (1S,2S,3R,5S)-3,5-diammoniocyclohexane-1,2-diol with the InChIKey QOLDZWBHLDQIJR-FSIIMWSLSA-P 

Please merge them.
Best wishes,
Kristian

**Comment by amalik01** [comment]
Now merged. Thanks
