### ISSUE TITLE
please delete (or merge?) CHEBI:176978 (submitted by MetaboLights), this is actually CHEBI:70713

### ISSUE THREAD

**Issue by ANiknejad** [ebi-chebi/ChEBI#4457]
Hello ChEBI Team,

CHEBI:176978
5-cis-8-cis-Tetradecadienoyl-CoA
Submitter | MetaboLights
2-stars
 
has to be merged or remove, the correct CHEBI is 

CHEBI:70713 cis,cis-tetradeca-5,8-dienoyl-CoA

Thank you!

Anne

**Comment by amalik01** [comment]
Both entries now merged. Thanks
