### ISSUE TITLE
Weird Unicode characters

### ISSUE THREAD

**Issue by smoretti** [ebi-chebi/ChEBI#4463]
Hi
I found some weird Unicode characters in the following ChEBI names or synonyms:
- CHEBI:218817    In the name, between the 4 and the - characters, there is a NULL character.
- CHEBI:227899   In the name, the first 2 and 6 characters have a ' at their top. Is it normal?
- CHEBI:209316   In the name, the weird characters between 'alpha' and '-D' should not be there.

Thanks

**Comment by amalik01** [comment]
All 3 entries have now been fixed. Thanks
