### ISSUE TITLE
CHEBI:73117 structure is wrong

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#4464]
Hi Adnan,

CHEBI:73117 is 1-hexadecanoyl-2-(5Z,8Z,11Z,14Z-icosatetraenoyl)-sn-glycero-3-phosphoethanolamine while
CHEBI:73009 is 1-hexadecanoyl-2-(5Z,8Z,11Z,14Z-icosatetraenoyl)-sn-glycero-3-phosphoethanolamine zwitterion
Both entries have the relationship: CHEBI:73009 is a tautomer of CHEBI:73117.
The error is that CHEBI:73117 has the tautomer structure so the two entries have identical structures. 
I have attached the correct structure that has no charges.
[CHEBI_73117.txt](https://github.com/ebi-chebi/ChEBI/files/13989644/CHEBI_73117.txt)

Best wishes,
Kristian

**Comment by amalik01** [comment]
Now fixed. Thanks
