### ISSUE TITLE
CHEBI:77093 and CHEBI:87223 are identical, please merge. Both compounds are 3-star

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#4465]
Hi Adnan,

The two above compounds are both 1-icosanoyl-2-arachidonoyl-sn-glycerol with the InChIKey OUGXERRDRINUQU-AICYSBPGSA-N 
Please merge them. 

Best wishes,
Kristian

**Comment by amalik01** [comment]
Now merged. Thanks
