### ISSUE TITLE
Strucutre not being saved in some submissions

### ISSUE THREAD

**Issue by NRayya** [ebi-chebi/ChEBI#4466]
Hello,

I have tried adding a strucutre for [this submission ](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A229454&conversationContext=8 ) several times but it didn't get saved. So I would like to report:

- [ ] Need to add strucutre to the mentioned compound ([same as here](https://pubchem.ncbi.nlm.nih.gov/compound/Yttrium-nitrate.))
- [ ] A bug in saving drawn structures

**Comment by amalik01** [comment]
Hi,
When you pasted the MOL or SDF file in the structure editor, did you click update properties?

**Comment by amalik01** [comment]
I have now added a structure to the entry

**Comment by NRayya** [comment]
Sorry for the late response.
I drew the structure manually, and update properties didn't work for me.
I did a lot of rotation and cleaning of the structure. I don't know if it caused a bug

**Comment by amalik01** [comment]
Possibly a bug.
