### ISSUE TITLE
NTR: Environmentally Persistent Free Radicals

### ISSUE THREAD

**Issue by diatomsRcool** [ebi-chebi/ChEBI#4468]
Label: Environmentally Persistent Free Radicals
Synonym: EPFR
Parent Class: Persistent Organic Pollutant CHEBI:77853
Definition: A persistent organic pollutant which is composed of organic free radicals stabilized on or inside other particles
Definition Source: PMC7330507

**Comment by amalik01** [comment]
A new entry for environmentally persistent free radical (CHEBI:229460) has now been created. The entry should be searchable on the ChEBI website by tomorrow.
