### ISSUE TITLE
Incorrect CAS number for CHEBI:195767

### ISSUE THREAD

**Issue by bgyori** [ebi-chebi/ChEBI#4469]
For CHEBI:195767 (2-Methyl-4-phenyl-2-butanol), the CAS number [0103-05-09](https://commonchemistry.cas.org/detail?cas_rn=0103-05-09) is provided. The correctly formatted CAS number would be [103-05-9](https://commonchemistry.cas.org/detail?cas_rn=103-05-9).

**Comment by amalik01** [comment]
Now fixed. Thanks
