### ISSUE TITLE
currently no relationships between CHEBI:70800 and CHEBI:70783

### ISSUE THREAD

**Issue by ANiknejad** [ebi-chebi/ChEBI#4478]
Hi ChEBI Team,

As an user, I would like having a direct relation between this 2 compounds (is conjugate acid of/is conjugate base of )

CHEBI:70800 CDP-4-dehydro-3,6-dideoxy-α-D-glucose
CHEBI:70783 CDP-4-dehydro-3,6-dideoxy-α-D-glucose(2−)

the fact that CHEBI:70800 has currently only the relationship
`CDP-4-dehydro-3,6-dideoxy-α-D-glucose (CHEBI:70800) is a CDP-4-dehydro-3,6-dideoxy-D-glucose ([CHEBI:17817)`
makes me wondering if
CHEBI:58283 CDP-4-dehydro-3,6-dideoxy-D-glucose(2-) (no reaction associated to this compound)
AND
CHEBI:70783 CDP-4-dehydro-3,6-dideoxy-α-D-glucose(2−) (https://www.rhea-db.org/rhea/19653)
should be merged?

Many thanks in advance for your help.

Anne

**Comment by amalik01** [comment]
Hi Anne,

The conjugate acid/base relationship has been added for CHEBI:70800 and CHEBI:70783.

CHEBI:58283 and CHEBI:70783 cannot be merged since they are different structures. One of the entries has an α-D-glucose moiety in the structure and the other has a D-glucose moiety.
