### ISSUE TITLE
CHEBI:219774, error in structure and formula

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#4479]
Hi Adnan,

The compound CHEBI:219774, bonnadiene, has an error in the structure as there is a methyl group too many. You can compare the structure with that of CHEBI:192983 ent-bonnadiene to see the error. I have attached the correct structure. I have traced the error to ChemSpider that cites pmid:29758116 that depicts the structure I have attached. Another article supporting me in that the current structure is an error is pmid:36757147.

I hope you have time to correct this error soon as I need the compound for a new reaction which is also based on pmid:29758116.
[CHEBI_219774.txt](https://github.com/ebi-chebi/ChEBI/files/14295823/CHEBI_219774.txt)

Best,
Kristian

**Comment by amalik01** [comment]
Now fixed. Thanks
