### ISSUE TITLE
CHEBI:219780, please Check

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#4480]
Hi Adnan,

As I need allokutznerene for a new reaction I would be happy if you would check the compound. I have attached a nicer depiction of the structure.

[CHEBI_219780.txt](https://github.com/ebi-chebi/ChEBI/files/14295781/CHEBI_219780.txt)

Best, 
Kristian

**Comment by amalik01** [comment]
Now checked. Thanks
