### ISSUE TITLE
missing relationship between CHEBI:10502 and CHEBI:63262

### ISSUE THREAD

**Issue by ANiknejad** [ebi-chebi/ChEBI#4481]
hello ChEBI Team,

CHEBI:10502 dTDP-3-amino-3,4,6-trideoxy-alpha-D-glucose
is UniProt synonym of CHEBI:63262 dTDP-3-azaniumyl-3,4,6-trideoxy-alpha-D-glucose(1-)
but there is no relationships such as is conjugate acid of/is conjugate base between these 2 compounds, could you please update these compounds?
Many thanks in advance,

Anne

**Comment by amalik01** [comment]
Now added. Thanks
