### ISSUE TITLE
CHEBI:88072, wrong relationship

### ISSUE THREAD

**Issue by ANiknejad** [ebi-chebi/ChEBI#4486]
Hello ChEBI Team,

CHEBI:88072 (3**S**,5Z)-3-hydroxytetradec-5-enoyl-CoA
has currently

> Outgoing	(3S,5Z)-3-hydroxytetradec-5-enoyl-CoA CHEBI:88072 is a (**R**)-3-hydroxyacyl-CoA CHEBI:15456

Should have the same relationship such as correct in its conjugate base CHEBI:87705

--> is a (**S**)-3-hydroxyacyl-CoA(4−) CHEBI:57318

**Comment by amalik01** [comment]
The entry has now been fixed - There were quite a few redundant relationships present which have also been removed.
Thank you
