### ISSUE TITLE
Add NMR solvent role to hexafluorobenzene

### ISSUE THREAD

**Issue by NRayya** [ebi-chebi/ChEBI#4487]
Dear ChEBI team,

we as NFDI4Chem suggest adding the term [NMR solvent (CHEBI:197449)](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:197449) as a role via the "has role" property to the ChEBI term[ hexafluorobenzene (CHEBI:38589) ](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:38589).

Thanks

**Comment by amalik01** [comment]
now added. thanks
