### ISSUE TITLE
Correct entry CHEBI:229458 - titan(III)-nitrate

### ISSUE THREAD

**Issue by NRayya** [ebi-chebi/ChEBI#4488]
I have earlier submitted this entry: https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:229458. However, by mistake I mixed Tl (Thallium) with Ti (Titanium). So the entry name should be corrected to "Thallium(III) nitrate". And the relation "titan(III)-nitrate ([CHEBI:229458](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A229458)) is a titanium coordination entity ([CHEBI:51004](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A51004))" should be removed. 

Sorry for the inconvenience.

**Comment by amalik01** [comment]
Now fixed. Thanks
