### ISSUE TITLE
to merge CHEBI:74106 and CHEBI:80548

### ISSUE THREAD

**Issue by ANiknejad** [ebi-chebi/ChEBI#4494]
Hello ChEBI Team,

these compounds can be merged, I guess, thank you in advance.

Anne

---------------

CHEBI:74106
erucoyl-CoA
Synonym 13Z-docosenoyl-CoA

(2-stars) CHEBI:80548 Docosenoyl-CoA
Synonym (13Z)-Docosenoyl-CoA

**Comment by amalik01** [comment]
Now merged. Thanks
