### ISSUE TITLE
Adding new term to ChEBI Submission Tool using structure broken

### ISSUE THREAD

**Issue by cerivs** [ebi-chebi/ChEBI#4496]
As you can see from the image the ChEBI Submission Tool If I upload a MOL file the tool isn't calculating a Chemical formula, Average Mass,  InChI or InChIKey.   The uploaded file isn't being displayed if the submission is given a record see CHEBI:231400 - 6-nitro-2-octyl-2H-chromene and frequently the submission fails with the error  

    Error during submission - could not execute statement; SQL [n/a]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement Caused by:ORA-01400: cannot insert NULL into ("CHEBI"."IMAGE_PRECOMPUTES"."IMAGE") 

![image](https://github.com/ebi-chebi/ChEBI/assets/2602957/e9b47984-1215-4856-aa10-9b3c7efa0fe6)

**Comment by amalik01** [comment]
I hope this issue has now been resolved as discussed via e-mail. I think the issue arises due to the uploading of an incompatible MOL file.
