### ISSUE TITLE
Wrong description CHEBI:25387

### ISSUE THREAD

**Issue by eriksson1800** [ebi-chebi/ChEBI#4498]
Hi,
i have a suggestion to change the definition of the class `25387` from 

> "A hydroxyacetophenone carrying at least one hydroxy substituent."

 to 

> "A hydroxyacetophenone carrying exactly one hydroxy substituent."

Best regards,
Erik

**Comment by amalik01** [comment]
definition now updated to:
A hydroxyacetophenone carrying a single hydroxy substituent.
