### ISSUE TITLE
Wrong classification of CHEBI:146179 and CHEBI:146848

### ISSUE THREAD

**Issue by eriksson1800** [ebi-chebi/ChEBI#4499]
Hi,
I have a found a possible mistake in the ontology of the class `146179` (galactotriose). It is currently classified as a disaccharide as well as a trisaccharide. As the definition suggests, it should only be classified as a trisaccharide `27150`.

Moreover, the class `146848` (selaginose) is classified as a glycosyl glycoside and a trisaccharide, where the definition says it is a glycosyl glycoside derivative. Because the molecule contains three monosaccharides connected at their anomeric centers, it should only be classified as a trisaccharide or at least as an glycosyl glycoside derivative `63356`.

Best regards, 

Erik

**Comment by amalik01** [comment]
The two entries have now been fixed. Thanks
