### ISSUE TITLE
Ontology recommendations for new subclasses

### ISSUE THREAD

**Issue by eriksson1800** [ebi-chebi/ChEBI#4500]
Hi,
I have two suggestions for new subclasses.
First I would like to suggest adding the class "saturated fatty acyl CoA", as the counterpart to the existing class "unsaturated fatty acyl-CoA" `51006`.

Second, I would like to suggest adding the class "unsaturated fatty aldehyde", as the counterpart to the existing class "saturated fatty aldehyde" `133249`.

Best regards, 

Erik

**Comment by amalik01** [comment]
Both classes have now been created:
saturated fatty acyl CoA - CHEBI:231546
unsaturated fatty aldehyde - CHEBI:231547
