### ISSUE TITLE
acyl-CoA (CHEBI:17984) should not be is_a adenosine 3',5'-bisphosphate (CHEBI:37240)

### ISSUE THREAD

**Issue by ValWood** [ebi-chebi/ChEBI#4503]
acyl-CoA (CHEBI:17984)
should not be is_a adenosine 3',5'-bisphosphate (CHEBI:37240)

This causes true path violations (incorrect superclasses) in GO
but we are not sure what the correct parent should be.

see
https://github.com/geneontology/go-ontology/issues/27724#issuecomment-2136673120

**Comment by amalik01** [comment]
Hi @ValWood 

There are several articles that classify coenzyme A as modified ribonucleotides (see example: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6850382/). I have decided to move both coenzyme A and acyl-CoA from the adenosine 3’,5’-biphosphate class to adenyl nucleotide class (a less specific class). I hope this does not cause any violations. ChEBI's classification is now aligned with MeSH classification of coenzyme A.

![image](https://github.com/ebi-chebi/ChEBI/assets/41328040/87fb2ab5-5897-46eb-9519-eef0c3fdbd1b)

**Comment by ValWood** [comment]
Hi @amalik01 

derived from pantothenic acid (vitamin B5), which includes a 3'-phosphoadenosine diphosphate (3'-phospho-ADP) moiety, a pantothenic acid unit, and a terminal thiol group (-SH) that binds to the acetyl group.
SO it seems more that AcetylCO-A is a modified pantothenic acid.

While acetyl-CoA contains an adenosine moiety, which is also found in ATP (a nucleotide), its primary function and overall structure differ significantly from that of nucleotides.

This situation seems similar to carbohydrate derivatives,  and amino acid derivatives, these are not classified as carbohydrates or amino acids in CHEBI.

Biologists wouldn’t class acetyl-CoA as a nucleotide. 
Nucleotides, specifically  consist of three components:
	•	A nitrogenous base (adenine, thymine, cytosine, guanine, or uracil)
	•	A five-carbon sugar (ribose in RNA and deoxyribose in DNA)
	•	One or more phosphate groups

The effect on GO is to place all 928,000 genes annotated to acyl-CoA metabolic process

as nucleotide metabolic processes which seems biologically incorrect?


CC @pgaudet

**Comment by ValWood** [comment]
see
https://www.ebi.ac.uk/chebi/chebiOntology.do?chebiId=CHEBI:83821
"amino acid derivative" aka  "modified amino acid" is not a subclass of "amino acid"
Can you do the same for "nucleotide derivative"?

**Comment by amalik01** [comment]
Hi Val,
Historically, coenzyme A has been classed as a nucleotide coenzyme since its structure contains a nucleotide moiety.
I have contacted IUPAC to get their opinion on this before I start making any changes to the ontology - Waiting to hear from them.

**Comment by ValWood** [comment]
It is definitely a "nucleotide coenzymes", but the nucleotide coenzymes are "modified ribonucleotides" or "nucleotide derivative", it could be classed as a "nucleotide coenzymes", but a "nucleotide coenzymes" should be a "nucleotide derivative".

**Comment by ValWood** [comment]
Note that all of the other nucleotide ATP/NAD/NADH etc co-enzymes are nucleotides as well as nucleotide coenzymes

**Comment by amalik01** [comment]
I have created a class called 'nucleotide derivative' and have placed both CoA and acyl-CoA under this class. Both entries are no longer classified as nucleotides. The changes will be visible in the downloadable files in next months release.

**Comment by ValWood** [comment]
That's. great, thanks!
