### ISSUE TITLE
nmrCV calibration compound vs reference compound confusion reflected in CHEBI - unasign roles 

### ISSUE THREAD

**Issue by NRayya** [ebi-chebi/ChEBI#4504]
Dear ChEBI team,

we as NFDI4Chem has been working on curating NMR calibration compounds in nmrCV which lead us to find some errors there, mainly confusing the two concepts "calibration compound" and "reference compound, the peak shift is 0". As some of the definitions and entries were [added to CHEBI referencing nmrCV](https://github.com/ebi-chebi/ChEBI/issues/4450), here you can find all the needed corrections and enhancements:

- [ ] [CHEBI:228364 - NMR chemical shift reference compound](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A228364&conversationContext=8) definition:  A compound that produces the peak used as reference frequency in the δ chemical shift scale. 
  - [Old definition](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A228364&conversationContext=8) included "data pre-processing" which isn't always true.
  
- [ ] Remove the role **reference compound** from the following list. Some came from [nmrCV and some were added by CHEBI team](https://github.com/ebi-chebi/ChEBI/issues/4450). However, this list is in actuality a collection of solvents, calibration compounds, and others, not references. While all reference compounds can be found in IUPAC recommendations [1](https://www.degruyter.com/document/doi/10.1351/pac200173111795/html), [2](https://www.degruyter.com/document/doi/10.1351/pac200880010059/html):
  - [ ] [CHEBI:47032 - 1,4-dioxane](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:47032)
  - [ ] [CHEBI:85365 - deuterated chloroform](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:85365)
  - [ ] [CHEBI:85363 - sodium 3-(trimethylsilyl)propionate](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:85363)
  - [ ] [CHEBI:55317 - tetramethylammonium bromide](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:55317)
  - [ ] [CHEBI:34856 - morpholine](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:34856)
  - [ ] [CHEBI:85364 - ammonium bromide](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:85364)
  - [ ] [CHEBI:16227 - pyridine](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:16227)
  - [ ] [CHEBI:63005 - sodium nitrate](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:63005)
  - [ ] [CHEBI:55317 - tetramethylammonium bromide](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:55317)
  - [ ] [CHEBI:228806 - 2,2-Dimethyl-2-silapentane-5-sulfonate](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A228806&conversationContext=7) 
    - The correct reference is the Sodium salt, which already has the role in CHEBI.
  - [ ] [CHEBI:38472 - acetonitrile](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:38472)
  - [ ] [CHEBI:32954 - sodium acetate](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:32954)
  - [ ] [CHEBI:85486 - 3-(trimethylsilyl)propionate](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:85486)
  - [ ] [CHEBI:183318 - triphenylphosphine](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:183318)
  - [ ] [CHEBI:36601 - triphenylphosphane oxide](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:36601)

The rest I believe came from CHEBI team for 19F, while[ the only reference there is CCl3F (IUPAC)](https://www.degruyter.com/document/doi/10.1351/pac200173111795/html), so they need to be removed too.

  - [ ] [CHEBI:36810 - (trifluoromethyl)benzene](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A36810)
  - [ ] [CHEBI:38585 - 1,4-difluorobenzene](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A38585)
  - [ ] [CHEBI:33093 - boron trifluoride](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A33093)
    -  check I[UPAC page 80 ](https://www.degruyter.com/document/doi/10.1351/pac200880010059/html)for Boron
  - [ ] [CHEBI:30236 - difluorine](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A30236)
  - [ ] [CHEBI:39429 - hexafluoroacetone](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A39429)
  - [ ] [CHEBI:38589 - hexafluorobenzene](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A38589)
  - [ ] [CHEBI:29228 - hydrogen fluoride](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A29228)
  - [ ] [CHEBI:5115 - monofluorobenzene](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A5115)
  - [ ] [CHEBI:66872 - potassium fluoride](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A66872)
  - [ ] [CHEBI:30496 - sulfur hexafluoride](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A30496)
  - [ ] [CHEBI:45892 - trifluoroacetic acid](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A45892)

Our apologies if you are using a different source to assign the references other than IUPAC, then part of this issue will be invalid. 
Thanks a lot.

**Comment by amalik01** [comment]
@NRayya I have removed the above compounds from having the NMR chemical shift reference compound role (CHEBI:228364). Please double check the list again (https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:228364). If anything else needs removing, let me know. Thanks

**Comment by NRayya** [comment]
Dear @amalik01 
I checked the list and it is accurate, thanks a lot

**Comment by amalik01** [comment]
great, thanks. I am closing this issue.
