### ISSUE TITLE
Norgestrel vs levonorgestrel: cross references unclear

### ISSUE THREAD

**Issue by cmpich** [ebi-chebi/ChEBI#4507]
the chebi term

CHEBI:7630 : norgestrel
has this CAS cross reference: CAS:6533-00-2

while the chebi term
CHEBI:6443 : levonorgestrel
has two CAS cross references: CAS:6533-00-2, CAS:797-63-7

It looks like the latter should not have the same cross reference as norgestrel, ie 
CAS:6533-00-2
should be removed. It has norgestrel as a functional_parent relationship.

**Comment by amalik01** [comment]
The CAS numbers have now been fixed. Thanks
