### ISSUE TITLE
CHEBI:71539, add synonym

### ISSUE THREAD

**Issue by ANiknejad** [ebi-chebi/ChEBI#4509]
Hello ChEBI Team,

CHEBI:71539
(8Z,11Z,14Z)-3-oxoicosa-8,11,14-trienoyl-CoA

should have synonym '3-oxodihomo γ-linolenoyl-CoA' or ' 3-oxodihomo gamma-linolenoyl-CoA'

please see https://biocyc.org/compound?orgid=META&id=CPD-14404

Cheers,

Anne

**Comment by amalik01** [comment]
now added. Thanks
