### ISSUE TITLE
CHEBI:173797 name and structure do not fit

### ISSUE THREAD

**Issue by ANiknejad** [ebi-chebi/ChEBI#4512]
hello ChEBI Team,

I am looking for '4(R),8-dimethyl-trans-2-nonenoyl-CoA' aka BiGG CE4806, aka 
https://www.vmh.life/#metabolite/CE4806

The metabolite currently available is 
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:173797
name is '4(R),8-dimethyl-trans-2-nonenoyl-CoA' but structure is dimethyl 3-oxopentanedioate

voilà, voilà...

**Comment by ANiknejad** [comment]
The mol file of CE4806 should be, I guess, this one here


  Ketcher 07112412252D 1   1.00000     0.00000     0

 60 62  0     1  0            999 V2000
   17.8692   -5.7129    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   17.0612   -5.1256    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   17.5606   -6.6630    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   16.2528   -5.7129    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   16.5617   -6.6630    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   18.1477   -7.4713    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    9.7006  -10.6062    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   10.5999  -11.1058    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    8.8353  -11.1058    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    7.9702  -10.6062    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    7.1049  -11.1058    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    8.8697   -9.1077    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    7.9702   -9.6072    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    8.8697   -8.1087    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    7.1393   -8.1087    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    8.0044   -7.6090    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    9.7348   -6.6100    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    8.3702   -5.2454    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    8.8697   -6.1105    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    9.3693   -5.2454    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    8.0044   -6.6100    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    7.1393   -6.1105    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   10.5999   -6.1105    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   12.5980   -6.1105    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   14.5961   -6.1105    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   11.5990   -5.1114    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   11.5990   -7.1095    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   13.5971   -5.1114    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   13.5971   -7.1095    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   11.5990   -6.1105    0.0000 P   0  0  0  0  0  0  0  0  0  0  0  0
   13.5971   -6.1105    0.0000 P   0  0  0  0  0  0  0  0  0  0  0  0
   15.3027   -5.4043    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   15.9742   -7.4713    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   14.9751   -8.4704    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   16.9733   -8.4704    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   15.9742   -8.4704    0.0000 P   0  0  0  0  0  0  0  0  0  0  0  0
   15.9742   -9.4694    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   18.8194   -5.4043    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   19.5620   -6.0727    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   19.2257   -4.4914    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   20.4271   -5.5733    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   19.5620   -7.0717    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   20.2194   -4.5958    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   21.2922   -6.0724    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   20.4271   -7.5710    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   21.2922   -7.0715    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   22.1573   -5.5730    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   11.4653  -10.6062    0.0000 S   0  0  0  0  0  0  0  0  0  0  0  0
   12.3304  -11.1058    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   12.3304  -12.1048    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   14.0607  -11.1058    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   14.9261  -10.6062    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   13.1956  -10.6062    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   15.7912  -11.1058    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   16.6565  -10.6062    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   17.5216  -11.1059    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   18.3867  -10.6064    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   19.2520  -11.1059    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   14.9261   -9.6072    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   18.3869   -9.6073    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1 38  1  1     0  0
  2  1  1  0     0  0
  3  1  1  0     0  0
  4  2  1  0     0  0
  5  3  1  0     0  0
  3  6  1  6     0  0
  4 32  1  1     0  0
  5  4  1  0     0  0
  5 33  1  6     0  0
  9  7  1  0     0  0
  7  8  1  0     0  0
  8 48  1  0     0  0
 10  9  1  0     0  0
 13 10  1  0     0  0
 10 11  2  0     0  0
 12 14  1  0     0  0
 13 12  1  0     0  0
 16 14  1  0     0  0
 16 15  2  0     0  0
 16 21  1  0     0  0
 19 17  1  0     0  0
 17 23  1  0     0  0
 19 18  1  0     0  0
 21 19  1  0     0  0
 19 20  1  0     0  0
 21 22  1  6     0  0
 23 30  1  0     0  0
 30 24  1  0     0  0
 24 31  1  0     0  0
 31 25  1  0     0  0
 32 25  1  0     0  0
 30 26  2  0     0  0
 30 27  1  0     0  0
 31 28  2  0     0  0
 31 29  1  0     0  0
 33 36  1  0     0  0
 36 34  1  0     0  0
 36 35  1  0     0  0
 36 37  2  0     0  0
 39 38  1  0     0  0
 40 38  1  0     0  0
 41 39  2  0     0  0
 42 39  1  0     0  0
 43 40  2  0     0  0
 44 41  1  0     0  0
 43 41  1  0     0  0
 45 42  2  0     0  0
 46 44  2  0     0  0
 47 44  1  0     0  0
 46 45  1  0     0  0
 48 49  1  0     0  0
 49 53  1  0     0  0
 49 50  2  0     0  0
 53 51  2  0     0  0
 51 52  1  0     0  0
 52 54  1  0     0  0
 54 55  1  0     0  0
 55 56  1  0     0  0
 56 57  1  0     0  0
 57 58  1  0     0  0
 52 59  1  6     0  0
 57 60  1  0     0  0
M  CHG  4  27  -1  29  -1  34  -1  35  -1
M  END

**Comment by ANiknejad** [comment]
why not possible to attach a mol file to the issue, BTW ?

**Comment by kaxelsen** [comment]
Change the extension to txt, then it is possible

**Comment by ANiknejad** [comment]
[CE4806_corrected copy.txt](https://github.com/user-attachments/files/16176103/CE4806_corrected.copy.txt)

**Comment by ANiknejad** [comment]
@kaxelsen I tried previously with .tsv, not working, but right .txt does, thanks a lot
Cheers,
Anne

**Comment by ANiknejad** [comment]
the issue is OPEN, CHEBI:173797 is a bad ChEBI representative!

**Comment by amalik01** [comment]
Hi @ANiknejad 

I have updated the name of CHEBI:173797 to dimethyl 3-oxopentanedioate
Please submit a new entry for 4(R),8-dimethyl-trans-2-nonenoyl-CoA.

**Comment by ANiknejad** [comment]
Thank you very much, Adnan!
I submitted _4(R),8-dimethyl-trans-2-nonenoyl-CoA (4-)_ CHEBI:231724.
