### ISSUE TITLE
Invalid Unicode in CHEBI:229934 name

### ISSUE THREAD

**Issue by smoretti** [ebi-chebi/ChEBI#4513]
Hi

The ChEBI name for CHEBI:229934 contains weird Unicode characters.

According to the IUPAC Name, the ChEBI name should be
`(2beta,3beta,5beta)-2,3-Diacetoxy-5,14-dihydroxy-19-oxobufa-20,22-dienolide`
not
`(2Î²,3Î²,5Î²)-2,3-Diacetoxy-5,14-dihydroxy-19-oxobufa-20,22-dienolide`

**Comment by amalik01** [comment]
Now fixed. The changes will be visible in the downloadable files in next month release.

Thanks
