### ISSUE TITLE
CHEBI:79972 and CHEBI:12755, to merge please

### ISSUE THREAD

**Issue by ANiknejad** [ebi-chebi/ChEBI#4514]
Hello ChEBI Team,

CHEBI:79972 (2-stars) is S-2-(Indol-3-yl)acetyl-CoA, xref https://www.genome.jp/dbget-bin/www_bget?cpd:C15489, and represents the same compound, CHEBI:12755 indol-3-ylacetyl-CoA, but has a non-canonical CoA part: the hydroxy of the panteic acid part is flat in CHEBI:79972.

Could you please manage to have both identifiers on the same correct compound CHEBI:12755 indol-3-ylacetyl-CoA?

Thank you

Anne

**Comment by amalik01** [comment]
Now merged. Thanks
