### ISSUE TITLE
Weird xrefs

### ISSUE THREAD

**Issue by smoretti** [ebi-chebi/ChEBI#4515]
Hi

Some ChEBI entries have xrefs that do not look to be well-formed
E.g. a KEGG glycan id not beginning by a G followed by 5 digits.

- CHEBI:177667 with KEGG glycan `G-7333`
- CHEBI:219179 with KEGG glycan `G-6302`
- CHEBI:166731 with KEGG glycan `G-5400`
- CHEBI:181014 with KEGG glycan `G-5300`
- CHEBI:230869 with KEGG glycan `G-2408`
- CHEBI:172478 with KEGG glycan `G-1029`
- CHEBI:231137 with KEGG glycan `G 4120`
- CHEBI:182994 with KEGG drug `D8008`
- CHEBI:170047 with KEGG drug `D2959`
- CHEBI:180605 with KEGG compound `C2339`
- CHEBI:201814 with KEGG compound `C-9520`
- CHEBI:177923 with KEGG compound `C-8514`
- CHEBI:220572 with KEGG compound `C-4400`
- CHEBI:157715 with HMDB `0136947`
- CHEBI:157735 with HMDB `0038839`
- CHEBI:157725 with HMDB `0033586`
- CHEBI:157726 with HMDB `0033486`
- CHEBI:157719 with HMDB `0033018`
- CHEBI:157724 with HMDB `0030766`
- CHEBI:157716 with HMDB `0030549`
- CHEBI:197996 with CAS `pubchem:139583232`
- CHEBI:198879 with CAS `pubchem:101408975;nikkaji:j2.364.775c;nmrshiftdb:70094587;zinc:zinc000013380199`
- CHEBI:199618 with CAS `nmrshiftdb:60057454;pubchem:21593947;nikkaji:j3.516.333f;zinc:zinc000138682451`

**Comment by amalik01** [comment]
Hi,
Thank you for pointing out these errors in database accessions. They have now been fixed.
