### ISSUE TITLE
`proteinogenic amino acid` contains non-proteinogenic subclass

### ISSUE THREAD

**Issue by sfluegel05** [ebi-chebi/ChEBI#4518]
Hi,

I had a look at the `proteinogenic amino acid` (CHEBI:83813) class and found that it has 24 amino acids as subclasses. However, the definition claims only 23 amino acid. The 24th is probably `L-homocysteine` (CHEBI:17588), which is, as far as I know, not proteinogenic. 

This should be fixable by removing the `is_a` relation between `serine family amino acid` (CHEBI:26650) and `proteinogenic amino acid`.

Thanks!

**Comment by amalik01** [comment]
Now fixed. Thanks
