### ISSUE TITLE
CHEBI:73870, a synonym is missing

### ISSUE THREAD

**Issue by ANiknejad** [ebi-chebi/ChEBI#4520]
Hello ChEBI Team,

https://www.ebi.ac.uk/chebi/searchId.do?chebiId=73870
(7Z,10Z,13Z,16Z,19Z)-docosapentaenoyl-CoA(4-)

_Virtual Metabolic Human_, and _BiGG Models,_ both use '**Clupanodonyl CoA**' to describe '(7Z,10Z,13Z,16Z,19Z)-docosapentaenoyl-CoA'.

- https://www.vmh.life/#metabolite/clpndcoa
- http://bigg.ucsd.edu/universal/metabolites/clpndcoa

While chebi:53488 ((7Z,10Z,13Z,16Z,19Z)-docosapentaenoic acid) does have synonym 'clupanodonic acid' 
(https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:53488), there is no corresponding synonym for chebi:73870
(7Z,10Z,13Z,16Z,19Z)-docosapentaenoyl-CoA(4-). 

I suggest to add synonym 'Clupanodonyl CoA' to chebi:73870

Thank you,

Anne

**Comment by amalik01** [comment]
The following synonym have now been added to CHEBI:73870:
clupanodonyl CoA(4−)
