### ISSUE TITLE
CHEBI:73856, a synonym is missing

### ISSUE THREAD

**Issue by ANiknejad** [ebi-chebi/ChEBI#4523]
Hello,

CHEBI:53487 _all-cis-docosa-7,10,13,16-tetraenoic acid_, has synonym 'adrenic acid'

Could you add 'Adrenyl coenzyme A' to CHEBI:73856 (7Z,10Z,13Z,16Z)-docosatetraenoyl-CoA(4-)?

'Adrenyl coenzyme A'  is used in 

https://www.vmh.life/#metabolite/adrncoa

and 

https://hmdb.ca/metabolites/HMDB0060208

Thank you!

Anne

**Comment by amalik01** [comment]
Adrenyl coenzyme A(4-) now added as a synonym to CHEBI:73856
