### ISSUE TITLE
conjugate_base_of should always connect a lower charge state to a higher charge state

### ISSUE THREAD

**Issue by cmungall** [ebi-chebi/ChEBI#4524]
The follow tables has cases where the difference between charges is either 0 or negative:

|subject|object|subject_charge|object_charge|diff|diff_sign|subject_label|object_label|
|---|---|---|---|---|---|---|---|
|CHEBI:132991|CHEBI:132993|0|-1|1|1|pyroglutamylvaline|pyroglutamylvalinate|
|CHEBI:136587|CHEBI:133948|0|-1|1|1|(4Z,7Z,11Z,13Z,15E,17S,19Z)-10,17-bis(hydroperoxy)docosahexaenoic acid|(4Z,7Z,11Z,13Z,15E,17S,19Z)-10,17-bis(hydroperoxy)docosahexaenoate|
|CHEBI:136625|CHEBI:137483|-1|-1|0|0|2-O-(alpha-D-mannopyranosyl)-6-O-(6-acyl-alpha-D-mannopyranosyl)-1-phosphatidyl-1D-myo-inositol(1-)|2-O-(alpha-D-mannopyranosyl)-6-O-(6-acyl-alpha-D-mannopyranosyl)-1-phosphatidyl-1D-myo-inositol|
|CHEBI:141055|CHEBI:141057|1|0|1|1|validoxylamine B(1+)|validoxylamine B|
|CHEBI:149469|CHEBI:42085|1|0|1|1|(7R,8S)-7,8-diammoniononanoate|(7R,8S)-7,8-diaminononanoic acid|
|CHEBI:15243|CHEBI:26984|0|0|0|0|threonate|threonic acid|
|CHEBI:15885|CHEBI:32819|0|-1|1|1|L-2-amino-4-chloropent-4-enoic acid|L-2-amino-4-chloropent-4-enoate|
|CHEBI:166697|CHEBI:142861|0|-1|1|1|Sulfated Dihydromenaquinone-9|omega-sulfo-beta-dihydromenaquinone-9|
|CHEBI:16705|CHEBI:30938|0|-1|1|1|6-aminopenicillanic acid|6-aminopenicillanate|
|CHEBI:16849|CHEBI:20937|0|0|0|0|D-fructuronate|D-fructuronic acid|
|CHEBI:169944|CHEBI:75970|-1|-3|2|1|kaempferol 7-O-beta-D-glucoside(1-)|2'-phospho-cyclic ADP-ribose(3-)|
|CHEBI:172403|CHEBI:84846|0|0|0|0|1,2-dilinoleoyl-sn-glycero-3-phosphoethanolamine zwitterion|1,2-di-(9Z,12Z-octadecadienoyl)-sn-glycero-3-phosphoethanolamine|
|CHEBI:178058|CHEBI:178083|0|0|0|0|alpha-ketoglutarate-13C4|alpha-ketoglutaric acid-13C4|
|CHEBI:183796|CHEBI:183797|2|0|2|1|(4-ammoniobutyl)(3-oxopropyl)azanium|3-[(4-aminobutyl)amino]propanal|
|CHEBI:189077|CHEBI:189059|0|-5|5|1|(R,S)-[hydroxy(phenyl)methyl]succinyl-CoA|(R,S)-[hydroxy(phenyl)methyl]succinyl-CoA(5-)|
|CHEBI:189545|CHEBI:189532|2|0|2|1|ICR 340(2+)|ICR 340 (free base)|
|CHEBI:191173|CHEBI:190702|0|-2|2|1|N-acetyl-L-seryl-L-aspartic acid|N-acetyl-L-seryl-L-aspartate(2-)|
|CHEBI:192077|CHEBI:134261|0|0|0|0|N-methyl-aminoisobutyrate zwitterion|alpha-(methylamino)isobutyric acid|
|CHEBI:196947|CHEBI:196977|0|-1|1|1|8-undecenoic acid|8-undecenoate|
|CHEBI:20909|CHEBI:20910|0|0|0|0|D-arabinarate(1-)|D-arabinaric acid|
|CHEBI:21048|CHEBI:21049|0|0|0|0|D-mannarate(1-)|D-mannaric acid|
|CHEBI:21225|CHEBI:21226|0|0|0|0|L-arabinarate(1-)|L-arabinaric acid|
|CHEBI:21358|CHEBI:21359|0|0|0|0|L-mannarate(1-)|L-mannaric acid|
|CHEBI:24112|CHEBI:24113|0|0|0|0|fructuronate|fructuronic acid|
|CHEBI:24115|CHEBI:24116|0|0|0|0|fuconate|fuconic acid|
|CHEBI:24297|CHEBI:24298|0|0|0|0|glucuronate|glucuronic acid|
|CHEBI:24464|CHEBI:33816|0|0|0|0|guluronic acid|guluronate|
|CHEBI:25482|CHEBI:25483|0|0|0|0|naphthoate|naphthoic acid|
|CHEBI:26544|CHEBI:21376|0|0|0|0|rhamnonate|rhamnonic acid|
|CHEBI:26986|CHEBI:32833|0|0|0|0|threonine|threoninium|
|CHEBI:27345|CHEBI:33828|0|0|0|0|xylonate|xylonic acid|
|CHEBI:28394|CHEBI:17479|0|-2|2|1|enol-oxaloacetic acid|enol-oxaloacetate|
|CHEBI:28699|CHEBI:79081|0|-3|3|1|cyclic 2,3-bisphospho-D-glyceric acid|cyclic 2,3-bisphospho-D-glycerate(3-)|
|CHEBI:29003|CHEBI:30936|0|-2|2|1|L-citramalic acid|L-citramalate(2-)|
|CHEBI:30830|CHEBI:16724|0|-1|1|1|4-hydroxybutyric acid|4-hydroxybutyrate|
|CHEBI:30913|CHEBI:30633|0|-1|1|1|L-pipecolic acid|L-pipecolate|
|CHEBI:32832|CHEBI:26986|0|0|0|0|threoninate|threonine|
|CHEBI:33523|CHEBI:29286|0|0|0|0|peroxysulfate(1-)|peroxysulfuric acid|
|CHEBI:33531|CHEBI:24157|0|0|0|0|galactosaminate|galactosaminic acid|
|CHEBI:33541|CHEBI:33540|0|0|0|0|thiosulfate(1-)|thiosulfuric acid|
|CHEBI:33801|CHEBI:16002|0|0|0|0|D-glucarate(1-)|D-glucaric acid|
|CHEBI:33820|CHEBI:24769|0|0|0|0|iduronate|iduronic acid|
|CHEBI:33821|CHEBI:25176|0|0|0|0|mannuronate|mannuronic acid|
|CHEBI:33986|CHEBI:28118|0|0|0|0|muramate|muramic acid|
|CHEBI:35383|CHEBI:22285|0|0|0|0|allarate(1-)|allaric acid|
|CHEBI:35384|CHEBI:24765|0|0|0|0|idarate(1-)|idaric acid|
|CHEBI:35385|CHEBI:35384|0|0|0|0|idarate(2-)|idarate(1-)|
|CHEBI:35386|CHEBI:21041|0|0|0|0|D-idarate(1-)|D-idaric acid|
|CHEBI:35387|CHEBI:21333|0|0|0|0|L-idarate(1-)|L-idaric acid|
|CHEBI:35389|CHEBI:26847|0|0|0|0|altrarate(1-)|altraric acid|
|CHEBI:35392|CHEBI:17301|0|0|0|0|glucarate(1-)|glucaric acid|
|CHEBI:35944|CHEBI:35926|0|0|0|0|thiosulfite(1-)|sulfurothious S-acid|
|CHEBI:36458|CHEBI:36459|0|0|0|0|homocitrate(2-)|homocitrate(1-)|
|CHEBI:36459|CHEBI:17852|0|0|0|0|homocitrate(1-)|homocitric acid|
|CHEBI:36461|CHEBI:15670|0|0|0|0|(E)-glutaconate(1-)|(E)-glutaconic acid|
|CHEBI:36462|CHEBI:24309|0|0|0|0|glutaconate(1-)|glutaconic acid|
|CHEBI:37539|CHEBI:35388|0|0|0|0|mannarate(2-)|mannarate(1-)|
|CHEBI:37540|CHEBI:35393|0|0|0|0|arabinarate(2-)|arabinarate(1-)|
|CHEBI:37545|CHEBI:35389|0|0|0|0|altrarate(2-)|altrarate(1-)|
|CHEBI:38427|CHEBI:31069|0|0|0|0|2,3,5-trichloro-cis,cis-muconate(1-)|2,3,5-trichloro-cis,cis-muconic acid|
|CHEBI:38596|CHEBI:14973|0|0|0|0|pyrazolide|pyrazole|
|CHEBI:38708|CHEBI:38705|0|0|0|0|thiomalate(1-)|thiomalic acid|
|CHEBI:38710|CHEBI:38708|0|0|0|0|thiomalate(2-)|thiomalate(1-)|
|CHEBI:38793|CHEBI:38794|0|0|0|0|pteroate|pteroic acid|
|CHEBI:39056|CHEBI:39053|0|-1|1|1|nitrilotriacetate(2-)|nitrilotriacetate(1-)|
|CHEBI:41582|CHEBI:18703|0|-1|1|1|D-pipecolic acid|D-pipecolate|
|CHEBI:41983|CHEBI:47898|1|0|1|1|4'-epidoxorubicinium|4'-epidoxorubicin|
|CHEBI:42037|CHEBI:47897|1|0|1|1|4'-deoxy-4'-iododoxorubicinium|4'-deoxy-4'-iododoxorubicin|
|CHEBI:46841|CHEBI:44737|0|0|0|0|lutidinate(1-)|lutidinic acid|
|CHEBI:46862|CHEBI:46860|0|0|0|0|cinchomeronate(1-)|cinchomeronic acid|
|CHEBI:46870|CHEBI:46865|0|0|0|0|isocinchomeronate(1-)|isocinchomeronic acid|
|CHEBI:58193|CHEBI:17559|1|0|1|1|3alpha(S)-strictosidinium(1+)|3alpha(S)-strictosidine|
|CHEBI:58644|CHEBI:32818|1|0|1|1|p-coumaroylagmatine(1+)|p-coumaroylagmatine|
|CHEBI:59233|CHEBI:87709|0|-1|1|1|methoxy mycolic acid|methoxy mycolate|
|CHEBI:60431|CHEBI:75137|0|-2|2|1|2,2'-dilysocardiolipin|2,2'-dilysocardiolipin(2-)|
|CHEBI:61575|CHEBI:78607|0|-1|1|1|alpha-L-Fuc-(1->2)-beta-D-Gal-(1->3)-beta-D-GalNAc-(1->4)-[alpha-Neu5Ac-(2->3)]-beta-D-Gal-(1->4)-beta-D-Glc-(1<->1')-Cer|alpha-L-Fuc-(1->2)-beta-D-Gal-(1->3)-beta-D-GalNAc-(1->4)-[alpha-Neu5Ac-(2->3)]-beta-D-Gal-(1->4)-beta-D-Glc-(1<->1')-Cer(1-)|
|CHEBI:63061|CHEBI:60981|0|-2|2|1|UDP-rhamnose|UDP-rhamnose(2-)|
|CHEBI:63968|CHEBI:63971|2|0|2|1|N(6)-acetimidoyl-L-lysinium(2+)|N(6)-acetimidoyl-L-lysine|
|CHEBI:63987|CHEBI:63988|1|0|1|1|N-allyl-1-phenyl-2,3,4,5-tetrahydro-3-benzazepinium-7,8-diol(1+)|N-allyl-1-phenyl-2,3,4,5-tetrahydro-3-benzazepine-7,8-diol|
|CHEBI:64003|CHEBI:64004|1|0|1|1|N-allyl-6-chloro-1-(3-methylphenyl)-2,3,4,5-tetrahydro-3-benzazepinium-7,8-diol(1+)|N-allyl-6-chloro-1-(3-methylphenyl)-2,3,4,5-tetrahydro-3-benzazepinium-7,8-diol|
|CHEBI:64364|CHEBI:10650|1|0|1|1|sumatriptan(1+)|sumatriptan|
|CHEBI:64687|CHEBI:64675|0|-1|1|1|2,6-dioxo-6-phenylhexa-3-enoic acid|2,6-dioxo-6-phenylhexa-3-enoate(1-)|
|CHEBI:64918|CHEBI:64884|0|-1|1|1|C20 phytosphingosine 1-phosphate|C20 phytosphingosine 1-phosphate(1-)|
|CHEBI:67213|CHEBI:67223|3|0|3|1|2'-deamino-2'-hydroxyneamine(3+)|2'-deamino-2'-hydroxyneamine|
|CHEBI:67214|CHEBI:67225|2|0|2|1|2'-deamino-2'-hydroxy-6'-dehydroparomamine(2+)|2'-deamino-2'-hydroxy-6'-dehydroparomamine|
|CHEBI:71290|CHEBI:71294|0|-4|4|1|3-hydroxy-3-phenylpropionyl-CoA|3-hydroxy-3-phenylpropionyl-CoA(4-)|
|CHEBI:72567|CHEBI:6438|1|0|1|1|levobunolol(1+)|levobunolol|
|CHEBI:72756|CHEBI:72797|3|0|3|1|kanamycin X(3+)|kanamycin X|
|CHEBI:72945|CHEBI:73078|3|0|3|1|3''-deamino-3''-hydroxykanamycin C(3+)|3''-deamino-3''-hydroxykanamycin C|
|CHEBI:72946|CHEBI:72992|2|0|2|1|3''-deamino-3''-hydroxykanamycin X(2+)|3''-deamino-3''-hydroxykanamycin X|
|CHEBI:72947|CHEBI:73079|3|0|3|1|kanamycin D(3+)|kanamycin D|
|CHEBI:73792|CHEBI:74938|0|-2|2|1|1-arachidonoyl-sn-glycerol 3-phosphate|1-arachidonoyl-sn-glycerol 3-phosphate(2-)|
|CHEBI:74455|CHEBI:74679|0|0|0|0|5-methylaminomethyl-2-thiouridine 5'-monophosphate zwitterion residue|5-methylaminomethyl-2-thiouridine 5'-monophosphate residue|
|CHEBI:74674|CHEBI:74445|0|-1|1|1|2'-O-methylguanosine 5'-monophosphate residue|2'-O-methylguanosine 5'-monophosphate(1-) residue|
|CHEBI:75275|CHEBI:75274|0|-1|1|1|tetradecyl sulfonic acid|tetradecyl sulfate|
|CHEBI:75297|CHEBI:31057|1|0|1|1|13-deoxydaunorubicin(1+)|13-deoxydaunorubicin|
|CHEBI:76278|CHEBI:16299|1|0|1|1|dehydrocoformycin(1+)|dehydrocoformycin|
|CHEBI:76819|CHEBI:15906|1|0|1|1|demethylmacrocin(1+)|demethylmacrocin|
|CHEBI:76930|CHEBI:76610|0|-1|1|1|omega-hydroxytetracosanoic acid|omega-hydroxytetracosanoate|
|CHEBI:77525|CHEBI:82836|0|0|0|0|(17Z)-hexacosenoic acid|(9Z)-hexacosenoic acid|
|CHEBI:77932|CHEBI:27902|0|0|0|0|tetracycline zwitterion|tetracycline|
|CHEBI:78176|CHEBI:77547|0|-4|4|1|undecanoyl-CoA|undecanoyl-CoA(4-)|
|CHEBI:79028|CHEBI:140804|0|-1|1|1|icas#9|icas#9(1-)|
|CHEBI:82745|CHEBI:78680|0|-4|4|1|(9Z,12Z)-tetradecadienoyl-CoA|(9Z,12Z)-tetradecadienoyl-CoA(4-)|
|CHEBI:82770|CHEBI:83547|4|0|4|1|N(4)-aminopropylspermidine(4+)|N(4)-aminopropylspermidine|
|CHEBI:82771|CHEBI:83553|5|1|4|1|N(4)-bis(aminopropyl)spermidine(5+)|N(4)-bis(aminopropyl)spermidine(1+)|
|CHEBI:82772|CHEBI:83554|5|0|5|1|N(4)-aminopropylspermine(5+)|N(4)-aminopropylspermine|
|CHEBI:83175|CHEBI:20386|1|0|1|1|4-hydroxysphing-8-enine(1+)|4-hydroxy-8-sphingenine|
|CHEBI:83675|CHEBI:84460|-1|-1|0|0|10-PAHSA(1-)|10-PAHSA|
|CHEBI:85829|CHEBI:85830|0|0|0|0|CDP-1-stearoyl-2-arachidonoyl-sn-glycerol|CDP-1-palmitoyl-2-arachidonoyl-sn-glycerol|
|CHEBI:86011|CHEBI:85720|0|-2|2|1|oxetanocin A 4-(dihydrogen phosphate)|oxetanocin A 4-phosphate(2-)|
|CHEBI:86083|CHEBI:86085|1|0|1|1|(Z)-p-coumaroylagmatine(1+)|(Z)-p-coumaroylagmatine|
|CHEBI:86279|CHEBI:85971|0|-2|2|1|D-arabinofuranose 5-phosphate|D-arabinofuranose 5-phosphate(2-)|
|CHEBI:86380|CHEBI:599440|1|0|1|1|amorolfine(1+)|amorolfine|
|CHEBI:87475|CHEBI:87474|0|-4|4|1|(R)-2-hydroxybutanoyl-CoA|(R)-2-hydroxybutanoyl-CoA(4-)|
|CHEBI:90702|CHEBI:90704|0|-1|1|1|carboxy-PTIO|carboxylato-PTIO|

**Comment by amalik01** [comment]
Thanks @cmungall 
I have now fixed the above entries. We will try and build some checks/validations into the new curator/submissions tool that we are developing to prevent this from happening again.
