### ISSUE TITLE
Submission Error

### ISSUE THREAD

**Issue by jpquast** [ebi-chebi/ChEBI#4531]
I can currently not submit any new entries to ChEBI. Not sure if this is a problem from my side or if it affects everyone. 
The error is:

`Error during submission - could not execute statement; nested exception is org.hibernate.exception.GenericJDBCException: could not execute statement Caused by:ORA-01652: unable to extend temp segment by 64 in tablespace TEMP ORA-06512: at "CHEBI.PCK_CHEBI_AUDIT_LOG", line 7`

**Comment by amalik01** [comment]
@jpquast The EBI servers are undergoing maintenance at the moment and this is affecting some of our tools. Hopefully, it will be resolved by the end of the day.

**Comment by amalik01** [comment]
@jpquast Please try now. The submissions tool should be working fine now.
