### ISSUE TITLE
CHEBI:165348 - 2,3-Dinor-TXB1

### ISSUE THREAD

**Issue by docmattc** [ebi-chebi/ChEBI#4533]
CHEBI:165348 is not 2,3-Dinor-TXB1- there should be an oxygen in the ring in a meta- position relative to the chain with the  carboxylate (and para- to the hydroxyl)
This is an error that has propagated from LIPID MAPS via a metabolights study- proving that folks will happily find non-existent compounds in their metabolomics studies if they are in a reference database.

LIPIDMAPS LMFA03030012 has been updated

**Comment by amalik01** [comment]
Now fixed. Thanks
