### ISSUE TITLE
CHEBI:17801, add synonym

### ISSUE THREAD

**Issue by ANiknejad** [ebi-chebi/ChEBI#4534]
Hello ChEBI Team,

it could be useful to add 'parapyruvate' as a synonym of CHEBI:17801 4-hydroxy-4-methyl-2-oxoglutaric acid

please see  https://pubs.acs.org/doi/10.1021/acsomega.0c00877

and  this recent publication

https://pubmed.ncbi.nlm.nih.gov/38343944/

Thank you very much,

Anne

**Comment by amalik01** [comment]
In ChEBI, there is a clear distinction between pyruvic acid and pyruvate hence i have added the above synonym to the deprotonated entry (CHEBI:58276).
