### ISSUE TITLE
CHEBI:74298, please add synonym

### ISSUE THREAD

**Issue by ANiknejad** [ebi-chebi/ChEBI#4538]
Hello ChEBI Team,

CHEBI:74298 (4Z,7Z,10Z,13Z,16Z,19Z)-docosahexaenoyl-CoA(4-)

may have maybe synonym 'cervonyl CoA', see
https://hmdb.ca/metabolites/HMDB0060198

There is also https://hmdb.ca/metabolites/HMDB0060199 but with an issue on the CoA structure I guess: the 3′-phosphoadenosine part is not in the canonical form

IUPAC Name
(2S)-4-({[({[(2R,3S,4R,5R)-5-(6-amino-9H-purin-9-yl)-4-hydroxy-3-(phosphonooxy)oxolan-2-yl]methoxy}(hydroxy)phosphoryl)oxy](hydroxy)phosphoryl}oxy)-N-[2-({2-[(**4Z,7Z,10Z,13Z,16Z,19Z**)-docosa-4,7,10,13,16,19-hexaenoylsulfanyl]ethyl}-C-hydroxycarbonimidoyl)ethyl]-2-hydroxy-3,3-dimethylbutanimidic acid

Thank very much, and of course open to discussion, should you have comments about this request

Anne

**Comment by amalik01** [comment]
synonym now added. Thanks
