### ISSUE TITLE
Relation CHEBI:74141 is_a CHEBI:90736 please consider change 

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#4539]
CHEBI:143018 (ultra long) has a definition that includes carbon chains of 27 or longer, as CHEBI:74141 is 28 carbons-long, can we change the relation CHEBI:74141 is_a CHEBI:90736 (very long) to CHEBI:74141 is_a CHEBI:143018?

**Comment by amalik01** [comment]
The relationship has now been added. Thanks
