### ISSUE TITLE
24-methylene lanosterol 

### ISSUE THREAD

**Issue by ValWood** [ebi-chebi/ChEBI#4541]
hi,

should 
24-methylene lanosterol 
be a synonym of 4,25-dihydrolanosterol CHEBI:28113
thanks

val

for https://github.com/pombase/fypo/issues/4541

**Comment by ValWood** [comment]
No it seems not. DO you know which CHEBI ID applies to   24-methylene lanosterol
PMID:17276356

**Comment by amalik01** [comment]
Hi, 

24-methylene lanosterol is CHEBI:70315.
