### ISSUE TITLE
CHEBI:48742, please add synonyms

### ISSUE THREAD

**Issue by ANiknejad** [ebi-chebi/ChEBI#4543]
Hello Adnan,

It would be nice to have synonym 'varanic acid' and even '24-OH-THCA'
to CHEBI:48742 3alpha,7alpha,12alpha,24-tetrahydroxy-5beta-cholestan-26-oic acid
please see this publication
https://pubmed.ncbi.nlm.nih.gov/8916357/
Do you agree?
Cheers,

Anne

**Comment by amalik01** [comment]
Now added. Thanks
