### ISSUE TITLE
submission error

### ISSUE THREAD

**Issue by rwst** [ebi-chebi/ChEBI#4548]
I can't get past the captcha, getting: Error
Error during submission - could not execute statement; nested exception is org.hibernate.exception.GenericJDBCException: could not execute statement Caused by:ORA-01652: unable to extend temp segment by 64 in tablespace TEMP ORA-06512: at "CHEBI.PCK_CHEBI_AUDIT_LOG", line 7

![Screenshot from 2024-10-06 09-54-17](https://github.com/user-attachments/assets/1383e614-2c0a-4063-9df4-68da599b6e03)

UPDATE: I just found my submission would be a duplicate of CHEBI:167616. That the reason for this error?

**Comment by amalik01** [comment]
Hi, 

We are having some issues with temp tablespace which prevents users from adding any data to the database. Please try again, it should be working fine now.

**Comment by ANiknejad** [comment]
could not execute statement Caused by:ORA-01652: unable to extend temp segment by 64 in tablespace TEMP ORA-06512: at "CHEBI.PCK_CHEBI_AUDIT_LOG", line 7

Today the same warning message @amalik01

**Comment by amalik01** [comment]
@ANiknejad The ChEBI infrastructure is quite unstable at the moment. I have restarted the services so it should now be working. If you encounter the issue again, please send an e-mail to chebi-help@ebi.ac.uk

Thanks
