### ISSUE TITLE
NTR dolichol phosphate mannose

### ISSUE THREAD

**Issue by ValWood** [ebi-chebi/ChEBI#4553]
Request  for 
dolichol phosphate mannose
dolichol-P-mannose
Dol-P-Man

required for logical definition of dolichol phosphate mannose biosynthetic process
https://github.com/geneontology/go-ontology/issues/28929

reference e
PMID: 18387370
and others

**Comment by amalik01** [comment]
@ValWood The name given is pretty vague and most likely refers to CHEBI:17624 based on evidence found in PMID:28743912. Its major microspecies at pH 7.3 is CHEBI:58211
