### ISSUE TITLE
Please check  CHEBI:81478, 81479, 81480 (status OK) and CHEBI:61514

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#4554]
Dear Adnan,

Please could you check these entries needed for Rhea

CHEBI:81478 N1,N5,N10-tris[(E)-caffeoyll]spermidine
PMID:19779199
MetaCyc xref: CPD-12213
status OK

CHEBI:81479	N1,N5,N10-tris[(E)-feruloyl]spermidine
PMID:19779199
MetaCyc xref: CPD-12214
status OK

CHEBI:81480 N1,N5,N10-tris[(E)-5-hydroxyferuloyl]spermidine
PMID:19779199
MetaCyc xref: CPD-11667
status OK

CHEBI:61514	N1,N5,N10-tris[(E)-p-coumaroyl]spermidine
PMID:19779199
MetaCyc xref: CPD-12212

Kind regards, Anne

**Comment by amalik01** [comment]
Now checked. Thanks.
