### ISSUE TITLE
Please, update CHEBI:60481 structure

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#4557]
Hi Adnan,
Please, could you update CHEBI:60481 structure and citation with the attached structure nicely drawn by Kristian from PMID:30070018 Fig.1
Thank you
Anne

[NAcfusarinine_mol.txt](https://github.com/user-attachments/files/17412702/NAcfusarinine_mol.txt)

**Comment by amalik01** [comment]
Structure now updated. Thanks
