### ISSUE TITLE
Secretin and 'human secretin' placement

### ISSUE THREAD

**Issue by sbello** [ebi-chebi/ChEBI#4559]
CHEBI has 2 terms 

secretin human - http://purl.obolibrary.org/obo/CHEBI_135913
Secretin - http://purl.obolibrary.org/obo/CHEBI_34972

'secretin human' is a direct child of polypetide and is not a descendant of Secretin. Secretin is a child of 'organic molecular entity'.

Secretin also lacks a text definition. 

Please review the placement of these terms if Secretin is meant to be the parent class of any species secretin then shouldn't human secretin be a child?

There is also a PRO term for secretin (http://purl.obolibrary.org/obo/PR_000014543) that appears under organic amino compound in the CHEBI hierarchy. Not sure how that might factor in.

**Comment by amalik01** [comment]
Both entries have now been fixed. Thanks
