### ISSUE TITLE
CHEBI:16436 Definition Erratum

### ISSUE THREAD

**Issue by NathanWEdwards** [ebi-chebi/ChEBI#4560]
The CHEBI:16436 `Oct-22-2024` _Definition_ entry has  
choline ester (CHEBI:23213) misspelled.

> CDP-choline is a member of the class of phosphocholines that is the chloine [sic] ester of CDP.

The _Definition_ should denote the chemical name, choline ester (CHEBI:23213), that generalizes phosphocholines (CHEBI:36700).

> CDP-choline is a member of the class of phosphocholines that is the choline ester of CDP.

**Comment by amalik01** [comment]
The misspelling has been fixed. Thanks

There are a set of rules which one should follow when writing good ontological definitions:

- Ontological definitions should describe the entity that is being defined, not the label itself or the class that represents the defined thing. 

- Definitions should not include the label for the entity. 

For these reasons, we do not mention the name of the chemical in the definition.
