### ISSUE TITLE
Please remove MetaCyc CPD-12253 from CHEBI:50612

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#4564]
Hi Adnan,
I have submitted CHEBI:232384 and mapped it to MetaCyc CPD-12253. I'm not granted to remove CPD-12253 from CHEBI:50612 in the curator tool.
Cheers, Anne

**Comment by amalik01** [comment]
Hi Anne, 
Is there a specific reason why you want to remove the MetaCyc identifier? It seems fine to me since the InChIKeys match

**Comment by amorgat** [comment]
MetaCyc CPD-12253 AFENDNXGAFYKQO-GSVOUGTGSA-**M**
CHEBI:232384 AFENDNXGAFYKQO-GSVOUGTGSA-**M**
CHEBI:50612 AFENDNXGAFYKQO-GSVOUGTGSA-**N**

**Comment by amorgat** [comment]
Hi Adnan,
CPD-12253 and CHEBI:232384 are the anionic form (charge -1). CHEBI:50612 has a charge = 0
MetaCyc CPD-12253 AFENDNXGAFYKQO-GSVOUGTGSA-M
CHEBI:232384 AFENDNXGAFYKQO-GSVOUGTGSA-M
CHEBI:50612 AFENDNXGAFYKQO-GSVOUGTGSA-N

From: amalik01 ***@***.***>
Date: Friday, 25 October 2024 at 10:52
To: ebi-chebi/ChEBI ***@***.***>
Cc: Anne Morgat ***@***.***>, Author ***@***.***>
Subject: Re: [ebi-chebi/ChEBI] Please remove MetaCyc CPD-12253 from CHEBI:50612 (Issue #4564)

Hi Anne,
Is there a specific reason why you want to remove the MetaCyc identifier? It seems fine to me since the InChIKeys match

**Comment by amalik01** [comment]
previous msg was sent by mistake

**Comment by amalik01** [comment]
MetaCyc identifier now removed. Thanks
