### ISSUE TITLE
chebi:88795, CE(20:1(11Z)), the scaffold of the cholesterol part sounds wrong

### ISSUE THREAD

**Issue by ANiknejad** [ebi-chebi/ChEBI#4566]
Hello ChEBI Team,

Could you please review this 2-stars chebi compound? 
I was on the way to submit SLM:000500284 (11Z-eicosenoyl)-cholesterol to chebi, but when adding the xref HMDB0005193, the submission tool gave a warning about this xref already used in chebi:88795 CE(20:1(11Z)): actually the only difference is missing some stereo info in the cholesterol part of chebi:88795 ? Do I have to submit a correct compound, and then you will merge both entries (the new I would have created and chebi:88795), or do you update   chebi:88795?

Thank you in advance for your help,

Anne

**Comment by amalik01** [comment]
Hi Anne,

There is no need to create a new entry (I will update the existing entry).

**Comment by amalik01** [comment]
CHEBI:88795 now annotated.
