### ISSUE TITLE
CHEBI:88763, to delete or to merge with CHEBI:196788

### ISSUE THREAD

**Issue by ANiknejad** [ebi-chebi/ChEBI#4570]
Hello ChEBI Team,

CHEBI:196788 cholest-5-en-3beta-yl eicosanoate is identical to SLM:000500285
https://www.swisslipids.org/#/entity/SLM:000500285/?classification
and its definition is the same as the one for CHEBI:88763 CE(20:0), which has erroneous synonym(s), such as 'Eicosanoate'

Could you consider merging (or deleting ?) CHEBI:88763?

I hope, I do not miss something here because in SwissLipids I see that SLM:000500285 eicosanoyl-cholesterol has 2 parents ?

Thanks,
Cheers,

Anne

**Comment by amalik01** [comment]
Now fixed. Thanks
