### ISSUE TITLE
CHEBI:88774, to delete or to merge with CHEBI:166785

### ISSUE THREAD

**Issue by ANiknejad** [ebi-chebi/ChEBI#4571]
Hello ChEBI Team,

CHEBI:166785 Cholest-5-en-3beta-yl (13Z,16Z-docosadienoate) is a 2-stars chebi, but it has the same mol file as the one of SLM:000500292 (13Z,16Z-docosadienoyl)-cholesterol

CHEBI:88774 CE(22:2(13Z,16Z)) is also a 2-stars chebi compound, with synonym Cholest-5-en-3beta-yl (13Z,16Z-docosadienoate) in HMDB

The difference, as far as I understand, is the stereo on the cholesteryl part, with CHEBI:166785 having the correct stereo.
So I guess, both compounds should be merged

Thank you for your help,
Cheers,

Anne

**Comment by amalik01** [comment]
Now merged. Thanks
