### ISSUE TITLE
CHEBI:169515, needs a review, is identical to SLM:000043110

### ISSUE THREAD

**Issue by ANiknejad** [ebi-chebi/ChEBI#4572]
Hello Adnan,

CHEBI:169515 PG(12:0/0:0) is currently 2-stars chebi, and its structure is defined and identical to the one of SLM:000043110 https://swisslipids.vital-it.ch/#/entity/SLM:000043110/ , with name '1-dodecanoyl-sn-glycero-3-phospho-(1'-sn-glycerol)' aka PG(12:0/0:0)

CHEBI:169515 is in apples (sic!), but this review of PG https://www.sciencedirect.com/topics/biochemistry-genetics-and-molecular-biology/phosphatidylglycerol sounds to make PG consistent through photosynthetic and non-photosynthetic species.

I wandering if you could review and update the name to CHEBI:169515 to make him definitely identical to SLM:000043110?

Many thanks in advance,
Cheers,

Anne

**Comment by amalik01** [comment]
The entry has now been fixed. Thanks
