### ISSUE TITLE
Wrong xref for petunidin and petunidin chloride

### ISSUE THREAD

**Issue by smoretti** [ebi-chebi/ChEBI#4580]
Hi

CHEBI:75318 (petunidin) has a xref to KEGG:C08727 that is _Petunidin chloride_. I think it should not be. No `Cl` in CHEBI:75318.

KEGG:C08727 is already a xref to CHEBI:75035 that is really _petunidin chloride_.

CHEBI:75035 also has a xref to HMDB:HMDB0003173, but I guess, according to its structural information, it should be linked to CHEBI:75318. No `Cl` in structural information of HMDB:HMDB0003173.

I guess the Wikipedia xref should also only go to CHEBI:75318

**Comment by amalik01** [comment]
Now fixed. Thanks
