### ISSUE TITLE
CHEBI:29000, IUPAC name is correct, but not the ChEBI name

### ISSUE THREAD

**Issue by ANiknejad** [ebi-chebi/ChEBI#4583]
Hello ChEBI Team,

CHEBI:29000
ChEBI ASCII Name 	(2E,4**E**)-3,8,8,8-tetrachloro-7-(4-chlorophenyl)-2-hydroxy-6-oxo-octa-2,4-dienoate
has IUPAC name

(2E,4**Z**)-3,8,8,8-tetrachloro-7-(4-chlorophenyl)-2-hydroxy-6-oxoocta-2,4-dienoate 

IUPAC name sounds correct, could you please modify accordingly the ChEBI name?
Thank you in advance

**Comment by amalik01** [comment]
ChEBI name has now been fixed. Thanks
