### ISSUE TITLE
CHEBI:136572, please fix molFile

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#4584]
Hi Adnan,

Please could you fix the molFile of CHEBI:136572.
The polymerization index is written as "n\" instead of "n". 
When I used CHEBI:136572 molFile to submit a related structure, the submission tool was not able to create the picture. This error disappeared when I manually replaced "n\" by "n".

Thank you!

Anne

**Comment by amalik01** [comment]
The existing mol file has now been replaced.
