### ISSUE TITLE
CHEBI:38344 hellebrigenin vs CAS 465-90-7

### ISSUE THREAD

**Issue by W-ostr** [ebi-chebi/ChEBI#4585]
CHEBI:38344 (hellebrigenin) is generated with
`InChI=1S/C24H32O6/c1-21-8-5-18-19(6-10-23(28)12-16(26)4-9-22(18,23)14-25)24(21,29)11-7-17(21)15-2-3-20(27)30-13-15/h2-3,13-14,16-19,26,28-29H,4-12H2,1H3/t16-,17+,18-,19?,21+,22-,23-,24-/m0/s1` 
so with configuration of one stereocentre unknown. On the other hand the linked CAS number matches
`InChI=1S/C24H32O6/c1-21-8-5-18-19(6-10-23(28)12-16(26)4-9-22(18,23)14-25)24(21,29)11-7-17(21)15-2-3-20(27)30-13-15/h2-3,13-14,16-19,26,28-29H,4-12H2,1H3/t16-,17+,18-,19+,21+,22-,23-,24-/m0/s1`
So there is some inconsistency between the ChEBI and CAS Registry/SciFinder.

**Comment by amalik01** [comment]
The structure in ChEBI has now been fixed. Thanks
