### ISSUE TITLE
Formula, Mass, Monoisotopicmass of Nitrogen Isotopes 

### ISSUE THREAD

**Issue by jmkeil** [ebi-chebi/ChEBI#4586]
The isotopes of nitrogen ([nitrogen-13 atom](http://purl.obolibrary.org/obo/CHEBI_36935), [nitrogen-14 atom](http://purl.obolibrary.org/obo/CHEBI_36938), [nitrogen-15 atom](http://purl.obolibrary.org/obo/CHEBI_36934), [nitrogen-16 atom](http://purl.obolibrary.org/obo/CHEBI_36936), [nitrogen-17 atom](http://purl.obolibrary.org/obo/CHEBI_36937)) all have [formula](http://purl.obolibrary.org/obo/chebi/formula) value `N`, but from other isotopes I guess it should be `[13N]`, `[14N]`, `[15N]`, `[16N]`, `[17N]`. Also the [mass](http://purl.obolibrary.org/obo/chebi/mass) and the [monoisotopicmass](http://purl.obolibrary.org/obo/chebi/monoisotopicmass) is equal for all of them.

**Comment by amalik01** [comment]
This has now been fixed. All of the nitrogen isotope entries did not have a chemical structure. I have now added chemical structures to the entries and the properties have been regenerated based on the structure. 
Thanks.
