### ISSUE TITLE
CHEBI:16335 Deoxyadenosine should not be a synonym of adenosine

### ISSUE THREAD

**Issue by deborahharrus** [ebi-chebi/ChEBI#4587]
"Deoxyadenosine" is a synonym of adenosine (CHEBI:16335) where it should not be.
Is it correctly a synonym of 2'-deoxyadenosine (CHEBI:17256).

**Comment by deborahharrus** [comment]
Complete list of synonyms which should be removed from CHEBI:16335 
"Adenine Deoxyribonucleoside"
"adenyldeoxyriboside"
"Deoxyadenosine"
"Desoxyadenosine"

**Comment by amalik01** [comment]
Entry has now been fixed (The incorrect synonyms have now been removed).
