### ISSUE TITLE
73645 and 73711 should have `functional parent` arginine

### ISSUE THREAD

**Issue by sfluegel05** [ebi-chebi/ChEBI#4600]
Hi, 

I noticed that CHEBI:73645 (Pro-Arg) and CHEBI:73711 (Val-Arg) both have the axiom `has functional parent some L-asparagine`. The second one's definition also mentions L-asparagine. 

However, judging by the molecular structure and the name, it should be `L-arginine` instead. Could you please fix that?

**Comment by amalik01** [comment]
Now fixed. Thanks
