### ISSUE TITLE
CHEBI:157683 is not a pentapeptide

### ISSUE THREAD

**Issue by sfluegel05** [ebi-chebi/ChEBI#4603]
The entity althiomycin (CHEBI:157683) is currently classified as a pentapeptide (CHEBI:48545). I'm not quite sure why exactly this classification has been made, since the definition does not make a reference to pentapeptides. 

However, there are definitely less than 5 amino acid residues in this molecule. There are 2 amide bonds which sets the upper limit to three amino acids. In addition, I would argue that the structure on the left-hand side does not contain an amino group since both nitrogen atoms are double-bonded. So my conclusion is that althiomycin is a dipeptide. 

I would suggest to either change the axiom or remove it entirely (for most other peptide antibiotics, no classification based on the number of amino acids has been made).

**Comment by amalik01** [comment]
The pentapeptide relationship has now been removed. I assume that the relationship was added because a few articles classify it as a heavily modified pentapeptide (E.g. https://chemistry-europe.onlinelibrary.wiley.com/doi/epdf/10.1002/cbic.201100154).
