### ISSUE TITLE
CHEBI:58588, please remove wrong MetaCyc xref

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#4604]
Hi Adnan,
Please remove MetaCyc:[Flavonols](http://biocyc.org/META/NEW-IMAGE?type=NIL&object=Flavonols&redirect=T) from CHEBI:58588
It is correctly mapped to CHEBI:28802
Thank you
Anne

**Comment by amalik01** [comment]
now removed. thanks
