### ISSUE TITLE
duplicates: CHEBI:61978 and CHEBI:82620 

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#4605]
Hi Adnan
CHEBI:61978 and CHEBI:82620 are duplicates, please could you merge them.
It would be very useful to keep CHEBI:82620 as the primary ID, as it is already used in Rhea and in the UniProt annotation (PTMs).
Thank you Adnan
Best wishes
Anne

**Comment by amalik01** [comment]
Hi @amorgat 

Both entries have now been merged. The Primary ChEBI ID = 61978.

Please update the CHEBI ID in Rhea/UniProt. Thanks
