### ISSUE TITLE
Incomplete ontology for CHEBI:61265 (base J)

### ISSUE THREAD

**Issue by muthuvenkat** [ebi-chebi/ChEBI#503]
[CHEBI:61265 β-D-glucopyranosyloxymethyluracil residue](http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:61265) contains the following definition: "A deoxyribonucleotide residue in which a 5-hydroxymethyluracil residue is glycosidically linked via the 5-hydroxymethyl oxygen to β-D-glucose."

However, its ontology only contains a single tree, stating that this entry ![is a](http://www.ebi.ac.uk/chebi/images/ontology/checked/is_a.gif) is a [CHEBI:55367 deoxyribonucleotide residue](http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:55367).

I would suggest that the following relationship be added:

Outgoing: ![has functional parent](http://www.ebi.ac.uk/chebi/images/ontology/checked/has_functional_parent.gif) has functional parent [CHEBI:16964 5-hydroxymethyluracil](http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:16964) (which has functional parent [CHEBI:17568 uracil](http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:17568)).

Reported by: cviner

**Comment by cviner** [comment]
Thank you for migrating this and assigning it high priority!

**Comment by stevet7** [comment]
Hi, 
I have created the parent nucleotide (CHEBI:111511), linked this to the residue (via is substituent group from relationship) and added the functional parent relationship to this compound. As a rule we don't have functional parent relationships between residues/groups and actual molecules.

Kind regards,
Steve

**Comment by cviner** [comment]
Great. Thanks, Steve!
