### ISSUE TITLE
terpenoid and isoprenoid

### ISSUE THREAD

**Issue by muthuvenkat** [ebi-chebi/ChEBI#643]
Are these the same? And how do they relate to isoprene
and terpene? This issue has arisen in GO:

https://sourceforge.net/tracker/index.php?func=detail&aid=1400564&group\_id=36855&atid=440764

We'll hold off on fixing anything in GO until these
terms are resolved in ChEBI...

jane

Reported by: jl242

**Comment by linuxjackto1** [comment]
thanks www.movied.org
