### ISSUE TITLE
new term request: phenylacetylglutamine

### ISSUE THREAD

**Issue by muthuvenkat** [ebi-chebi/ChEBI#656]
Phenylacetylglutamine, Phenylacetyl-L-glutamine ... 
IUPAC: 4-carbamoyl-2-[(2-phenylacetyl)amino]butanoic 
acid 
MW: 264.277 | MF: C13H16N2O4 
known to PubChem: 
http://pubchem.ncbi.nlm.nih.gov/summary/summary.cgi?
cid=306137

Reported by: deustp01

**Comment by linuxjackto1** [comment]
thanks www.movied.org
