### ISSUE TITLE
anadamide

### ISSUE THREAD

**Issue by muthuvenkat** [ebi-chebi/ChEBI#657]
Name: anandamide
Database identifier: C11695
Database name: KEGG
Database URL:
http://www.genome.jp/dbget-bin/www\_bget?cpd:C11695
CAS number: 94421-68-8
Synonyms:Arachidonylethanolamide;
N-(5Z,8Z,11Z,14Z-icosatetraenoyl)-ethanolamide
Formulae:C22H37NO2

Reported by: lenov

**Comment by linuxjackto1** [comment]
thanks www.movied.org
