### ISSUE TITLE
glycogen

### ISSUE THREAD

**Issue by muthuvenkat** [ebi-chebi/ChEBI#658]
glycogen 
CAS: 9005-79-2
PubChem: 3482
KEGG:C00182
IUPAC: (2S,3R,4R,5S,6S)-5-[(2R,3R,4R,5S,6S)-3,4-dihydroxy-5-[(2R,3R,
4R,5S,6S)-3,4,5-trihydroxy-6-(hydroxymethyl)oxan-2-yl]oxy-6-[[(2R,3R,
4R,5S,6S)-3,4,5-trihydroxy-6-(hydroxymethyl)oxan-2-yl]oxymethyl]
oxan-2-yl]oxy-6-(hydroxymethyl)oxane-2,3,4-triol

child of polysaccharides (CHEBI:18154)

Thanks,

marek@genome.stanford.edu

Reported by: *anonymous

**Comment by linuxjackto1** [comment]
thanks www.movied.org
